include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml

image: maven:3-jdk-8

cache:
  paths:
    - .m2/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

stages:
  - deploy
  - build
  - test

build:
  stage: build
  script:
   - "mvn clean install -Dmaven.test.skip=true"
   - 'mvn deploy -s ci_settings.xml'
  artifacts:
    when: on_success
    paths:
    - target/*.jar

pages:
  stage: deploy
  image: ubuntu:latest
  before_script:
  - apt-get update
  - apt-get install doxygen graphviz -y 
  script:
  - cd docs
  - doxygen Doxyfile
  - mv html ../public 
  artifacts:
    paths:
    - public
  only:
  - master
