rdf4j-postgis: POSTGIS Class Reference
POSTGIS Class Reference
Static Public Attributes
static final String NAMESPACE ="http://www.opengis.net/ont/geosparql#"
static final ValueFactory factory = SimpleValueFactory.getInstance()
static final IRI ST_DWITHIN3D =factory.createIRI(NAMESPACE, "ST_3DDWithin")
static final IRI ST_CLOSESTPOINT3D =factory.createIRI(NAMESPACE, "ST_ClosestPoint3D")
static final IRI ST_LONGESTLINE3D =factory.createIRI(NAMESPACE, "ST_LongestLine3D")
static final IRI ST_MAXDISTANCE3D =factory.createIRI(NAMESPACE, "ST_MaxDistance3D")
static final IRI ST_SHORTESTLINE3D =factory.createIRI(NAMESPACE, "ST_ShortestLine3D")
static final IRI ST_ACCUM =factory.createIRI(NAMESPACE, "ST_Accum")
static final IRI ST_ADDBAND =factory.createIRI(NAMESPACE, "ST_AddBand")
static final IRI st_addGeometry =factory.createIRI(NAMESPACE, "ST_AddGeometry")
static final IRI st_addInteriorRing =factory.createIRI(NAMESPACE, "ST_AddInteriorRing")
static final IRI st_addMeasure =factory.createIRI(NAMESPACE, "ST_AddMeasure")
static final IRI ST_ADDPOINT =factory.createIRI(NAMESPACE, "ST_AddPoint")
static final IRI ST_ADDZ =factory.createIRI(NAMESPACE, "ST_AddZ")
static final IRI st_angle = factory.createIRI(NAMESPACE,"ST_Angle")
static final IRI ST_ASBINARY =factory.createIRI(NAMESPACE, "ST_AsBinary")
static final IRI ST_ASENCODEDPOLYLINE =factory.createIRI(NAMESPACE, "ST_AsEncodedPolyline")
static final IRI ST_ASHEXEWKB =factory.createIRI(NAMESPACE, "ST_AsHEXEWKB")
static final IRI ST_ASKML =factory.createIRI(NAMESPACE, "ST_AsKML")
static final IRI ST_ASGARS =factory.createIRI(NAMESPACE, "ST_AsGARS")
static final IRI ST_ASGML =factory.createIRI(NAMESPACE, "ST_AsGML")
static final IRI ST_ASGEOHASH =factory.createIRI(NAMESPACE, "ST_AsGeoHash")
static final IRI ST_ASGEOURI =factory.createIRI(NAMESPACE, "ST_AsGeoURI")
static final IRI ST_ASGEOBUF =factory.createIRI(NAMESPACE, "ST_AsGeoBuf")
static final IRI ST_ASGEOJSON =factory.createIRI(NAMESPACE, "ST_AsGeoJSON")
static final IRI ST_ASGEOJSONLD =factory.createIRI(NAMESPACE, "ST_AsGeoJSONLD")
static final IRI ST_ASGEORSS =factory.createIRI(NAMESPACE, "ST_AsGeoRSS")
static final IRI ST_ASGEOTIFF =factory.createIRI(NAMESPACE, "ST_AsGeoTIFF")
static final IRI ST_ASCOVERAGEJSON =factory.createIRI(NAMESPACE, "ST_AsCoverageJSON")
static final IRI ST_ASGMLCOV =factory.createIRI(NAMESPACE, "ST_AsGMLCOV")
static final IRI ST_ASGPX =factory.createIRI(NAMESPACE, "ST_AsGPX")
static final IRI st_aspect =factory.createIRI(NAMESPACE, "ST_Aspect")
static final IRI ST_ASNETCDF =factory.createIRI(NAMESPACE, "ST_AsNetCDF")
static final IRI ST_ASPOLYSHAPE =factory.createIRI(NAMESPACE, "ST_AsPolyshape")
static final IRI ST_ASTIFF =factory.createIRI(NAMESPACE, "ST_AsTIFF")
static final IRI ST_ASTOPOJSON =factory.createIRI(NAMESPACE, "ST_AsTopoJSON")
static final IRI ST_ASJPG =factory.createIRI(NAMESPACE, "ST_AsJPG")
static final IRI ST_ASLATLONTEXT =factory.createIRI(NAMESPACE, "ST_AsLatLonText")
static final IRI ST_ASPNG =factory.createIRI(NAMESPACE, "ST_AsPNG")
static final IRI ST_ASMVT =factory.createIRI(NAMESPACE, "ST_AsMVT")
static final IRI ST_ASMVTGEOM =factory.createIRI(NAMESPACE, "ST_AsMVTGeom")
static final IRI ST_ASSVG =factory.createIRI(NAMESPACE, "ST_AsSVG")
static final IRI ST_ASTEXT =factory.createIRI(NAMESPACE, "ST_AsText")
static final IRI ST_ASTEXTRAW =factory.createIRI(NAMESPACE, "ST_AsTextRaw")
static final IRI ST_ASTEXTROUND =factory.createIRI(NAMESPACE, "ST_AsTextRound")
static final IRI ST_ASTWKB =factory.createIRI(NAMESPACE, "ST_AsTWKB")
static final IRI ST_ASWKB =factory.createIRI(NAMESPACE, "ST_AsWKB")
static final IRI st_asRasterHexWKB = factory.createIRI(NAMESPACE,"ST_AsRasterHexWKB")
static final IRI st_asRasterWKB = factory.createIRI(NAMESPACE,"ST_AsRasterWKB")
static final IRI st_asRaster = factory.createIRI(NAMESPACE,"ST_AsRaster")
static final IRI ST_ASWKT =factory.createIRI(NAMESPACE, "ST_AsWKT")
static final IRI ST_ASX3D =factory.createIRI(NAMESPACE, "ST_AsX3D")
static final IRI ST_AREA =factory.createIRI(NAMESPACE, "ST_Area")
static final IRI ST_AREA3D =factory.createIRI(NAMESPACE, "ST_Area3D")
static final IRI ST_AREASIMILARITY =factory.createIRI(NAMESPACE, "ST_AreaSimilarity")
static final IRI ST_AZIMUTH =factory.createIRI(NAMESPACE, "ST_Azimuth")
static final IRI ST_BANDMAX =factory.createIRI(NAMESPACE, "ST_BandMax")
static final IRI ST_BANDMin =factory.createIRI(NAMESPACE, "ST_BandMin")
static final IRI st_bboxabove =factory.createIRI(NAMESPACE,"ST_BBOXAbove")
static final IRI st_bboxbelow = factory.createIRI(NAMESPACE,"ST_BBOXBelow")
static final IRI st_bboxcontains = factory.createIRI(NAMESPACE,"ST_BBOXContains")
static final IRI st_bboxdistance = factory.createIRI(NAMESPACE,"ST_BBOXDistance")
static final IRI st_bboxequals = factory.createIRI(NAMESPACE, "ST_BBOXEquals")
static final IRI st_bboxfpintersects = factory.createIRI(NAMESPACE, "ST_BBOXFPIntersects")
static final IRI st_bboxintersect = factory.createIRI(NAMESPACE, "ST_BBOXIntersects")
static final IRI st_bboxiscontainedby =factory.createIRI(NAMESPACE, "ST_BBOXIsContainedBy")
static final IRI st_bboxleftof = factory.createIRI(NAMESPACE, "ST_BBOXLeftOf")
static final IRI st_bboxoverlapsabove = factory.createIRI(NAMESPACE, "ST_BBOXOverlapsAbove")
static final IRI st_bboxoverlapsbelow =factory.createIRI(NAMESPACE, "ST_BBOXOverlapsBelow")
static final IRI st_bboxoverlapsleft = factory.createIRI(NAMESPACE ,"ST_BBOXOverlapsLeft")
static final IRI st_bboxoverlapsright = factory.createIRI(NAMESPACE, "ST_BBOXOverlapsRight")
static final IRI st_bboxrightof = factory.createIRI(NAMESPACE, "ST_BBOXRightOf")
static final IRI ST_BAND =factory.createIRI(NAMESPACE, "ST_Band")
static final IRI ST_BANDISNODATA =factory.createIRI(NAMESPACE, "ST_BandIsNoData")
static final IRI ST_BANDMETADATA =factory.createIRI(NAMESPACE, "ST_BandMetaData")
static final IRI ST_BANDNODATAVALUE =factory.createIRI(NAMESPACE, "ST_BandNoDataValue")
static final IRI ST_BANDPIXELTYPE =factory.createIRI(NAMESPACE, "ST_BandPixelType")
static final IRI ST_BEZIERSMOOTHING =factory.createIRI(NAMESPACE, "ST_BezierSmoothing")
static final IRI ST_BOUNDARY =factory.createIRI(NAMESPACE, "ST_Boundary")
static final IRI ST_BOUNDINGDIAGONAL =factory.createIRI(NAMESPACE, "ST_BoundingDiagonal")
static final IRI ST_CENTROID =factory.createIRI(NAMESPACE, "ST_Centroid")
static final IRI ST_CENTROIDDISTANCE =factory.createIRI(NAMESPACE, "ST_CentroidDistance")
static final IRI ST_CHAIKINSMOOTHING =factory.createIRI(NAMESPACE, "ST_ChaikinSmoothing")
static final IRI st_circumcentre =factory.createIRI(NAMESPACE, "ST_Circumcentre")
static final IRI ST_CLIP =factory.createIRI(NAMESPACE, "ST_Clip")
static final IRI ST_CLIPBYBOX2D =factory.createIRI(NAMESPACE, "ST_ClipByBox2D")
static final IRI ST_CLOSESTPOINT =factory.createIRI(NAMESPACE, "ST_ClosestPoint")
static final IRI ST_CLOSESTPOINTOFAPPROACH =factory.createIRI(NAMESPACE, "ST_ClosestPointOfApproach")
static final IRI ST_CLUSTERINTERSECTING =factory.createIRI(NAMESPACE, "ST_ClusterIntersecting")
static final IRI ST_CLUSTERKMEANS =factory.createIRI(NAMESPACE, "ST_ClusterKMeans")
static final IRI ST_CLUSTERWITHIN =factory.createIRI(NAMESPACE, "ST_ClusterWithin")
static final IRI ST_COLLECTIONHOMOGENIZE =factory.createIRI(NAMESPACE, "ST_CollectionHomogenize")
static final IRI st_collectionextract =factory.createIRI(NAMESPACE, "ST_CollectionExtract")
static final IRI ST_COMPACTNESSRATIO =factory.createIRI(NAMESPACE, "ST_CompactnessRatio")
static final IRI ST_CONCAVEHULL =factory.createIRI(NAMESPACE, "ST_ConcaveHull")
static final IRI st_cosinedistance =factory.createIRI(NAMESPACE, "ST_CosineDistance")
static final IRI st_cosinesimilarity =factory.createIRI(NAMESPACE, "ST_CosineSimilarity")
static final IRI ST_CONTAINS =factory.createIRI(NAMESPACE, "ST_Contains")
static final IRI ST_CONTAINSPROPERLY =factory.createIRI(NAMESPACE, "ST_ContainsProperly")
static final IRI ST_CONVEXHULL =factory.createIRI(NAMESPACE, "ST_ConvexHull")
static final IRI ST_COUNT =factory.createIRI(NAMESPACE, "ST_Count")
static final IRI ST_CURVETOLINE =factory.createIRI(NAMESPACE, "ST_CurveToLine")
static final IRI st_circularity =factory.createIRI(NAMESPACE, "ST_Circularity")
static final IRI st_curvature =factory.createIRI(NAMESPACE, "ST_Curvature")
static final IRI st_crop =factory.createIRI(NAMESPACE, "ST_Crop")
static final IRI ST_DENSIFY =factory.createIRI(NAMESPACE, "ST_Densify")
static final IRI ST_DELAUNAYTRIANGLES =factory.createIRI(NAMESPACE, "ST_DelaunayTriangles")
static final IRI ST_DIMENSION =factory.createIRI(NAMESPACE, "ST_Dimension")
static final IRI ST_DISTANCE =factory.createIRI(NAMESPACE, "ST_Distance")
static final IRI ST_DISTANCE3D =factory.createIRI(NAMESPACE, "ST_Distance3D")
static final IRI ST_DISTANCESPHERE =factory.createIRI(NAMESPACE, "ST_DistanceSphere")
static final IRI st_dissolvepoints =factory.createIRI(NAMESPACE, "ST_DissolvePoints")
static final IRI st_dissolvesegments =factory.createIRI(NAMESPACE, "ST_DissolveSegments")
static final IRI st_dump =factory.createIRI(NAMESPACE, "ST_Dump")
static final IRI st_dumprings =factory.createIRI(NAMESPACE, "ST_DumpRings")
static final IRI ST_DWITHIN =factory.createIRI(NAMESPACE, "ST_DWithin")
static final IRI ST_ENDPOINT =factory.createIRI(NAMESPACE, "ST_EndPoint")
static final IRI st_ensureClosed =factory.createIRI(NAMESPACE, "ST_EnsureClosed")
static final IRI ST_EQUALS =factory.createIRI(NAMESPACE, "ST_Equals")
static final IRI ST_EQUALSNORM =factory.createIRI(NAMESPACE, "ST_EqualsNorm")
static final IRI ST_EQUALSTOPO =factory.createIRI(NAMESPACE, "ST_EqualsTopo")
static final IRI ST_EQUALSRS =factory.createIRI(NAMESPACE, "ST_EqualSRS")
static final IRI ST_EPSGTOSRID =factory.createIRI(NAMESPACE, "ST_EPSGToSRID")
static final IRI ST_FILTERBYM =factory.createIRI(NAMESPACE, "ST_FilterByM")
static final IRI ST_FILTERBYT =factory.createIRI(NAMESPACE, "ST_FilterByT")
static final IRI st_flip =factory.createIRI(NAMESPACE, "ST_Flip")
static final IRI ST_FLIPCOORDINATES =factory.createIRI(NAMESPACE, "ST_FlipCoordinates")
static final IRI ST_flowdirection =factory.createIRI(NAMESPACE, "ST_FlowDirection")
static final IRI st_ensureClosedRings =factory.createIRI(NAMESPACE, "ST_EnsureClosedRings")
static final IRI st_equals =factory.createIRI(NAMESPACE, "ST_Equals")
static final IRI st_equalsNorm =factory.createIRI(NAMESPACE, "ST_EqualNorm")
static final IRI st_equalsTopo =factory.createIRI(NAMESPACE, "ST_EqualTopo")
static final IRI st_equalType =factory.createIRI(NAMESPACE, "ST_EqualType")
static final IRI st_equalSRS =factory.createIRI(NAMESPACE, "ST_EqualSRS")
static final IRI st_epsgToSRID =factory.createIRI(NAMESPACE, "ST_EPSGToSRID")
static final IRI st_expand =factory.createIRI(NAMESPACE, "ST_Expand")
static final IRI st_exteriorRing =factory.createIRI(NAMESPACE, "ST_ExteriorRing")
static final IRI st_filterByM =factory.createIRI(NAMESPACE, "ST_FilterByM")
static final IRI st_filterByT =factory.createIRI(NAMESPACE, "ST_FilterByT")
static final IRI st_flipCoordinates =factory.createIRI(NAMESPACE, "ST_FlipCoordinates")
static final IRI st_force2d =factory.createIRI(NAMESPACE, "ST_Force2D")
static final IRI st_force3d =factory.createIRI(NAMESPACE, "ST_Force3D")
static final IRI st_force3dm =factory.createIRI(NAMESPACE, "ST_Force3DM")
static final IRI st_force3dz =factory.createIRI(NAMESPACE, "ST_Force3D")
static final IRI st_force4d =factory.createIRI(NAMESPACE, "ST_Force4D")
static final IRI st_forceCollection =factory.createIRI(NAMESPACE, "ST_ForceCollection")
static final IRI st_forceCurve =factory.createIRI(NAMESPACE, "ST_ForceCurve")
static final IRI st_forceLHR =factory.createIRI(NAMESPACE, "ST_ForceLHR")
static final IRI st_forcePolygonCW =factory.createIRI(NAMESPACE, "ST_ForcePolygonCW")
static final IRI st_forcePolygonCCW =factory.createIRI(NAMESPACE, "ST_ForcePolygonCCW")
static final IRI st_forceSFS =factory.createIRI(NAMESPACE, "ST_ForceSFS")
static final IRI st_frechetDistance =factory.createIRI(NAMESPACE, "ST_FrechetDistance")
static final IRI st_furthestcoordinate =factory.createIRI(NAMESPACE, "ST_FurthestCoordinate")
static final IRI st_fullyWithinDistance3D =factory.createIRI(NAMESPACE, "ST_FullyWithinDistance3D")
static final IRI st_generatePoints =factory.createIRI(NAMESPACE, "ST_GeneratePoints")
static final IRI st_geohash =factory.createIRI(NAMESPACE, "ST_AsGeoHash")
static final IRI st_geomCollFromText = factory.createIRI(NAMESPACE,"ST_GeomCollFromText")
static final IRI st_geomFromGeoJSON =factory.createIRI(NAMESPACE, "ST_GeomFromGeoJSON")
static final IRI st_geomFromGeoHash =factory.createIRI(NAMESPACE, "ST_GeomFromGeoHash")
static final IRI st_geomFromGML =factory.createIRI(NAMESPACE, "ST_GeomFromGML")
static final IRI st_geomFromKML =factory.createIRI(NAMESPACE, "ST_GeomFromKML")
static final IRI st_geomFromWKB =factory.createIRI(NAMESPACE, "ST_GeomFromWKB")
static final IRI st_geomFromText =factory.createIRI(NAMESPACE, "ST_GeomFromText")
static final IRI st_geometricMedian =factory.createIRI(NAMESPACE, "ST_GeometricMedian")
static final IRI st_geometryN =factory.createIRI(NAMESPACE, "ST_GeometryN")
static final IRI st_geometryType =factory.createIRI(NAMESPACE, "ST_GeometryType")
static final IRI st_gmlToSQL =factory.createIRI(NAMESPACE, "ST_GeomFromGML")
static final IRI st_hasConnectedInterior =factory.createIRI(NAMESPACE, "ST_HasConnectedInterior")
static final IRI st_hasDuplicateRings =factory.createIRI(NAMESPACE, "ST_HasDuplicateRings")
static final IRI st_hasNestedRings =factory.createIRI(NAMESPACE, "ST_HasNestedRings")
static final IRI st_hasNoBand =factory.createIRI(NAMESPACE, "ST_HasNoBand")
static final IRI ST_hasHorizontalCRS =factory.createIRI(NAMESPACE, "ST_HasHorizontalCRS")
static final IRI st_hasRepeatedPoints =factory.createIRI(NAMESPACE, "ST_HasRepeatedPoints")
static final IRI ST_hasSelfIntersections = factory.createIRI(NAMESPACE, "ST_HasSelfIntersections")
static final IRI st_hausdorffDistance =factory.createIRI(NAMESPACE, "ST_HausdorffDistance")
static final IRI st_height =factory.createIRI(NAMESPACE, "ST_Height")
static final IRI st_hillshade =factory.createIRI(NAMESPACE, "ST_Hillshade")
static final IRI st_histogram = factory.createIRI(NAMESPACE,"ST_Histogram")
static final IRI st_interiorRingN =factory.createIRI(NAMESPACE, "ST_InteriorRingN")
static final IRI st_interpolatePoint =factory.createIRI(NAMESPACE, "ST_InterpolatePoint")
static final IRI st_intersectionMatrix =factory.createIRI(NAMESPACE, "ST_IntersectionMatrix")
static final IRI st_intersectionPercentage =factory.createIRI(NAMESPACE, "ST_IntersectionPercentage")
static final IRI st_is3D =factory.createIRI(NAMESPACE, "ST_Is3D")
static final IRI st_isAcute =factory.createIRI(NAMESPACE, "ST_IsAcute")
static final IRI st_isCollection =factory.createIRI(NAMESPACE, "ST_IsCollection")
static final IRI st_isClosed =factory.createIRI(NAMESPACE, "ST_IsClosed")
static final IRI st_isConvex =factory.createIRI(NAMESPACE, "ST_IsConvex")
static final IRI st_isDegenerate =factory.createIRI(NAMESPACE, "ST_IsDegenerate")
static final IRI st_isEmpty =factory.createIRI(NAMESPACE, "ST_IsEmpty")
static final IRI st_isEquilateralTriangle =factory.createIRI(NAMESPACE, "ST_IsEquilateralTriangle")
static final IRI st_isGrayscale =factory.createIRI(NAMESPACE, "ST_IsGrayscale")
static final IRI st_isInCRSAreaOfValidity =factory.createIRI(NAMESPACE, "ST_IsInCRSAreaOfValidity")
static final IRI st_isIndexed =factory.createIRI(NAMESPACE, "ST_IsIndexed")
static final IRI st_isIsocelesTriangle =factory.createIRI(NAMESPACE, "ST_IsIsocelesTriangle")
static final IRI st_isLocationOnEdge =factory.createIRI(NAMESPACE, "ST_IsLocationOnEdge")
static final IRI st_isMeasured =factory.createIRI(NAMESPACE, "ST_IsMeasured")
static final IRI st_isMorePrecise =factory.createIRI(NAMESPACE, "ST_IsMorePrecise")
static final IRI st_isNodingValid =factory.createIRI(NAMESPACE, "ST_IsNodingValid")
static final IRI st_isOpaquePixel =factory.createIRI(NAMESPACE, "ST_IsOpaquePixel")
static final IRI st_isPlanar = factory.createIRI(NAMESPACE, "ST_IsPlanar")
static final IRI st_isPointOnLine =factory.createIRI(NAMESPACE, "ST_IsPointOnLine")
static final IRI st_isPointInRing =factory.createIRI(NAMESPACE, "ST_IsPointInRing")
static final IRI st_isPolygonCW =factory.createIRI(NAMESPACE, "ST_IsPolygonCW")
static final IRI st_isPolygonCCW =factory.createIRI(NAMESPACE, "ST_IsPolygonCCW")
static final IRI st_isRectangle =factory.createIRI(NAMESPACE, "ST_IsRectangle")
static final IRI st_isRightTriangle =factory.createIRI(NAMESPACE, "ST_IsRightTriangle")
static final IRI st_isRing =factory.createIRI(NAMESPACE, "ST_IsRing")
static final IRI st_isSimple =factory.createIRI(NAMESPACE, "ST_IsSimpleFF")
static final IRI st_isSolid = factory.createIRI(NAMESPACE, "ST_IsSolid")
static final IRI st_isSquare = factory.createIRI(NAMESPACE, "ST_IsSquare")
static final IRI st_isTiled =factory.createIRI(NAMESPACE, "ST_IsTiled")
static final IRI st_isTranslucent =factory.createIRI(NAMESPACE, "ST_IsTranslucent")
static final IRI st_isTransparentPixel =factory.createIRI(NAMESPACE, "ST_IsTransparentPixel")
static final IRI st_isTriangle = factory.createIRI(NAMESPACE, "ST_IsTriangle")
static final IRI st_isValid =factory.createIRI(NAMESPACE, "ST_IsValidFF")
static final IRI st_isValidTrajectory =factory.createIRI(NAMESPACE, "ST_IsValidTrajectory")
static final IRI st_isValidReason =factory.createIRI(NAMESPACE, "ST_IsValidReason")
static final IRI st_isValidDetail =factory.createIRI(NAMESPACE, "ST_IsValidDetail")
static final IRI st_Length =factory.createIRI(NAMESPACE, "ST_Length")
static final IRI st_Length2D =factory.createIRI(NAMESPACE, "ST_Length")
static final IRI st_Length3D =factory.createIRI(NAMESPACE, "ST_Length3D")
static final IRI st_LengthToPoint =factory.createIRI(NAMESPACE, "ST_LengthToPoint")
static final IRI st_lineCrossingDirection =factory.createIRI(NAMESPACE, "ST_LineCrossingDirection")
static final IRI st_lineFromEncodedPolyline =factory.createIRI(NAMESPACE, "ST_LineFromEncodedPolyline")
static final IRI st_lineFromMultiPoint =factory.createIRI(NAMESPACE, "ST_LineFromMultiPoint")
static final IRI st_lineFromWKB =factory.createIRI(NAMESPACE, "ST_LineFromWKB")
static final IRI st_lineFromWKT =factory.createIRI(NAMESPACE, "ST_LineFromText")
static final IRI st_lineFromText =factory.createIRI(NAMESPACE, "ST_LineFromText")
static final IRI st_lineInterpolatePoint =factory.createIRI(NAMESPACE, "ST_LineInterpolatePoint")
static final IRI st_lineInterpolatePoints =factory.createIRI(NAMESPACE, "ST_LineInterpolatePoints")
static final IRI st_lineLocatePoint =factory.createIRI(NAMESPACE, "ST_LineLocatePoint")
static final IRI st_lineLength3D =factory.createIRI(NAMESPACE, "ST_LineLength3D")
static final IRI st_lineMerge =factory.createIRI(NAMESPACE, "ST_LineMerge")
static final IRI st_lineSelfIntersectionPoint =factory.createIRI(NAMESPACE, "ST_LineSelfIntersectionPoint")
static final IRI st_lineSubstring =factory.createIRI(NAMESPACE, "ST_LineSubstring")
static final IRI st_lineToCurve =factory.createIRI(NAMESPACE, "ST_LineToCurve")
static final IRI st_linesCutAtNodes =factory.createIRI(NAMESPACE, "ST_LinesCutAtNodes")
static final IRI st_linesFromRings =factory.createIRI(NAMESPACE, "ST_LinesFromRings")
static final IRI st_locateAlong =factory.createIRI(NAMESPACE, "ST_LocateAlong")
static final IRI st_locateBetween =factory.createIRI(NAMESPACE, "ST_LocateBetween")
static final IRI st_locateBetweenElevations =factory.createIRI(NAMESPACE, "ST_LocateBetweenElevations")
static final IRI st_longestLine =factory.createIRI(NAMESPACE, "ST_LongestLine")
static final IRI st_m =factory.createIRI(NAMESPACE, "ST_M")
static final IRI st_maxDistance =factory.createIRI(NAMESPACE, "ST_MaxDistance")
static final IRI st_maxDistance3D =factory.createIRI(NAMESPACE, "ST_MaxDistance3D")
static final IRI st_makeBox2D =factory.createIRI(NAMESPACE, "ST_MakeBox2D")
static final IRI st_makeBox3D =factory.createIRI(NAMESPACE, "ST_MakeBox3D")
static final IRI st_makeCircle =factory.createIRI(NAMESPACE, "ST_MakeCircle")
static final IRI st_makeEllipse =factory.createIRI(NAMESPACE, "ST_MakeEllipse")
static final IRI st_makeEmptyCoverage =factory.createIRI(NAMESPACE, "ST_MakeEmptyCoverage")
static final IRI st_makeEmptyRaster =factory.createIRI(NAMESPACE, "ST_MakeEmptyRaster")
static final IRI st_makeEnvelope =factory.createIRI(NAMESPACE, "ST_MakeEnvelope")
static final IRI st_makeLine =factory.createIRI(NAMESPACE, "ST_MakeLine")
static final IRI st_makePoint =factory.createIRI(NAMESPACE, "ST_MakePoint")
static final IRI st_makePointM =factory.createIRI(NAMESPACE, "ST_MakePointM")
static final IRI st_makePolygon =factory.createIRI(NAMESPACE, "ST_MakePolygon")
static final IRI st_makeValid =factory.createIRI(NAMESPACE, "ST_MakeValid")
static final IRI st_makeValidDiscarded =factory.createIRI(NAMESPACE, "ST_MakeValidDiscarded")
static final IRI st_memsize =factory.createIRI(NAMESPACE, "ST_MemSize")
static final IRI st_minkowskidistance =factory.createIRI(NAMESPACE, "ST_MinkowskiDistance")
static final IRI st_minimumBoundingCircle =factory.createIRI(NAMESPACE, "ST_MinimumBoundingCircle")
static final IRI st_minimumBoundingCircleCenter =factory.createIRI(NAMESPACE, "ST_MinimumBoundingCircleCenter")
static final IRI st_minimumBoundingRadius =factory.createIRI(NAMESPACE, "ST_MinimumBoundingRadius")
static final IRI st_minimumClearance =factory.createIRI(NAMESPACE, "ST_MinimumClearance")
static final IRI st_minimumClearanceLine =factory.createIRI(NAMESPACE, "ST_MinimumClearanceLine")
static final IRI st_minimumDiameter =factory.createIRI(NAMESPACE, "ST_MinimumDiameter")
static final IRI st_minimumDiameterLine =factory.createIRI(NAMESPACE, "ST_MinimumDiameterLine")
static final IRI st_minimumRectangle =factory.createIRI(NAMESPACE, "ST_MinimumRectangle")
static final IRI st_minConvexHull =factory.createIRI(NAMESPACE, "ST_MinConvexHull")
static final IRI st_minTileX =factory.createIRI(NAMESPACE, "ST_MinTileX")
static final IRI st_minTileY =factory.createIRI(NAMESPACE, "ST_MinTileY")
static final IRI st_rast_minX = factory.createIRI(NAMESPACE, "ST_MinX")
static final IRI st_rast_maxX = factory.createIRI(NAMESPACE, "ST_MaxX")
static final IRI st_rast_minY = factory.createIRI(NAMESPACE, "ST_MinY")
static final IRI st_rast_maxY = factory.createIRI(NAMESPACE, "ST_MaxY")
static final IRI st_manhattandistance = factory.createIRI(NAMESPACE, "ST_ManhattanDistance")
static final IRI st_mirror =factory.createIRI(NAMESPACE, "ST_Mirror")
static final IRI st_mLineFromText =factory.createIRI(NAMESPACE, "ST_MLineFromText")
static final IRI st_mMin =factory.createIRI(NAMESPACE, "ST_MMin")
static final IRI st_mMax =factory.createIRI(NAMESPACE, "ST_MMax")
static final IRI st_mPointFromText =factory.createIRI(NAMESPACE, "ST_MPointFromText")
static final IRI st_mPolyFromText =factory.createIRI(NAMESPACE, "ST_MPolyFromText")
static final IRI st_multi =factory.createIRI(NAMESPACE, "ST_Multi")
static final IRI st_multiplyz =factory.createIRI(NAMESPACE, "ST_MultiplyZ")
static final IRI st_nearestValue =factory.createIRI(NAMESPACE, "ST_NearestValue")
static final IRI st_numBands =factory.createIRI(NAMESPACE, "ST_NumBands")
static final IRI st_numDataElements =factory.createIRI(NAMESPACE, "ST_NumDataElements")
static final IRI st_numDistinctGeometries =factory.createIRI(NAMESPACE, "ST_NumDistinctGeometries")
static final IRI st_numDistinctPoints =factory.createIRI(NAMESPACE, "ST_NumDistinctPoints")
static final IRI st_numGeometries =factory.createIRI(NAMESPACE, "ST_NumGeometries")
static final IRI st_numDistinctInteriorRings =factory.createIRI(NAMESPACE, "ST_NumDistinctInteriorRings")
static final IRI st_numInteriorRings =factory.createIRI(NAMESPACE, "ST_NumInteriorRings")
static final IRI st_numPatches =factory.createIRI(NAMESPACE, "ST_NumPatches")
static final IRI st_numPoints =factory.createIRI(NAMESPACE, "ST_NumPoints")
static final IRI st_numXTiles =factory.createIRI(NAMESPACE, "ST_NumXTiles")
static final IRI st_numYTiles =factory.createIRI(NAMESPACE, "ST_NumYTiles")
static final IRI st_nDims =factory.createIRI(NAMESPACE, "ST_NDims")
static final IRI st_nPoints =factory.createIRI(NAMESPACE, "ST_NumPoints")
static final IRI st_nRings =factory.createIRI(NAMESPACE, "ST_NRings")
static final IRI st_nodataPixelCount =factory.createIRI(NAMESPACE, "ST_NoDataPixelCount")
static final IRI st_node =factory.createIRI(NAMESPACE, "ST_Node")
static final IRI st_normalize =factory.createIRI(NAMESPACE, "ST_Normalize")
static final IRI st_octogonalEnvelope =factory.createIRI(NAMESPACE, "ST_OctogonalEnvelope")
static final IRI st_offsetCurve =factory.createIRI(NAMESPACE, "ST_OffsetCurve")
static final IRI st_orientation =factory.createIRI(NAMESPACE, "ST_Orientation")
static final IRI st_orderingEquals =factory.createIRI(NAMESPACE, "ST_OrderingEquals")
static final IRI st_osmlink =factory.createIRI(NAMESPACE, "ST_AsOSMLink")
static final IRI st_patchN =factory.createIRI(NAMESPACE, "ST_PatchN")
static final IRI st_partOfGeometryAfter =factory.createIRI(NAMESPACE, "ST_PartOfGeometryAfter")
static final IRI st_partOfGeometryBefore =factory.createIRI(NAMESPACE, "ST_PartOfGeometryBefore")
static final IRI st_perimeter =factory.createIRI(NAMESPACE, "ST_Perimeter")
static final IRI st_perimeter2D =factory.createIRI(NAMESPACE, "ST_Perimeter")
static final IRI st_perimeter3D =factory.createIRI(NAMESPACE, "ST_Perimeter3D")
static final IRI st_pixelAsCentroid =factory.createIRI(NAMESPACE, "ST_PixelAsCentroid")
static final IRI st_pixelAsCentroids =factory.createIRI(NAMESPACE, "ST_PixelAsCentroids")
static final IRI st_pixelAsPoint =factory.createIRI(NAMESPACE, "ST_PixelAsPoint")
static final IRI st_pixelAsPoints =factory.createIRI(NAMESPACE, "ST_PixelAsPoints")
static final IRI st_pixelAsPolygon =factory.createIRI(NAMESPACE, "ST_PixelAsPolygon")
static final IRI st_pixelAsPolygons =factory.createIRI(NAMESPACE, "ST_PixelAsPolygons")
static final IRI st_pixelHeight =factory.createIRI(NAMESPACE, "ST_PixelHeight")
static final IRI st_pixelOfValue =factory.createIRI(NAMESPACE, "ST_PixelOfValue")
static final IRI st_pixelWidth =factory.createIRI(NAMESPACE, "ST_PixelWidth")
static final IRI st_points =factory.createIRI(NAMESPACE, "ST_Points")
static final IRI st_pointN =factory.createIRI(NAMESPACE, "ST_PointN")
static final IRI st_pointFromGeoHash =factory.createIRI(NAMESPACE, "ST_PointFromGeoHash")
static final IRI st_pointFromWKB =factory.createIRI(NAMESPACE, "ST_PointFromWKB")
static final IRI st_pointFromText =factory.createIRI(NAMESPACE, "ST_PointFromText")
static final IRI st_pointInsideCircle =factory.createIRI(NAMESPACE, "ST_PointInsideCircle")
static final IRI st_pointOnSurface =factory.createIRI(NAMESPACE, "ST_PointOnSurface")
static final IRI st_polygon =factory.createIRI(NAMESPACE, "ST_Polygon")
static final IRI st_polygonize =factory.createIRI(NAMESPACE, "ST_Polygonize")
static final IRI st_polygonFromText =factory.createIRI(NAMESPACE, "ST_PolygonFromText")
static final IRI st_polygonFromWKB =factory.createIRI(NAMESPACE, "ST_PolygonFromWKB")
static final IRI st_precisionReducer =factory.createIRI(NAMESPACE, "ST_PrecisionReducer")
static final IRI st_rastFromCovJSON =factory.createIRI(NAMESPACE,"ST_RastFromCovJSON")
static final IRI st_rastFromGMLCOV =factory.createIRI(NAMESPACE,"ST_RastFromGMLCOV")
static final IRI st_rastFromNetCDF =factory.createIRI(NAMESPACE,"ST_RastFromNetCDF")
static final IRI st_rastFromWKB =factory.createIRI(NAMESPACE, "ST_RastFromWKB")
static final IRI st_rastFromHexWKB =factory.createIRI(NAMESPACE, "ST_RastFromHexWKB")
static final IRI ST_rast_algebra_abs = factory.createIRI(NAMESPACE, "ST_Abs")
static final IRI ST_rast_algebra_add =factory.createIRI(NAMESPACE, "ST_Add")
static final IRI ST_rast_algebra_addconst =factory.createIRI(NAMESPACE, "ST_AddConst")
static final IRI ST_rast_algebra_and =factory.createIRI(NAMESPACE, "ST_And")
static final IRI ST_rast_algebra_andconst =factory.createIRI(NAMESPACE, "ST_AndConst")
static final IRI ST_rast_algebra_equal =factory.createIRI(NAMESPACE, "ST_Equal")
static final IRI ST_rast_algebra_exp =factory.createIRI(NAMESPACE, "ST_Exp")
static final IRI ST_rast_algebra_idct =factory.createIRI(NAMESPACE, "ST_IDCT")
static final IRI ST_rast_algebra_idft =factory.createIRI(NAMESPACE, "ST_IDFT")
static final IRI ST_rast_algebra_subtract =factory.createIRI(NAMESPACE, "ST_Subtract")
static final IRI ST_rast_algebra_subtractconst =factory.createIRI(NAMESPACE, "ST_SubtractConst")
static final IRI ST_rast_algebra_div =factory.createIRI(NAMESPACE, "ST_Divide")
static final IRI ST_rast_algebra_divconst =factory.createIRI(NAMESPACE, "ST_DivideConst")
static final IRI ST_rast_algebra_invert =factory.createIRI(NAMESPACE, "ST_Invert")
static final IRI ST_rast_algebra_log =factory.createIRI(NAMESPACE, "ST_Log")
static final IRI ST_rast_algebra_or =factory.createIRI(NAMESPACE, "ST_Or")
static final IRI ST_rast_algebra_orconst =factory.createIRI(NAMESPACE, "ST_OrConst")
static final IRI ST_rast_algebra_max =factory.createIRI(NAMESPACE, "ST_Max")
static final IRI ST_rast_algebra_maxfilter =factory.createIRI(NAMESPACE, "ST_MaxFilter")
static final IRI ST_rast_algebra_mean =factory.createIRI(NAMESPACE, "ST_Mean")
static final IRI ST_rast_algebra_medianfilter =factory.createIRI(NAMESPACE, "ST_MedianFilter")
static final IRI ST_rast_algebra_min =factory.createIRI(NAMESPACE, "ST_Min")
static final IRI ST_rast_algebra_minfilter =factory.createIRI(NAMESPACE, "ST_MinFilter")
static final IRI ST_rast_algebra_mult =factory.createIRI(NAMESPACE, "ST_Mult")
static final IRI ST_rast_algebra_multconst =factory.createIRI(NAMESPACE, "ST_MultConst")
static final IRI ST_rast_algebra_not =factory.createIRI(NAMESPACE, "ST_Not")
static final IRI ST_rast_algebra_xor =factory.createIRI(NAMESPACE, "ST_Xor")
static final IRI ST_rast_algebra_xorconst =factory.createIRI(NAMESPACE, "ST_XorConst")
static final IRI st_rast_isEmpty =factory.createIRI(NAMESPACE, "ST_IsEmpty")
static final IRI st_rast_Contains =factory.createIRI(NAMESPACE, "ST_Contains")
static final IRI st_rast_Covers =factory.createIRI(NAMESPACE, "ST_Covers")
static final IRI st_rast_CoveredBy =factory.createIRI(NAMESPACE, "ST_CoveredBy")
static final IRI st_rast_Crosses =factory.createIRI(NAMESPACE, "ST_Crosses")
static final IRI st_rast_Disjoint =factory.createIRI(NAMESPACE, "ST_Disjoint")
static final IRI st_rast_DWithin = factory.createIRI(NAMESPACE, "ST_DWithin")
static final IRI st_rast_DFullyWithin = factory.createIRI(NAMESPACE, "ST_DFullyWithin")
static final IRI st_rast_Intersects =factory.createIRI(NAMESPACE, "ST_Intersects")
static final IRI st_rast_Intersection =factory.createIRI(NAMESPACE, "ST_Intersection")
static final IRI st_rast_Overlaps =factory.createIRI(NAMESPACE, "ST_Overlaps")
static final IRI st_rast_SameAlignment = factory.createIRI(NAMESPACE, "ST_SameAlignment")
static final IRI st_rast_srid =factory.createIRI(NAMESPACE, "ST_SRID")
static final IRI st_rast_Touches =factory.createIRI(NAMESPACE, "ST_Touches")
static final IRI st_rast_Within =factory.createIRI(NAMESPACE, "ST_Within")
static final IRI st_rasterToWorldCoord =factory.createIRI(NAMESPACE, "ST_RasterToWorldCoord")
static final IRI st_rasterToWorldCoordX =factory.createIRI(NAMESPACE, "ST_RasterToWorldCoordX")
static final IRI st_rasterToWorldCoordY =factory.createIRI(NAMESPACE, "ST_RasterToWorldCoordY")
static final IRI st_rayCrossings =factory.createIRI(NAMESPACE, "ST_RayCrossings")
static final IRI st_reflect =factory.createIRI(NAMESPACE, "ST_Reflect")
static final IRI st_relate =factory.createIRI(NAMESPACE, "ST_Relate")
static final IRI st_relateMatch =factory.createIRI(NAMESPACE, "ST_RelateMatch")
static final IRI st_removeGeometry =factory.createIRI(NAMESPACE, "ST_RemoveGeometry")
static final IRI st_removeInteriorRing =factory.createIRI(NAMESPACE, "ST_RemoveInteriorRing")
static final IRI st_removePoint =factory.createIRI(NAMESPACE, "ST_RemovePoint")
static final IRI st_removePoints =factory.createIRI(NAMESPACE, "ST_RemovePoints")
static final IRI st_removeRepeatedPoints =factory.createIRI(NAMESPACE, "ST_RemoveRepeatedPoints")
static final IRI st_reskew =factory.createIRI(NAMESPACE, "ST_Reskew")
static final IRI st_resample =factory.createIRI(NAMESPACE, "ST_Resample")
static final IRI st_rescale =factory.createIRI(NAMESPACE, "ST_Rescale")
static final IRI st_resize =factory.createIRI(NAMESPACE, "ST_Resize")
static final IRI st_retile =factory.createIRI(NAMESPACE, "ST_Retile")
static final IRI st_reverse =factory.createIRI(NAMESPACE, "ST_Reverse")
static final IRI st_reverseRing =factory.createIRI(NAMESPACE, "ST_ReverseRing")
static final IRI st_ringsCutAtNodes =factory.createIRI(NAMESPACE, "ST_RingsCutAtNodes")
static final IRI st_rotate =factory.createIRI(NAMESPACE, "ST_Rotate")
static final IRI st_rotateX =factory.createIRI(NAMESPACE, "ST_RotateX")
static final IRI st_rotateY =factory.createIRI(NAMESPACE, "ST_RotateY")
static final IRI st_rotateZ =factory.createIRI(NAMESPACE, "ST_RotateZ")
static final IRI st_rotation =factory.createIRI(NAMESPACE, "ST_Rotation")
static final IRI st_roughness =factory.createIRI(NAMESPACE, "ST_Roughness")
static final IRI st_scale =factory.createIRI(NAMESPACE, "ST_Scale")
static final IRI st_scaleX =factory.createIRI(NAMESPACE, "ST_ScaleX")
static final IRI st_scaleY =factory.createIRI(NAMESPACE, "ST_ScaleY")
static final IRI st_shearTransformation =factory.createIRI(NAMESPACE, "ST_ShearTransformation")
static final IRI st_segmentize =factory.createIRI(NAMESPACE, "ST_Segmentize")
static final IRI ST_selfIntersections =factory.createIRI(NAMESPACE, "ST_SelfIntersections")
static final IRI st_setBandNoDataValue = factory.createIRI(NAMESPACE, "ST_SetBandNoDataValue")
static final IRI st_setEndPoint =factory.createIRI(NAMESPACE, "ST_SetEndPoint")
static final IRI st_setGeometry =factory.createIRI(NAMESPACE, "ST_SetGeometry")
static final IRI st_setScale =factory.createIRI(NAMESPACE, "ST_SetScale")
static final IRI st_setSkew =factory.createIRI(NAMESPACE, "ST_SetSkew")
static final IRI st_setStartPoint =factory.createIRI(NAMESPACE, "ST_SetStartPoint")
static final IRI st_setRotation =factory.createIRI(NAMESPACE, "ST_SetRotation")
static final IRI st_setGeoReference =factory.createIRI(NAMESPACE, "ST_SetGeoReference")
static final IRI st_setInteriorRing =factory.createIRI(NAMESPACE, "ST_SetInteriorRing")
static final IRI st_setUpperLeft =factory.createIRI(NAMESPACE, "ST_SetUpperLeft")
static final IRI st_setPoint =factory.createIRI(NAMESPACE, "ST_SetPoint")
static final IRI st_setSRID =factory.createIRI(NAMESPACE, "ST_SetSRID")
static final IRI st_shift =factory.createIRI(NAMESPACE, "ST_Shift")
static final IRI st_simplify =factory.createIRI(NAMESPACE, "ST_Simplify")
static final IRI st_simplifyPreserveTopology =factory.createIRI(NAMESPACE, "ST_SimplifyPreserveTopology")
static final IRI st_simplifyVW =factory.createIRI(NAMESPACE, "ST_SimplifyVW")
static final IRI st_sharedPaths =factory.createIRI(NAMESPACE, "ST_SharedPaths")
static final IRI st_shearx =factory.createIRI(NAMESPACE, "ST_ShearX")
static final IRI st_sheary =factory.createIRI(NAMESPACE, "ST_ShearY")
static final IRI st_shiftLongitude =factory.createIRI(NAMESPACE, "ST_ShiftLongitude")
static final IRI st_shortestLine =factory.createIRI(NAMESPACE, "ST_ShortestLine")
static final IRI st_shortestLine3D =factory.createIRI(NAMESPACE, "ST_ShortestLine3D")
static final IRI st_slope =factory.createIRI(NAMESPACE, "ST_Slope")
static final IRI st_skewX =factory.createIRI(NAMESPACE, "ST_SkewX")
static final IRI st_skewY =factory.createIRI(NAMESPACE, "ST_SkewY")
static final IRI st_snap =factory.createIRI(NAMESPACE, "ST_Snap")
static final IRI st_split =factory.createIRI(NAMESPACE, "ST_Split")
static final IRI st_srid =factory.createIRI(NAMESPACE, "ST_GetSRIDFF")
static final IRI st_sridToEPSG =factory.createIRI(NAMESPACE, "ST_SRIDToEPSG")
static final IRI st_startPoint =factory.createIRI(NAMESPACE, "ST_StartPoint")
static final IRI st_straightSkeleton =factory.createIRI(NAMESPACE, "ST_StraightSkeleton")
static final IRI st_subdividelines = factory.createIRI(NAMESPACE, "ST_SubdivideLines")
static final IRI st_summary =factory.createIRI(NAMESPACE, "ST_Summary")
static final IRI st_swapOrdinates =factory.createIRI(NAMESPACE, "ST_SwapOrdinates")
static final IRI st_symDifference =factory.createIRI(NAMESPACE, "ST_SymDifference")
static final IRI st_tesselate =factory.createIRI(NAMESPACE, "ST_Tesselate")
static final IRI st_t =factory.createIRI(NAMESPACE, "ST_T")
static final IRI st_tileGridXOffset = factory.createIRI(NAMESPACE, "ST_TileGridXOffset")
static final IRI st_tileGridYOffset = factory.createIRI(NAMESPACE, "ST_TileGridYOffset")
static final IRI st_tileHeight = factory.createIRI(NAMESPACE, "ST_TileHeight")
static final IRI st_tileWidth = factory.createIRI(NAMESPACE, "ST_TileWidth")
static final IRI st_tMin =factory.createIRI(NAMESPACE, "ST_TMin")
static final IRI st_tMax =factory.createIRI(NAMESPACE, "ST_TMax")
static final IRI st_tpi =factory.createIRI(NAMESPACE, "ST_TPI")
static final IRI st_tri =factory.createIRI(NAMESPACE, "ST_TRI")
static final IRI st_trajectoryInterpolatePoint =factory.createIRI(NAMESPACE, "ST_TrajectoryInterpolatePoint")
static final IRI st_transscale =factory.createIRI(NAMESPACE, "ST_TransScale")
static final IRI st_translate =factory.createIRI(NAMESPACE, "ST_Translate")
static final IRI st_translatex =factory.createIRI(NAMESPACE, "ST_TranslateX")
static final IRI st_translatey =factory.createIRI(NAMESPACE, "ST_TranslateY")
static final IRI st_transform =factory.createIRI(NAMESPACE, "ST_Transform")
static final IRI ST_Topo_AddPoint = factory.createIRI(NAMESPACE, "ST_Topo_AddPoint")
static final IRI ST_Topo_AddLineString = factory.createIRI(NAMESPACE, "ST_Topo_AddLineString")
static final IRI ST_TopologyFromTopoJSON = factory.createIRI(NAMESPACE, "ST_TopologyFromTopoJSON")
static final IRI st_toRaster = factory.createIRI(NAMESPACE, "ST_ToRaster")
static final IRI st_union =factory.createIRI(NAMESPACE, "ST_Union")
static final IRI st_unaryUnion =factory.createIRI(NAMESPACE, "ST_UnaryUnion")
static final IRI st_upperLeftX =factory.createIRI(NAMESPACE, "ST_UpperLeftX")
static final IRI st_upperLeftY =factory.createIRI(NAMESPACE, "ST_UpperLeftY")
static final IRI st_value = factory.createIRI(NAMESPACE, "ST_Value")
static final IRI st_vectorize =factory.createIRI(NAMESPACE, "ST_Vectorize")
static final IRI st_volume =factory.createIRI(NAMESPACE, "ST_Volume")
static final IRI st_voronoiLines =factory.createIRI(NAMESPACE, "ST_VoronoiLines")
static final IRI st_voronoiPolygons =factory.createIRI(NAMESPACE, "ST_VoronoiPolygons")
static final IRI st_width =factory.createIRI(NAMESPACE, "ST_Width")
static final IRI st_wkbToSQL =factory.createIRI(NAMESPACE, "ST_GeomFromWKB")
static final IRI st_wktToSQL =factory.createIRI(NAMESPACE, "ST_GeomFromText")
static final IRI st_worldToRasterCoord =factory.createIRI(NAMESPACE, "ST_WorldToRasterCoord")
static final IRI st_worldToRasterCoordX =factory.createIRI(NAMESPACE, "ST_WorldToRasterCoordX")
static final IRI st_worldToRasterCoordY =factory.createIRI(NAMESPACE, "ST_WorldToRasterCoordY")
static final IRI st_x =factory.createIRI(NAMESPACE, "ST_X")
static final IRI st_xMin =factory.createIRI(NAMESPACE, "ST_XMin")
static final IRI st_xMax =factory.createIRI(NAMESPACE, "ST_XMax")
static final IRI st_y =factory.createIRI(NAMESPACE, "ST_Y")
static final IRI st_yMin =factory.createIRI(NAMESPACE, "ST_YMin")
static final IRI st_yMax =factory.createIRI(NAMESPACE, "ST_YMax")
static final IRI st_z =factory.createIRI(NAMESPACE, "ST_Z")
static final IRI st_zMin =factory.createIRI(NAMESPACE, "ST_ZMin")
static final IRI st_zMax =factory.createIRI(NAMESPACE, "ST_ZMax")
static final IRI st_zmFlag =factory.createIRI(NAMESPACE, "ST_Zmflag")
static final IRI Abs =factory.createIRI(NAMESPACE, "Abs")
static final IRI Cos =factory.createIRI(NAMESPACE, "Cos")
static final IRI CosH = factory.createIRI(NAMESPACE, "CosH")
static final IRI ACos =factory.createIRI(NAMESPACE, "ACos")
static final IRI Exp =factory.createIRI(NAMESPACE, "Exp")
static final IRI Sin =factory.createIRI(NAMESPACE, "Sin")
static final IRI SinH = factory.createIRI(NAMESPACE, "SinH")
static final IRI Sqrt = factory.createIRI(NAMESPACE, "Sqrt")
static final IRI ASin =factory.createIRI(NAMESPACE, "ASin")
static final IRI Log =factory.createIRI(NAMESPACE, "Log")
static final IRI Log10 =factory.createIRI(NAMESPACE, "Log10")
static final IRI Pow =factory.createIRI(NAMESPACE, "Pow")
static final IRI Tan =factory.createIRI(NAMESPACE, "Tan")
static final IRI TanH =factory.createIRI(NAMESPACE, "TanH")
static final IRI ATan =factory.createIRI(NAMESPACE, "ATan")
static final IRI Ceil =factory.createIRI(NAMESPACE, "Ceil")
static final IRI Sign =factory.createIRI(NAMESPACE, "Sign")
static final IRI Floor =factory.createIRI(NAMESPACE, "Floor")
static final IRI PI =factory.createIRI(NAMESPACE, "PI")
static final IRI CentimeterToMeter =factory.createIRI(NAMESPACE, "CentimeterToMeter")
static final IRI MillimeterToMeter =factory.createIRI(NAMESPACE, "MillimeterToMeter")
static final IRI KilometerToMeter =factory.createIRI(NAMESPACE, "KilometerToMeter")
static final IRI DecimeterToMeter =factory.createIRI(NAMESPACE, "DecimeterToMeter")
static final IRI MeterToCentimeter =factory.createIRI(NAMESPACE, "MeterToCentimeter")
static final IRI MeterToKilometer =factory.createIRI(NAMESPACE, "MeterToKilometer")
static final IRI MeterToDecimeter =factory.createIRI(NAMESPACE, "MeterToDecimeter")
static final IRI MeterToMillimeter =factory.createIRI(NAMESPACE, "MeterToMillimeter")
static final IRI MeterToNauticalMile =factory.createIRI(NAMESPACE, "MeterToNauticalMile")
static final IRI MeterToChain =factory.createIRI(NAMESPACE, "MeterToChain")
static final IRI MeterToInch =factory.createIRI(NAMESPACE, "MeterToInch")
static final IRI MeterToFoot =factory.createIRI(NAMESPACE, "MeterToFoot")
static final IRI MeterToLink = factory.createIRI(NAMESPACE, "MeterToLink")
static final IRI MeterToYard =factory.createIRI(NAMESPACE, "MeterToYard")
static final IRI MeterToMile =factory.createIRI(NAMESPACE, "MeterToMile")
static final IRI MeterToFathom =factory.createIRI(NAMESPACE, "MeterToFathom")
static final IRI MeterToUSMile = factory.createIRI(NAMESPACE, "MeterToUSMile")
static final IRI MeterToUSFoot = factory.createIRI(NAMESPACE, "MeterToUSFoot")
static final IRI MeterToUSYard = factory.createIRI(NAMESPACE, "MeterToUSYard")
static final IRI ChainToMeter =factory.createIRI(NAMESPACE, "ChainToMeter")
static final IRI InchToMeter =factory.createIRI(NAMESPACE, "InchToMeter")
static final IRI LinkToMeter =factory.createIRI(NAMESPACE, "LinkToMeter")
static final IRI FootToMeter =factory.createIRI(NAMESPACE, "FootToMeter")
static final IRI MileToMeter =factory.createIRI(NAMESPACE, "MileToMeter")
static final IRI NauticalMileToMeter =factory.createIRI(NAMESPACE, "NauticalMileToMeter")
static final IRI YardToMeter =factory.createIRI(NAMESPACE, "YardToMeter")
static final IRI FathomToMeter =factory.createIRI(NAMESPACE, "FathomToMeter")
static final IRI USMileToMeter =factory.createIRI(NAMESPACE, "USMileToMeter")
static final IRI USFootToMeter =factory.createIRI(NAMESPACE, "USFootToMeter")
static final IRI USYardToMeter =factory.createIRI(NAMESPACE, "USYardToMeter")
static final IRI USInchToMeter =factory.createIRI(NAMESPACE, "USInchToMeter")
static final IRI EPSGToSRID =factory.createIRI(NAMESPACE, "EPSGToSRID")
static final IRI SRIDGetAxis1Name =factory.createIRI(NAMESPACE, "SRID_GetAxis1Name")
static final IRI SRIDGetAxis2Name =factory.createIRI(NAMESPACE, "SRID_GetAxis2Name")
static final IRI SRIDGetAxis1Orientation =factory.createIRI(NAMESPACE, "SRID_GetAxis1Orientation")
static final IRI SRIDGetAxis2Orientation =factory.createIRI(NAMESPACE, "SRID_GetAxis2Orientation")
static final IRI SRIDGetDatum =factory.createIRI(NAMESPACE, "SRID_GetDatum")
static final IRI SRIDGetUnit =factory.createIRI(NAMESPACE, "SRID_GetUnit")
static final IRI SRIDHasFlippedAxis =factory.createIRI(NAMESPACE, "SRID_HasFlippedAxis")
static final IRI SRIDIsGeographic = factory.createIRI(NAMESPACE, "SRID_IsGeographic")
static final IRI SRIDIsProjected =factory.createIRI(NAMESPACE, "SRID_IsProjected")
static final IRI SRIDIsVertical =factory.createIRI(NAMESPACE, "SRID_IsVertical")
static final IRI SRIDToEPSG =factory.createIRI(NAMESPACE, "SRIDToEPSG")
static final String WKB = "WKB"
static final String GeoJSON = "GeoJSON"
static final String GeoJSONLD = "GeoJSONLD"
static final String GeoHash = "GeoHash"
static final String GeoBuf = "GeoBuf"
static final String GeoURI ="GeoURI"
static final String GeoRSS ="GeoRSS"
static final String GMLCOV ="GMLCOV"
static final String KML = "KML"
static final String WKBRaster = "WKBRaster"
static final String GEOTIFF = "GeoTIFF"
static final String EncodedPolyline = "EncodedPolyline"
static final String Polyshape = "Polyshape"
static final String TWKB = "TWKB"
static final String HEXWKB = "HEXWKB"
static final String DXF ="DXF"
static final String MVT = "MVT"
static final String X3D = "X3D"
static final String OSM = "OSM"
static final String HexWKBRaster = "HexWKBRaster"
static final String TopoJSON = "TopoJSON"
static final String TemporalRange ="TemporalRange"
static final String CoverageJSON = "CoverageJSON"
static final String SVG ="SVG"
static final String NETCDF ="NetCDF"
static final String GML ="GML"
static final String WKT ="WKT"
static final IRI ST_ToDegrees =factory.createIRI(NAMESPACE, "ST_ToDegrees")
static final IRI ST_ToRadians =factory.createIRI(NAMESPACE, "ST_ToRadians")
Member Data Documentation
Abs
final IRI Abs =factory.createIRI(NAMESPACE, "Abs") static
Referenced by Abs.getURI().
ACos
final IRI ACos =factory.createIRI(NAMESPACE, "ACos") static
Referenced by ACos.getURI().
ASin
final IRI ASin =factory.createIRI(NAMESPACE, "ASin") static
Referenced by ASin.getURI().
ATan
final IRI ATan =factory.createIRI(NAMESPACE, "ATan") static
Referenced by ATan.getURI().
Ceil
final IRI Ceil =factory.createIRI(NAMESPACE, "Ceil") static
Referenced by Ceil.getURI().
CentimeterToMeter
final IRI CentimeterToMeter =factory.createIRI(NAMESPACE, "CentimeterToMeter") static
Referenced by CentimeterToMeter.getURI().
ChainToMeter
final IRI ChainToMeter =factory.createIRI(NAMESPACE, "ChainToMeter") static
Referenced by ChainToMeter.getURI(), and MeterToChain.getURI().
Cos
final IRI Cos =factory.createIRI(NAMESPACE, "Cos") static
Referenced by Cosine.getURI().
CosH
final IRI CosH = factory.createIRI(NAMESPACE, "CosH") static
Referenced by CosH.getURI().
CoverageJSON
final String CoverageJSON = "CoverageJSON" static
DecimeterToMeter
final IRI DecimeterToMeter =factory.createIRI(NAMESPACE, "DecimeterToMeter") static
Referenced by DecimeterToMeter.getURI().
DXF
final String DXF ="DXF" static
EncodedPolyline
final String EncodedPolyline = "EncodedPolyline" static
EPSGToSRID
final IRI EPSGToSRID =factory.createIRI(NAMESPACE, "EPSGToSRID") static
Referenced by EPSGToSRID.getURI().
Exp
final IRI Exp =factory.createIRI(NAMESPACE, "Exp") static
Referenced by Exp.getURI().
factory
final ValueFactory factory = SimpleValueFactory.getInstance() static
FathomToMeter
final IRI FathomToMeter =factory.createIRI(NAMESPACE, "FathomToMeter") static
Referenced by FathomToMeter.getURI().
Floor
final IRI Floor =factory.createIRI(NAMESPACE, "Floor") static
Referenced by Floor.getURI().
FootToMeter
final IRI FootToMeter =factory.createIRI(NAMESPACE, "FootToMeter") static
Referenced by FootToMeter.getURI().
GeoBuf
final String GeoBuf = "GeoBuf" static
GeoHash
final String GeoHash = "GeoHash" static
GeoJSON
final String GeoJSON = "GeoJSON" static
GeoJSONLD
final String GeoJSONLD = "GeoJSONLD" static
GeoRSS
final String GeoRSS ="GeoRSS" static
GEOTIFF
final String GEOTIFF = "GeoTIFF" static
GeoURI
final String GeoURI ="GeoURI" static
GML
final String GML ="GML" static
GMLCOV
final String GMLCOV ="GMLCOV" static
HEXWKB
final String HEXWKB = "HEXWKB" static
HexWKBRaster
final String HexWKBRaster = "HexWKBRaster" static
InchToMeter
final IRI InchToMeter =factory.createIRI(NAMESPACE, "InchToMeter") static
Referenced by InchToMeter.getURI().
KilometerToMeter
final IRI KilometerToMeter =factory.createIRI(NAMESPACE, "KilometerToMeter") static
Referenced by KilometerToMeter.getURI(), and MillimeterToMeter.getURI().
KML
final String KML = "KML" static
LinkToMeter
final IRI LinkToMeter =factory.createIRI(NAMESPACE, "LinkToMeter") static
Referenced by LinkToMeter.getURI().
Log
final IRI Log =factory.createIRI(NAMESPACE, "Log") static
Referenced by Log.getURI().
Log10
final IRI Log10 =factory.createIRI(NAMESPACE, "Log10") static
Referenced by Log10.getURI().
MeterToCentimeter
final IRI MeterToCentimeter =factory.createIRI(NAMESPACE, "MeterToCentimeter") static
Referenced by MeterToCentimeter.getURI().
MeterToChain
final IRI MeterToChain =factory.createIRI(NAMESPACE, "MeterToChain") static
MeterToDecimeter
final IRI MeterToDecimeter =factory.createIRI(NAMESPACE, "MeterToDecimeter") static
Referenced by MeterToDecimeter.getURI().
MeterToFathom
final IRI MeterToFathom =factory.createIRI(NAMESPACE, "MeterToFathom") static
Referenced by MeterToFathom.getURI().
MeterToFoot
final IRI MeterToFoot =factory.createIRI(NAMESPACE, "MeterToFoot") static
Referenced by MeterToFoot.getURI().
MeterToInch
final IRI MeterToInch =factory.createIRI(NAMESPACE, "MeterToInch") static
Referenced by MeterToInch.getURI(), and MeterToUSInch.getURI().
MeterToKilometer
final IRI MeterToKilometer =factory.createIRI(NAMESPACE, "MeterToKilometer") static
Referenced by MeterToKilometer.getURI(), and MeterToMillimeter.getURI().
MeterToLink
final IRI MeterToLink = factory.createIRI(NAMESPACE, "MeterToLink") static
Referenced by MeterToLink.getURI().
MeterToMile
final IRI MeterToMile =factory.createIRI(NAMESPACE, "MeterToMile") static
Referenced by MeterToMile.getURI().
MeterToMillimeter
final IRI MeterToMillimeter =factory.createIRI(NAMESPACE, "MeterToMillimeter") static
MeterToNauticalMile
final IRI MeterToNauticalMile =factory.createIRI(NAMESPACE, "MeterToNauticalMile") static
Referenced by MeterToNauticalMile.getURI().
MeterToUSFoot
final IRI MeterToUSFoot = factory.createIRI(NAMESPACE, "MeterToUSFoot") static
Referenced by MeterToUSFoot.getURI().
MeterToUSMile
final IRI MeterToUSMile = factory.createIRI(NAMESPACE, "MeterToUSMile") static
Referenced by MeterToUSMile.getURI().
MeterToUSYard
final IRI MeterToUSYard = factory.createIRI(NAMESPACE, "MeterToUSYard") static
MeterToYard
final IRI MeterToYard =factory.createIRI(NAMESPACE, "MeterToYard") static
Referenced by MeterToUSYard.getURI(), and MeterToYard.getURI().
MileToMeter
final IRI MileToMeter =factory.createIRI(NAMESPACE, "MileToMeter") static
Referenced by MileToMeter.getURI().
MillimeterToMeter
final IRI MillimeterToMeter =factory.createIRI(NAMESPACE, "MillimeterToMeter") static
MVT
final String MVT = "MVT" static
NAMESPACE
final String NAMESPACE ="http://www.opengis.net/ont/geosparql#" static
NauticalMileToMeter
final IRI NauticalMileToMeter =factory.createIRI(NAMESPACE, "NauticalMileToMeter") static
Referenced by NauticalMileToMeter.getURI().
NETCDF
final String NETCDF ="NetCDF" static
OSM
final String OSM = "OSM" static
PI
final IRI PI =factory.createIRI(NAMESPACE, "PI") static
Referenced by PI.getURI().
Polyshape
final String Polyshape = "Polyshape" static
Pow
final IRI Pow =factory.createIRI(NAMESPACE, "Pow") static
Referenced by Pow.getURI().
Sign
final IRI Sign =factory.createIRI(NAMESPACE, "Sign") static
Referenced by Sign.getURI().
Sin
final IRI Sin =factory.createIRI(NAMESPACE, "Sin") static
Referenced by Sine.getURI().
SinH
final IRI SinH = factory.createIRI(NAMESPACE, "SinH") static
Referenced by SinH.getURI().
Sqrt
final IRI Sqrt = factory.createIRI(NAMESPACE, "Sqrt") static
Referenced by Sqrt.getURI().
SRIDGetAxis1Name
final IRI SRIDGetAxis1Name =factory.createIRI(NAMESPACE, "SRID_GetAxis1Name") static
Referenced by SridGetAxis1Name.getURI().
SRIDGetAxis1Orientation
final IRI SRIDGetAxis1Orientation =factory.createIRI(NAMESPACE, "SRID_GetAxis1Orientation") static
Referenced by SridGetAxis1Orientation.getURI().
SRIDGetAxis2Name
final IRI SRIDGetAxis2Name =factory.createIRI(NAMESPACE, "SRID_GetAxis2Name") static
Referenced by SridGetAxis2Name.getURI().
SRIDGetAxis2Orientation
final IRI SRIDGetAxis2Orientation =factory.createIRI(NAMESPACE, "SRID_GetAxis2Orientation") static
Referenced by SridGetAxis2Orientation.getURI().
SRIDGetDatum
final IRI SRIDGetDatum =factory.createIRI(NAMESPACE, "SRID_GetDatum") static
Referenced by SridGetDatum.getURI().
SRIDGetUnit
final IRI SRIDGetUnit =factory.createIRI(NAMESPACE, "SRID_GetUnit") static
SRIDHasFlippedAxis
final IRI SRIDHasFlippedAxis =factory.createIRI(NAMESPACE, "SRID_HasFlippedAxis") static
Referenced by SridHasFlippedAxis.getURI().
SRIDIsGeographic
final IRI SRIDIsGeographic = factory.createIRI(NAMESPACE, "SRID_IsGeographic") static
Referenced by SridIsGeographic.getURI().
SRIDIsProjected
final IRI SRIDIsProjected =factory.createIRI(NAMESPACE, "SRID_IsProjected") static
Referenced by SridIsProjected.getURI().
SRIDIsVertical
final IRI SRIDIsVertical =factory.createIRI(NAMESPACE, "SRID_IsVertical") static
Referenced by SridIsVertical.getURI().
SRIDToEPSG
final IRI SRIDToEPSG =factory.createIRI(NAMESPACE, "SRIDToEPSG") static
Referenced by SRIDToEPSG.getURI().
ST_ACCUM
final IRI ST_ACCUM =factory.createIRI(NAMESPACE, "ST_Accum") static
ST_ADDBAND
final IRI ST_ADDBAND =factory.createIRI(NAMESPACE, "ST_AddBand") static
Referenced by AddBand.getURI().
st_addGeometry
final IRI st_addGeometry =factory.createIRI(NAMESPACE, "ST_AddGeometry") static
Referenced by AddGeometry.getURI().
st_addInteriorRing
final IRI st_addInteriorRing =factory.createIRI(NAMESPACE, "ST_AddInteriorRing") static
Referenced by AddInteriorRing.getURI().
st_addMeasure
final IRI st_addMeasure =factory.createIRI(NAMESPACE, "ST_AddMeasure") static
Referenced by AddMeasure.getURI().
ST_ADDPOINT
final IRI ST_ADDPOINT =factory.createIRI(NAMESPACE, "ST_AddPoint") static
Referenced by AddPoint.getURI().
ST_ADDZ
final IRI ST_ADDZ =factory.createIRI(NAMESPACE, "ST_AddZ") static
Referenced by AddZ.getURI().
st_angle
final IRI st_angle = factory.createIRI(NAMESPACE,"ST_Angle") static
Referenced by Angle.getURI().
ST_AREA
final IRI ST_AREA =factory.createIRI(NAMESPACE, "ST_Area") static
Referenced by Area.getURI().
ST_AREA3D
final IRI ST_AREA3D =factory.createIRI(NAMESPACE, "ST_Area3D") static
Referenced by Area3D.getURI().
ST_AREASIMILARITY
final IRI ST_AREASIMILARITY =factory.createIRI(NAMESPACE, "ST_AreaSimilarity") static
Referenced by AreaSimilarity.getURI().
ST_ASBINARY
final IRI ST_ASBINARY =factory.createIRI(NAMESPACE, "ST_AsBinary") static
Referenced by AsBinary.getURI().
ST_ASCOVERAGEJSON
final IRI ST_ASCOVERAGEJSON =factory.createIRI(NAMESPACE, "ST_AsCoverageJSON") static
Referenced by AsCoverageJSON.getURI().
ST_ASENCODEDPOLYLINE
final IRI ST_ASENCODEDPOLYLINE =factory.createIRI(NAMESPACE, "ST_AsEncodedPolyline") static
Referenced by AsEncodedPolyline.getURI().
ST_ASGARS
final IRI ST_ASGARS =factory.createIRI(NAMESPACE, "ST_AsGARS") static
Referenced by AsGARS.getURI().
ST_ASGEOBUF
final IRI ST_ASGEOBUF =factory.createIRI(NAMESPACE, "ST_AsGeoBuf") static
Referenced by AsGeobuf.getURI().
ST_ASGEOHASH
final IRI ST_ASGEOHASH =factory.createIRI(NAMESPACE, "ST_AsGeoHash") static
Referenced by AsGeoHash.getURI().
ST_ASGEOJSON
final IRI ST_ASGEOJSON =factory.createIRI(NAMESPACE, "ST_AsGeoJSON") static
Referenced by AsGeoJSON.getURI().
ST_ASGEOJSONLD
final IRI ST_ASGEOJSONLD =factory.createIRI(NAMESPACE, "ST_AsGeoJSONLD") static
ST_ASGEORSS
final IRI ST_ASGEORSS =factory.createIRI(NAMESPACE, "ST_AsGeoRSS") static
Referenced by AsGeoRSS.getURI().
ST_ASGEOTIFF
final IRI ST_ASGEOTIFF =factory.createIRI(NAMESPACE, "ST_AsGeoTIFF") static
Referenced by AsGeoTIFF.getURI().
ST_ASGEOURI
final IRI ST_ASGEOURI =factory.createIRI(NAMESPACE, "ST_AsGeoURI") static
Referenced by AsGeoURI.getURI().
ST_ASGML
final IRI ST_ASGML =factory.createIRI(NAMESPACE, "ST_AsGML") static
Referenced by AsGML.getURI().
ST_ASGMLCOV
final IRI ST_ASGMLCOV =factory.createIRI(NAMESPACE, "ST_AsGMLCOV") static
Referenced by AsGMLCOV.getURI().
ST_ASGPX
final IRI ST_ASGPX =factory.createIRI(NAMESPACE, "ST_AsGPX") static
Referenced by AsGPX.getURI().
ST_ASHEXEWKB
final IRI ST_ASHEXEWKB =factory.createIRI(NAMESPACE, "ST_AsHEXEWKB") static
ST_ASJPG
final IRI ST_ASJPG =factory.createIRI(NAMESPACE, "ST_AsJPG") static
ST_ASKML
final IRI ST_ASKML =factory.createIRI(NAMESPACE, "ST_AsKML") static
Referenced by AsKML.getURI().
ST_ASLATLONTEXT
final IRI ST_ASLATLONTEXT =factory.createIRI(NAMESPACE, "ST_AsLatLonText") static
Referenced by AsLatLonText.getURI().
ST_ASMVT
final IRI ST_ASMVT =factory.createIRI(NAMESPACE, "ST_AsMVT") static
Referenced by AsMVT.getURI().
ST_ASMVTGEOM
final IRI ST_ASMVTGEOM =factory.createIRI(NAMESPACE, "ST_AsMVTGeom") static
ST_ASNETCDF
final IRI ST_ASNETCDF =factory.createIRI(NAMESPACE, "ST_AsNetCDF") static
Referenced by AsNetCDF.getURI().
st_aspect
final IRI st_aspect =factory.createIRI(NAMESPACE, "ST_Aspect") static
ST_ASPNG
final IRI ST_ASPNG =factory.createIRI(NAMESPACE, "ST_AsPNG") static
ST_ASPOLYSHAPE
final IRI ST_ASPOLYSHAPE =factory.createIRI(NAMESPACE, "ST_AsPolyshape") static
Referenced by AsPolyshape.getURI().
st_asRaster
final IRI st_asRaster = factory.createIRI(NAMESPACE,"ST_AsRaster") static
Referenced by AsRaster.getURI().
st_asRasterHexWKB
final IRI st_asRasterHexWKB = factory.createIRI(NAMESPACE,"ST_AsRasterHexWKB") static
Referenced by AsHexWKB.getURI().
st_asRasterWKB
final IRI st_asRasterWKB = factory.createIRI(NAMESPACE,"ST_AsRasterWKB") static
Referenced by AsBinary.getURI().
ST_ASSVG
final IRI ST_ASSVG =factory.createIRI(NAMESPACE, "ST_AsSVG") static
Referenced by AsSVG.getURI().
ST_ASTEXT
final IRI ST_ASTEXT =factory.createIRI(NAMESPACE, "ST_AsText") static
Referenced by AsText.getURI().
ST_ASTEXTRAW
final IRI ST_ASTEXTRAW =factory.createIRI(NAMESPACE, "ST_AsTextRaw") static
Referenced by AsTextRaw.getURI().
ST_ASTEXTROUND
final IRI ST_ASTEXTROUND =factory.createIRI(NAMESPACE, "ST_AsTextRound") static
Referenced by AsTextRound.getURI().
ST_ASTIFF
final IRI ST_ASTIFF =factory.createIRI(NAMESPACE, "ST_AsTIFF") static
ST_ASTOPOJSON
final IRI ST_ASTOPOJSON =factory.createIRI(NAMESPACE, "ST_AsTopoJSON") static
Referenced by AsTopoJSON.getURI().
ST_ASTWKB
final IRI ST_ASTWKB =factory.createIRI(NAMESPACE, "ST_AsTWKB") static
Referenced by AsTWKB.getURI().
ST_ASWKB
final IRI ST_ASWKB =factory.createIRI(NAMESPACE, "ST_AsWKB") static
ST_ASWKT
final IRI ST_ASWKT =factory.createIRI(NAMESPACE, "ST_AsWKT") static
ST_ASX3D
final IRI ST_ASX3D =factory.createIRI(NAMESPACE, "ST_AsX3D") static
Referenced by AsX3D.getURI().
ST_AZIMUTH
final IRI ST_AZIMUTH =factory.createIRI(NAMESPACE, "ST_Azimuth") static
ST_BAND
final IRI ST_BAND =factory.createIRI(NAMESPACE, "ST_Band") static
Referenced by Band.getURI().
ST_BANDISNODATA
final IRI ST_BANDISNODATA =factory.createIRI(NAMESPACE, "ST_BandIsNoData") static
Referenced by BandIsNoData.getURI().
ST_BANDMAX
final IRI ST_BANDMAX =factory.createIRI(NAMESPACE, "ST_BandMax") static
Referenced by BandMax.getURI().
ST_BANDMETADATA
final IRI ST_BANDMETADATA =factory.createIRI(NAMESPACE, "ST_BandMetaData") static
Referenced by BandMetadata.getURI().
ST_BANDMin
final IRI ST_BANDMin =factory.createIRI(NAMESPACE, "ST_BandMin") static
Referenced by BandMin.getURI().
ST_BANDNODATAVALUE
final IRI ST_BANDNODATAVALUE =factory.createIRI(NAMESPACE, "ST_BandNoDataValue") static
Referenced by BandNoDataValue.getURI().
ST_BANDPIXELTYPE
final IRI ST_BANDPIXELTYPE =factory.createIRI(NAMESPACE, "ST_BandPixelType") static
st_bboxabove
final IRI st_bboxabove =factory.createIRI(NAMESPACE,"ST_BBOXAbove") static
Referenced by BBOXAbove.getURI().
st_bboxbelow
final IRI st_bboxbelow = factory.createIRI(NAMESPACE,"ST_BBOXBelow") static
Referenced by BBOXBelow.getURI().
st_bboxcontains
final IRI st_bboxcontains = factory.createIRI(NAMESPACE,"ST_BBOXContains") static
Referenced by BBOXContains.getURI().
st_bboxdistance
final IRI st_bboxdistance = factory.createIRI(NAMESPACE,"ST_BBOXDistance") static
Referenced by BBOXDistance.getURI().
st_bboxequals
final IRI st_bboxequals = factory.createIRI(NAMESPACE, "ST_BBOXEquals") static
Referenced by BBOXEquals.getURI().
st_bboxfpintersects
final IRI st_bboxfpintersects = factory.createIRI(NAMESPACE, "ST_BBOXFPIntersects") static
Referenced by BBOXFPIntersects.getURI().
st_bboxintersect
final IRI st_bboxintersect = factory.createIRI(NAMESPACE, "ST_BBOXIntersects") static
Referenced by BBOXIntersects.getURI().
st_bboxiscontainedby
final IRI st_bboxiscontainedby =factory.createIRI(NAMESPACE, "ST_BBOXIsContainedBy") static
Referenced by BBOXIsContainedBy.getURI().
st_bboxleftof
final IRI st_bboxleftof = factory.createIRI(NAMESPACE, "ST_BBOXLeftOf") static
Referenced by BBOXLeftOf.getURI().
st_bboxoverlapsabove
final IRI st_bboxoverlapsabove = factory.createIRI(NAMESPACE, "ST_BBOXOverlapsAbove") static
Referenced by BBOXOverlapsAbove.getURI().
st_bboxoverlapsbelow
final IRI st_bboxoverlapsbelow =factory.createIRI(NAMESPACE, "ST_BBOXOverlapsBelow") static
Referenced by BBOXOverlapsBelow.getURI().
st_bboxoverlapsleft
final IRI st_bboxoverlapsleft = factory.createIRI(NAMESPACE ,"ST_BBOXOverlapsLeft") static
Referenced by BBOXOverlapsLeft.getURI().
st_bboxoverlapsright
final IRI st_bboxoverlapsright = factory.createIRI(NAMESPACE, "ST_BBOXOverlapsRight") static
Referenced by BBOXOverlapsRight.getURI().
st_bboxrightof
final IRI st_bboxrightof = factory.createIRI(NAMESPACE, "ST_BBOXRightOf") static
Referenced by BBOXRightOf.getURI().
ST_BEZIERSMOOTHING
final IRI ST_BEZIERSMOOTHING =factory.createIRI(NAMESPACE, "ST_BezierSmoothing") static
ST_BOUNDARY
final IRI ST_BOUNDARY =factory.createIRI(NAMESPACE, "ST_Boundary") static
Referenced by Boundary.getURI().
ST_BOUNDINGDIAGONAL
final IRI ST_BOUNDINGDIAGONAL =factory.createIRI(NAMESPACE, "ST_BoundingDiagonal") static
Referenced by BoundingDiagonal.getURI().
ST_CENTROID
final IRI ST_CENTROID =factory.createIRI(NAMESPACE, "ST_Centroid") static
Referenced by Centroid.getURI().
ST_CENTROIDDISTANCE
final IRI ST_CENTROIDDISTANCE =factory.createIRI(NAMESPACE, "ST_CentroidDistance") static
Referenced by CentroidDistance.getURI().
ST_CHAIKINSMOOTHING
final IRI ST_CHAIKINSMOOTHING =factory.createIRI(NAMESPACE, "ST_ChaikinSmoothing") static
st_circularity
final IRI st_circularity =factory.createIRI(NAMESPACE, "ST_Circularity") static
Referenced by Circularity.getURI().
st_circumcentre
final IRI st_circumcentre =factory.createIRI(NAMESPACE, "ST_Circumcentre") static
Referenced by Circumcentre.getURI().
ST_CLIP
final IRI ST_CLIP =factory.createIRI(NAMESPACE, "ST_Clip") static
ST_CLIPBYBOX2D
final IRI ST_CLIPBYBOX2D =factory.createIRI(NAMESPACE, "ST_ClipByBox2D") static
ST_CLOSESTPOINT
final IRI ST_CLOSESTPOINT =factory.createIRI(NAMESPACE, "ST_ClosestPoint") static
Referenced by ClosestPoint.getURI().
ST_CLOSESTPOINT3D
final IRI ST_CLOSESTPOINT3D =factory.createIRI(NAMESPACE, "ST_ClosestPoint3D") static
Referenced by ClosestPoint3D.getURI().
ST_CLOSESTPOINTOFAPPROACH
final IRI ST_CLOSESTPOINTOFAPPROACH =factory.createIRI(NAMESPACE, "ST_ClosestPointOfApproach") static
ST_CLUSTERINTERSECTING
final IRI ST_CLUSTERINTERSECTING =factory.createIRI(NAMESPACE, "ST_ClusterIntersecting") static
ST_CLUSTERKMEANS
final IRI ST_CLUSTERKMEANS =factory.createIRI(NAMESPACE, "ST_ClusterKMeans") static
ST_CLUSTERWITHIN
final IRI ST_CLUSTERWITHIN =factory.createIRI(NAMESPACE, "ST_ClusterWithin") static
st_collectionextract
final IRI st_collectionextract =factory.createIRI(NAMESPACE, "ST_CollectionExtract") static
Referenced by CollectionExtract.getURI().
ST_COLLECTIONHOMOGENIZE
final IRI ST_COLLECTIONHOMOGENIZE =factory.createIRI(NAMESPACE, "ST_CollectionHomogenize") static
Referenced by CollectionHomogenize.getURI().
ST_COMPACTNESSRATIO
final IRI ST_COMPACTNESSRATIO =factory.createIRI(NAMESPACE, "ST_CompactnessRatio") static
Referenced by CompactnessRatio.getURI().
ST_CONCAVEHULL
final IRI ST_CONCAVEHULL =factory.createIRI(NAMESPACE, "ST_ConcaveHull") static
Referenced by ConcaveHull.getURI().
ST_CONTAINS
final IRI ST_CONTAINS =factory.createIRI(NAMESPACE, "ST_Contains") static
Referenced by Contains.getURI().
ST_CONTAINSPROPERLY
final IRI ST_CONTAINSPROPERLY =factory.createIRI(NAMESPACE, "ST_ContainsProperly") static
Referenced by ContainsProperly.getURI().
ST_CONVEXHULL
final IRI ST_CONVEXHULL =factory.createIRI(NAMESPACE, "ST_ConvexHull") static
Referenced by ConvexHull.getURI().
st_cosinedistance
final IRI st_cosinedistance =factory.createIRI(NAMESPACE, "ST_CosineDistance") static
st_cosinesimilarity
final IRI st_cosinesimilarity =factory.createIRI(NAMESPACE, "ST_CosineSimilarity") static
ST_COUNT
final IRI ST_COUNT =factory.createIRI(NAMESPACE, "ST_Count") static
st_crop
final IRI st_crop =factory.createIRI(NAMESPACE, "ST_Crop") static
st_curvature
final IRI st_curvature =factory.createIRI(NAMESPACE, "ST_Curvature") static
ST_CURVETOLINE
final IRI ST_CURVETOLINE =factory.createIRI(NAMESPACE, "ST_CurveToLine") static
ST_DELAUNAYTRIANGLES
final IRI ST_DELAUNAYTRIANGLES =factory.createIRI(NAMESPACE, "ST_DelaunayTriangles") static
Referenced by DelaunayTriangles.getURI().
ST_DENSIFY
final IRI ST_DENSIFY =factory.createIRI(NAMESPACE, "ST_Densify") static
Referenced by Densify.getURI().
ST_DIMENSION
final IRI ST_DIMENSION =factory.createIRI(NAMESPACE, "ST_Dimension") static
st_dissolvepoints
final IRI st_dissolvepoints =factory.createIRI(NAMESPACE, "ST_DissolvePoints") static
Referenced by DissolvePoints.getURI().
st_dissolvesegments
final IRI st_dissolvesegments =factory.createIRI(NAMESPACE, "ST_DissolveSegments") static
Referenced by DissolveSegments.getURI().
ST_DISTANCE
final IRI ST_DISTANCE =factory.createIRI(NAMESPACE, "ST_Distance") static
ST_DISTANCE3D
final IRI ST_DISTANCE3D =factory.createIRI(NAMESPACE, "ST_Distance3D") static
Referenced by WithinDistance3D.getURI(), and Distance3D.getURI().
ST_DISTANCESPHERE
final IRI ST_DISTANCESPHERE =factory.createIRI(NAMESPACE, "ST_DistanceSphere") static
Referenced by DistanceSphere.getURI().
st_dump
final IRI st_dump =factory.createIRI(NAMESPACE, "ST_Dump") static
Referenced by Dump.getURI().
st_dumprings
final IRI st_dumprings =factory.createIRI(NAMESPACE, "ST_DumpRings") static
Referenced by DumpRings.getURI().
ST_DWITHIN
final IRI ST_DWITHIN =factory.createIRI(NAMESPACE, "ST_DWithin") static
Referenced by FullyWithinDistance.getURI().
ST_DWITHIN3D
final IRI ST_DWITHIN3D =factory.createIRI(NAMESPACE, "ST_3DDWithin") static
ST_ENDPOINT
final IRI ST_ENDPOINT =factory.createIRI(NAMESPACE, "ST_EndPoint") static
Referenced by EndPoint.getURI().
st_ensureClosed
final IRI st_ensureClosed =factory.createIRI(NAMESPACE, "ST_EnsureClosed") static
Referenced by EnsureClosed.getURI().
st_ensureClosedRings
final IRI st_ensureClosedRings =factory.createIRI(NAMESPACE, "ST_EnsureClosedRings") static
Referenced by EnsureClosedRings.getURI().
ST_EPSGTOSRID
final IRI ST_EPSGTOSRID =factory.createIRI(NAMESPACE, "ST_EPSGToSRID") static
st_epsgToSRID
final IRI st_epsgToSRID =factory.createIRI(NAMESPACE, "ST_EPSGToSRID") static
ST_EQUALS
final IRI ST_EQUALS =factory.createIRI(NAMESPACE, "ST_Equals") static
st_equals
final IRI st_equals =factory.createIRI(NAMESPACE, "ST_Equals") static
Referenced by Equals.getURI().
ST_EQUALSNORM
final IRI ST_EQUALSNORM =factory.createIRI(NAMESPACE, "ST_EqualsNorm") static
st_equalsNorm
final IRI st_equalsNorm =factory.createIRI(NAMESPACE, "ST_EqualNorm") static
Referenced by EqualsNorm.getURI().
ST_EQUALSRS
final IRI ST_EQUALSRS =factory.createIRI(NAMESPACE, "ST_EqualSRS") static
st_equalSRS
final IRI st_equalSRS =factory.createIRI(NAMESPACE, "ST_EqualSRS") static
Referenced by EqualSRS.getURI().
ST_EQUALSTOPO
final IRI ST_EQUALSTOPO =factory.createIRI(NAMESPACE, "ST_EqualsTopo") static
st_equalsTopo
final IRI st_equalsTopo =factory.createIRI(NAMESPACE, "ST_EqualTopo") static
Referenced by EqualsTopo.getURI().
st_equalType
final IRI st_equalType =factory.createIRI(NAMESPACE, "ST_EqualType") static
Referenced by EqualType.getURI().
st_expand
final IRI st_expand =factory.createIRI(NAMESPACE, "ST_Expand") static
Referenced by Expand.getURI().
st_exteriorRing
final IRI st_exteriorRing =factory.createIRI(NAMESPACE, "ST_ExteriorRing") static
Referenced by ExteriorRing.getURI().
ST_FILTERBYM
final IRI ST_FILTERBYM =factory.createIRI(NAMESPACE, "ST_FilterByM") static
st_filterByM
final IRI st_filterByM =factory.createIRI(NAMESPACE, "ST_FilterByM") static
ST_FILTERBYT
final IRI ST_FILTERBYT =factory.createIRI(NAMESPACE, "ST_FilterByT") static
st_filterByT
final IRI st_filterByT =factory.createIRI(NAMESPACE, "ST_FilterByT") static
st_flip
final IRI st_flip =factory.createIRI(NAMESPACE, "ST_Flip") static
ST_FLIPCOORDINATES
final IRI ST_FLIPCOORDINATES =factory.createIRI(NAMESPACE, "ST_FlipCoordinates") static
st_flipCoordinates
final IRI st_flipCoordinates =factory.createIRI(NAMESPACE, "ST_FlipCoordinates") static
Referenced by FlipCoordinates.getURI().
ST_flowdirection
final IRI ST_flowdirection =factory.createIRI(NAMESPACE, "ST_FlowDirection") static
st_force2d
final IRI st_force2d =factory.createIRI(NAMESPACE, "ST_Force2D") static
Referenced by Force2D.getURI().
st_force3d
final IRI st_force3d =factory.createIRI(NAMESPACE, "ST_Force3D") static
Referenced by Force3D.getURI().
st_force3dm
final IRI st_force3dm =factory.createIRI(NAMESPACE, "ST_Force3DM") static
Referenced by Force3DM.getURI().
st_force3dz
final IRI st_force3dz =factory.createIRI(NAMESPACE, "ST_Force3D") static
st_force4d
final IRI st_force4d =factory.createIRI(NAMESPACE, "ST_Force4D") static
Referenced by Force4D.getURI().
st_forceCollection
final IRI st_forceCollection =factory.createIRI(NAMESPACE, "ST_ForceCollection") static
Referenced by ForceCollection.getURI().
st_forceCurve
final IRI st_forceCurve =factory.createIRI(NAMESPACE, "ST_ForceCurve") static
st_forceLHR
final IRI st_forceLHR =factory.createIRI(NAMESPACE, "ST_ForceLHR") static
st_forcePolygonCCW
final IRI st_forcePolygonCCW =factory.createIRI(NAMESPACE, "ST_ForcePolygonCCW") static
Referenced by ForcePolygonCCW.getURI().
st_forcePolygonCW
final IRI st_forcePolygonCW =factory.createIRI(NAMESPACE, "ST_ForcePolygonCW") static
Referenced by ForcePolygonCW.getURI().
st_forceSFS
final IRI st_forceSFS =factory.createIRI(NAMESPACE, "ST_ForceSFS") static
st_frechetDistance
final IRI st_frechetDistance =factory.createIRI(NAMESPACE, "ST_FrechetDistance") static
st_fullyWithinDistance3D
final IRI st_fullyWithinDistance3D =factory.createIRI(NAMESPACE, "ST_FullyWithinDistance3D") static
Referenced by FullyWithinDistance3D.getURI().
st_furthestcoordinate
final IRI st_furthestcoordinate =factory.createIRI(NAMESPACE, "ST_FurthestCoordinate") static
Referenced by FurthestCoordinate.getURI().
st_generatePoints
final IRI st_generatePoints =factory.createIRI(NAMESPACE, "ST_GeneratePoints") static
Referenced by GeneratePoints.getURI().
st_geohash
final IRI st_geohash =factory.createIRI(NAMESPACE, "ST_AsGeoHash") static
st_geomCollFromText
final IRI st_geomCollFromText = factory.createIRI(NAMESPACE,"ST_GeomCollFromText") static
Referenced by GeomCollFromText.getURI().
st_geometricMedian
final IRI st_geometricMedian =factory.createIRI(NAMESPACE, "ST_GeometricMedian") static
Referenced by GeometricMedian.getURI().
st_geometryN
final IRI st_geometryN =factory.createIRI(NAMESPACE, "ST_GeometryN") static
Referenced by GeometryN.getURI().
st_geometryType
final IRI st_geometryType =factory.createIRI(NAMESPACE, "ST_GeometryType") static
Referenced by GeometryType.getURI().
st_geomFromGeoHash
final IRI st_geomFromGeoHash =factory.createIRI(NAMESPACE, "ST_GeomFromGeoHash") static
Referenced by GeomFromGeoHash.getURI().
st_geomFromGeoJSON
final IRI st_geomFromGeoJSON =factory.createIRI(NAMESPACE, "ST_GeomFromGeoJSON") static
Referenced by GeomFromGeoJSON.getURI().
st_geomFromGML
final IRI st_geomFromGML =factory.createIRI(NAMESPACE, "ST_GeomFromGML") static
st_geomFromKML
final IRI st_geomFromKML =factory.createIRI(NAMESPACE, "ST_GeomFromKML") static
st_geomFromText
final IRI st_geomFromText =factory.createIRI(NAMESPACE, "ST_GeomFromText") static
Referenced by GeomFromText.getURI().
st_geomFromWKB
final IRI st_geomFromWKB =factory.createIRI(NAMESPACE, "ST_GeomFromWKB") static
Referenced by GeomFromWKB.getURI().
st_gmlToSQL
final IRI st_gmlToSQL =factory.createIRI(NAMESPACE, "ST_GeomFromGML") static
st_hasConnectedInterior
final IRI st_hasConnectedInterior =factory.createIRI(NAMESPACE, "ST_HasConnectedInterior") static
Referenced by HasConnectedInterior.getURI().
st_hasDuplicateRings
final IRI st_hasDuplicateRings =factory.createIRI(NAMESPACE, "ST_HasDuplicateRings") static
Referenced by HasDuplicateRings.getURI().
ST_hasHorizontalCRS
final IRI ST_hasHorizontalCRS =factory.createIRI(NAMESPACE, "ST_HasHorizontalCRS") static
Referenced by HasHorizontalCRS.getURI().
st_hasNestedRings
final IRI st_hasNestedRings =factory.createIRI(NAMESPACE, "ST_HasNestedRings") static
Referenced by HasNestedRings.getURI().
st_hasNoBand
final IRI st_hasNoBand =factory.createIRI(NAMESPACE, "ST_HasNoBand") static
Referenced by HasNoBand.getURI().
st_hasRepeatedPoints
final IRI st_hasRepeatedPoints =factory.createIRI(NAMESPACE, "ST_HasRepeatedPoints") static
Referenced by HasRepeatedPoints.getURI().
ST_hasSelfIntersections
final IRI ST_hasSelfIntersections = factory.createIRI(NAMESPACE, "ST_HasSelfIntersections") static
Referenced by HasSelfIntersections.getURI().
st_hausdorffDistance
final IRI st_hausdorffDistance =factory.createIRI(NAMESPACE, "ST_HausdorffDistance") static
Referenced by HausdorffDistance.getURI().
st_height
final IRI st_height =factory.createIRI(NAMESPACE, "ST_Height") static
Referenced by Height.getURI().
st_hillshade
final IRI st_hillshade =factory.createIRI(NAMESPACE, "ST_Hillshade") static
st_histogram
final IRI st_histogram = factory.createIRI(NAMESPACE,"ST_Histogram") static
st_interiorRingN
final IRI st_interiorRingN =factory.createIRI(NAMESPACE, "ST_InteriorRingN") static
Referenced by InteriorRingN.getURI().
st_interpolatePoint
final IRI st_interpolatePoint =factory.createIRI(NAMESPACE, "ST_InterpolatePoint") static
st_intersectionMatrix
final IRI st_intersectionMatrix =factory.createIRI(NAMESPACE, "ST_IntersectionMatrix") static
Referenced by IntersectionMatrix.getURI().
st_intersectionPercentage
final IRI st_intersectionPercentage =factory.createIRI(NAMESPACE, "ST_IntersectionPercentage") static
Referenced by IntersectionPercentage.getURI().
st_is3D
final IRI st_is3D =factory.createIRI(NAMESPACE, "ST_Is3D") static
Referenced by Is3D.getURI().
st_isAcute
final IRI st_isAcute =factory.createIRI(NAMESPACE, "ST_IsAcute") static
Referenced by IsAcute.getURI().
st_isClosed
final IRI st_isClosed =factory.createIRI(NAMESPACE, "ST_IsClosed") static
Referenced by IsClosed.getURI().
st_isCollection
final IRI st_isCollection =factory.createIRI(NAMESPACE, "ST_IsCollection") static
Referenced by IsCollection.getURI().
st_isConvex
final IRI st_isConvex =factory.createIRI(NAMESPACE, "ST_IsConvex") static
Referenced by IsConvex.getURI().
st_isDegenerate
final IRI st_isDegenerate =factory.createIRI(NAMESPACE, "ST_IsDegenerate") static
st_isEmpty
final IRI st_isEmpty =factory.createIRI(NAMESPACE, "ST_IsEmpty") static
Referenced by IsEmpty.getURI().
st_isEquilateralTriangle
final IRI st_isEquilateralTriangle =factory.createIRI(NAMESPACE, "ST_IsEquilateralTriangle") static
Referenced by IsEquilateralTriangle.getURI().
st_isGrayscale
final IRI st_isGrayscale =factory.createIRI(NAMESPACE, "ST_IsGrayscale") static
Referenced by IsGrayscale.getURI().
st_isInCRSAreaOfValidity
final IRI st_isInCRSAreaOfValidity =factory.createIRI(NAMESPACE, "ST_IsInCRSAreaOfValidity") static
Referenced by IsInCRSAreaOfValidity.getURI().
st_isIndexed
final IRI st_isIndexed =factory.createIRI(NAMESPACE, "ST_IsIndexed") static
Referenced by IsIndexed.getURI().
st_isIsocelesTriangle
final IRI st_isIsocelesTriangle =factory.createIRI(NAMESPACE, "ST_IsIsocelesTriangle") static
Referenced by IsIsocelesTriangle.getURI().
st_isLocationOnEdge
final IRI st_isLocationOnEdge =factory.createIRI(NAMESPACE, "ST_IsLocationOnEdge") static
Referenced by IsLocationOnEdge.getURI().
st_isMeasured
final IRI st_isMeasured =factory.createIRI(NAMESPACE, "ST_IsMeasured") static
Referenced by IsMeasured.getURI().
st_isMorePrecise
final IRI st_isMorePrecise =factory.createIRI(NAMESPACE, "ST_IsMorePrecise") static
Referenced by IsMorePrecise.getURI().
st_isNodingValid
final IRI st_isNodingValid =factory.createIRI(NAMESPACE, "ST_IsNodingValid") static
Referenced by IsNodingValid.getURI().
st_isOpaquePixel
final IRI st_isOpaquePixel =factory.createIRI(NAMESPACE, "ST_IsOpaquePixel") static
Referenced by IsOpaquePixel.getURI().
st_isPlanar
final IRI st_isPlanar = factory.createIRI(NAMESPACE, "ST_IsPlanar") static
Referenced by IsPlanar.getURI().
st_isPointInRing
final IRI st_isPointInRing =factory.createIRI(NAMESPACE, "ST_IsPointInRing") static
Referenced by IsPointInRing.getURI().
st_isPointOnLine
final IRI st_isPointOnLine =factory.createIRI(NAMESPACE, "ST_IsPointOnLine") static
Referenced by IsPointOnLine.getURI().
st_isPolygonCCW
final IRI st_isPolygonCCW =factory.createIRI(NAMESPACE, "ST_IsPolygonCCW") static
Referenced by IsPolygonCCW.getURI().
st_isPolygonCW
final IRI st_isPolygonCW =factory.createIRI(NAMESPACE, "ST_IsPolygonCW") static
Referenced by IsPolygonCW.getURI().
st_isRectangle
final IRI st_isRectangle =factory.createIRI(NAMESPACE, "ST_IsRectangle") static
Referenced by IsRectangle.getURI().
st_isRightTriangle
final IRI st_isRightTriangle =factory.createIRI(NAMESPACE, "ST_IsRightTriangle") static
Referenced by IsRightTriangle.getURI().
st_isRing
final IRI st_isRing =factory.createIRI(NAMESPACE, "ST_IsRing") static
Referenced by IsRing.getURI().
st_isSimple
final IRI st_isSimple =factory.createIRI(NAMESPACE, "ST_IsSimpleFF") static
Referenced by IsSimple.getURI().
st_isSolid
final IRI st_isSolid = factory.createIRI(NAMESPACE, "ST_IsSolid") static
Referenced by IsSolid.getURI().
st_isSquare
final IRI st_isSquare = factory.createIRI(NAMESPACE, "ST_IsSquare") static
Referenced by IsSquare.getURI().
st_isTiled
final IRI st_isTiled =factory.createIRI(NAMESPACE, "ST_IsTiled") static
Referenced by IsTiled.getURI().
st_isTranslucent
final IRI st_isTranslucent =factory.createIRI(NAMESPACE, "ST_IsTranslucent") static
Referenced by IsTranslucent.getURI().
st_isTransparentPixel
final IRI st_isTransparentPixel =factory.createIRI(NAMESPACE, "ST_IsTransparentPixel") static
Referenced by IsTransparentPixel.getURI().
st_isTriangle
final IRI st_isTriangle = factory.createIRI(NAMESPACE, "ST_IsTriangle") static
Referenced by IsTriangle.getURI().
st_isValid
final IRI st_isValid =factory.createIRI(NAMESPACE, "ST_IsValidFF") static
Referenced by IsValid.getURI().
st_isValidDetail
final IRI st_isValidDetail =factory.createIRI(NAMESPACE, "ST_IsValidDetail") static
Referenced by IsValidDetail.getURI().
st_isValidReason
final IRI st_isValidReason =factory.createIRI(NAMESPACE, "ST_IsValidReason") static
Referenced by IsValidReason.getURI().
st_isValidTrajectory
final IRI st_isValidTrajectory =factory.createIRI(NAMESPACE, "ST_IsValidTrajectory") static
Referenced by IsValidTrajectory.getURI().
st_Length
final IRI st_Length =factory.createIRI(NAMESPACE, "ST_Length") static
Referenced by Length.getURI().
st_Length2D
final IRI st_Length2D =factory.createIRI(NAMESPACE, "ST_Length") static
st_Length3D
final IRI st_Length3D =factory.createIRI(NAMESPACE, "ST_Length3D") static
Referenced by Length3D.getURI().
st_LengthToPoint
final IRI st_LengthToPoint =factory.createIRI(NAMESPACE, "ST_LengthToPoint") static
Referenced by LengthToPoint.getURI().
st_lineCrossingDirection
final IRI st_lineCrossingDirection =factory.createIRI(NAMESPACE, "ST_LineCrossingDirection") static
Referenced by LineCrossingDirection.getURI().
st_lineFromEncodedPolyline
final IRI st_lineFromEncodedPolyline =factory.createIRI(NAMESPACE, "ST_LineFromEncodedPolyline") static
Referenced by LineFromEncodedPolyline.getURI().
st_lineFromMultiPoint
final IRI st_lineFromMultiPoint =factory.createIRI(NAMESPACE, "ST_LineFromMultiPoint") static
Referenced by LineFromMultiPoint.getURI().
st_lineFromText
final IRI st_lineFromText =factory.createIRI(NAMESPACE, "ST_LineFromText") static
Referenced by LineFromText.getURI().
st_lineFromWKB
final IRI st_lineFromWKB =factory.createIRI(NAMESPACE, "ST_LineFromWKB") static
Referenced by LineFromWKB.getURI().
st_lineFromWKT
final IRI st_lineFromWKT =factory.createIRI(NAMESPACE, "ST_LineFromText") static
st_lineInterpolatePoint
final IRI st_lineInterpolatePoint =factory.createIRI(NAMESPACE, "ST_LineInterpolatePoint") static
Referenced by LineInterpolatePoint.getURI().
st_lineInterpolatePoints
final IRI st_lineInterpolatePoints =factory.createIRI(NAMESPACE, "ST_LineInterpolatePoints") static
st_lineLength3D
final IRI st_lineLength3D =factory.createIRI(NAMESPACE, "ST_LineLength3D") static
Referenced by LineLength3D.getURI().
st_lineLocatePoint
final IRI st_lineLocatePoint =factory.createIRI(NAMESPACE, "ST_LineLocatePoint") static
st_lineMerge
final IRI st_lineMerge =factory.createIRI(NAMESPACE, "ST_LineMerge") static
Referenced by LineMerge.getURI().
st_linesCutAtNodes
final IRI st_linesCutAtNodes =factory.createIRI(NAMESPACE, "ST_LinesCutAtNodes") static
Referenced by LinesCutAtNodes.getURI().
st_lineSelfIntersectionPoint
final IRI st_lineSelfIntersectionPoint =factory.createIRI(NAMESPACE, "ST_LineSelfIntersectionPoint") static
Referenced by LineSelfIntersectionPoint.getURI().
st_linesFromRings
final IRI st_linesFromRings =factory.createIRI(NAMESPACE, "ST_LinesFromRings") static
Referenced by LinesFromRings.getURI().
st_lineSubstring
final IRI st_lineSubstring =factory.createIRI(NAMESPACE, "ST_LineSubstring") static
st_lineToCurve
final IRI st_lineToCurve =factory.createIRI(NAMESPACE, "ST_LineToCurve") static
st_locateAlong
final IRI st_locateAlong =factory.createIRI(NAMESPACE, "ST_LocateAlong") static
Referenced by LocateAlong.getURI().
st_locateBetween
final IRI st_locateBetween =factory.createIRI(NAMESPACE, "ST_LocateBetween") static
Referenced by LocateBetweenMeasures.getURI().
st_locateBetweenElevations
final IRI st_locateBetweenElevations =factory.createIRI(NAMESPACE, "ST_LocateBetweenElevations") static
st_longestLine
final IRI st_longestLine =factory.createIRI(NAMESPACE, "ST_LongestLine") static
Referenced by LongestLine.getURI().
ST_LONGESTLINE3D
final IRI ST_LONGESTLINE3D =factory.createIRI(NAMESPACE, "ST_LongestLine3D") static
st_m
final IRI st_m =factory.createIRI(NAMESPACE, "ST_M") static
Referenced by M.getURI().
st_makeBox2D
final IRI st_makeBox2D =factory.createIRI(NAMESPACE, "ST_MakeBox2D") static
Referenced by MakeBox2D.getURI().
st_makeBox3D
final IRI st_makeBox3D =factory.createIRI(NAMESPACE, "ST_MakeBox3D") static
Referenced by MakeBox3D.getURI().
st_makeCircle
final IRI st_makeCircle =factory.createIRI(NAMESPACE, "ST_MakeCircle") static
st_makeEllipse
final IRI st_makeEllipse =factory.createIRI(NAMESPACE, "ST_MakeEllipse") static
st_makeEmptyCoverage
final IRI st_makeEmptyCoverage =factory.createIRI(NAMESPACE, "ST_MakeEmptyCoverage") static
st_makeEmptyRaster
final IRI st_makeEmptyRaster =factory.createIRI(NAMESPACE, "ST_MakeEmptyRaster") static
Referenced by MakeEmptyRaster.getURI().
st_makeEnvelope
final IRI st_makeEnvelope =factory.createIRI(NAMESPACE, "ST_MakeEnvelope") static
Referenced by MakeEnvelope.getURI().
st_makeLine
final IRI st_makeLine =factory.createIRI(NAMESPACE, "ST_MakeLine") static
Referenced by MakeLine.getURI().
st_makePoint
final IRI st_makePoint =factory.createIRI(NAMESPACE, "ST_MakePoint") static
Referenced by MakePoint.getURI().
st_makePointM
final IRI st_makePointM =factory.createIRI(NAMESPACE, "ST_MakePointM") static
st_makePolygon
final IRI st_makePolygon =factory.createIRI(NAMESPACE, "ST_MakePolygon") static
Referenced by MakePolygon.getURI().
st_makeValid
final IRI st_makeValid =factory.createIRI(NAMESPACE, "ST_MakeValid") static
Referenced by MakeValid.getURI().
st_makeValidDiscarded
final IRI st_makeValidDiscarded =factory.createIRI(NAMESPACE, "ST_MakeValidDiscarded") static
Referenced by MakeValidDiscarded.getURI().
st_manhattandistance
final IRI st_manhattandistance = factory.createIRI(NAMESPACE, "ST_ManhattanDistance") static
Referenced by ManhattanDistance.getURI().
st_maxDistance
final IRI st_maxDistance =factory.createIRI(NAMESPACE, "ST_MaxDistance") static
Referenced by MaxDistance.getURI().
ST_MAXDISTANCE3D
final IRI ST_MAXDISTANCE3D =factory.createIRI(NAMESPACE, "ST_MaxDistance3D") static
st_maxDistance3D
final IRI st_maxDistance3D =factory.createIRI(NAMESPACE, "ST_MaxDistance3D") static
Referenced by MaxDistance3D.getURI().
st_memsize
final IRI st_memsize =factory.createIRI(NAMESPACE, "ST_MemSize") static
st_minConvexHull
final IRI st_minConvexHull =factory.createIRI(NAMESPACE, "ST_MinConvexHull") static
st_minimumBoundingCircle
final IRI st_minimumBoundingCircle =factory.createIRI(NAMESPACE, "ST_MinimumBoundingCircle") static
Referenced by MinimumBoundingCircle.getURI().
st_minimumBoundingCircleCenter
final IRI st_minimumBoundingCircleCenter =factory.createIRI(NAMESPACE, "ST_MinimumBoundingCircleCenter") static
Referenced by MinimumBoundingCircleCenter.getURI().
st_minimumBoundingRadius
final IRI st_minimumBoundingRadius =factory.createIRI(NAMESPACE, "ST_MinimumBoundingRadius") static
Referenced by MinimumBoundingRadius.getURI().
st_minimumClearance
final IRI st_minimumClearance =factory.createIRI(NAMESPACE, "ST_MinimumClearance") static
Referenced by MinimumClearance.getURI().
st_minimumClearanceLine
final IRI st_minimumClearanceLine =factory.createIRI(NAMESPACE, "ST_MinimumClearanceLine") static
Referenced by MinimumClearanceLine.getURI().
st_minimumDiameter
final IRI st_minimumDiameter =factory.createIRI(NAMESPACE, "ST_MinimumDiameter") static
Referenced by MinimumDiameter.getURI().
st_minimumDiameterLine
final IRI st_minimumDiameterLine =factory.createIRI(NAMESPACE, "ST_MinimumDiameterLine") static
Referenced by MinimumDiameterLine.getURI().
st_minimumRectangle
final IRI st_minimumRectangle =factory.createIRI(NAMESPACE, "ST_MinimumRectangle") static
Referenced by MinimumRectangle.getURI().
st_minkowskidistance
final IRI st_minkowskidistance =factory.createIRI(NAMESPACE, "ST_MinkowskiDistance") static
st_minTileX
final IRI st_minTileX =factory.createIRI(NAMESPACE, "ST_MinTileX") static
Referenced by MinTileX.getURI().
st_minTileY
final IRI st_minTileY =factory.createIRI(NAMESPACE, "ST_MinTileY") static
Referenced by MinTileY.getURI().
st_mirror
final IRI st_mirror =factory.createIRI(NAMESPACE, "ST_Mirror") static
st_mLineFromText
final IRI st_mLineFromText =factory.createIRI(NAMESPACE, "ST_MLineFromText") static
Referenced by MLineFromText.getURI().
st_mMax
final IRI st_mMax =factory.createIRI(NAMESPACE, "ST_MMax") static
Referenced by MMax.getURI().
st_mMin
final IRI st_mMin =factory.createIRI(NAMESPACE, "ST_MMin") static
Referenced by MMin.getURI().
st_mPointFromText
final IRI st_mPointFromText =factory.createIRI(NAMESPACE, "ST_MPointFromText") static
Referenced by MPointFromText.getURI().
st_mPolyFromText
final IRI st_mPolyFromText =factory.createIRI(NAMESPACE, "ST_MPolyFromText") static
st_multi
final IRI st_multi =factory.createIRI(NAMESPACE, "ST_Multi") static
Referenced by Multi.getURI().
st_multiplyz
final IRI st_multiplyz =factory.createIRI(NAMESPACE, "ST_MultiplyZ") static
Referenced by MultiplyZ.getURI().
st_nDims
final IRI st_nDims =factory.createIRI(NAMESPACE, "ST_NDims") static
Referenced by NDims.getURI().
st_nearestValue
final IRI st_nearestValue =factory.createIRI(NAMESPACE, "ST_NearestValue") static
st_nodataPixelCount
final IRI st_nodataPixelCount =factory.createIRI(NAMESPACE, "ST_NoDataPixelCount") static
st_node
final IRI st_node =factory.createIRI(NAMESPACE, "ST_Node") static
Referenced by Node.getURI().
st_normalize
final IRI st_normalize =factory.createIRI(NAMESPACE, "ST_Normalize") static
Referenced by Normalize.getURI().
st_nPoints
final IRI st_nPoints =factory.createIRI(NAMESPACE, "ST_NumPoints") static
st_nRings
final IRI st_nRings =factory.createIRI(NAMESPACE, "ST_NRings") static
st_numBands
final IRI st_numBands =factory.createIRI(NAMESPACE, "ST_NumBands") static
Referenced by NumBands.getURI().
st_numDataElements
final IRI st_numDataElements =factory.createIRI(NAMESPACE, "ST_NumDataElements") static
Referenced by NumDataElements.getURI().
st_numDistinctGeometries
final IRI st_numDistinctGeometries =factory.createIRI(NAMESPACE, "ST_NumDistinctGeometries") static
Referenced by NumDistinctGeometries.getURI().
st_numDistinctInteriorRings
final IRI st_numDistinctInteriorRings =factory.createIRI(NAMESPACE, "ST_NumDistinctInteriorRings") static
Referenced by NumDistinctInteriorRings.getURI().
st_numDistinctPoints
final IRI st_numDistinctPoints =factory.createIRI(NAMESPACE, "ST_NumDistinctPoints") static
Referenced by NumDistinctPoints.getURI().
st_numGeometries
final IRI st_numGeometries =factory.createIRI(NAMESPACE, "ST_NumGeometries") static
Referenced by NumGeometries.getURI().
st_numInteriorRings
final IRI st_numInteriorRings =factory.createIRI(NAMESPACE, "ST_NumInteriorRings") static
Referenced by NumInteriorRings.getURI().
st_numPatches
final IRI st_numPatches =factory.createIRI(NAMESPACE, "ST_NumPatches") static
Referenced by NumPatches.getURI().
st_numPoints
final IRI st_numPoints =factory.createIRI(NAMESPACE, "ST_NumPoints") static
Referenced by NumPoints.getURI().
st_numXTiles
final IRI st_numXTiles =factory.createIRI(NAMESPACE, "ST_NumXTiles") static
Referenced by NumXTiles.getURI().
st_numYTiles
final IRI st_numYTiles =factory.createIRI(NAMESPACE, "ST_NumYTiles") static
Referenced by NumYTiles.getURI().
st_octogonalEnvelope
final IRI st_octogonalEnvelope =factory.createIRI(NAMESPACE, "ST_OctogonalEnvelope") static
Referenced by OctogonalEnvelope.getURI().
st_offsetCurve
final IRI st_offsetCurve =factory.createIRI(NAMESPACE, "ST_OffsetCurve") static
Referenced by OffsetCurve.getURI().
st_orderingEquals
final IRI st_orderingEquals =factory.createIRI(NAMESPACE, "ST_OrderingEquals") static
Referenced by OrderingEquals.getURI().
st_orientation
final IRI st_orientation =factory.createIRI(NAMESPACE, "ST_Orientation") static
Referenced by Orientation.getURI().
st_osmlink
final IRI st_osmlink =factory.createIRI(NAMESPACE, "ST_AsOSMLink") static
Referenced by AsOSMLink.getURI().
st_partOfGeometryAfter
final IRI st_partOfGeometryAfter =factory.createIRI(NAMESPACE, "ST_PartOfGeometryAfter") static
st_partOfGeometryBefore
final IRI st_partOfGeometryBefore =factory.createIRI(NAMESPACE, "ST_PartOfGeometryBefore") static
st_patchN
final IRI st_patchN =factory.createIRI(NAMESPACE, "ST_PatchN") static
st_perimeter
final IRI st_perimeter =factory.createIRI(NAMESPACE, "ST_Perimeter") static
Referenced by Perimeter.getURI().
st_perimeter2D
final IRI st_perimeter2D =factory.createIRI(NAMESPACE, "ST_Perimeter") static
st_perimeter3D
final IRI st_perimeter3D =factory.createIRI(NAMESPACE, "ST_Perimeter3D") static
Referenced by Perimeter3D.getURI().
st_pixelAsCentroid
final IRI st_pixelAsCentroid =factory.createIRI(NAMESPACE, "ST_PixelAsCentroid") static
st_pixelAsCentroids
final IRI st_pixelAsCentroids =factory.createIRI(NAMESPACE, "ST_PixelAsCentroids") static
st_pixelAsPoint
final IRI st_pixelAsPoint =factory.createIRI(NAMESPACE, "ST_PixelAsPoint") static
Referenced by PixelAsPoint.getURI().
st_pixelAsPoints
final IRI st_pixelAsPoints =factory.createIRI(NAMESPACE, "ST_PixelAsPoints") static
st_pixelAsPolygon
final IRI st_pixelAsPolygon =factory.createIRI(NAMESPACE, "ST_PixelAsPolygon") static
st_pixelAsPolygons
final IRI st_pixelAsPolygons =factory.createIRI(NAMESPACE, "ST_PixelAsPolygons") static
st_pixelHeight
final IRI st_pixelHeight =factory.createIRI(NAMESPACE, "ST_PixelHeight") static
Referenced by PixelHeight.getURI().
st_pixelOfValue
final IRI st_pixelOfValue =factory.createIRI(NAMESPACE, "ST_PixelOfValue") static
st_pixelWidth
final IRI st_pixelWidth =factory.createIRI(NAMESPACE, "ST_PixelWidth") static
st_pointFromGeoHash
final IRI st_pointFromGeoHash =factory.createIRI(NAMESPACE, "ST_PointFromGeoHash") static
Referenced by PointFromGeoHash.getURI().
st_pointFromText
final IRI st_pointFromText =factory.createIRI(NAMESPACE, "ST_PointFromText") static
Referenced by PointFromText.getURI().
st_pointFromWKB
final IRI st_pointFromWKB =factory.createIRI(NAMESPACE, "ST_PointFromWKB") static
Referenced by PointFromWKB.getURI().
st_pointInsideCircle
final IRI st_pointInsideCircle =factory.createIRI(NAMESPACE, "ST_PointInsideCircle") static
Referenced by PointInsideCircle.getURI().
st_pointN
final IRI st_pointN =factory.createIRI(NAMESPACE, "ST_PointN") static
Referenced by PointN.getURI().
st_pointOnSurface
final IRI st_pointOnSurface =factory.createIRI(NAMESPACE, "ST_PointOnSurface") static
Referenced by PointOnSurface.getURI().
st_points
final IRI st_points =factory.createIRI(NAMESPACE, "ST_Points") static
Referenced by Points.getURI().
st_polygon
final IRI st_polygon =factory.createIRI(NAMESPACE, "ST_Polygon") static
Referenced by Polygon.getURI().
st_polygonFromText
final IRI st_polygonFromText =factory.createIRI(NAMESPACE, "ST_PolygonFromText") static
Referenced by PolygonFromText.getURI().
st_polygonFromWKB
final IRI st_polygonFromWKB =factory.createIRI(NAMESPACE, "ST_PolygonFromWKB") static
Referenced by PolygonFromWKB.getURI().
st_polygonize
final IRI st_polygonize =factory.createIRI(NAMESPACE, "ST_Polygonize") static
Referenced by Polygonize.getURI().
st_precisionReducer
final IRI st_precisionReducer =factory.createIRI(NAMESPACE, "ST_PrecisionReducer") static
Referenced by PrecisionReducer.getURI().
ST_rast_algebra_abs
final IRI ST_rast_algebra_abs = factory.createIRI(NAMESPACE, "ST_Abs") static
Referenced by Abs.getURI().
ST_rast_algebra_add
final IRI ST_rast_algebra_add =factory.createIRI(NAMESPACE, "ST_Add") static
Referenced by Add.getURI().
ST_rast_algebra_addconst
final IRI ST_rast_algebra_addconst =factory.createIRI(NAMESPACE, "ST_AddConst") static
Referenced by AddConst.getURI().
ST_rast_algebra_and
final IRI ST_rast_algebra_and =factory.createIRI(NAMESPACE, "ST_And") static
Referenced by And.getURI().
ST_rast_algebra_andconst
final IRI ST_rast_algebra_andconst =factory.createIRI(NAMESPACE, "ST_AndConst") static
Referenced by AndConst.getURI().
ST_rast_algebra_div
final IRI ST_rast_algebra_div =factory.createIRI(NAMESPACE, "ST_Divide") static
Referenced by Div.getURI().
ST_rast_algebra_divconst
final IRI ST_rast_algebra_divconst =factory.createIRI(NAMESPACE, "ST_DivideConst") static
Referenced by DivConst.getURI().
ST_rast_algebra_equal
final IRI ST_rast_algebra_equal =factory.createIRI(NAMESPACE, "ST_Equal") static
ST_rast_algebra_exp
final IRI ST_rast_algebra_exp =factory.createIRI(NAMESPACE, "ST_Exp") static
Referenced by Exp.getURI().
ST_rast_algebra_idct
final IRI ST_rast_algebra_idct =factory.createIRI(NAMESPACE, "ST_IDCT") static
Referenced by IDCT.getURI().
ST_rast_algebra_idft
final IRI ST_rast_algebra_idft =factory.createIRI(NAMESPACE, "ST_IDFT") static
Referenced by IDFT.getURI().
ST_rast_algebra_invert
final IRI ST_rast_algebra_invert =factory.createIRI(NAMESPACE, "ST_Invert") static
Referenced by Invert.getURI().
ST_rast_algebra_log
final IRI ST_rast_algebra_log =factory.createIRI(NAMESPACE, "ST_Log") static
Referenced by Log.getURI().
ST_rast_algebra_max
final IRI ST_rast_algebra_max =factory.createIRI(NAMESPACE, "ST_Max") static
Referenced by Max.getURI().
ST_rast_algebra_maxfilter
final IRI ST_rast_algebra_maxfilter =factory.createIRI(NAMESPACE, "ST_MaxFilter") static
Referenced by MaxFilter.getURI().
ST_rast_algebra_mean
final IRI ST_rast_algebra_mean =factory.createIRI(NAMESPACE, "ST_Mean") static
Referenced by Mean.getURI().
ST_rast_algebra_medianfilter
final IRI ST_rast_algebra_medianfilter =factory.createIRI(NAMESPACE, "ST_MedianFilter") static
Referenced by MedianFilter.getURI().
ST_rast_algebra_min
final IRI ST_rast_algebra_min =factory.createIRI(NAMESPACE, "ST_Min") static
Referenced by Min.getURI().
ST_rast_algebra_minfilter
final IRI ST_rast_algebra_minfilter =factory.createIRI(NAMESPACE, "ST_MinFilter") static
Referenced by MinFilter.getURI().
ST_rast_algebra_mult
final IRI ST_rast_algebra_mult =factory.createIRI(NAMESPACE, "ST_Mult") static
Referenced by Mult.getURI().
ST_rast_algebra_multconst
final IRI ST_rast_algebra_multconst =factory.createIRI(NAMESPACE, "ST_MultConst") static
Referenced by MultConst.getURI().
ST_rast_algebra_not
final IRI ST_rast_algebra_not =factory.createIRI(NAMESPACE, "ST_Not") static
Referenced by Not.getURI().
ST_rast_algebra_or
final IRI ST_rast_algebra_or =factory.createIRI(NAMESPACE, "ST_Or") static
Referenced by Or.getURI().
ST_rast_algebra_orconst
final IRI ST_rast_algebra_orconst =factory.createIRI(NAMESPACE, "ST_OrConst") static
Referenced by OrConst.getURI().
ST_rast_algebra_subtract
final IRI ST_rast_algebra_subtract =factory.createIRI(NAMESPACE, "ST_Subtract") static
Referenced by Subtract.getURI().
ST_rast_algebra_subtractconst
final IRI ST_rast_algebra_subtractconst =factory.createIRI(NAMESPACE, "ST_SubtractConst") static
Referenced by SubtractConst.getURI().
ST_rast_algebra_xor
final IRI ST_rast_algebra_xor =factory.createIRI(NAMESPACE, "ST_Xor") static
Referenced by Xor.getURI().
ST_rast_algebra_xorconst
final IRI ST_rast_algebra_xorconst =factory.createIRI(NAMESPACE, "ST_XorConst") static
Referenced by XorConst.getURI().
st_rast_Contains
final IRI st_rast_Contains =factory.createIRI(NAMESPACE, "ST_Contains") static
st_rast_CoveredBy
final IRI st_rast_CoveredBy =factory.createIRI(NAMESPACE, "ST_CoveredBy") static
Referenced by CoveredBy.getURI().
st_rast_Covers
final IRI st_rast_Covers =factory.createIRI(NAMESPACE, "ST_Covers") static
st_rast_Crosses
final IRI st_rast_Crosses =factory.createIRI(NAMESPACE, "ST_Crosses") static
Referenced by Crosses.getURI().
st_rast_DFullyWithin
final IRI st_rast_DFullyWithin = factory.createIRI(NAMESPACE, "ST_DFullyWithin") static
Referenced by DFullyWithin.getURI().
st_rast_Disjoint
final IRI st_rast_Disjoint =factory.createIRI(NAMESPACE, "ST_Disjoint") static
Referenced by Disjoint.getURI().
st_rast_DWithin
final IRI st_rast_DWithin = factory.createIRI(NAMESPACE, "ST_DWithin") static
Referenced by DWithin.getURI().
st_rast_Intersection
final IRI st_rast_Intersection =factory.createIRI(NAMESPACE, "ST_Intersection") static
Referenced by Intersection.getURI().
st_rast_Intersects
final IRI st_rast_Intersects =factory.createIRI(NAMESPACE, "ST_Intersects") static
Referenced by Intersects.getURI().
st_rast_isEmpty
final IRI st_rast_isEmpty =factory.createIRI(NAMESPACE, "ST_IsEmpty") static
st_rast_maxX
final IRI st_rast_maxX = factory.createIRI(NAMESPACE, "ST_MaxX") static
st_rast_maxY
final IRI st_rast_maxY = factory.createIRI(NAMESPACE, "ST_MaxY") static
st_rast_minX
final IRI st_rast_minX = factory.createIRI(NAMESPACE, "ST_MinX") static
st_rast_minY
final IRI st_rast_minY = factory.createIRI(NAMESPACE, "ST_MinY") static
st_rast_Overlaps
final IRI st_rast_Overlaps =factory.createIRI(NAMESPACE, "ST_Overlaps") static
Referenced by Overlaps.getURI().
st_rast_SameAlignment
final IRI st_rast_SameAlignment = factory.createIRI(NAMESPACE, "ST_SameAlignment") static
Referenced by SameAlignment.getURI().
st_rast_srid
final IRI st_rast_srid =factory.createIRI(NAMESPACE, "ST_SRID") static
st_rast_Touches
final IRI st_rast_Touches =factory.createIRI(NAMESPACE, "ST_Touches") static
Referenced by Touches.getURI().
st_rast_Within
final IRI st_rast_Within =factory.createIRI(NAMESPACE, "ST_Within") static
Referenced by Within.getURI().
st_rasterToWorldCoord
final IRI st_rasterToWorldCoord =factory.createIRI(NAMESPACE, "ST_RasterToWorldCoord") static
Referenced by RasterToWorldCoord.getURI().
st_rasterToWorldCoordX
final IRI st_rasterToWorldCoordX =factory.createIRI(NAMESPACE, "ST_RasterToWorldCoordX") static
Referenced by RasterToWorldCoordX.getURI().
st_rasterToWorldCoordY
final IRI st_rasterToWorldCoordY =factory.createIRI(NAMESPACE, "ST_RasterToWorldCoordY") static
Referenced by RasterToWorldCoordY.getURI().
st_rastFromCovJSON
final IRI st_rastFromCovJSON =factory.createIRI(NAMESPACE,"ST_RastFromCovJSON") static
Referenced by RastFromCoverageJSON.getURI().
st_rastFromGMLCOV
final IRI st_rastFromGMLCOV =factory.createIRI(NAMESPACE,"ST_RastFromGMLCOV") static
Referenced by RastFromGMLCOV.getURI().
st_rastFromHexWKB
final IRI st_rastFromHexWKB =factory.createIRI(NAMESPACE, "ST_RastFromHexWKB") static
Referenced by RastFromHexWKB.getURI().
st_rastFromNetCDF
final IRI st_rastFromNetCDF =factory.createIRI(NAMESPACE,"ST_RastFromNetCDF") static
Referenced by RastFromNetCDF.getURI().
st_rastFromWKB
final IRI st_rastFromWKB =factory.createIRI(NAMESPACE, "ST_RastFromWKB") static
Referenced by RastFromWKB.getURI().
st_rayCrossings
final IRI st_rayCrossings =factory.createIRI(NAMESPACE, "ST_RayCrossings") static
st_reflect
final IRI st_reflect =factory.createIRI(NAMESPACE, "ST_Reflect") static
Referenced by Reflect.getURI().
st_relate
final IRI st_relate =factory.createIRI(NAMESPACE, "ST_Relate") static
Referenced by Relate.getURI().
st_relateMatch
final IRI st_relateMatch =factory.createIRI(NAMESPACE, "ST_RelateMatch") static
Referenced by RelateMatch.getURI().
st_removeGeometry
final IRI st_removeGeometry =factory.createIRI(NAMESPACE, "ST_RemoveGeometry") static
Referenced by RemoveGeometry.getURI().
st_removeInteriorRing
final IRI st_removeInteriorRing =factory.createIRI(NAMESPACE, "ST_RemoveInteriorRing") static
Referenced by RemoveInteriorRing.getURI().
st_removePoint
final IRI st_removePoint =factory.createIRI(NAMESPACE, "ST_RemovePoint") static
Referenced by RemovePoint.getURI().
st_removePoints
final IRI st_removePoints =factory.createIRI(NAMESPACE, "ST_RemovePoints") static
st_removeRepeatedPoints
final IRI st_removeRepeatedPoints =factory.createIRI(NAMESPACE, "ST_RemoveRepeatedPoints") static
Referenced by RemoveRepeatedPoints.getURI().
st_resample
final IRI st_resample =factory.createIRI(NAMESPACE, "ST_Resample") static
Referenced by Resample.getURI().
st_rescale
final IRI st_rescale =factory.createIRI(NAMESPACE, "ST_Rescale") static
Referenced by Rescale.getURI().
st_resize
final IRI st_resize =factory.createIRI(NAMESPACE, "ST_Resize") static
st_reskew
final IRI st_reskew =factory.createIRI(NAMESPACE, "ST_Reskew") static
st_retile
final IRI st_retile =factory.createIRI(NAMESPACE, "ST_Retile") static
st_reverse
final IRI st_reverse =factory.createIRI(NAMESPACE, "ST_Reverse") static
Referenced by Reverse.getURI().
st_reverseRing
final IRI st_reverseRing =factory.createIRI(NAMESPACE, "ST_ReverseRing") static
Referenced by ReverseRing.getURI().
st_ringsCutAtNodes
final IRI st_ringsCutAtNodes =factory.createIRI(NAMESPACE, "ST_RingsCutAtNodes") static
Referenced by RingsCutAtNodes.getURI().
st_rotate
final IRI st_rotate =factory.createIRI(NAMESPACE, "ST_Rotate") static
Referenced by Rotate.getURI().
st_rotateX
final IRI st_rotateX =factory.createIRI(NAMESPACE, "ST_RotateX") static
Referenced by RotateX.getURI().
st_rotateY
final IRI st_rotateY =factory.createIRI(NAMESPACE, "ST_RotateY") static
st_rotateZ
final IRI st_rotateZ =factory.createIRI(NAMESPACE, "ST_RotateZ") static
st_rotation
final IRI st_rotation =factory.createIRI(NAMESPACE, "ST_Rotation") static
st_roughness
final IRI st_roughness =factory.createIRI(NAMESPACE, "ST_Roughness") static
st_scale
final IRI st_scale =factory.createIRI(NAMESPACE, "ST_Scale") static
st_scaleX
final IRI st_scaleX =factory.createIRI(NAMESPACE, "ST_ScaleX") static
Referenced by ScaleX.getURI().
st_scaleY
final IRI st_scaleY =factory.createIRI(NAMESPACE, "ST_ScaleY") static
Referenced by ScaleY.getURI().
st_segmentize
final IRI st_segmentize =factory.createIRI(NAMESPACE, "ST_Segmentize") static
Referenced by Segmentize.getURI(), and SubdivideLines.getURI().
ST_selfIntersections
final IRI ST_selfIntersections =factory.createIRI(NAMESPACE, "ST_SelfIntersections") static
Referenced by SelfIntersections.getURI().
st_setBandNoDataValue
final IRI st_setBandNoDataValue = factory.createIRI(NAMESPACE, "ST_SetBandNoDataValue") static
Referenced by SetBandNoDataValue.getURI().
st_setEndPoint
final IRI st_setEndPoint =factory.createIRI(NAMESPACE, "ST_SetEndPoint") static
Referenced by SetEndPoint.getURI().
st_setGeometry
final IRI st_setGeometry =factory.createIRI(NAMESPACE, "ST_SetGeometry") static
Referenced by SetGeometry.getURI().
st_setGeoReference
final IRI st_setGeoReference =factory.createIRI(NAMESPACE, "ST_SetGeoReference") static
st_setInteriorRing
final IRI st_setInteriorRing =factory.createIRI(NAMESPACE, "ST_SetInteriorRing") static
Referenced by SetInteriorRing.getURI().
st_setPoint
final IRI st_setPoint =factory.createIRI(NAMESPACE, "ST_SetPoint") static
Referenced by SetPoint.getURI().
st_setRotation
final IRI st_setRotation =factory.createIRI(NAMESPACE, "ST_SetRotation") static
Referenced by SetRotation.getURI().
st_setScale
final IRI st_setScale =factory.createIRI(NAMESPACE, "ST_SetScale") static
Referenced by SetScale.getURI().
st_setSkew
final IRI st_setSkew =factory.createIRI(NAMESPACE, "ST_SetSkew") static
Referenced by SetSkew.getURI().
st_setSRID
final IRI st_setSRID =factory.createIRI(NAMESPACE, "ST_SetSRID") static
Referenced by SetSRID.getURI().
st_setStartPoint
final IRI st_setStartPoint =factory.createIRI(NAMESPACE, "ST_SetStartPoint") static
Referenced by SetStartPoint.getURI().
st_setUpperLeft
final IRI st_setUpperLeft =factory.createIRI(NAMESPACE, "ST_SetUpperLeft") static
Referenced by SetUpperLeft.getURI().
st_sharedPaths
final IRI st_sharedPaths =factory.createIRI(NAMESPACE, "ST_SharedPaths") static
Referenced by SharedPaths.getURI().
st_shearTransformation
final IRI st_shearTransformation =factory.createIRI(NAMESPACE, "ST_ShearTransformation") static
Referenced by ShearTransformation.getURI().
st_shearx
final IRI st_shearx =factory.createIRI(NAMESPACE, "ST_ShearX") static
Referenced by ShearX.getURI().
st_sheary
final IRI st_sheary =factory.createIRI(NAMESPACE, "ST_ShearY") static
Referenced by ShearY.getURI().
st_shift
final IRI st_shift =factory.createIRI(NAMESPACE, "ST_Shift") static
st_shiftLongitude
final IRI st_shiftLongitude =factory.createIRI(NAMESPACE, "ST_ShiftLongitude") static
Referenced by ShiftLongitude.getURI().
st_shortestLine
final IRI st_shortestLine =factory.createIRI(NAMESPACE, "ST_ShortestLine") static
Referenced by ShortestLine.getURI().
ST_SHORTESTLINE3D
final IRI ST_SHORTESTLINE3D =factory.createIRI(NAMESPACE, "ST_ShortestLine3D") static
st_shortestLine3D
final IRI st_shortestLine3D =factory.createIRI(NAMESPACE, "ST_ShortestLine3D") static
Referenced by ShortestLine3D.getURI().
st_simplify
final IRI st_simplify =factory.createIRI(NAMESPACE, "ST_Simplify") static
Referenced by Simplify.getURI().
st_simplifyPreserveTopology
final IRI st_simplifyPreserveTopology =factory.createIRI(NAMESPACE, "ST_SimplifyPreserveTopology") static
Referenced by SimplifyPreserveTopology.getURI().
st_simplifyVW
final IRI st_simplifyVW =factory.createIRI(NAMESPACE, "ST_SimplifyVW") static
Referenced by SimplifyVW.getURI().
st_skewX
final IRI st_skewX =factory.createIRI(NAMESPACE, "ST_SkewX") static
Referenced by SkewX.getURI().
st_skewY
final IRI st_skewY =factory.createIRI(NAMESPACE, "ST_SkewY") static
Referenced by SkewY.getURI().
st_slope
final IRI st_slope =factory.createIRI(NAMESPACE, "ST_Slope") static
st_snap
final IRI st_snap =factory.createIRI(NAMESPACE, "ST_Snap") static
Referenced by Snap.getURI().
st_split
final IRI st_split =factory.createIRI(NAMESPACE, "ST_Split") static
st_srid
final IRI st_srid =factory.createIRI(NAMESPACE, "ST_GetSRIDFF") static
st_sridToEPSG
final IRI st_sridToEPSG =factory.createIRI(NAMESPACE, "ST_SRIDToEPSG") static
st_startPoint
final IRI st_startPoint =factory.createIRI(NAMESPACE, "ST_StartPoint") static
Referenced by StartPoint.getURI().
st_straightSkeleton
final IRI st_straightSkeleton =factory.createIRI(NAMESPACE, "ST_StraightSkeleton") static
st_subdividelines
final IRI st_subdividelines = factory.createIRI(NAMESPACE, "ST_SubdivideLines") static
st_summary
final IRI st_summary =factory.createIRI(NAMESPACE, "ST_Summary") static
st_swapOrdinates
final IRI st_swapOrdinates =factory.createIRI(NAMESPACE, "ST_SwapOrdinates") static
Referenced by SwapOrdinates.getURI().
st_symDifference
final IRI st_symDifference =factory.createIRI(NAMESPACE, "ST_SymDifference") static
st_t
final IRI st_t =factory.createIRI(NAMESPACE, "ST_T") static
st_tesselate
final IRI st_tesselate =factory.createIRI(NAMESPACE, "ST_Tesselate") static
st_tileGridXOffset
final IRI st_tileGridXOffset = factory.createIRI(NAMESPACE, "ST_TileGridXOffset") static
Referenced by TileGridXOffset.getURI().
st_tileGridYOffset
final IRI st_tileGridYOffset = factory.createIRI(NAMESPACE, "ST_TileGridYOffset") static
Referenced by TileGridYOffset.getURI().
st_tileHeight
final IRI st_tileHeight = factory.createIRI(NAMESPACE, "ST_TileHeight") static
Referenced by TileHeight.getURI().
st_tileWidth
final IRI st_tileWidth = factory.createIRI(NAMESPACE, "ST_TileWidth") static
Referenced by TileWidth.getURI().
st_tMax
final IRI st_tMax =factory.createIRI(NAMESPACE, "ST_TMax") static
st_tMin
final IRI st_tMin =factory.createIRI(NAMESPACE, "ST_TMin") static
ST_ToDegrees
final IRI ST_ToDegrees =factory.createIRI(NAMESPACE, "ST_ToDegrees") static
Referenced by ToDegrees.getURI().
ST_Topo_AddLineString
final IRI ST_Topo_AddLineString = factory.createIRI(NAMESPACE, "ST_Topo_AddLineString") static
ST_Topo_AddPoint
final IRI ST_Topo_AddPoint = factory.createIRI(NAMESPACE, "ST_Topo_AddPoint") static
Referenced by Topo_AddPoint.getURI().
ST_TopologyFromTopoJSON
final IRI ST_TopologyFromTopoJSON = factory.createIRI(NAMESPACE, "ST_TopologyFromTopoJSON") static
ST_ToRadians
final IRI ST_ToRadians =factory.createIRI(NAMESPACE, "ST_ToRadians") static
Referenced by ToRadians.getURI().
st_toRaster
final IRI st_toRaster = factory.createIRI(NAMESPACE, "ST_ToRaster") static
Referenced by ToRaster.getURI().
st_tpi
final IRI st_tpi =factory.createIRI(NAMESPACE, "ST_TPI") static
st_trajectoryInterpolatePoint
final IRI st_trajectoryInterpolatePoint =factory.createIRI(NAMESPACE, "ST_TrajectoryInterpolatePoint") static
st_transform
final IRI st_transform =factory.createIRI(NAMESPACE, "ST_Transform") static
Referenced by Transform.getURI().
st_translate
final IRI st_translate =factory.createIRI(NAMESPACE, "ST_Translate") static
Referenced by Translate.getURI().
st_translatex
final IRI st_translatex =factory.createIRI(NAMESPACE, "ST_TranslateX") static
Referenced by TranslateX.getURI().
st_translatey
final IRI st_translatey =factory.createIRI(NAMESPACE, "ST_TranslateY") static
Referenced by TranslateY.getURI().
st_transscale
final IRI st_transscale =factory.createIRI(NAMESPACE, "ST_TransScale") static
Referenced by TransScale.getURI().
st_tri
final IRI st_tri =factory.createIRI(NAMESPACE, "ST_TRI") static
st_unaryUnion
final IRI st_unaryUnion =factory.createIRI(NAMESPACE, "ST_UnaryUnion") static
st_union
final IRI st_union =factory.createIRI(NAMESPACE, "ST_Union") static
st_upperLeftX
final IRI st_upperLeftX =factory.createIRI(NAMESPACE, "ST_UpperLeftX") static
Referenced by UpperLeftX.getURI().
st_upperLeftY
final IRI st_upperLeftY =factory.createIRI(NAMESPACE, "ST_UpperLeftY") static
Referenced by UpperLeftY.getURI().
st_value
final IRI st_value = factory.createIRI(NAMESPACE, "ST_Value") static
Referenced by Value.getURI().
st_vectorize
final IRI st_vectorize =factory.createIRI(NAMESPACE, "ST_Vectorize") static
st_volume
final IRI st_volume =factory.createIRI(NAMESPACE, "ST_Volume") static
st_voronoiLines
final IRI st_voronoiLines =factory.createIRI(NAMESPACE, "ST_VoronoiLines") static
st_voronoiPolygons
final IRI st_voronoiPolygons =factory.createIRI(NAMESPACE, "ST_VoronoiPolygons") static
Referenced by VoronoiPolygons.getURI().
st_width
final IRI st_width =factory.createIRI(NAMESPACE, "ST_Width") static
Referenced by Width.getURI().
st_wkbToSQL
final IRI st_wkbToSQL =factory.createIRI(NAMESPACE, "ST_GeomFromWKB") static
st_wktToSQL
final IRI st_wktToSQL =factory.createIRI(NAMESPACE, "ST_GeomFromText") static
st_worldToRasterCoord
final IRI st_worldToRasterCoord =factory.createIRI(NAMESPACE, "ST_WorldToRasterCoord") static
Referenced by WorldToRasterCoord.getURI().
st_worldToRasterCoordX
final IRI st_worldToRasterCoordX =factory.createIRI(NAMESPACE, "ST_WorldToRasterCoordX") static
Referenced by WorldToRasterCoordX.getURI().
st_worldToRasterCoordY
final IRI st_worldToRasterCoordY =factory.createIRI(NAMESPACE, "ST_WorldToRasterCoordY") static
Referenced by WorldToRasterCoordY.getURI().
st_x
final IRI st_x =factory.createIRI(NAMESPACE, "ST_X") static
Referenced by X.getURI().
st_xMax
final IRI st_xMax =factory.createIRI(NAMESPACE, "ST_XMax") static
Referenced by XMax.getURI().
st_xMin
final IRI st_xMin =factory.createIRI(NAMESPACE, "ST_XMin") static
Referenced by XMin.getURI().
st_y
final IRI st_y =factory.createIRI(NAMESPACE, "ST_Y") static
Referenced by Y.getURI().
st_yMax
final IRI st_yMax =factory.createIRI(NAMESPACE, "ST_YMax") static
Referenced by YMax.getURI().
st_yMin
final IRI st_yMin =factory.createIRI(NAMESPACE, "ST_YMin") static
Referenced by YMin.getURI().
st_z
final IRI st_z =factory.createIRI(NAMESPACE, "ST_Z") static
Referenced by Z.getURI().
st_zMax
final IRI st_zMax =factory.createIRI(NAMESPACE, "ST_ZMax") static
Referenced by ZMax.getURI().
st_zmFlag
final IRI st_zmFlag =factory.createIRI(NAMESPACE, "ST_Zmflag") static
Referenced by Zmflag.getURI().
st_zMin
final IRI st_zMin =factory.createIRI(NAMESPACE, "ST_ZMin") static
Referenced by ZMin.getURI().
SVG
final String SVG ="SVG" static
Tan
final IRI Tan =factory.createIRI(NAMESPACE, "Tan") static
Referenced by Tangent.getURI().
TanH
final IRI TanH =factory.createIRI(NAMESPACE, "TanH") static
Referenced by TanH.getURI().
TemporalRange
final String TemporalRange ="TemporalRange" static
TopoJSON
final String TopoJSON = "TopoJSON" static
TWKB
final String TWKB = "TWKB" static
USFootToMeter
final IRI USFootToMeter =factory.createIRI(NAMESPACE, "USFootToMeter") static
Referenced by USFootToMeter.getURI().
USInchToMeter
final IRI USInchToMeter =factory.createIRI(NAMESPACE, "USInchToMeter") static
Referenced by USInchToMeter.getURI().
USMileToMeter
final IRI USMileToMeter =factory.createIRI(NAMESPACE, "USMileToMeter") static
Referenced by USMileToMeter.getURI().
USYardToMeter
final IRI USYardToMeter =factory.createIRI(NAMESPACE, "USYardToMeter") static
Referenced by USYardToMeter.getURI().
WKB
final String WKB = "WKB" static
WKBRaster
final String WKBRaster = "WKBRaster" static
WKT
final String WKT ="WKT" static
X3D
final String X3D = "X3D" static
YardToMeter
final IRI YardToMeter =factory.createIRI(NAMESPACE, "YardToMeter") static
Referenced by YardToMeter.getURI().