rdf4j-postgis: ConcatenateLines Class Reference
ConcatenateLines Class Reference
Public Member Functions
ConcatenateLines (ValueExpr arg)
ConcatenateLines (ValueExpr arg, boolean distinct)
boolean equals (Object other)
int hashCode ()
ConcatenateLines clone ()
Package Functions
public< X extends Exception > void visit (QueryModelVisitor< X > visitor) throws X
Constructor & Destructor Documentation
ConcatenateLines() [1/2]
ConcatenateLines (ValueExpr arg)
{
                 super(arg);
         }
ConcatenateLines() [2/2]
ConcatenateLines (ValueExpr arg, boolean distinct)
{
                 super(arg, distinct);
         }
Member Function Documentation
clone()
ConcatenateLines clone ()
References ConcatenateLines.clone().
Referenced by ConcatenateLines.clone().
{
                 return (ConcatenateLines) super.clone();
         }
equals()
boolean equals (Object other)
References AggCentroid.equals().
{
                 return other instanceof AggCentroid && super.equals(other);
         }
hashCode()
int hashCode ()
{
                 return super.hashCode() ^ "ConcatenateLines".hashCode();
         }
visit()
public<X extends Exception> void visit (QueryModelVisitor< X > visitor) throws X package
{
                 visitor.meet(this);
         }