rdf4j-postgis: TripleStoreConnection Class Reference
TripleStoreConnection Class Reference
Public Member Functions
TripleStoreConnection ()
Static Public Member Functions
static String executeQuery (String query, String model) throws JSONException
static void main (String[] args) throws JSONException
Static Public Attributes
static final TripleStoreConnection INSTANCE = new TripleStoreConnection()
static final String prefixCollection
static final Map< String, Model > modelmap =new TreeMap<>()
static Repository repo = new SailRepository(new MemoryStore())
Constructor & Destructor Documentation
TripleStoreConnection()
TripleStoreConnection ()
{
                 //modelmap=new TreeMap<>();
                 repo= new SailRepository(new MemoryStore());
                 repo.initialize();
                 // read the file 'example-data-artists.ttl' as an InputStream.
                 //InputStream input = Example08ReadTurtle.class.getResourceAsStream("/" + filename);
                 try {
                         //modelmap.put("testdata.ttl", Rio.parse(new File("testdata.ttl").toURL().openStream(), "", RDFFormat.TURTLE));
                         modelmap.put("testdata2.ttl", Rio.parse(new File("testdata2.ttl").toURL().openStream(), "", RDFFormat.TURTLE));
                         //modelmap.put("rasterexample.ttl", Rio.parse(new File("rasterexample.ttl").toURL().openStream(), "", RDFFormat.TURTLE));
                 } catch (RDFParseException | UnsupportedRDFormatException | IOException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 }
                 // modelmap.put("testdata3.ttl", ModelFactory.createOntologyModel());
                 // modelmap.put("testdata4.ttl", ModelFactory.createOntologyModel());
         }
Member Function Documentation
executeQuery()
static String executeQuery (String query, String model) throws JSONException static
References LiteralRegistry.getLiteral(), TripleStoreConnection.modelmap, and AsGeoJSON.operation().
Referenced by ExampleWebService.main(), TripleStoreConnection.main(), and ExampleWebService.queryService().
{
                 query=prefixCollection+query;
                 System.out.println(query);
                 System.out.println(model);
                 System.out.println(INSTANCE.modelmap.keySet());
                 RepositoryConnection con = repo.getConnection();
                 System.out.println(INSTANCE.modelmap);
                 con.begin();
                 con.add(INSTANCE.modelmap.get(model));
                 con.commit();
                 //System.out.println("Empty? "+con.isEmpty());
                 /*for(Statement statement:modelmap.get(model)) {
                         System.out.println(statement);
                 }*/
                 TupleQuery tupleQuery = con.prepareTupleQuery(QueryLanguage.SPARQL, query);
                 //System.out.println(tupleQuery.toString());
                 TupleQueryResult qresult = tupleQuery.evaluate();
                 //System.out.println(qresult.getBindingNames());
                 //System.out.println(qresult.hasNext());
                 //System.out.println(qresult.);
                 List<JSONArray> allfeatures=new LinkedList<JSONArray>();
                 JSONObject result=new JSONObject();
                 JSONArray geojsonresults=new JSONArray();
                 JSONArray obj=new JSONArray();
                 Boolean first=true;
                 while(qresult.hasNext()) {
                         BindingSet bindingSet = qresult.next();
                         JSONObject jsonobj=new JSONObject();
                         JSONObject properties=new JSONObject();
                         List<JSONObject> geoms=new LinkedList<JSONObject>();
                         int geomvars=0;
                         for(String name:bindingSet.getBindingNames()) {
                                 if(name.endsWith("_geom")) {
                                         //System.out.println(name+" end with geom");
                                         if(first) {
                                                 JSONObject geojsonresult=new JSONObject();
                                                 geojsonresult.put("type", "FeatureCollection");
                                                 geojsonresult.put("name", name);
                                                 JSONArray features=new JSONArray();
                                                 allfeatures.add(features);
                                                 geojsonresults.put(geojsonresult);
                                                 geojsonresults.getJSONObject(geojsonresults.length()-1).put("features",features);
                                         }
                                         geomvars++;
                                         AsGeoJSON geojson=new AsGeoJSON();
                                         Value val=bindingSet.getValue(name);
                                         Literal lit=(Literal)val;
                                         //System.out.println(LiteralRegistry.INSTANCE.literals);
                                         //System.out.println(LiteralRegistry.getLiteral(lit.getDatatype().toString()));
                                         if(LiteralRegistry.getLiteral(lit.getDatatype().toString())!=null){
                                                 LiteralType l=LiteralRegistry.getLiteral(lit.getDatatype().toString());
                                                 Geometry geom=((VectorLiteral)l).read(bindingSet.getValue(name).stringValue());
                                                 String geojsonstring=geojson.operation(geom);
                                                 JSONObject geomobj=new JSONObject(geojsonstring);
                                                 geoms.add(geomobj);
                                         }
                                         //System.out.println("Geoms: "+geoms.size());
                                 }
                                 jsonobj.put(name, bindingSet.getValue(name));
                                 properties.put(name, bindingSet.getValue(name));
                                 obj.put(jsonobj);
                         }
                         first=false;
                         int geomcounter=0;
                         for(JSONObject geom:geoms) {
                                 JSONObject geojsonobj=new JSONObject();
                                 geojsonobj.put("type", "Feature");
                                 geojsonobj.put("properties", properties);
                                 geojsonobj.put("geometry", geom);
                                 allfeatures.get(geomcounter%geomvars).put(geojsonobj);
                                 geomcounter++;
                         }
                 }
                 result.put("geojson", geojsonresults);
                 result.put("data", obj);
                 //result.put("size", test.size());
                 return result.toString();
         }
main()
static void main (String [] args) throws JSONException static
References TripleStoreConnection.executeQuery().
{
                 String res = TripleStoreConnection.executeQuery(
                                 " SELECT ?geom ?wkt_geom WHERE { ?geom geo:asWKT ?wkt_geom .  } LIMIT 10",
                                 "testdata2.ttl");
                 // System.out.println(res[0]);
                 System.out.println(res);
                 System.out.println(
                                 "=====================================================================================================");
                 /*res = TripleStoreConnection.executeQuery(
                                         "SELECT ?geom ?wkt WHERE { ?geom geo:asWKT ?wkt . FILTER(geo:ST_Area(?wkt)>10) }", "testdata2.ttl");
                         // System.out.println(res[0]);
                         System.out.println(res);
                         res = TripleStoreConnection.executeQuery(
                                         "SELECT ?wkt2 WHERE { ?geom geo:asWKT ?wkt . BIND(geo:ST_YMax(?wkt) AS ?wkt2). FILTER(geo:ST_Area(?wkt)>10) }",
                                         "testdata2.ttl");
                         System.out.println(res);
                         System.out.println(res);*/
         }
Member Data Documentation
INSTANCE
final TripleStoreConnection INSTANCE = new TripleStoreConnection() static
modelmap
final Map<String, Model> modelmap =new TreeMap<>() static
Referenced by TripleStoreConnection.executeQuery().
prefixCollection
final String prefixCollection static
Initial value:
= "PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>"
                        + System.lineSeparator() + "PREFIX geo: <http://www.opengis.net/ont/geosparql#>"
repo
Repository repo = new SailRepository(new MemoryStore()) static