rdf4j-postgis: LLtoGARS Class Reference
LLtoGARS Class Reference
https://github.com/mil-oss/GARSutils MIT License
Static Public Member Functions
static String getLongitudeBand (double longitude)
Get the GARS 3 letter longitude band descriptor for a given longitude (-180.0..180.0)
static String getLatitudeBand (double latitude)
Get the GARS 2 letter latitude band descriptor for a given latitude (-90..90)
static String getQudarant (double latitude, double longitude)
Returns the GARS 15 minute quadrant cell identifier for a latitude, longitude pair.This identifier is the 6th character of the GARS code.
static String getKeyPad (double latitude, double longitude)
Returns the GARS 5 minute keypad cell identifier for a latitude, longitude pair.
static String getGARS (double latitude, double longitude, String precision)
Returns a GARS coordinate string for a point (latitude, longitude)
static String getGARS (double latitude, double longitude)
Returns a GARS 5x5 minute coordinate string for a point (latitude, longitude)
Detailed Description
https://github.com/mil-oss/GARSutils MIT License
Author
marty
Member Function Documentation
getGARS() [1/2]
static String getGARS (double latitude, double longitude, String precision) static
Returns a GARS coordinate string for a point (latitude, longitude)
The precision parameter indicates if a 30x30min, 15x15min, or 5x5min GARS code is to be returned.
Valid precision values are ["30","15","5"]
Parameters
latitude as double in degrees decimal
longitude as double in degrees decimal
precision as String representing the precision of the GARS string
Returns
String representation of the GARS identifier, returns 0 if lat/lon is invalid
Referenced by LLtoGARS.getGARS(), and AsGARS.operation().
{
         /* North pole is an exception, read over and down */
         if (latitude == 90.0) {
             latitude = 89.99999999999;
         }
         // Check for valid lat/lon range
         if (latitude < -90 || latitude > 90) {
             return "0";
         }
         if (longitude < -180 || longitude > 180) {
             return "0";
         }
         // Get the longitude band ==============================================
         Double longBand = longitude + 180;
         // Normalize to 0.0 <= longBand < 360
         while (longBand < 0) {
             longBand = longBand + 360;
         }
         while (longBand > 360) {
             longBand = longBand - 360;
         }
         longBand = Math.floor(longBand * 2.0);
         Integer intLongBand = longBand.intValue() + 1; // Start at 001, not 000
         String strLongBand = intLongBand.toString();
         // Left pad the string with 0's so X becomes 00X
         while (strLongBand.length() < 3) {
             strLongBand = "0" + strLongBand;
         }
         // Get the latitude band ===============================================
         char[] letterArray = "ABCDEFGHJKLMNPQRSTUVWXYZ".toCharArray();
         Double offset = latitude + 90;
         // Normalize offset to 0< offset <90
         while (offset < 0) {
             offset = offset + 180;
         }
         while (offset > 180) {
             offset = offset - 180;
         }
         offset = Math.floor(offset * 2.0);
         Double firstOffest = offset / letterArray.length;
         Double secondOffest = offset % letterArray.length;
         StringBuilder sb = new StringBuilder();
         String strLatBand = sb.append(letterArray[firstOffest.intValue()]).append(letterArray[secondOffest.intValue()]).toString();
         // Id the precision is 30x30min then return the longitudinal and latitudinal bands
         if (precision.contains("30")) {
             return strLongBand + strLatBand;
         }
         // Get the quadrant ====================================================
         Double latBand = (Math.floor((latitude + 90.0) * 4.0) % 2.0);
         longBand = (Math.floor((longitude + 180.0) * 4.0) % 2.0);
         String quadrant = "0";
         // return "0" if error occurs
         if (latBand < 0 || latBand > 1) {
             return "0";
         }
         if (longBand < 0 || longBand > 1) {
             return "0";
         }
         // Otherwise get the quadrant
         if (latBand == 0.0 && longBand == 0.0) {
             quadrant = "3";
         } else if (latBand == 1.0 && longBand == 0.0) {
             quadrant = "1";
         } else if (latBand == 1.0 && longBand == 1.0) {
             quadrant = "2";
         } else if (latBand == 0.0 && longBand == 1.0) {
             quadrant = "4";
         }
         // Id the precision is 15x15min then return the longitudinal and latitudinal bands
         // plus the quadrant
         if (precision.contains("15")) {
             return strLongBand + strLatBand + quadrant;
         }
         // Get the keypad ======================================================
         /* Convert longitude and latitude from degrees to minutes */
         /* longitude assumed in -180 <= long < +180 range */
         double long_minutes = (longitude + 180) * 60.0;
         double lat_minutes = (latitude + 90) * 60.0;
         /* now we have a positive number of minutes */
         /* Find 30-min cell indices 0-719 and 0-359 */
         long horiz_index_30 = (long) (long_minutes / 30.0);
         long vert_index_30 = (long) (lat_minutes / 30.0);
         /* Compute remainders 0 <= x < 30.0 */
         double long_remainder = long_minutes - (horiz_index_30) * 30.0;
         double lat_remainder = lat_minutes - (vert_index_30) * 30.0;
         /* Find 15-min cell indices 0 or 1 */
         long horiz_index_15 = (long) (long_remainder / 15.0);
         long vert_index_15 = (long) (lat_remainder / 15.0);
         /* Compute remainders 0 <= x < 15.0 */
         long_remainder = long_remainder - (horiz_index_15) * 15.0;
         lat_remainder = lat_remainder - (vert_index_15) * 15.0;
         /* Find 5-min cell indices 0, 1, or 2 */
         long horiz_index_5 = (long) (long_remainder / 5.0);
         long vert_index_5 = (long) (lat_remainder / 5.0);
         String[][] _5_minute_array = {{"7", "4", "1"}, {"8", "5", "2"}, {"9", "6", "3"}};
         String keypad = _5_minute_array[(int) horiz_index_5][(int) vert_index_5];
         return strLongBand + strLatBand + quadrant + keypad;
     }//getGARS
getGARS() [2/2]
static String getGARS (double latitude, double longitude) static
Returns a GARS 5x5 minute coordinate string for a point (latitude, longitude)
Parameters
latitude as double in degrees decimal
longitude as double in degrees decimal
Returns
String representation of the GARS identifier, returns 0 if lat/lon is invalid
References LLtoGARS.getGARS().
{
         return getGARS(latitude, longitude, "5");
     }//getGARS
getKeyPad()
static String getKeyPad (double latitude, double longitude) static
Returns the GARS 5 minute keypad cell identifier for a latitude, longitude pair.
This is the seventh character of the GARS code.
Each 15-minute quadrant is divided into nine 5-minute by 5-minute areas. The areas are numbered sequentially, from west to east, starting with the northernmost band. The graphical representation of a 15-minute quadrant with numbered 5-minute by 5-minute areas resembles a telephone keypad.
This code was ported from the Geotrans 3.5 CCP implementation: http://earth-info.nga.mil/GandG/geotrans/
Parameters
latitude as double in degrees decimal
longitude as double in degrees decimal
Returns
String of the 5x5 identifier (1..9), returns 0 if lat/lon is invalid
{
         // Check for valid lat/lon range
         if (latitude < -90 || latitude > 90) {
             return "0";
         }
         if (longitude < -180 || longitude > 180) {
             return "0";
         }
         /* Convert longitude and latitude from degrees to minutes */
         /* longitude assumed in -180 <= long < +180 range */
         double long_minutes = (longitude + 180) * 60.0;
         double lat_minutes = (latitude + 90) * 60.0;
         /* now we have a positive number of minutes */
         /* Find 30-min cell indices 0-719 and 0-359 */
         long horiz_index_30 = (long) (long_minutes / 30.0);
         long vert_index_30 = (long) (lat_minutes / 30.0);
         /* Compute remainders 0 <= x < 30.0 */
         double long_remainder = long_minutes - (horiz_index_30) * 30.0;
         double lat_remainder = lat_minutes - (vert_index_30) * 30.0;
         /* Find 15-min cell indices 0 or 1 */
         long horiz_index_15 = (long) (long_remainder / 15.0);
         long vert_index_15 = (long) (lat_remainder / 15.0);
         /* Compute remainders 0 <= x < 15.0 */
         long_remainder = long_remainder - (horiz_index_15) * 15.0;
         lat_remainder = lat_remainder - (vert_index_15) * 15.0;
         /* Find 5-min cell indices 0, 1, or 2 */
         long horiz_index_5 = (long) (long_remainder / 5.0);
         long vert_index_5 = (long) (lat_remainder / 5.0);
         String[][] _5_minute_array = {{"7", "4", "1"}, {"8", "5", "2"}, {"9", "6", "3"}};
         String keypad = _5_minute_array[(int) horiz_index_5][(int) vert_index_5];
         return keypad;
     }//getKeyPad
getLatitudeBand()
static String getLatitudeBand (double latitude) static
Get the GARS 2 letter latitude band descriptor for a given latitude (-90..90)
The fourth and fifth characters of a GARS code represent 30-minute latitudinal bands and are numbered from AA through QZ, starting at -90 through 90.
Parameters
latitude as double in degrees decimal
Returns
String representation of the 2 character latitudinal band
{
         char[] letterArray = "ABCDEFGHJKLMNPQRSTUVWXYZ".toCharArray();
         Double offset = latitude + 90;
         // Normalize offset to 0< offset <90
         while (offset < 0) {
             offset = offset + 180;
         }
         while (offset > 180) {
             offset = offset - 180;
         }
         offset = Math.floor(offset * 2.0);
         Double firstOffest = offset / letterArray.length;
         Double secondOffest = offset % letterArray.length;
         StringBuilder sb = new StringBuilder();
         sb.append(letterArray[firstOffest.intValue()]).append(letterArray[secondOffest.intValue()]);
         return sb.toString();
     }//getLatitudeBand
getLongitudeBand()
static String getLongitudeBand (double longitude) static
Get the GARS 3 letter longitude band descriptor for a given longitude (-180.0..180.0)
The longitude band are the first three characters of the GARS code.
The bands are numbered from 001 through 720, starting at -180 through 180 and depict 30-minute longitudinal bands.
Parameters
longitude as double in degrees decimal
Returns
String representation of the 3 character longitudinal band
{
         Double longBand = longitude + 180;
         // Normalize to 0.0 <= longBand < 360
         while (longBand < 0) {
             longBand = longBand + 360;
         }
         while (longBand > 360) {
             longBand = longBand - 360;
         }
         longBand = Math.floor(longBand * 2.0);
         Integer intLongBand = longBand.intValue() + 1; // Start at 001, not 000
         String strLongBand = intLongBand.toString();
         // Left pad the string with 0's so X becomes 00X
         while (strLongBand.length() < 3) {
             strLongBand = "0" + strLongBand;
         }
         return strLongBand;
     }//getLongitudeBand
getQudarant()
static String getQudarant (double latitude, double longitude) static
Returns the GARS 15 minute quadrant cell identifier for a latitude, longitude pair.This identifier is the 6th character of the GARS code.
Each 30-minute cell is divided into four 15-minute by 15-minute quadrants. The quadrants are numbered sequentially, from west to east, starting with the northernmost band. Specifically, the northwest quadrant is 1; the northeast quadrant is 2; the southwest quadrant is 3; the southeast quadrant is 4.
Parameters
latitude as double in degrees decimal
longitude as double in degrees decimal
Returns
String of the quadrant identifier (1..4), returns 0 if lat/lon is invalid
{
         Double latBand = (Math.floor((latitude + 90.0) * 4.0) % 2.0);
         Double longBand = (Math.floor((longitude + 180.0) * 4.0) % 2.0);
         // Return "0" if error occurs
         if (latBand < 0 || latBand > 1) {
             return "0";
         }
         if (longBand < 0 || longBand > 1) {
             return "0";
         }
         // Otherwise return the quadrant
         if (latBand == 0.0 && longBand == 0.0) {
             return "3";
         } else if (latBand == 1.0 && longBand == 0.0) {
             return "1";
         } else if (latBand == 1.0 && longBand == 1.0) {
             return "2";
         } else if (latBand == 0.0 && longBand == 1.0) {
             return "4";
         }
         return "0";
     }//getQudarant