rdf4j-postgis: IsConvex Class Reference
IsConvex Class Reference
Returns true if the given geometry is convex.
Public Member Functions
boolean attribute (Geometry geom)
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Static Public Member Functions
static boolean isConvex (Polygon p)
Detailed Description
Returns true if the given geometry is convex.
Member Function Documentation
attribute()
boolean attribute (Geometry geom)
References IsConvex.isConvex().
{
                 if (geom instanceof LinearRing || geom instanceof Polygon) {
             boolean isConvex = isConvex((Polygon)geom);
             return isConvex;
         }
         return false;
         }
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References GeometricBinaryAttributeFunction.attribute(), and LiteralRegistry.getLiteral().
Referenced by IsCollectionTest.testGeometryCollectionIsCollection(), HasConnectedInteriorTest.testHasConnectedInteriorFalse(), HasConnectedInteriorTest.testHasConnectedInteriorTrue(), HasDuplicateRingsTest.testHasDuplicateRingsFalse(), HasDuplicateRingsTest.testHasDuplicateRingsTrue(), HasRepeatedPointsTest.testHasRepeatedPoints(), HasRepeatedPointsTest.testHasRepeatedPoints2(), Is3DTest.testIs3DFalse(), IsAcuteTest.testIsAcuteFalse(), IsAcuteTest.testIsAcuteTrue(), IsConvexTest.testIsConvexFalse(), IsConvexTest.testIsConvexTrue(), IsEmptyTest.testIsEmptyFalse(), IsEmptyTest.testIsEmptyTrue(), IsIsocelesTriangleTest.testIsIsocelesTriangleFalse(), IsIsocelesTriangleTest.testIsIsocelesTriangleTrue(), IsMeasuredTest.testIsMeasuredFalse(), IsMeasuredTest.testIsMeasuredTrue(), IsNodingValidTest.testIsNodingValuedTrue(), IsPlanarTest.testIsPlanarTrue(), IsPolygonCCWTest.testIsPolygonCCWFalse(), IsPolygonCCWTest.testIsPolygonCCWTrue(), IsPolygonCWTest.testIsPolygonCWFalse(), IsPolygonCWTest.testIsPolygonCWTrue(), IsSolidTest.testIsSolidFalse(), IsTriangleTest.testIsTriangleFalse(), IsTriangleTest.testIsTriangleTrue(), IsClosedTest.testLineStringClosed(), IsCollectionTest.testLineStringIsCollection(), IsRingTest.testLineStringIsNotRing(), IsRingTest.testLineStringIsRing(), IsClosedTest.testLineStringNotClosed(), IsCollectionTest.testMultiLineStringIsCollection(), IsClosedTest.testMultiLineStringNotClosed(), IsClosedTest.testmultiPointClosed(), IsCollectionTest.testMultiPointIsCollection(), IsCollectionTest.testMultiPolygonIsCollection(), IsClosedTest.testpointClosed(), IsCollectionTest.testPointIsCollection(), and IsCollectionTest.testPolygonIsCollection().
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 System.out.println(l);
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         boolean result = attribute(geom);
                         return valueFactory.createLiteral(result);
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.st_isConvex.
{
                 return POSTGIS.st_isConvex.stringValue();
         }
isConvex()
static boolean isConvex (Polygon p) static
References Coordinate.x, and Coordinate.y.
Referenced by IsConvex.attribute().
{
         LinearRing r = (LinearRing) p.getExteriorRing();
         int sign = 0;
         for(int i = 1; i < r.getNumPoints(); ++i) {
             Coordinate c0 = r.getCoordinateN(i == 0 ? r.getNumPoints() - 1 : i - 1);
             Coordinate c1 = r.getCoordinateN(i);
             Coordinate c2 = r.getCoordinateN(i == r.getNumPoints() - 1 ? 0 : i + 1);
             double dx1 = c1.x - c0.x;
             double dy1 = c1.y - c0.y;
             double dx2 = c2.x - c1.x;
             double dy2 = c2.y - c2.y;
             double z = dx1 * dy2 - dy1 * dx2;
             int s = z >= 0.0 ? 1 : -1;
             if(sign == 0) {
                 sign = s;
             } else if(sign != s) {
                 return false;
             }
         }
         return true;
     }