rdf4j-postgis: VectorToRaster Class Reference
VectorToRaster Class Reference
Rasterize features onto a WritableRaster object using Java 2D Graphics/BufferedImage.
Classes
class FeatureRasterizerException
Public Member Functions
VectorToRaster ()
Constructor for the FeatureRasterizer object.
VectorToRaster (float noData)
Constructor for the FeatureRasterizer object - will use default 800x800 raster.
VectorToRaster (int height, int width)
Constructor for the FeatureRasterizer object.
VectorToRaster (int height, int width, float noData)
Constructor for the FeatureRasterizer object.
GridCoverage rasterize (String name, Geometry geom, String attributeName)
GridCoverage rasterize (String name, FeatureCollection fc, String attributeName, ReferencedEnvelope env) throws FeatureRasterizerException
void rasterize (FeatureCollection fc, String attributeName) throws FeatureRasterizerException
Gets the raster attribute of the FeatureRasterizer object Processes data from the FeatureCollection and approximates onto a Raster Grid.
void rasterize (FeatureCollection fc, java.awt.geom.Rectangle2D.Double bounds, String attributeName) throws FeatureRasterizerException
Gets the raster attribute of the FeatureRasterizer object Processes data from the FeatureCollection and approximates onto a Raster Grid.
void addFeature (Feature feature)
Implementation the StreamingProcess interface.
void close ()
Implementation the StreamingProcess interface - this copies values from BufferedImage RGB to WritableRaster of floats.
boolean isEmptyGrid ()
Gets the emptyGrid attribute of the FeatureRasterizer object.
WritableRaster getWritableRaster ()
Gets the writableRaster attribute of the FeatureRasterizer object.
void setWritableRaster (WritableRaster raster)
Sets the writableRaster attribute of the FeatureRasterizer object.
java.awt.geom.Rectangle2D.Double getBounds ()
Gets the bounds attribute of the FeatureRasterizer object.
void setBounds (java.awt.geom.Rectangle2D.Double bounds)
Sets the bounds for the Rasterizer.
void clearRaster ()
Sets the entire raster to NoData.
String getAttName ()
Get the current attribute to use as the grid cell values.
void setAttName (String attName)
Sets the current attribute to use as the grid cell values.
double getCellsize ()
Gets the cellsize attribute of the FeatureRasterizer object.
double getNoDataValue ()
void setNoDataValue (double noData)
int getHeight ()
void setHeight (int height)
int getWidth ()
void setWidth (int width)
double getMinAttValue ()
double getMaxAttValue ()
String toString ()
Static Public Attributes
static GridCoverageBuilder2 rasterFactory = new GridCoverageBuilder2()
Private Member Functions
void drawGeometry (Geometry geometry)
Static Private Member Functions
static int floatBitsToInt (float f)
Private Attributes
int height
int width
double noDataValue
WritableRaster raster = null
BufferedImage bimage = null
Graphics2D graphics = null
java.awt.geom.Rectangle2D.Double bounds
double cellsize
double minAttValue = 999999999
double maxAttValue = -999999999
int [] coordGridX = new int[3500]
int [] coordGridY = new int[3500]
float value
boolean emptyGrid = false
Geometry extentGeometry
GeometryFactory geoFactory = new GeometryFactory()
String attributeName = "value"
double xInterval
double yInterval
boolean resetRaster = false
Detailed Description
Rasterize features onto a WritableRaster object using Java 2D Graphics/BufferedImage.
Author
steve.ansari
Ferdinando Villa March 20, 2008
Constructor & Destructor Documentation
VectorToRaster() [1/4]
VectorToRaster ()
Constructor for the FeatureRasterizer object.
Exceptions
FeatureRasterizerException Description of the Exception
{
         this(800, 800, -999.0f);
     }
VectorToRaster() [2/4]
VectorToRaster (float noData)
Constructor for the FeatureRasterizer object - will use default 800x800 raster.
Parameters
noData No Data value for raster
Exceptions
FeatureRasterizerException Description of the Exception
{
         this(800, 800, noData);
     }
VectorToRaster() [3/4]
VectorToRaster (int height, int width)
Constructor for the FeatureRasterizer object.
No Data value defaults to -999.0
Parameters
height Height of raster (number of grid cells)
width Width of raster (number of grid cells)
References VectorToRaster.height, and VectorToRaster.width.
{
         this(height, width, -999.0f);
     }
VectorToRaster() [4/4]
VectorToRaster (int height, int width, float noData)
Constructor for the FeatureRasterizer object.
Parameters
height Height of raster (number of grid cells)
width Width of raster (number of grid cells)
noData No Data value for raster
References VectorToRaster.height, and VectorToRaster.width.
{
         this.height = height;
         this.width = width;
         this.noDataValue = noData;
         raster = RasterFactory.createBandedRaster(DataBuffer.TYPE_FLOAT,
                 width, height, 1, null);
         bimage = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
         bimage.setAccelerationPriority(1.0f);
         GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
 //      System.out.println("IMAGE ACCELERATED? "+bimage.getCapabilities(ge.getDefaultScreenDevice().getDefaultConfiguration()).isAccelerated());
         graphics = bimage.createGraphics();
         graphics.setPaintMode();
         graphics.setComposite(AlphaComposite.Src);
     }
Member Function Documentation
addFeature()
void addFeature (Feature feature)
Implementation the StreamingProcess interface.
Rasterize a single feature and update current WriteableRaster using the current settings.
Parameters
feature The feature to rasterize and add to current WritableRaster
References VectorToRaster.drawGeometry(), VectorToRaster.floatBitsToInt(), and VectorToRaster.value.
Referenced by VectorToRaster.rasterize().
{
         //System.out.println("rasterizer - processing feature: "+ attributeName + " -- " + feature);
         try {
             value = Float.parseFloat(feature.getProperty(attributeName).getValue().toString());
             if (value > maxAttValue) { maxAttValue = value; }
             if (value < minAttValue) { minAttValue = value; }
         } catch (Exception e) {
             e.printStackTrace();
             System.err.println("THE FEATURE COULD NOT BE RASTERIZED BASED ON THE '"+attributeName+
                     "' ATTRIBUTE VALUE OF '"+feature.getProperty(attributeName).getValue().toString()+"'");
             return;
         }
         int rgbVal = floatBitsToInt(value);
         graphics.setColor(new Color(rgbVal, true));
         // Extract polygon and rasterize!
         Geometry geometry = (Geometry)feature.getDefaultGeometryProperty().getValue();
         if (geometry.intersects(extentGeometry)) {
             if (geometry.getClass().equals(MultiPolygon.class)) {
                 MultiPolygon mp = (MultiPolygon)geometry;
                 for (int n=0; n<mp.getNumGeometries(); n++) {
                     drawGeometry(mp.getGeometryN(n));
                 }
             }
             else if (geometry.getClass().equals(MultiLineString.class)) {
                 MultiLineString mp = (MultiLineString)geometry;
                 for (int n=0; n<mp.getNumGeometries(); n++) {
                     drawGeometry(mp.getGeometryN(n));
                 }
             }
             else if (geometry.getClass().equals(MultiPoint.class)) {
                 MultiPoint mp = (MultiPoint)geometry;
                 for (int n=0; n<mp.getNumGeometries(); n++) {
                     drawGeometry(mp.getGeometryN(n));
                 }
             }
             else {
                 drawGeometry(geometry);
             }
         }
     }
clearRaster()
void clearRaster ()
Sets the entire raster to NoData.
References VectorToRaster.floatBitsToInt(), VectorToRaster.height, and VectorToRaster.width.
Referenced by VectorToRaster.rasterize().
{
 //      System.out.println("CLEARING RASTER");
         minAttValue = 999999999;
         maxAttValue = -999999999;
         // initialize raster to NoData value
         for (int i = 0; i < width; i++) {
             for (int j = 0; j < height; j++) {
                 raster.setSample(i, j, 0, noDataValue);
                 bimage.setRGB(i, j, floatBitsToInt((float)noDataValue));
             }
         }
     }
close()
void close ()
Implementation the StreamingProcess interface - this copies values from BufferedImage RGB to WritableRaster of floats.
References VectorToRaster.height, and VectorToRaster.width.
Referenced by VectorToRaster.rasterize().
{
         for (int i = 0; i < width; i++) {
             for (int j = 0; j < height; j++) {
                 double val = Float.intBitsToFloat(bimage.getRGB(i, j));
                 raster.setSample(i, j, 0, val);
             }
         }
     }
drawGeometry()
void drawGeometry (Geometry geometry) private
References VectorToRaster.bounds, and VectorToRaster.yInterval.
Referenced by VectorToRaster.addFeature().
{
         Coordinate[] coords = geometry.getCoordinates();
         // enlarge if needed
         if (coords.length > coordGridX.length) {
             coordGridX = new int[coords.length];
             coordGridY = new int[coords.length];
         }
         // Clear Array
         for (int i = 0; i < coords.length; i++) {
             coordGridX[i] = -1;
         }
         for (int i = 0; i < coords.length; i++) {
             coordGridY[i] = -1;
         }
         // Go through coordinate array in order received (clockwise)
         for (int n = 0; n < coords.length; n++) {
             coordGridX[n] = (int) (((coords[n].x - bounds.x) / xInterval));
             coordGridY[n] = (int) (((coords[n].y - bounds.y) / yInterval));
             coordGridY[n] = bimage.getHeight() - coordGridY[n];
         }
         if (geometry.getClass().equals(Polygon.class)) {
             graphics.fillPolygon(coordGridX, coordGridY, coords.length);
         }
         else if (geometry.getClass().equals(LinearRing.class)) {
             graphics.drawPolyline(coordGridX, coordGridY, coords.length);
         }
         else if (geometry.getClass().equals(LineString.class)) {
             graphics.drawPolyline(coordGridX, coordGridY, coords.length);
         }
         else if (geometry.getClass().equals(Point.class)) {
             graphics.drawPolyline(coordGridX, coordGridY, coords.length);
         }
     }
floatBitsToInt()
static int floatBitsToInt (float f) static private
Referenced by VectorToRaster.addFeature(), and VectorToRaster.clearRaster().
{
         ByteBuffer conv = ByteBuffer.allocate(4);
         conv.putFloat(0, f);
         return conv.getInt(0);
     }
getAttName()
String getAttName ()
Get the current attribute to use as the grid cell values.
References VectorToRaster.attributeName.
{
         return attributeName;
     }
getBounds()
java.awt.geom.Rectangle2D.Double getBounds ()
Gets the bounds attribute of the FeatureRasterizer object.
Returns
The bounds value
References VectorToRaster.bounds.
{
         return bounds;
     }
getCellsize()
double getCellsize ()
Gets the cellsize attribute of the FeatureRasterizer object.
Returns
The cellsize value
References VectorToRaster.cellsize.
{
         return cellsize;
     }
getHeight()
int getHeight ()
References VectorToRaster.height.
{
         return height;
     }
getMaxAttValue()
double getMaxAttValue ()
References VectorToRaster.maxAttValue.
{
         return maxAttValue;
     }
getMinAttValue()
double getMinAttValue ()
References VectorToRaster.minAttValue.
{
         return minAttValue;
     }
getNoDataValue()
double getNoDataValue ()
References VectorToRaster.noDataValue.
{
         return noDataValue;
     }
getWidth()
int getWidth ()
References VectorToRaster.width.
{
         return width;
     }
getWritableRaster()
WritableRaster getWritableRaster ()
Gets the writableRaster attribute of the FeatureRasterizer object.
Returns
The writableRaster value
References VectorToRaster.raster.
{
         return raster;
     }
isEmptyGrid()
boolean isEmptyGrid ()
Gets the emptyGrid attribute of the FeatureRasterizer object.
Returns
The emptyGrid value
References VectorToRaster.emptyGrid.
{
         return emptyGrid;
     }
rasterize() [1/4]
GridCoverage rasterize (String name, Geometry geom, String attributeName)
References VectorToRaster.clearRaster(), and VectorToRaster.setWritableRaster().
Referenced by VectorToRaster.rasterize().
{
         if (raster == null) {
             WritableRaster raster =
                 RasterFactory.createBandedRaster(
                     DataBuffer.TYPE_FLOAT,
                     this.width,
                     this.height,
                     1,
                     null);
             setWritableRaster(raster);
         }
         clearRaster();
         if (env == null) {
             rasterize(fc, attributeName);
             /*
              * Use full envelope from feature collection
              * TODO check if we need to use a buffer like in Steve's code above
              */
             env = fc.getBounds();
         } else {
             /*
              * TODO check if we need to use a buffer like in Steve's code above
              */
              java.awt.geom.Rectangle2D.Double box =
                    new java.awt.geom.Rectangle2D.Double(
                            env.getMinX(),
                            env.getMinY(),
                            env.getWidth(),
                            env.getHeight());
              rasterize(fc, box, attributeName);
         }
         GridCoverage coverage =
             rasterFactory.create(name, raster, env);
         return coverage;
     }
rasterize() [2/4]
GridCoverage rasterize (String name, FeatureCollection fc, String attributeName, ReferencedEnvelope env) throws FeatureRasterizerException
References VectorToRaster.clearRaster(), VectorToRaster.rasterize(), and VectorToRaster.setWritableRaster().
{
         if (raster == null) {
             WritableRaster raster =
                 RasterFactory.createBandedRaster(
                     DataBuffer.TYPE_FLOAT,
                     this.width,
                     this.height,
                     1,
                     null);
             setWritableRaster(raster);
         }
         clearRaster();
         if (env == null) {
             rasterize(fc, attributeName);
             /*
              * Use full envelope from feature collection
              * TODO check if we need to use a buffer like in Steve's code above
              */
             env = fc.getBounds();
         } else {
             /*
              * TODO check if we need to use a buffer like in Steve's code above
              */
              java.awt.geom.Rectangle2D.Double box =
                    new java.awt.geom.Rectangle2D.Double(
                            env.getMinX(),
                            env.getMinY(),
                            env.getWidth(),
                            env.getHeight());
              rasterize(fc, box, attributeName);
         }
         GridCoverage coverage =
             rasterFactory.create(name, raster, env);
         return coverage;
     }
rasterize() [3/4]
void rasterize (FeatureCollection fc, String attributeName) throws FeatureRasterizerException
Gets the raster attribute of the FeatureRasterizer object Processes data from the FeatureCollection and approximates onto a Raster Grid.
Parameters
fc Feature Collection with features to rasterize.
attributeName Name of attribute from feature collection to provide as the cell value.
Exceptions
FeatureRasterizerException An error when rasterizing the data
References VectorToRaster.bounds, and VectorToRaster.rasterize().
{
         // calculate variable resolution bounds that fit around feature collection
         double edgeBuffer = 0.001;
         double x = fc.getBounds().getMinX() - edgeBuffer;
         double y = fc.getBounds().getMinY() - edgeBuffer;
         double width = fc.getBounds().getWidth() + edgeBuffer * 2;
         double height = fc.getBounds().getHeight() + edgeBuffer * 2;
         java.awt.geom.Rectangle2D.Double bounds = new java.awt.geom.Rectangle2D.Double(x, y, width, height);
         System.out.println("BOUNDS: "+bounds);
         System.out.println("FCBNDS: "+fc.getBounds());
         rasterize(fc, bounds, attributeName);
     }
rasterize() [4/4]
void rasterize (FeatureCollection fc, java.awt.geom.Rectangle2D.Double bounds, String attributeName) throws FeatureRasterizerException
Gets the raster attribute of the FeatureRasterizer object Processes data from the FeatureCollection and approximates onto a Raster Grid.
Parameters
fc Description of the Parameter
bounds Description of the Parameter
attributeName Name of attribute from feature collection to provide as the cell value.
Exceptions
FeatureRasterizerException An error when rasterizing the data
References VectorToRaster.addFeature(), VectorToRaster.attributeName, VectorToRaster.bounds, VectorToRaster.clearRaster(), VectorToRaster.close(), VectorToRaster.height, VectorToRaster.setBounds(), and VectorToRaster.width.
{
         this.attributeName = attributeName;
         // Check if we need to change the underlying raster
         if (resetRaster) {
             raster = RasterFactory.createBandedRaster(DataBuffer.TYPE_FLOAT,
                     width, height, 1, null);
             bimage = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
             bimage.setAccelerationPriority(1.0f);
             GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
 //          System.out.println("IMAGE ACCELERATED? "+bimage.getCapabilities(ge.getDefaultScreenDevice().getDefaultConfiguration()).isAccelerated());
             graphics = bimage.createGraphics();
             graphics.setPaintMode();
             graphics.setComposite(AlphaComposite.Src);
             resetRaster = false;
             //System.out.println("---------------- RESETING FeatureRasterizer WritableRaster OBJECT -------------------- ");
         }
         // initialize raster to NoData value
         clearRaster();
         setBounds(bounds);
         // TODO - change method calls to account for a switch to control if rasterizer should work if vis bounds > feature bounds
         // All the data should start in the lower left corner.  Don't export what we don't need.
         double ratio = bounds.height / bounds.width;
         int ncols;
         int nrows;
         if (ratio < 1) {
             // wider than tall
             nrows = (int) (ratio * height);
             ncols = width;
         }
         else {
             nrows = height;
             ncols = (int) (height / ratio);
         }
         //System.out.println("1 --- WIDTH: " + ncols + "   HEIGHT: " + nrows);
         FeatureIterator fci = fc.features();
         Feature feature;
         while (fci.hasNext()) {
             feature = fci.next();
             addFeature(feature);
         }
         close();
     }
setAttName()
void setAttName (String attName)
Sets the current attribute to use as the grid cell values.
{
         this.attributeName = attName;
     }
setBounds()
void setBounds (java.awt.geom.Rectangle2D.Double bounds)
Sets the bounds for the Rasterizer.
Returns
The bounds value
References VectorToRaster.bounds, VectorToRaster.xInterval, and VectorToRaster.yInterval.
Referenced by VectorToRaster.rasterize().
{
         this.bounds = bounds;
         xInterval = bounds.width / (double) width;
         yInterval = bounds.height / (double) height;
         System.out.println("xInterval: " + xInterval + "  yInterval: " + yInterval);
         if (xInterval > yInterval) {
             yInterval = xInterval;
         }
         if (yInterval > xInterval) {
             xInterval = yInterval;
         }
         cellsize = yInterval;
         // Clip geometries to the provided bounds
         // Create extent geometry
         Envelope env = new Envelope(
                 bounds.getX(),
                 bounds.getX() + bounds.getWidth(),
                 bounds.getY(),
                 bounds.getY() + bounds.getHeight()
         );
         extentGeometry = geoFactory.toGeometry(env);
     }
setHeight()
void setHeight (int height)
References VectorToRaster.height.
{
         if (height != height) {
             resetRaster = true;
         }
         this.height = height;
     }
setNoDataValue()
void setNoDataValue (double noData)
{
         if (noData != noDataValue) {
             resetRaster = true;
         }
         this.noDataValue = noData;
     }
setWidth()
void setWidth (int width)
References VectorToRaster.width.
{
         if (width != width) {
             resetRaster = true;
         }
         this.width = width;
     }
setWritableRaster()
void setWritableRaster (WritableRaster raster)
Sets the writableRaster attribute of the FeatureRasterizer object.
Parameters
raster The new writableRaster value
References VectorToRaster.raster.
Referenced by VectorToRaster.rasterize().
{
         this.raster = raster;
     }
toString()
String toString ()
References VectorToRaster.noDataValue.
{
         return "FEATURE RASTERIZER: WIDTH="+width+" , HEIGHT="+height+" , NODATA="+noDataValue;
     }
Member Data Documentation
attributeName
String attributeName = "value" private
Referenced by VectorToRaster.getAttName(), and VectorToRaster.rasterize().
bimage
BufferedImage bimage = null private
bounds
java.awt.geom.Rectangle2D.Double bounds private
Referenced by VectorToRaster.drawGeometry(), VectorToRaster.getBounds(), VectorToRaster.rasterize(), and VectorToRaster.setBounds().
cellsize
double cellsize private
Referenced by VectorToRaster.getCellsize().
coordGridX
int [] coordGridX = new int[3500] private
coordGridY
int [] coordGridY = new int[3500] private
emptyGrid
boolean emptyGrid = false private
Referenced by VectorToRaster.isEmptyGrid().
extentGeometry
Geometry extentGeometry private
geoFactory
GeometryFactory geoFactory = new GeometryFactory() private
graphics
Graphics2D graphics = null private
height
int height private
Referenced by VectorToRaster.clearRaster(), VectorToRaster.close(), VectorToRaster.getHeight(), VectorToRaster.rasterize(), VectorToRaster.setHeight(), and VectorToRaster.VectorToRaster().
maxAttValue
double maxAttValue = -999999999 private
Referenced by VectorToRaster.getMaxAttValue().
minAttValue
double minAttValue = 999999999 private
Referenced by VectorToRaster.getMinAttValue().
noDataValue
double noDataValue private
Referenced by VectorToRaster.getNoDataValue(), and VectorToRaster.toString().
raster
WritableRaster raster = null private
Referenced by VectorToRaster.getWritableRaster(), and VectorToRaster.setWritableRaster().
rasterFactory
GridCoverageBuilder2 rasterFactory = new GridCoverageBuilder2() static
resetRaster
boolean resetRaster = false private
value
float value private
Referenced by VectorToRaster.addFeature().
width
int width private
Referenced by VectorToRaster.clearRaster(), VectorToRaster.close(), VectorToRaster.getWidth(), VectorToRaster.rasterize(), VectorToRaster.setWidth(), and VectorToRaster.VectorToRaster().
xInterval
double xInterval private
Referenced by VectorToRaster.setBounds().
yInterval
double yInterval private
Referenced by VectorToRaster.drawGeometry(), and VectorToRaster.setBounds().