rdf4j-postgis: MaxY Class Reference
MaxY Class Reference
Aggregate function to find the maximum y coordinate of a set of geometries.
Public Member Functions
MaxY (ValueExpr arg)
MaxY (ValueExpr arg, boolean distinct)
boolean equals (Object other)
int hashCode ()
MaxY clone ()
Package Functions
public< X extends Exception > void visit (QueryModelVisitor< X > visitor) throws X
Static Private Attributes
static final long serialVersionUID = 6796006337635345026L
Detailed Description
Aggregate function to find the maximum y coordinate of a set of geometries.
Constructor & Destructor Documentation
MaxY() [1/2]
MaxY (ValueExpr arg)
{
                 super(arg);
         }
MaxY() [2/2]
MaxY (ValueExpr arg, boolean distinct)
{
                 super(arg, distinct);
         }
Member Function Documentation
clone()
MaxY clone ()
References MaxY.clone().
Referenced by MaxY.clone().
{
                 return (MaxY) super.clone();
         }
equals()
boolean equals (Object other)
References MaxY.equals().
Referenced by MaxY.equals().
{
                 return other instanceof MaxY && super.equals(other);
         }
hashCode()
int hashCode ()
{
                 return super.hashCode() ^ "MaxY".hashCode();
         }
visit()
public<X extends Exception> void visit (QueryModelVisitor< X > visitor) throws X package
{
                 visitor.meet(this);
         }
Member Data Documentation
serialVersionUID
final long serialVersionUID = 6796006337635345026L static private