rdf4j-postgis: IsInCRSAreaOfValidity Class Reference
IsInCRSAreaOfValidity Class Reference
Public Member Functions
String getURI ()
boolean operation (Geometry geom, CoordinateReferenceSystem crs)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 Integer srid=Integer.valueOf(args[1].stringValue());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         boolean result;
                         try {
                                 result = operation(geom,CRS.forCode("EPSG:"+srid));
                                 return valueFactory.createLiteral(result);
                         } catch (FactoryException e) {
                                 // TODO Auto-generated catch block
                                 e.printStackTrace();
                                 return null;
                         }
                 }
                 throw new ValueExprEvaluationException("Arguments given are not geometry literals");
         }
References LiteralRegistry.getLiteral(), and GeometricBinaryCRSAttributeFunction.operation().
Referenced by IsInCRSAreaOfValidityTest.testIsInCRSAreaOfValidityFalse(), and IsInCRSAreaOfValidityTest.testIsInCRSAreaOfValidityTrue().
getURI()
String getURI ()
{
                 return POSTGIS.st_isInCRSAreaOfValidity.stringValue();
         }
References POSTGIS.st_isInCRSAreaOfValidity.
operation()
boolean operation (Geometry geom, CoordinateReferenceSystem crs)
Reimplemented from GeometricBinaryCRSAttributeFunction.
{
                 CoordinateSystemAxis x = crs.getCoordinateSystem().getAxis(0);
             CoordinateSystemAxis y = crs.getCoordinateSystem().getAxis(1);
             boolean xUnbounded = Double.isInfinite(x.getMinimumValue()) && Double.isInfinite(x.getMaximumValue());
         boolean yUnbounded = Double.isInfinite(y.getMinimumValue()) && Double.isInfinite(y.getMaximumValue());
         if (xUnbounded && yUnbounded) {
             return false;
         }
         Coordinate[] c = geom.getCoordinates();
         for (int i = 0; i < c.length; i++) {
             if (!xUnbounded && ((c[i].x < x.getMinimumValue()) || (c[i].x > x.getMaximumValue()))) {
                 return false;
             }
             if (!yUnbounded && ((c[i].y < y.getMinimumValue()) || (c[i].y > y.getMaximumValue()))) {
                 return false;
             }
         }
                 return true;
         }