rdf4j-postgis: MinZ Class Reference
MinZ Class Reference
Aggregate function to find the minimum z coordinate of a set of geometries.
Public Member Functions
MinZ (ValueExpr arg)
MinZ (ValueExpr arg, boolean distinct)
boolean equals (Object other)
int hashCode ()
MinZ clone ()
Package Functions
public< X extends Exception > void visit (QueryModelVisitor< X > visitor) throws X
Static Private Attributes
static final long serialVersionUID = -6545650405164933961L
Detailed Description
Aggregate function to find the minimum z coordinate of a set of geometries.
Constructor & Destructor Documentation
MinZ() [1/2]
MinZ (ValueExpr arg)
{
                 super(arg);
         }
MinZ() [2/2]
MinZ (ValueExpr arg, boolean distinct)
{
                 super(arg, distinct);
         }
Member Function Documentation
clone()
MinZ clone ()
References MinZ.clone().
Referenced by MinZ.clone().
{
                 return (MinZ) super.clone();
         }
equals()
boolean equals (Object other)
References MinZ.equals().
Referenced by MinZ.equals().
{
                 return other instanceof MinZ && super.equals(other);
         }
hashCode()
int hashCode ()
{
                 return super.hashCode() ^ "MinZ".hashCode();
         }
visit()
public<X extends Exception> void visit (QueryModelVisitor< X > visitor) throws X package
{
                 visitor.meet(this);
         }
Member Data Documentation
serialVersionUID
final long serialVersionUID = -6545650405164933961L static private