rdf4j-postgis: IsValidDetail Class Reference
IsValidDetail Class Reference
Public Member Functions
String getURI ()
String operation (Geometry geom)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and GeometricStringExportFunction.operation().
Referenced by AsBinaryTest.testAsBinary(), AsEncodedPolylineTest.testAsEncodedPolyline(), AsGARSTest.testAsGARS(), AsGeoJSONTest.testAsGeoJSON(), AsGeoURITest.testAsGeoURI(), AsLatLonTextTest.testAsLatLonText(), AsOSMLinkTest.testAsOSMLink(), AsPolyshapeTest.testAsPolyShape(), AsSVGTest.testAsSVG(), AsTextTest.testAsText(), AsTextRawTest.testAsTextRaw(), AsTWKBTest.testAsTWKB(), and GeometryTypeTest.testLineString().
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         String result = operation(geom);
                         return valueFactory.createLiteral(result);
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.st_isValidDetail.
{
                 return POSTGIS.st_isValidDetail.stringValue();
         }
operation()
String operation (Geometry geom)
{
             Object[] details = new Object[3];
             IsValidOp validOP = new IsValidOp(geom);
             GeometryFactory fac=new GeometryFactory();
             TopologyValidationError error = validOP.getValidationError();
             if (error != null) {
                 details[0] = false ;
                 details[1] = error.getMessage();
                 details[2] = fac.createPoint(error.getCoordinate());
             } else {
                 details[0] = true ;
                 details[1] = "Valid Geometry";
             }
             return Arrays.toString(details);
         }