rdf4j-postgis: MaxX Class Reference
MaxX Class Reference
Aggregate function to find the maximum x coordinate of a set of geometries.
Public Member Functions
MaxX (ValueExpr arg)
MaxX (ValueExpr arg, boolean distinct)
boolean equals (Object other)
int hashCode ()
MaxX clone ()
Package Functions
public< X extends Exception > void visit (QueryModelVisitor< X > visitor) throws X
Static Private Attributes
static final long serialVersionUID = 7571485725124116851L
Detailed Description
Aggregate function to find the maximum x coordinate of a set of geometries.
Constructor & Destructor Documentation
MaxX() [1/2]
MaxX (ValueExpr arg)
{
                 super(arg);
         }
MaxX() [2/2]
MaxX (ValueExpr arg, boolean distinct)
{
                 super(arg, distinct);
         }
Member Function Documentation
clone()
MaxX clone ()
References MaxX.clone().
Referenced by MaxX.clone().
{
                 return (MaxX) super.clone();
         }
equals()
boolean equals (Object other)
References MaxX.equals().
Referenced by MaxX.equals().
{
                 return other instanceof MaxX && super.equals(other);
         }
hashCode()
int hashCode ()
{
                 return super.hashCode() ^ "MaxX".hashCode();
         }
visit()
public<X extends Exception> void visit (QueryModelVisitor< X > visitor) throws X package
{
                 visitor.meet(this);
         }
Member Data Documentation
serialVersionUID
final long serialVersionUID = 7571485725124116851L static private