rdf4j-postgis: AggCentroid Class Reference
AggCentroid Class Reference
Public Member Functions
AggCentroid (ValueExpr arg)
AggCentroid (ValueExpr arg, boolean distinct)
boolean equals (Object other)
int hashCode ()
AggCentroid clone ()
Package Functions
public< X extends Exception > void visit (QueryModelVisitor< X > visitor) throws X
Constructor & Destructor Documentation
AggCentroid() [1/2]
AggCentroid (ValueExpr arg)
{
                 super(arg);
         }
AggCentroid() [2/2]
AggCentroid (ValueExpr arg, boolean distinct)
{
                 super(arg, distinct);
         }
Member Function Documentation
clone()
AggCentroid clone ()
References AggCentroid.clone().
Referenced by AggCentroid.clone().
{
                 return (AggCentroid) super.clone();
         }
equals()
boolean equals (Object other)
References AggCentroid.equals().
Referenced by AggCentroid.equals(), GeomUnion.equals(), and ConcatenateLines.equals().
{
                 return other instanceof AggCentroid && super.equals(other);
         }
hashCode()
int hashCode ()
{
                 return super.hashCode() ^ "AggCentroid".hashCode();
         }
visit()
public<X extends Exception> void visit (QueryModelVisitor< X > visitor) throws X package
{
                 visitor.meet(this);
         }