rdf4j-postgis: PointN Class Reference
PointN Class Reference
Returns the nth point of the given geometry if it exists.
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Geometry relation (Geometry geom, Integer value)
Detailed Description
Returns the nth point of the given geometry if it exists.
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and GeometricModifierIntegerFunction.relation().
Referenced by CollectionExtractTest.testCollectionExtract(), PointNTest.testLineString(), PrecisionReducerTest.testPrecisionReducer(), and RemovePointTest.testRemovePoint().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 Integer value=Integer.valueOf(args[1].stringValue());
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry result = relation(geom,value);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.st_pointN.
{
                 return POSTGIS.st_pointN.stringValue();
         }
relation()
Geometry relation (Geometry geom, Integer value) protected
{
         Coordinate[] coords = geom.getCoordinates();
         CoordinateXY coord = new CoordinateXY(coords[value].x, coords[value].y);
         GeometryFactory fac=new GeometryFactory();
         return fac.createPoint(coord);
         }