rdf4j-postgis: GeometricModifierFunction Class Reference
GeometricModifierFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
abstract Geometry relation (Geometry g1, Geometry g2)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 LiteralType l2=LiteralRegistry.getLiteral(((Literal)args[1]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry geom2=((VectorLiteral)l2).read(args[1].stringValue());
                         Geometry transformed=LiteralUtils.transform(geom2, geom);
                         Geometry result = relation(geom,transformed);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
References LiteralRegistry.getLiteral(), GeometricModifierFunction.relation(), and LiteralUtils.transform().
Referenced by AddGeometryTest.testAddGeometry(), AddGeometryTest.testAddGeometryZ(), AddPointTest.testAddPoint(), AddPointTest.testAddPointZ(), AddRingTest.testAddRing(), ClosestPointTest.testClosestPoint(), FurthestCoordinateTest.testFurthestCoordinate(), SetEndPointTest.testSetEndPoint(), and SetStartPointTest.testSetStartPoint().
relation()
abstract Geometry relation (Geometry g1, Geometry g2) abstract protected
Reimplemented in SetStartPoint, SetEndPoint, AddPoint, FurthestCoordinate, Node, Reflect, AddInteriorRing, LinesCutAtNodes, ClosestPoint3D, ClosestPoint, AddGeometry, MakeBox3D, and MakeBox2D.
Referenced by GeometricModifierFunction.evaluate().