rdf4j-postgis: GeometricModifierDoubleFunction Class Reference
GeometricModifierDoubleFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
abstract Geometry relation (Geometry geom, Double value)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 Double value=Double.valueOf(args[1].stringValue());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry result = relation(geom,value);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
References LiteralRegistry.getLiteral(), and GeometricModifierDoubleFunction.relation().
Referenced by DensifyTest.testDensify(), EnsureClosedTest.testEnsureClosed(), EnsureClosedTest.testEnsureClosed2(), RemoveGeometryTest.testRemoveGeometry1(), RemoveGeometryTest.testRemoveGeometry1Z(), RemoveGeometryTest.testRemoveGeometry2(), RemoveGeometryTest.testRemoveGeometry2Z(), RemoveRepeatedPointsTest.testRemoveRepeatedPoints(), SimplifyTest.testSimplify(), and SimplifyVWTest.testSimplifyVW().
relation()
abstract Geometry relation (Geometry geom, Double value) abstract protected
Reimplemented in SubdivideLines, Segmentize, LineInterpolatePoint, AddMeasure, MultiplyZ, RemoveRepeatedPoints, EnsureClosedRings, EnsureClosed, AddZ, Expand, VoronoiPolygons, SimplifyVW, Simplify, Densify, DelaunayTriangles, Rotate, LocateAlong, OffsetCurve, LineInterpolatePoint, and RemoveGeometry.
Referenced by GeometricModifierDoubleFunction.evaluate().