rdf4j-postgis: GeometricModifierDoubleDoubleFunction Class Reference
GeometricModifierDoubleDoubleFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
abstract Geometry relation (Geometry geom, Double value, Double value2)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
{
                 if (args.length != 3) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 3 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 Double value=Double.valueOf(args[1].stringValue());
                 Double value2=Double.valueOf(args[2].stringValue());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry result = relation(geom,value,value2);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
References LiteralRegistry.getLiteral(), and GeometricModifierDoubleDoubleFunction.relation().
relation()
abstract Geometry relation (Geometry geom, Double value, Double value2) abstract protected
Reimplemented in ShearTransformation, and LocateBetweenMeasures.
Referenced by GeometricModifierDoubleDoubleFunction.evaluate().