rdf4j-postgis: GeometricDoubleAttributeFunction Class Reference
GeometricDoubleAttributeFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract double attribute (Geometry geom)
Member Function Documentation
attribute()
abstract double attribute (Geometry geom) abstract
Reimplemented in Circularity, ZMin, ZMax, Z, YMin, YMax, Y, XMin, XMax, X, MMin, MMax, M, LineLength3D, Perimeter3D, Perimeter, MinimumDiameter, MinimumClearance, MinimumBoundingRadius, Length3D, Length, CompactnessRatio, Area3D, and Area.
Referenced by GeometricDoubleAttributeFunction.evaluate().
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         double result = attribute(geom);
                         return valueFactory.createLiteral(result);
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
References GeometricDoubleAttributeFunction.attribute(), and LiteralRegistry.getLiteral().
Referenced by AreaTest.testArea(), CompactnessRatioTest.testCompactnessRatio(), CompactnessRatioTest.testCompactnessRatioNaN(), CircularityTest.testIsScaleneTriangleFalse(), CircularityTest.testIsScaleneTriangleTrue(), LengthTest.testLineString(), MTest.testM(), MinimumBoundingRadiusTest.testMinimumBoundingRadius(), MinimumClearanceTest.testMinimumClearance(), MinimumDiameterTest.testMinimumDiameter(), MaxMTest.testMMax(), MinMTest.testMMin(), PerimeterTest.testPerimeter(), XTest.testX(), MaxXTest.testXMax(), MinXTest.testXMin(), YTest.testY(), MaxYTest.testYMax(), MinYTest.testYMin(), ZTest.testZ(), MaxZTest.testZMax(), and MinZTest.testZMin().