rdf4j-postgis: RemoveGeometry Class Reference
RemoveGeometry Class Reference
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Geometry relation (Geometry g1, Double value)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and GeometricModifierDoubleFunction.relation().
Referenced by RemoveGeometryTest.testAddGeometry(), DensifyTest.testDensify(), EnsureClosedTest.testEnsureClosed(), EnsureClosedTest.testEnsureClosed2(), RemoveRepeatedPointsTest.testRemoveRepeatedPoints(), RemoveRingTest.testRemoveRing(), ReverseRingTest.testReverseRing(), SimplifyTest.testSimplifyVW(), and SimplifyVWTest.testSimplifyVW().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 Double value=Double.valueOf(args[1].stringValue());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry result = relation(geom,value);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.st_removeGeometry.
{
                 return POSTGIS.st_removeGeometry.stringValue();
         }
relation()
Geometry relation (Geometry g1, Double value) protected
{
                 GeometryFactory fac=new GeometryFactory();
                 List<Geometry> geometries=new LinkedList<Geometry>();
                 for(int i=0;i<g1.getNumGeometries();i++) {
                         if(value!=i) {
                                 geometries.add(g1.getGeometryN(i));
                         }
                 }
                 return fac.createGeometryCollection(geometries.toArray(new Geometry[0]));
         }