rdf4j-postgis: GeometricBinaryCRSAttributeFunction Class Reference
GeometricBinaryCRSAttributeFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
abstract boolean operation (Geometry g1, CoordinateReferenceSystem crs)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
References LiteralRegistry.getLiteral(), and GeometricBinaryCRSAttributeFunction.operation().
Referenced by IsInCRSAreaOfValidityTest.testIsInCRSAreaOfValidityFalse(), and IsInCRSAreaOfValidityTest.testIsInCRSAreaOfValidityTrue().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 Integer srid=Integer.valueOf(args[1].stringValue());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         boolean result;
                         try {
                                 result = operation(geom,CRS.forCode("EPSG:"+srid));
                                 return valueFactory.createLiteral(result);
                         } catch (FactoryException e) {
                                 // TODO Auto-generated catch block
                                 e.printStackTrace();
                                 return null;
                         }
                 }
                 throw new ValueExprEvaluationException("Arguments given are not geometry literals");
         }
operation()
abstract boolean operation (Geometry g1, CoordinateReferenceSystem crs) abstract protected
Referenced by GeometricBinaryCRSAttributeFunction.evaluate().