rdf4j-postgis: GeometricRelationDoubleDoubleFunction Class Reference
GeometricRelationDoubleDoubleFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
abstract double relation (Geometry g1, Geometry g2, Double value)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
References LiteralRegistry.getLiteral(), GeometricRelationDoubleDoubleFunction.relation(), and LiteralUtils.transform().
{
                 if (args.length != 3) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 3 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 LiteralType l2=LiteralRegistry.getLiteral(((Literal)args[1]).getDatatype().toString());
                 Double value=Double.valueOf(args[2].stringValue());
                 if(l instanceof VectorLiteral && l2 instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry geom2=((VectorLiteral)l2).read(args[1].stringValue());
                         Geometry transformed=LiteralUtils.transform(geom2, geom);
                         double result = relation(geom,transformed,value);
                         return valueFactory.createLiteral(result);
                 }
                 throw new ValueExprEvaluationException("Arguments given are not a geometry literal");
         }
relation()
abstract double relation (Geometry g1, Geometry g2, Double value) abstract protected
Referenced by GeometricRelationDoubleDoubleFunction.evaluate().