rdf4j-postgis: GeometricStringExportFunction Class Reference
GeometricStringExportFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract String operation (Geometry geom)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         String result = operation(geom);
                         return valueFactory.createLiteral(result);
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
References LiteralRegistry.getLiteral(), and GeometricStringExportFunction.operation().
Referenced by AsBinaryTest.testAsBinary(), AsEncodedPolylineTest.testAsEncodedPolyline(), AsGARSTest.testAsGARS(), AsGeoJSONTest.testAsGeoJSON(), AsGeoRSSTest.testAsGeoRSS(), AsGeoURITest.testAsGeoURI(), AsLatLonTextTest.testAsLatLonText(), AsOSMLinkTest.testAsOSMLink(), AsPolyshapeTest.testAsPolyShape(), AsTextTest.testAsText(), AsTextRawTest.testAsTextRaw(), AsTextTest.testAsTextZ(), DumpTest.testDump(), GeomCRSToWKTTest.testGeomCRSToWKT(), GeometryTypeTest.testLineString(), SridGetAxis1OrientationTest.testSridAxis1Orientation(), SridGetAxis2OrientationTest.testSridAxis2Orientation(), SridGetAxis1NameTest.testSridGetAxis1Name(), SridGetAxis2NameTest.testSridGetAxis2Name(), and SridGetDatumTest.testSridGetDatum().
operation()
abstract String operation (Geometry geom) abstract
Reimplemented in DumpRings, Zmflag, AsEncodedPolyline, SridGetUnit, SridGetDatum, SridGetAxis2Orientation, SridGetAxis2Name, SridGetAxis1Orientation, SridGetAxis1Name, GeomCRSToWKT, AsX3D, AsTextRaw, AsText, AsPolyshape, AsOSMLink, AsMVT, AsLatLonText, AsKML, AsGPX, AsGML, AsGeoURI, AsGeoRSS, AsGeoJSON, AsGeoHash, AsGeobuf, AsGARS, AsBinary, IsValidReason, IsValidDetail, and GeometryType.
Referenced by GeometricStringExportFunction.evaluate().