rdf4j-postgis: ClosestPoint Class Reference
ClosestPoint Class Reference
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Geometry relation (Geometry g1, Geometry g2)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), GeometricModifierFunction.relation(), and LiteralUtils.transform().
Referenced by AddGeometryTest.testAddGeometry(), AddPointTest.testAddPoint(), AddRingTest.testAddRing(), ClosestPointTest.testClosestPoint(), FurthestCoordinateTest.testFurthestCoordinate(), SetEndPointTest.testLineString2D(), and SetStartPointTest.testLineString2D().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 LiteralType l2=LiteralRegistry.getLiteral(((Literal)args[1]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry geom2=((VectorLiteral)l2).read(args[1].stringValue());
                         Geometry transformed=LiteralUtils.transform(geom2, geom);
                         Geometry result = relation(geom,transformed);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.ST_CLOSESTPOINT.
{
                 return POSTGIS.ST_CLOSESTPOINT.stringValue();
         }
relation()
Geometry relation (Geometry g1, Geometry g2) protected
{
                 DistanceOp distop = new DistanceOp(g1, g2);
                 Coordinate[] coords = distop.nearestPoints();
                 Coordinate coord = new Coordinate(coords[0].x, coords[0].y);
                 GeometryFactory fac=new GeometryFactory();
                 return fac.createPoint(coord);
         }