rdf4j-postgis: AsGeoRSS Class Reference
AsGeoRSS Class Reference
Returns a GeoRSS representation of a given geometry.
Public Member Functions
String operation (Geometry geom)
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Package Attributes
String out
String out2 ="</item></channel></rss>"
Detailed Description
Returns a GeoRSS representation of a given geometry.
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and GeometricStringExportFunction.operation().
Referenced by AsBinaryTest.testAsBinary(), AsEncodedPolylineTest.testAsEncodedPolyline(), AsGARSTest.testAsGARS(), AsGeoJSONTest.testAsGeoJSON(), AsGeoRSSTest.testAsGeoURI(), AsGeoURITest.testAsGeoURI(), AsLatLonTextTest.testAsLatLonText(), AsOSMLinkTest.testAsOSMLink(), AsPolyshapeTest.testAsPolyShape(), AsSVGTest.testAsSVG(), AsTextTest.testAsText(), AsTextRawTest.testAsTextRaw(), AsTextTest.testAsTextZ(), AsTWKBTest.testAsTWKB(), GeomCRSToWKTTest.testGeomCRSToWKT(), GeometryTypeTest.testLineString(), SridGetAxis1OrientationTest.testSridAxis1Orientation(), SridGetAxis2OrientationTest.testSridAxis2Orientation(), SridGetAxis1NameTest.testSridGetAxis1Name(), SridGetAxis2NameTest.testSridGetAxis2Name(), and SridGetDatumTest.testSridGetDatum().
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         String result = operation(geom);
                         return valueFactory.createLiteral(result);
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.ST_ASGEORSS.
{
                 return POSTGIS.ST_ASGEORSS.stringValue();
         }
operation()
String operation (Geometry geom)
References AsGML.operation(), AsGeoRSS.out, and AsGeoRSS.out2.
{
         AsGML asgml=new AsGML();
         String gml=asgml.operation(geom);
         return out+gml+out2;
         }
Member Data Documentation
out
String out package
Initial value:
="<?xml version=\"1.0\" encoding=\"UTF-8\"?>"+
                          "<rss version=\"2.0\""+
                               "xmlns:georss=\"http://www.georss.org/georss\""+
                               "xmlns:gml=\"http://www.opengis.net/gml\">"+
                            "<channel>"+
                            "<link>http://www.i3mainz.de/postgis-jena</link>"+
                            "<title>Cambridge Neighborhoods</title>"+
                            "<description>One guy's view of Cambridge, MA</description>"+
                            "<item>"+
                              "<guid isPermaLink=\"false\">00000111c36421c1321d3</guid>"+
                              "<pubDate>"+System.currentTimeMillis()+"</pubDate>"
Referenced by AsGeoRSS.operation().
out2
String out2 ="</item></channel></rss>" package
Referenced by AsGeoRSS.operation().