rdf4j-postgis: SetGeometry Class Reference
SetGeometry Class Reference
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Geometry relation (Geometry g1, Geometry geom2, Integer value)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), GeometricModifierGeometryIntegerFunction.relation(), and LiteralUtils.transform().
Referenced by SetGeometryTest.testSetGeometry(), and SetRingTest.testSetRing().
{
                 if (args.length != 3) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 3 arguments, got " + args.length);
                 }
                 Integer value=Integer.valueOf(args[2].stringValue());
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 LiteralType l2=LiteralRegistry.getLiteral(((Literal)args[1]).getDatatype().toString());
                 if(l instanceof VectorLiteral && l2 instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry geom2=((VectorLiteral)l2).read(args[1].stringValue());
                         Geometry transformed=LiteralUtils.transform(geom2, geom);
                         Geometry result = relation(geom,transformed,value);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Arguments given are not geometry literals");
         }
getURI()
String getURI ()
References POSTGIS.st_setGeometry.
{
                 return POSTGIS.st_setGeometry.stringValue();
         }
relation()
Geometry relation (Geometry g1, Geometry geom2, Integer value) protected
{
                 GeometryFactory fac=new GeometryFactory();
                 List<Geometry> geometries=new LinkedList<Geometry>();
                 for(int i=0;i<g1.getNumGeometries();i++) {
                         if(value==i) {
                                 geometries.add(geom2);
                         }
                 }
                 return fac.createGeometryCollection(geometries.toArray(new Geometry[0]));
         }