rdf4j-postgis: ShortestLine3D Class Reference
ShortestLine3D Class Reference
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Geometry relation (Geometry geom1, Geometry geom2)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), GeometricRelationModifierFunction.relation(), and LiteralUtils.transform().
Referenced by LongestLineTest.testLongestLine(), ShortestLine3DTest.testShortestLine(), and ShortestLineTest.testShortestLine().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 LiteralType l2=LiteralRegistry.getLiteral(((Literal)args[1]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry geom2=((VectorLiteral)l2).read(args[1].stringValue());
                         Geometry transformed=LiteralUtils.transform(geom2, geom);
                         Geometry result = relation(geom,transformed);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Arguments given are not geometry literals");
         }
getURI()
String getURI ()
References POSTGIS.st_shortestLine3D.
{
                 return POSTGIS.st_shortestLine3D.stringValue();
         }
relation()
Geometry relation (Geometry geom1, Geometry geom2) protected
References LiteralUtils.createGeometry(), and LiteralUtils.transform().
{
                         Geometry transformed=LiteralUtils.transform(geom2, geom1);
             Distance3DOp distop = new Distance3DOp(geom1, transformed);
             Coordinate[] coord = distop.nearestPoints();
             return LiteralUtils.createGeometry(coord, "LINESTRING", geom1.getSRID());
         }