rdf4j-postgis: MinkowskiDistance Class Reference
MinkowskiDistance Class Reference
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
double relation (Geometry geom1, Geometry geom2, Double power)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), GeometricRelationDoubleDoubleFunction.relation(), and LiteralUtils.transform().
{
                 if (args.length != 3) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 3 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 LiteralType l2=LiteralRegistry.getLiteral(((Literal)args[1]).getDatatype().toString());
                 Double value=Double.valueOf(args[2].stringValue());
                 if(l instanceof VectorLiteral && l2 instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry geom2=((VectorLiteral)l2).read(args[1].stringValue());
                         Geometry transformed=LiteralUtils.transform(geom2, geom);
                         double result = relation(geom,transformed,value);
                         return valueFactory.createLiteral(result);
                 }
                 throw new ValueExprEvaluationException("Arguments given are not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.st_minkowskidistance.
{
                 return POSTGIS.st_minkowskidistance.stringValue();
         }
relation()
double relation (Geometry geom1, Geometry geom2, Double power) protected
{
                 double sum=0.;
                 for(Coordinate coord:geom1.getCoordinates()) {
                         sum+=Math.pow(Math.abs(coord.y-coord.x), power);
                 }
                 return Math.pow(sum, 1 / power);
         }