rdf4j-postgis: EqualsTopo Class Reference
EqualsTopo Class Reference
Returns true if two geometries are topologically equal.
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
boolean relation (Geometry g1, Geometry g2)
Detailed Description
Returns true if two geometries are topologically equal.
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), GeometricRelationBinaryFunction.relation(), and LiteralUtils.transform().
Referenced by BBOXAboveTest.testBBOXAbove(), BBOXAboveTest.testBBOXAbove1(), BBOXBelowTest.testBBOXBelow(), BBOXBelowTest.testBBOXBelow1(), BBOXContainsTest.testBBOXContainsFalse(), BBOXContainsTest.testBBOXContainsTrue(), BBOXEqualsTest.testBBOXEqualsFalse(), BBOXEqualsTest.testBBOXEqualsTrue(), BBOXIntersectsTest.testBBOXIntersectsFalse(), BBOXIntersectsTest.testBBOXIntersectsTrue(), BBOXIsContainedByTest.testBBOXIsContainedByFalse(), BBOXIsContainedByTest.testBBOXIsContainedByTrue(), BBOXLeftOfTest.testBBOXLeftOf(), BBOXLeftOfTest.testBBOXLeftOf1(), BBOXOverlapsLeftTest.testBBOXLeftOfFalse(), BBOXOverlapsLeftTest.testBBOXLeftOfTrue(), BBOXOverlapsRightTest.testBBOXRightOf(), BBOXRightOfTest.testBBOXRightOf(), BBOXOverlapsRightTest.testBBOXRightOf1(), BBOXRightOfTest.testBBOXRightOf1(), EqualTypeTest.testEqual(), EqualNormTest.testEqualNormFalse(), EqualNormTest.testEqualNormTrue(), EqualSRSTest.testEqualSRS(), EqualTopoTest.testEqualTopoFalse(), EqualTopoTest.testEqualTopoTrue(), EqualSRSTest.testNoSRS(), EqualTypeTest.testNotEqual(), EqualSRSTest.testNotEqualSRS(), OrderingEqualsTest.testOrderingEquals1(), OrderingEqualsTest.testOrderingEquals2(), and OrderingEqualsTest.testOrderingEquals3().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 LiteralType l2=LiteralRegistry.getLiteral(((Literal)args[1]).getDatatype().toString());
                 if(l instanceof VectorLiteral && l2 instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry geom2=((VectorLiteral)l2).read(args[1].stringValue());
                         Geometry transformed=LiteralUtils.transform(geom2, geom);
                         boolean result = relation(geom,transformed);
                         return valueFactory.createLiteral(result);
                 }
                 throw new ValueExprEvaluationException("Arguments given are not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.st_equalsTopo.
{
                 return POSTGIS.st_equalsTopo.stringValue();
         }
relation()
boolean relation (Geometry g1, Geometry g2) protected
{
                 return g1.equalsTopo(g2);
         }