rdf4j-postgis: EPSGToSRID Class Reference
EPSGToSRID Class Reference
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
References EPSGToSRID.getURI().
Referenced by EPSGToSRIDTest.testEPSGToSRID().
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 Integer srid=Integer.valueOf(args[0].stringValue().substring(args[0].stringValue().indexOf(':')+1));
                 return valueFactory.createLiteral(srid);
         }
getURI()
String getURI ()
References POSTGIS.EPSGToSRID.
Referenced by EPSGToSRID.evaluate().
{
                 // TODO Auto-generated method stub
                 return POSTGIS.EPSGToSRID.stringValue();
         }