rdf4j-postgis: Multi Class Reference
Multi Class Reference
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Geometry operation (Geometry geom)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and GeometricUnaryFunction.operation().
Referenced by CentroidTest.testCentroid(), StartPointTest.testCircularString(), CollectionHomogenizeTest.testCollectionHomogenize(), FlipCoordinatesTest.testFlipCoordinates(), Force2DTest.testForce2D(), Force3DTest.testForce3D(), Force3DMTest.testForce3DM(), Force3DMTest.testForce3DM2(), Force4DTest.testForce4D(), ForceCollectionTest.testForceCollection(), ForcePolygonCCWTest.testForcePolygonCCW(), ForcePolygonCWTest.testForcePolygonCW(), EndPointTest.testLineString2D(), StartPointTest.testLineString2D(), EndPointTest.testLineString3D(), StartPointTest.testLineString3D(), MinimumBoundingCircleCenterTest.testMinimumBoundingCircle(), MinimumBoundingCircleTest.testMinimumBoundingCircle(), MinimumClearanceLineTest.testMinimumClearanceLine(), MinimumDiameterLineTest.testMinimumDiameterLine(), MinimumRectangleTest.testMinimumRectangle(), EndPointTest.testPoint(), StartPointTest.testPoint(), ReverseTest.testReverse(), ShiftLongitudeTest.testShiftLongitude(), SimplifyPreserveTopologyTest.testSimplifyVW(), and TransScaleTest.testTransScale().
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 argument, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry result = operation(geom);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.st_multi.
{
                 return POSTGIS.st_multi.stringValue();
         }
operation()
Geometry operation (Geometry geom) protected
References LiteralUtils.createGeometry().
{
         if(geom.getGeometryType().toUpperCase().contains("MULTI")) {
                 return geom;
         }
         switch(geom.getGeometryType()) {
         case "Point":
                 return LiteralUtils.createGeometry(geom.getCoordinates(), "MultiPoint", geom.getSRID());
         case "Polygon":
                 List<Polygon> polylist=new LinkedList<Polygon>();
                 polylist.add((Polygon)geom);
                 return LiteralUtils.createGeometry(geom.getCoordinates(), "MultiPolygon", geom.getSRID());
         case "LineString":
                 List<LineString> linelist=new LinkedList<LineString>();
                 linelist.add((LineString)geom);
                 return LiteralUtils.createGeometry(geom.getCoordinates(), "MultiLineString", geom.getSRID());
         default:
                 return null;
         }
         }