rdf4j-postgis: ManhattanDistance Class Reference
ManhattanDistance Class Reference
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
double relation (Geometry geom1, Geometry geom2)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), GeometricRelationDoubleFunction.relation(), and LiteralUtils.transform().
Referenced by AreaSimilarityTest.testAreaSimilarity(), BBOXDistanceTest.testBBOXDistance(), CentroidDistanceTest.testCentroidDistance(), DistanceSphereTest.testDistanceSphere(), DistanceSphereTest.testDistanceSphere2(), HausdorffDistanceTest.testHausdorffDistance(), IntersectionPercentageTest.testIntersectionPercentage(), IntersectionPercentageTest.testIntersectionPercentage2(), MaxDistance3DTest.testMaxDistance(), and MaxDistanceTest.testMaxDistance().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 LiteralType l2=LiteralRegistry.getLiteral(((Literal)args[1]).getDatatype().toString());
                 if(l instanceof VectorLiteral && l2 instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry geom2=((VectorLiteral)l2).read(args[1].stringValue());
                         Geometry transformed=LiteralUtils.transform(geom2, geom);
                         double result = relation(geom,transformed);
                         return valueFactory.createLiteral(result);
                 }
                 throw new ValueExprEvaluationException("Arguments given are not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.st_manhattandistance.
{
                 return POSTGIS.st_manhattandistance.stringValue();
         }
relation()
double relation (Geometry geom1, Geometry geom2) protected
References Coordinate.x, and Coordinate.y.
{
                 Coordinate coord1=null,coord2=null;
                 if(geom1 instanceof Point) {
                         coord1=((Point)geom1).getCoordinate();
                 }else {
                         coord1=geom1.getCentroid().getCoordinate();
                 }
                 if(geom2 instanceof Point) {
                         coord1=((Point)geom2).getCoordinate();
                 }else {
                         coord1=geom2.getCentroid().getCoordinate();
                 }
             return Math.abs(coord1.x - coord2.x) + Math.abs(coord1.y - coord2.y);
         }