rdf4j-postgis: DelaunayTriangles Class Reference
DelaunayTriangles Class Reference
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Geometry relation (Geometry geom, Double tolerance)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and GeometricModifierDoubleFunction.relation().
Referenced by DensifyTest.testDensify(), EnsureClosedTest.testEnsureClosed(), EnsureClosedTest.testEnsureClosed2(), RemoveGeometryTest.testRemoveGeometry1(), RemoveGeometryTest.testRemoveGeometry1Z(), RemoveGeometryTest.testRemoveGeometry2(), RemoveGeometryTest.testRemoveGeometry2Z(), RemoveRepeatedPointsTest.testRemoveRepeatedPoints(), RemoveRingTest.testRemoveRing(), ReverseRingTest.testReverseRing(), SimplifyTest.testSimplify(), and SimplifyVWTest.testSimplifyVW().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 Double value=Double.valueOf(args[1].stringValue());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry result = relation(geom,value);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.ST_DELAUNAYTRIANGLES.
{
                 return POSTGIS.ST_DELAUNAYTRIANGLES.stringValue();
         }
relation()
Geometry relation (Geometry geom, Double tolerance) protected
{
             DelaunayTriangulationBuilder builder = new DelaunayTriangulationBuilder();
             builder.setTolerance(tolerance);
             Geometry triangles = builder.getTriangles(new GeometryFactory());
             return triangles;
         }