rdf4j-postgis: CollectionExtract Class Reference
CollectionExtract Class Reference
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Geometry relation (Geometry geom, Integer type)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and GeometricModifierIntegerFunction.relation().
Referenced by CollectionExtractTest.testCollectionExtract(), GeneratePointsTest.testGeneratePoints(), PointNTest.testLineString(), PrecisionReducerTest.testPrecisionReducer(), RemovePointTest.testRemovePoint(), RemovePointTest.testRemovePointZ(), RemoveRingTest.testRemoveRing(), and ReverseRingTest.testReverseRing().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 Integer value=Integer.valueOf(args[1].stringValue());
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry result = relation(geom,value);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.st_collectionextract.
{
                 return POSTGIS.st_collectionextract.stringValue();
         }
relation()
Geometry relation (Geometry geom, Integer type) protected
{
             GeometryFactory fac=new GeometryFactory();
         GeometryCollection collection=(GeometryCollection)geom;
         switch(type) {
         case 1:
                 List<Coordinate> coords=new ArrayList<Coordinate>();
                 for(int i=0;i<collection.getNumGeometries();i++) {
                         for(Coordinate coord2:collection.getGeometryN(i).getCoordinates()) {
                                 coords.add(coord2);
                         }
                 }
                 return fac.createMultiPointFromCoords(coords.toArray(new Coordinate[0]));
         case 2:
                 List<LineString> lines=new ArrayList<LineString>();
                 for(int i=0;i<collection.getNumGeometries();i++) {
                                 lines.add((LineString)collection.getGeometryN(i));
                 }
                 return fac.createMultiLineString(lines.toArray(new LineString[0]));
         case 3:
                 List<Polygon> polys=new ArrayList<Polygon>();
                 for(int i=0;i<collection.getNumGeometries();i++) {
                                 polys.add((Polygon)collection.getGeometryN(i));
                 }
                 return fac.createMultiPolygon(polys.toArray(new Polygon[0]));
         }
         return null;
         }