rdf4j-postgis: LineLength3D Class Reference
LineLength3D Class Reference
Public Member Functions
String getURI ()
double attribute (Geometry geom)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Static Public Member Functions
static double length3D (CoordinateSequence pts)
FROM org.h2gis.drivers.utility; GPL3.
static double length3D (Geometry geom)
Returns the 3D length of the geometry.
static double length3D (LineString lineString)
Returns the 3D perimeter of a line string.
static double length3D (Polygon polygon)
Returns the 3D perimeter of a polygon.
Member Function Documentation
attribute()
double attribute (Geometry geom)
References LineLength3D.length3D().
{
                 return length3D(geom);
         }
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References GeometricDoubleAttributeFunction.attribute(), and LiteralRegistry.getLiteral().
Referenced by AreaTest.testArea(), CompactnessRatioTest.testCompactnessRatio(), CircularityTest.testIsScaleneTriangleFalse(), CircularityTest.testIsScaleneTriangleTrue(), LengthTest.testLineString(), MTest.testM(), MinimumBoundingRadiusTest.testMinimumBoundingRadius(), MinimumClearanceTest.testMinimumClearance(), MinimumDiameterTest.testMinimumDiameter(), MaxMTest.testMMax(), MinMTest.testMMin(), PerimeterTest.testPerimeter(), XTest.testX(), MaxXTest.testXMax(), MinXTest.testXMin(), YTest.testY(), MaxYTest.testYMax(), MinYTest.testYMin(), ZTest.testZ(), MaxZTest.testZMax(), and MinZTest.testZMin().
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         double result = attribute(geom);
                         return valueFactory.createLiteral(result);
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.st_lineLength3D.
{
                 return POSTGIS.st_lineLength3D.stringValue();
         }
length3D() [1/4]
static double length3D (CoordinateSequence pts) static
FROM org.h2gis.drivers.utility; GPL3.
Computes the length of a linestring specified by a sequence of points. if a coordinate has a NaN z return 0.
Parameters
pts the points specifying the linestring
Returns
the length of the linestring
References Coordinate.x, Coordinate.y, and Coordinate.z.
Referenced by Length3D.attribute(), Perimeter3D.attribute(), LineLength3D.attribute(), and LineLength3D.length3D().
{
             // optimized for processing CoordinateSequences
             int n = pts.size();
             if (n <= 1) {
                     return 0.0;
             }
             double len = 0.0;
             Coordinate p = new Coordinate();
             pts.getCoordinate(0, p);
             double x0 = p.x;
             double y0 = p.y;
             double z0 = p.z;
             if (Double.isNaN(z0)) {
                     return 0.0;
             }
             for (int i = 1; i < n; i++) {
                     pts.getCoordinate(i, p);
                     double x1 = p.x;
                     double y1 = p.y;
                     double z1 = p.z;
                     if (Double.isNaN(z1)) {
                             return 0.0;
                     }
                     double dx = x1 - x0;
                     double dy = y1 - y0;
                     double dz = z1 - z0;
                     len += Math.sqrt(dx * dx + dy * dy + dz * dz);
                     x0 = x1;
                     y0 = y1;
                     z0 = z1;
             }
             return len;
     }
length3D() [2/4]
static double length3D (Geometry geom) static
Returns the 3D length of the geometry.
Parameters
geom
Returns
References LineLength3D.length3D().
{
             double sum = 0;
             for (int i = 0; i < geom.getNumGeometries(); i++) {
                     Geometry subGeom = geom.getGeometryN(i);
                     if (subGeom instanceof Polygon) {
                             sum += length3D((Polygon) subGeom);
                     } else if (subGeom instanceof LineString) {
                             sum += length3D((LineString) subGeom);
                     }
             }
             return sum;
     }
length3D() [3/4]
static double length3D (LineString lineString) static
Returns the 3D perimeter of a line string.
Parameters
lineString
Returns
References LineLength3D.length3D().
{
             return length3D(lineString.getCoordinateSequence());
     }
length3D() [4/4]
static double length3D (Polygon polygon) static
Returns the 3D perimeter of a polygon.
Parameters
polygon
Returns
References LineLength3D.length3D().
{
             double len = 0.0;
             len += length3D(polygon.getExteriorRing().getCoordinateSequence());
             for (int i = 0; i < polygon.getNumInteriorRing(); i++) {
                     len += length3D(polygon.getInteriorRingN(i));
             }
             return len;
     }