rdf4j-postgis: SwapOrdinates Class Reference
SwapOrdinates Class Reference
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Geometry relation (Geometry geom, String value)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and GeometricModifierStringFunction.relation().
Referenced by SwapOrdinatesTest.testSwapOrdinates().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 String value=args[1].stringValue();
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry result = relation(geom,value);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Arguments given are not geometry literals");
         }
getURI()
String getURI ()
References POSTGIS.st_swapOrdinates.
{
                 return POSTGIS.st_swapOrdinates.stringValue();
         }
relation()
Geometry relation (Geometry geom, String value) protected
References LiteralUtils.createGeometry().
{
             String ords = value;
             List<Coordinate> newcoords=new ArrayList<Coordinate>();
             if(ords.equalsIgnoreCase("xy")) {
                 for(Coordinate coord:geom.getCoordinates()) {
                         if(coord instanceof CoordinateXYM) {
                                 newcoords.add(new CoordinateXYM(coord.getY(),coord.getX(),coord.getM()));
                         }else if(coord instanceof CoordinateXYZM) {
                                 newcoords.add(new CoordinateXYZM(coord.getY(),coord.getX(),coord.getZ(),coord.getM()));
                         }else {
                                 newcoords.add(new Coordinate(coord.getY(),coord.getX()));
                         }
                 }
             }else if(ords.equalsIgnoreCase("xz")) {
                 for(Coordinate coord:geom.getCoordinates()) {
                         if(coord instanceof CoordinateXYM) {
                                 throw new RuntimeException("Coordinates do not contain a Z value");
                         }else if(coord instanceof CoordinateXYZM) {
                                 newcoords.add(new CoordinateXYZM(coord.getZ(),coord.getY(),coord.getX(),coord.getM()));
                         }else {
                                 newcoords.add(new Coordinate(coord.getZ(),coord.getY(),coord.getX()));
                         }
                 }
             }else if(ords.equalsIgnoreCase("yz")) {
                 for(Coordinate coord:geom.getCoordinates()) {
                         if(coord instanceof CoordinateXYM) {
                                 throw new RuntimeException("Coordinates do not contain a Z value");
                         }else if(coord instanceof CoordinateXYZM) {
                                 newcoords.add(new CoordinateXYZM(coord.getX(),coord.getZ(),coord.getY(),coord.getM()));
                         }else {
                                 newcoords.add(new Coordinate(coord.getX(),coord.getZ(),coord.getY()));
                         }
                 }
             }else if(ords.equalsIgnoreCase("xm")) {
                 for(Coordinate coord:geom.getCoordinates()) {
                         if(coord instanceof CoordinateXYM) {
                                 newcoords.add(new CoordinateXYM(coord.getM(),coord.getY(),coord.getX()));
                         }else if(coord instanceof CoordinateXYZM) {
                                 newcoords.add(new CoordinateXYZM(coord.getM(),coord.getY(),coord.getZ(),coord.getX()));
                         }else {
                                 throw new RuntimeException("Coordinates do not contain a M value");
                         }
                 }
             }else if(ords.equalsIgnoreCase("ym")) {
                 for(Coordinate coord:geom.getCoordinates()) {
                         if(coord instanceof CoordinateXYM) {
                                 newcoords.add(new CoordinateXYM(coord.getX(),coord.getM(),coord.getY()));
                         }else if(coord instanceof CoordinateXYZM) {
                                 newcoords.add(new CoordinateXYZM(coord.getX(),coord.getM(),coord.getZ(),coord.getY()));
                         }else {
                                 throw new RuntimeException("Coordinates do not contain a M value");
                         }
                 }
             }else if(ords.equalsIgnoreCase("zm")) {
                 for(Coordinate coord:geom.getCoordinates()) {
                         if(coord instanceof CoordinateXYM) {
                                 throw new RuntimeException("Coordinates do not contain a M and Z value");
                         }else if(coord instanceof CoordinateXYZM) {
                                 newcoords.add(new CoordinateXYZM(coord.getX(),coord.getY(),coord.getM(),coord.getZ()));
                         }else {
                                 throw new RuntimeException("Coordinates do not contain a M and Z value");
                         }
                 }
             }else {
                 throw new RuntimeException("Invalid second argument");
             }
             return LiteralUtils.createGeometry(newcoords, geom.getGeometryType(), geom.getSRID());
         }