rdf4j-postgis: LineFromEncodedPolyline Class Reference
LineFromEncodedPolyline Class Reference
Creates a LineString from the encoded polyline format.
Public Member Functions
Geometry construct (String input)
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Static Public Member Functions
static List< Coordinate > decodePolyline (String polyline, int precision)
Decodes a polyline with a given precision.
Detailed Description
Creates a LineString from the encoded polyline format.
Member Function Documentation
construct()
Geometry construct (String input)
References LineFromEncodedPolyline.decodePolyline().
{
                 GeometryFactory fac=new GeometryFactory();
                 LineString ls=fac.createLineString(decodePolyline(input, 1).toArray(new Coordinate[0]));
                 return ls;
         }
decodePolyline()
static List<Coordinate> decodePolyline (String polyline, int precision) static
Decodes a polyline with a given precision.
Parameters
polyline the polyline String to decode
precision the precision used for decoding
Returns
the list of coordinates which have been decoded
Referenced by LineFromEncodedPolyline.construct().
     {
         List<Coordinate> coordinates = new ArrayList<Coordinate>();
         int index = 0, shift, result;
         int byte_;
         int lat = 0, lng = 0, latitude_change, longitude_change,
             factor = (int) Math.pow(10, precision);
         while (index < polyline.length()) {
             byte_ = 0;
             shift = 0;
             result = 0;
             do {
                 byte_ = polyline.charAt(index++) - 63;
                 result |= (byte_ & 0x1f) << shift;
                 shift += 5;
             } while (byte_ >= 0x20);
             latitude_change = ((result % 2 == 1) ? ~(result >> 1) : (result >> 1));
             shift = result = 0;
             do {
                 byte_ = polyline.charAt(index++) - 63;
                 result |= (byte_ & 0x1f) << shift;
                 shift += 5;
             } while (byte_ >= 0x20);
             longitude_change = ((result % 2 == 1) ? ~(result >> 1) : (result >> 1));
             lat += latitude_change;
             lng += longitude_change;
             coordinates.add(new Coordinate((double)lat / factor,(double)lng / factor));
         }
         return coordinates;
     }
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References GeometricConstructor.construct(), WKTDatatype.INSTANCE, WKTDatatype.LiteralIRI, and WKTDatatype.unparse().
Referenced by GeomFromGeoJSONTest.testGeomFromGeoJSON(), GeomFromTextTest.testGeomFromText(), GeomFromWKBTest.testGeomFromWKB(), MakeLineTest.testMakeLine1(), MakePointTest.testMakePoint1(), MakePointTest.testMakePointXYZ(), PointFromTextTest.testPointFromText(), and PolygonFromTextTest.testPolygonFromText().
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 String geomString = args[0].stringValue();
                 Geometry result = construct(geomString);
                 return valueFactory.createLiteral(WKTDatatype.INSTANCE.unparse(result), WKTDatatype.LiteralIRI);
         }
getURI()
String getURI ()
References POSTGIS.st_lineFromEncodedPolyline.
{
                 return POSTGIS.st_lineFromEncodedPolyline.stringValue();
         }