rdf4j-postgis: SubdivideLines Class Reference
SubdivideLines Class Reference
Public Member Functions
String getURI ()
List< LineString > createSegments (Geometry track, double numberOfPoints) throws NoSuchAuthorityCodeException, FactoryException
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Geometry relation (Geometry geom, Double value)
Member Function Documentation
createSegments()
List<LineString> createSegments (Geometry track, double numberOfPoints) throws NoSuchAuthorityCodeException, FactoryException
Referenced by SubdivideLines.relation().
{
                 GeometryFactory fac=new GeometryFactory();
         //GeometryFactory geometryFactory = new GeometryFactory(new PrecisionModel(PrecisionModel.FLOATING));
         List<LineString> segments = new ArrayList<>();
         int i=0;
         for(int j=0;j<track.getNumGeometries();j++) {
                 List<Coordinate> coords=new LinkedList<Coordinate>();
                 for(Coordinate coord:track.getGeometryN(j).getCoordinates()) {
                         if(i<numberOfPoints) {
                                 coords.add(coord);
                         }else {
                                 segments.add(fac.createLineString(coords.toArray(new Coordinate[0])));
                                 coords=new LinkedList<Coordinate>();
                                 i=0;
                         }
                 }
         }
         return segments;
     }
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and GeometricModifierDoubleFunction.relation().
Referenced by DensifyTest.testDensify(), EnsureClosedTest.testEnsureClosed(), EnsureClosedTest.testEnsureClosed2(), RemoveGeometryTest.testRemoveGeometry1(), RemoveGeometryTest.testRemoveGeometry1Z(), RemoveGeometryTest.testRemoveGeometry2(), RemoveGeometryTest.testRemoveGeometry2Z(), RemoveRepeatedPointsTest.testRemoveRepeatedPoints(), RemoveRingTest.testRemoveRing(), ReverseRingTest.testReverseRing(), SimplifyTest.testSimplify(), and SimplifyVWTest.testSimplifyVW().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 Double value=Double.valueOf(args[1].stringValue());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry result = relation(geom,value);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.st_segmentize.
{
                 return POSTGIS.st_segmentize.stringValue();
         }
relation()
Geometry relation (Geometry geom, Double value) protected
References SubdivideLines.createSegments().
{
         double segmentLength = value;
         List<LineString> linestrings;
         try {
                         linestrings = createSegments(geom, segmentLength);
                 GeometryFactory fac=new GeometryFactory();
                 return fac.createMultiLineString(linestrings.toArray(new LineString[0]));
         } catch (FactoryException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 }
         return null;
  }