rdf4j-postgis: SetPoint Class Reference
SetPoint Class Reference
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Geometry relation (Geometry geom1, Geometry geom2, Integer zerobasedposition)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), GeometricDoubleModifierIntegerFunction.relation(), and LiteralUtils.transform().
Referenced by SetPointTest.testSetPoint().
{
                         if (args.length != 3) {
                                 throw new ValueExprEvaluationException(getURI() + " requires exactly 3 arguments, got " + args.length);
                         }
                         Integer value=Integer.valueOf(args[1].stringValue());
                         LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                         LiteralType l2=LiteralRegistry.getLiteral(((Literal)args[1]).getDatatype().toString());
                         if(l instanceof VectorLiteral && l2 instanceof VectorLiteral) {
                                 Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                                 Geometry geom2=((VectorLiteral)l2).read(args[1].stringValue());
                                 Geometry transformed=LiteralUtils.transform(geom2, geom);
                                 Geometry result = relation(geom,transformed,value);
                                 return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                         }
                         throw new ValueExprEvaluationException("Argument given is not a geometry literal");
                 }
getURI()
String getURI ()
References POSTGIS.st_setPoint.
{
                 return POSTGIS.st_setPoint.stringValue();
         }
relation()
Geometry relation (Geometry geom1, Geometry geom2, Integer zerobasedposition) protected
References LiteralUtils.createGeometry().
{
         if (geom2 instanceof Point) {
             Coordinate[] coords=geom1.getCoordinates();
             Coordinate[] newcoords=coords;
             newcoords[zerobasedposition.intValue()]=geom2.getCoordinate();
             return LiteralUtils.createGeometry(newcoords, geom1.getGeometryType(), geom1.getSRID());
         }
         return null;
         }