rdf4j-postgis: Angle Class Reference
Angle Class Reference
Calculates an angle between three given points.
Public Member Functions
double findAngle (Coordinate a, Coordinate b, Coordinate c)
Calculates an angle between three diffrent coordinates.
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Double relation (Geometry geom, Geometry geom2, Geometry geom3)
Detailed Description
Calculates an angle between three given points.
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and GeometricDoubleThreeGeometryFunction.relation().
Referenced by AngleTest.testAngle().
{
                 if (args.length != 3) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 3 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 LiteralType l2=LiteralRegistry.getLiteral(((Literal)args[1]).getDatatype().toString());
                 LiteralType l3=LiteralRegistry.getLiteral(((Literal)args[2]).getDatatype().toString());
                 if(l instanceof VectorLiteral && l2 instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry geom2=((VectorLiteral)l2).read(args[1].stringValue());
                         Geometry geom3=((VectorLiteral)l3).read(args[2].stringValue());
                         Double result = relation(geom,geom2,geom3);
                         return valueFactory.createLiteral(result);
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
findAngle()
double findAngle (Coordinate a, Coordinate b, Coordinate c)
Calculates an angle between three diffrent coordinates.
Parameters
a the first coordinate
b the second coordinate
c the third coordinate
Returns
the calculated angle
References Coordinate.x, and Coordinate.y.
Referenced by Angle.relation().
{
             double AB = Math.sqrt(Math.pow(b.x-a.x,2)+ Math.pow(b.y-a.y,2));
             double BC = Math.sqrt(Math.pow(b.x-c.x,2)+ Math.pow(b.y-c.y,2));
             double AC = Math.sqrt(Math.pow(c.x-a.x,2)+ Math.pow(c.y-a.y,2));
             return Math.acos((BC*BC+AB*AB-AC*AC)/(2*BC*AB));
         }
getURI()
String getURI ()
References POSTGIS.st_angle.
{
                 return POSTGIS.st_angle.stringValue();
         }
relation()
Double relation (Geometry geom, Geometry geom2, Geometry geom3) protected
References Angle.findAngle().
{
                 Coordinate coord1,coord2,coord3;
                 if("Point".equals(geom.getGeometryType())) {
                         coord1=geom.getCoordinate();
                 }else {
                         coord1=geom.getCentroid().getCoordinate();
                 }
                 if("Point".equals(geom2.getGeometryType())) {
                         coord2=geom2.getCoordinate();
                 }else {
                         coord2=geom2.getCentroid().getCoordinate();
                 }
                 if("Point".equals(geom3.getGeometryType())) {
                         coord3=geom3.getCoordinate();
                 }else {
                         coord3=geom3.getCentroid().getCoordinate();
                 }
                 return findAngle(coord1,coord2,coord3);
         }