rdf4j-postgis: SharedPaths Class Reference
SharedPaths Class Reference
Calculates shared paths of two geometries.
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Geometry relation (Geometry geom1, Geometry geom2)
Detailed Description
Calculates shared paths of two geometries.
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), GeometricRelationModifierFunction.relation(), and LiteralUtils.transform().
Referenced by LongestLineTest.testLongestLine(), ShortestLineTest.testShortestLine(), and ShortestLine3DTest.testShortestLine3D().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 LiteralType l2=LiteralRegistry.getLiteral(((Literal)args[1]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry geom2=((VectorLiteral)l2).read(args[1].stringValue());
                         Geometry transformed=LiteralUtils.transform(geom2, geom);
                         Geometry result = relation(geom,transformed);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Arguments given are not geometry literals");
         }
getURI()
String getURI ()
References POSTGIS.st_sharedPaths.
{
                 return POSTGIS.st_sharedPaths.stringValue();
         }
relation()
Geometry relation (Geometry geom1, Geometry geom2) protected
References LiteralUtils.createGeometryCollection(), and LiteralUtils.transform().
{
         List<Geometry> intersections=new LinkedList<>();
         Geometry transformed=LiteralUtils.transform(geom2, geom1);
                 if((geom1.getGeometryType().equals("MultiLineString") || geom1.getGeometryType().equals("LineString"))
                                 && (transformed.getGeometryType().equals("MultiLineString") || transformed.getGeometryType().equals("LineString"))) {
                         for(int i=0;i<geom1.getNumGeometries();i++) {
                                 for(int j=0;j<transformed.getNumGeometries();j++) {
                                         if(geom1.intersects(transformed.getGeometryN(j))){
                                                 intersections.add(geom1.getGeometryN(i).intersection(transformed.getGeometryN(j)));
                                         }
                                 }
                         }
                         return LiteralUtils.createGeometryCollection(intersections, "GEOMETRYCOLLECTION", geom1.getSRID());
                 }
                 return null;
         }