rdf4j-postgis: PointFromGeoHash Class Reference
PointFromGeoHash Class Reference
Creates a point from a GeoHash representation.
Public Member Functions
Geometry construct (String input)
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Detailed Description
Creates a point from a GeoHash representation.
Member Function Documentation
construct()
Geometry construct (String input)
{
                 // TODO Auto-generated method stub
                 return null;
         }
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References GeometricConstructor.construct(), and LiteralRegistry.getLiteral().
Referenced by GeomFromGeoJSONTest.testGeomFromGeoJSON(), GeomFromTextTest.testGeomFromGeoJSON(), GeomFromWKBTest.testGeomFromGeoJSON(), MakeLineTest.testMakeLine1(), MakePointTest.testMakePoint1(), MakePointTest.testMakePointXYZ(), PointFromTextTest.testPointFromText(), and PolygonFromTextTest.testPolygonFromText().
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 String geomString = args[0].stringValue();
                 Geometry result = construct(geomString);
                 return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
         }
getURI()
String getURI ()
References POSTGIS.st_pointFromGeoHash.
{
                 return POSTGIS.st_pointFromGeoHash.stringValue();
         }