rdf4j-postgis: Polygon Class Reference
Polygon Class Reference
Public Member Functions
String getURI ()
Geometry construct (String input, Integer srid)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Member Function Documentation
construct()
Geometry construct (String input, Integer srid)
References LiteralUtils.createGeometry().
{
             WKTReader wktreader=new WKTReader();
             Geometry geom;
                         try {
                                 geom = wktreader.read(input);
                     if("LINESTRING".equals(geom.getGeometryType().toUpperCase())){
                         return LiteralUtils.createGeometry(geom.getCoordinates(), "Polygon", srid);
                     }
                         } catch (ParseException e) {
                                 // TODO Auto-generated catch block
                                 e.printStackTrace();
                         }
             return null;
         }
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References GeometricConstructorInteger.construct(), and LiteralRegistry.getLiteral().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 String input=args[0].stringValue();
                 Integer srid = Integer.valueOf(args[1].stringValue());
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry result = construct(input,srid);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Arguments given are not geometry literals");
         }
getURI()
String getURI ()
References POSTGIS.st_polygon.
{
                 return POSTGIS.st_polygon.stringValue();
         }