rdf4j-postgis: PolygonFromWKB Class Reference
PolygonFromWKB Class Reference
Public Member Functions
String getURI ()
Geometry construct (String input)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Member Function Documentation
construct()
Geometry construct (String input)
{
                 WKBReader wktreader=new WKBReader();
         Geometry geom;
                 try {
                         geom = wktreader.read(input.getBytes());
                 if("POLYGON".equalsIgnoreCase(geom.getGeometryType().toUpperCase())){
                         return geom;
                 }
                 } catch (ParseException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 }
         return null;
         }
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References GeometricConstructor.construct(), and LiteralRegistry.getLiteral().
Referenced by GeomFromGeoJSONTest.testGeomFromGeoJSON(), GeomFromTextTest.testGeomFromGeoJSON(), GeomFromWKBTest.testGeomFromGeoJSON(), MakeLineTest.testMakeLine1(), MakePointTest.testMakePoint1(), MakePointTest.testMakePointXYZ(), PointFromTextTest.testPointFromText(), and PolygonFromTextTest.testPolygonFromText().
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 String geomString = args[0].stringValue();
                 Geometry result = construct(geomString);
                 return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
         }
getURI()
String getURI ()
References POSTGIS.st_polygonFromWKB.
{
                 return POSTGIS.st_polygonFromWKB.stringValue();
         }