rdf4j-postgis: InteriorRingN Class Reference
InteriorRingN Class Reference
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Geometry relation (Geometry geom, Integer value)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and GeometricModifierIntegerFunction.relation().
Referenced by CollectionExtractTest.testCollectionExtract(), GeneratePointsTest.testGeneratePoints(), PointNTest.testLineString(), PrecisionReducerTest.testPrecisionReducer(), RemovePointTest.testRemovePoint(), and RemovePointTest.testRemovePointZ().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 Integer value=Integer.valueOf(args[1].stringValue());
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry result = relation(geom,value);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.st_interiorRingN.
{
                 return POSTGIS.st_interiorRingN.stringValue();
         }
relation()
Geometry relation (Geometry geom, Integer value) protected
{
                 // TODO Auto-generated method stub
                 return null;
         }