rdf4j-postgis: GeneratePoints Class Reference
GeneratePoints Class Reference
Generates a given number of points in a convex hull of a geometry.
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Geometry relation (Geometry geom, Integer amount)
Detailed Description
Generates a given number of points in a convex hull of a geometry.
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and GeometricModifierIntegerFunction.relation().
Referenced by CollectionExtractTest.testCollectionExtract(), GeneratePointsTest.testGeneratePoints(), PointNTest.testLineString(), PrecisionReducerTest.testPrecisionReducer(), RemovePointTest.testRemovePoint(), RemovePointTest.testRemovePointZ(), RemoveRingTest.testRemoveRing(), and ReverseRingTest.testReverseRing().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 Integer value=Integer.valueOf(args[1].stringValue());
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry result = relation(geom,value);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.st_generatePoints.
{
                 return POSTGIS.st_generatePoints.stringValue();
         }
relation()
Geometry relation (Geometry geom, Integer amount) protected
{
                 RandomPointsBuilder shapeBuilder = new RandomPointsBuilder(geom.getFactory());
                 shapeBuilder.setNumPoints(amount.intValue());
                 if(!geom.getGeometryType().equalsIgnoreCase("Polygon")) {
                         System.out.println(geom.getGeometryType());
                         Geometry convhull=geom.convexHull();
                         System.out.println(convhull.getGeometryType());
                         if(!convhull.getGeometryType().equalsIgnoreCase("Polygon")) {
                                 convhull=convhull.convexHull();
                         }
                         System.out.println(convhull.getGeometryType()+"=====");
                         shapeBuilder.setExtent(convhull);
                 }else {
                         shapeBuilder.setExtent(geom);
                 }
                 return shapeBuilder.getGeometry();
         }