rdf4j-postgis: ReverseRing Class Reference
ReverseRing Class Reference
Reverses the coordinates of a given ring of a polygon.
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Geometry relation (Geometry geom, Double value)
Detailed Description
Reverses the coordinates of a given ring of a polygon.
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and GeometricModifierDoubleFunction.relation().
Referenced by DensifyTest.testDensify(), EnsureClosedTest.testEnsureClosed(), EnsureClosedTest.testEnsureClosed2(), RemoveGeometryTest.testRemoveGeometry1(), RemoveGeometryTest.testRemoveGeometry1Z(), RemoveGeometryTest.testRemoveGeometry2(), RemoveGeometryTest.testRemoveGeometry2Z(), RemoveRepeatedPointsTest.testRemoveRepeatedPoints(), RemoveRingTest.testRemoveRing(), ReverseRingTest.testReverseRing(), SimplifyTest.testSimplify(), and SimplifyVWTest.testSimplifyVW().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 Double value=Double.valueOf(args[1].stringValue());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry result = relation(geom,value);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.st_reverseRing.
{
                 return POSTGIS.st_reverseRing.toString();
         }
relation()
Geometry relation (Geometry geom, Double value) protected
{
                 if(geom instanceof Polygon) {
                         Polygon poly=(Polygon) geom;
                         if(value<0 || value>poly.getNumInteriorRing()) {
                                 return geom;
                         }
                         List<LinearRing> rings=new LinkedList<LinearRing>();
                         for(int i=0;i<poly.getNumInteriorRing();i++) {
                                 if(i==value) {
                                         rings.add((LinearRing) poly.getInteriorRingN(i).reverse());
                                 }else {
                                         rings.add((LinearRing)poly.getInteriorRingN(i));
                                 }
                         }
                         GeometryFactory fac=new GeometryFactory();
                         return fac.createPolygon((LinearRing)poly.getExteriorRing(), rings.toArray(new LinearRing[0]));
                 }
                 return null;
         }