rdf4j-postgis: RemoveInteriorRing Class Reference
RemoveInteriorRing Class Reference
Removes an interior ring from a given polygon.
Public Member Functions
String getURI ()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
Geometry relation (Geometry geom, Integer value)
Detailed Description
Removes an interior ring from a given polygon.
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and GeometricModifierIntegerFunction.relation().
Referenced by CollectionExtractTest.testCollectionExtract(), GeneratePointsTest.testGeneratePoints(), PointNTest.testLineString(), PrecisionReducerTest.testPrecisionReducer(), RemovePointTest.testRemovePoint(), RemovePointTest.testRemovePointZ(), RemoveRingTest.testRemoveRing(), and ReverseRingTest.testReverseRing().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 Integer value=Integer.valueOf(args[1].stringValue());
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry result = relation(geom,value);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.st_removeInteriorRing.
{
                 return POSTGIS.st_removeInteriorRing.toString();
         }
relation()
Geometry relation (Geometry geom, Integer value) protected
{
                 if(geom instanceof Polygon) {
                         Polygon poly=(Polygon) geom;
                         List<LinearRing> rings=new LinkedList<LinearRing>();
                         for(int i=0;i<poly.getNumInteriorRing();i++) {
                                 if(i!=value) {
                                         rings.add((LinearRing)poly.getInteriorRingN(i));
                                 }
                         }
                         GeometryFactory fac=new GeometryFactory();
                         return fac.createPolygon((LinearRing)poly.getExteriorRing(), rings.toArray(new LinearRing[0]));
                 }
                 return null;
         }