rdf4j-postgis: Band Class Reference
Band Class Reference
Public Member Functions
String getURI ()
Integer attribute (GridCoverage geom, Integer numband)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Member Function Documentation
attribute()
Integer attribute (GridCoverage geom, Integer numband)
Reimplemented from RasterAttributeIntIntFunction.
{
                 //return geom.getSampleDimensions().get(numband);
                 return 0;
         }
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
{
         if (args.length != 2) {
                 throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
         }
         LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
         if(l instanceof RasterLiteral) {
                 GridCoverage geom=((RasterLiteral)l).read(args[0].stringValue());
                 Integer parameter = Integer.valueOf(args[1].stringValue());
                 Integer result = attribute(geom,parameter);
                 return valueFactory.createLiteral(result);
         }
         return null;
 }
References RasterAttributeIntIntFunction.attribute(), and LiteralRegistry.getLiteral().
Referenced by BandTest.testBand(), and BandNoDataValueTest.testBandNoDataValue().
getURI()
String getURI ()
{
                 return POSTGIS.ST_BAND.stringValue();
         }
References POSTGIS.ST_BAND.