rdf4j-postgis: NumInteriorRings Class Reference
NumInteriorRings Class Reference
Returns the number of interior rings of a polygon.
Public Member Functions
String getURI ()
int attribute (Geometry geom)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Detailed Description
Returns the number of interior rings of a polygon.
Member Function Documentation
attribute()
int attribute (Geometry geom)
{
                 if(geom instanceof Polygon) {
                         Polygon poly=(Polygon)geom;
                         Set<Geometry> coordset=new HashSet<Geometry>();
                         for(int i=0;i<poly.getNumInteriorRing();i++) {
                                 coordset.add(geom.getGeometryN(i));
                         }
                         return coordset.size();
                 }
                 return 0;
         }
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References GeometricIntegerAttributeFunction.attribute(), and LiteralRegistry.getLiteral().
Referenced by NDimsTest.test2DGeom(), NDimsTest.test3DGeom(), NDimsTest.testMGeom(), NRingsTest.testNRings(), NumDistinctInteriorRingsTest.testNRings(), NumDistinctGeometriesTest.testNumDistinctGeometries(), NumDistinctGeometriesTest.testNumDistinctGeometriesCollection(), NumDistinctPointsTest.testNumDistinctPoints(), NumGeometriesTest.testNumGeometries(), NumGeometriesTest.testNumGeometriesCollection(), and NumPointsTest.testNumPoints().
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         int result = attribute(geom);
                         return valueFactory.createLiteral(result);
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getURI()
String getURI ()
References POSTGIS.st_numInteriorRings.
{
                 return POSTGIS.st_numInteriorRings.stringValue();
         }