rdf4j-postgis: Xor Class Reference
Xor Class Reference
Public Member Functions
String getURI ()
GridCoverage modify (GridCoverage raster, Integer rd1, GridCoverage raster2, Integer rd2)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and RasterAlgebraFunction.modify().
Referenced by LogTest.testAdd(), AddTest.testAdd(), AndTest.testAnd(), DivTest.testDiv(), MultTest.testMult(), OrTest.testOr(), SubtractTest.testSubtract(), and XorTest.testXor().
{
                 if (args.length != 4) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 4 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 LiteralType l2=LiteralRegistry.getLiteral(((Literal)args[2]).getDatatype().toString());
                 if(l instanceof RasterLiteral && l2 instanceof RasterLiteral) {
                         GridCoverage geom=((RasterLiteral)l).read(args[0].stringValue());
                         Integer bd1=Integer.valueOf(args[1].stringValue());
                         GridCoverage geom2=((RasterLiteral)l).read(args[2].stringValue());
                         Integer bd2=Integer.valueOf(args[3].stringValue());
                         GridCoverage result = modify(geom,bd1,geom2,bd2);
                         return valueFactory.createLiteral(((RasterLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 return null;
         }
getURI()
String getURI ()
References POSTGIS.ST_rast_algebra_xor.
{
                 return POSTGIS.ST_rast_algebra_xor.stringValue();
         }
modify()
GridCoverage modify (GridCoverage raster, Integer rd1, GridCoverage raster2, Integer rd2)
{
                 ParameterBlock pbSubtracted = new ParameterBlock();
                 pbSubtracted.addSource(raster.render(raster.getGridGeometry().getExtent()));
                 pbSubtracted.addSource(raster2.render(raster2.getGridGeometry().getExtent()));
                 RenderedOp subtractedImage = JAI.create("xor", pbSubtracted);
                 /*
                  * final GridGeometry grid = new
                  * GridGeometry(raster.getGridGeometry().getExtent(), PixelInCell.CELL_CENTER,
                  * MathTransforms.identity(2),
                  * raster.getGridGeometry().getCoordinateReferenceSystem());
                  *
                  * final MathTransform1D toUnits = (MathTransform1D) MathTransforms.linear(0.5,
                  * 100);
                  */
                 final SampleDimension sd = new SampleDimension.Builder().setName("t")
                                 .addQuantitative(
                                                 (raster.getSampleDimensions().get(rd1).getName() + "xor"
                                                                 + raster2.getSampleDimensions().get(rd2).getName()).toString(),
                                                 raster.getSampleDimensions().get(0).getMeasurementRange().get(),
                                                 raster.getSampleDimensions().get(0).getTransferFunction().get(),
                                                 raster.getSampleDimensions().get(0).getUnits().get())
                                 .build();
                 List<SampleDimension>sds=new LinkedList<SampleDimension>();
                 sds.add(sd);
                 /*
                  * Create the grid coverage, gets its image and set values directly as short
                  * integers.
                  */
                 BufferedGridCoverage coverage = new BufferedGridCoverage(raster2.getGridGeometry(),
                                 sds, DataBuffer.TYPE_SHORT);
                 WritableRaster rasterr = ((BufferedImage) coverage.render(null)).getRaster();
                 rasterr.setRect(subtractedImage.getSourceImage(0).getData());
                 return coverage;
         }