rdf4j-postgis: DivConst Class Reference
DivConst Class Reference
Public Member Functions
String getURI ()
GridCoverage modify (GridCoverage raster, Integer rd1, Double constt)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and RasterAlgebraConstFunction.modify().
Referenced by AddConstTest.testAddConst(), AndConstTest.testAndConst(), DivConstTest.testDivConst(), MultConstTest.testMultConst(), OrConstTest.testOrConst(), SubtractConstTest.testSubtractConst(), and XorConstTest.testXorConst().
{
                 if (args.length != 3) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 3 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof RasterLiteral) {
                         GridCoverage geom=((RasterLiteral)l).read(args[0].stringValue());
                         Integer band=Integer.valueOf(args[1].stringValue());
                         Double constt=Double.valueOf(args[2].stringValue());
                         GridCoverage result = modify(geom,band,constt);
                         return valueFactory.createLiteral(((RasterLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 return null;
         }
getURI()
String getURI ()
References POSTGIS.ST_rast_algebra_divconst.
{
                 return POSTGIS.ST_rast_algebra_divconst.stringValue();
         }
modify()
GridCoverage modify (GridCoverage raster, Integer rd1, Double constt)
{
                 ParameterBlock pbSubtracted = new ParameterBlock();
                 pbSubtracted.addSource(raster.render(raster.getGridGeometry().getExtent()));
                 double[] consts=new double[raster.getSampleDimensions().size()];
                 if(rd1.intValue()<0) {
                         for(int i=0;i<consts.length;i++) {
                                 consts[i]=constt;
                         }
                 }else {
                         for(int i=0;i<consts.length;i++) {
                                 if(i==rd1.intValue()) {
                                         consts[i]=constt;
                                 }else {
                                         consts[i]=0;
                                 }
                         }
                 }
                 pbSubtracted.add(consts);
                 RenderedOp subtractedImage = JAI.create("DivideByConst", pbSubtracted);
                 final SampleDimension sd = new SampleDimension.Builder().setName("t")
                                 .addQuantitative(
                                                 (raster.getSampleDimensions().get(rd1).getName() + " dividebyconst "
                                                                 + constt).toString(),
                                                 raster.getSampleDimensions().get(rd1).getMeasurementRange().get(),
                                                 raster.getSampleDimensions().get(rd1).getTransferFunction().get(),
                                                 raster.getSampleDimensions().get(rd1).getUnits().get())
                                 .build();
                 List<SampleDimension>sds=new LinkedList<SampleDimension>();
                 sds.add(sd);
                 /*
                  * Create the grid coverage, gets its image and set values directly as short
                  * integers.
                  */
                 BufferedGridCoverage coverage = new BufferedGridCoverage(raster.getGridGeometry(),
                                 sds, DataBuffer.TYPE_SHORT);
                 WritableRaster rasterr = ((BufferedImage) coverage.render(null)).getRaster();
                 rasterr.setRect(subtractedImage.getSourceImage(0).getData());
                 return coverage;
         }