rdf4j-postgis: MakePolygon Class Reference
MakePolygon Class Reference
Public Member Functions
String getURI ()
Geometry construct (String input)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Member Function Documentation
construct()
Geometry construct (String input)
{
                 // TODO Auto-generated method stub
                 return null;
         }
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References GeometricConstructor.construct(), WKTDatatype.INSTANCE, WKTDatatype.LiteralIRI, and WKTDatatype.unparse().
Referenced by GeomFromGeoJSONTest.testGeomFromGeoJSON(), GeomFromTextTest.testGeomFromText(), GeomFromWKBTest.testGeomFromWKB(), MakeLineTest.testMakeLine1(), MakePointTest.testMakePoint1(), MakePointTest.testMakePointXYZ(), PointFromTextTest.testPointFromText(), and PolygonFromTextTest.testPolygonFromText().
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 String geomString = args[0].stringValue();
                 Geometry result = construct(geomString);
                 return valueFactory.createLiteral(WKTDatatype.INSTANCE.unparse(result), WKTDatatype.LiteralIRI);
         }
getURI()
String getURI ()
References POSTGIS.st_makePolygon.
{
                 return POSTGIS.st_makePolygon.stringValue();
         }