rdf4j-postgis: TileGridYOffset Class Reference
TileGridYOffset Class Reference
Public Member Functions
String getURI ()
double attribute (GridCoverage raster)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Member Function Documentation
attribute()
double attribute (GridCoverage raster)
{
                 return raster.render(raster.getGridGeometry().getExtent()).getTileGridYOffset();
         }
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References RasterAttributeFunction.attribute(), and LiteralRegistry.getLiteral().
Referenced by ScaleXTest.testMinScaleX(), ScaleYTest.testMinScaleY(), TileGridYOffsetTest.testMinTileX(), MinTileXTest.testMinTileX(), UpperLeftXTest.testMinTileX(), UpperLeftYTest.testMinTileX(), SkewXTest.testMinTileX(), SkewYTest.testMinTileX(), TileGridXOffsetTest.testMinTileX(), MinTileYTest.testMinTileY(), NumBandsTest.testNumBands(), NumXTilesTest.testNumXTiles(), NumYTilesTest.testNumYTiles(), HeightTest.testRasterHeight(), IsEmptyTest.testRasterIsEmptyFalse(), IsEmptyTest.testRasterIsEmptyTrue(), WidthTest.testRasterWidth(), ShearXTest.testShearX(), ShearYTest.testShearY(), TileWidthTest.testTileHeight(), TileHeightTest.testTileHeight(), TranslateXTest.testTranslateX(), and TranslateYTest.testTranslateY().
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 System.out.println(((Literal)args[0]).getDatatype().toString());
                 System.out.println(LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString()));
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 System.out.println(l);
                 if(l instanceof RasterLiteral) {
                         GridCoverage geom=((RasterLiteral)l).read(args[0].stringValue());
                         System.out.println("Extracted GridCoverage: "+geom);
                         Double result = attribute(geom);
                         return valueFactory.createLiteral(result);
                 }
                 return null;
         }
getURI()
String getURI ()
References POSTGIS.st_tileGridYOffset.
{
                 return POSTGIS.st_tileGridYOffset.stringValue();
         }