rdf4j-postgis: WorldToRasterCoordX Class Reference
WorldToRasterCoordX Class Reference
Public Member Functions
String getURI ()
Double attribute (GridCoverage raster, Integer longitude, Integer latitude)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Member Function Documentation
attribute()
Double attribute (GridCoverage raster, Integer longitude, Integer latitude)
References Coordinate.x.
{
         try {
          GridGeometry gg2D = raster.getGridGeometry();
             MathTransform gridToCRS = gg2D.getGridToCRS(PixelInCell.CELL_CENTER);
             MathTransform crsToGrid = gridToCRS.inverse();
             DirectPosition realPos=new DirectPosition2D(latitude, longitude);
             DirectPosition gridPos = new DirectPosition2D();
             DirectPosition res=crsToGrid.transform(realPos, gridPos);
             Coordinate coord=new Coordinate(res.getCoordinate()[0],res.getCoordinate()[1]);
             return coord.x;
        } catch (TransformException e) {
            return (Double) null;
        }
         }
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References RasterAttributeIntIntDoubleFunction.attribute(), and LiteralRegistry.getLiteral().
Referenced by RasterToWorldCoordXTest.testRasterToWorldCoordX(), RasterToWorldCoordYTest.testRasterToWorldCoordY(), WorldToRasterCoordXTest.testWorldToRasterCoordX(), and WorldToRasterCoordYTest.testWorldToRasterCoordY().
{
                 if (args.length != 3) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof RasterLiteral) {
                         GridCoverage geom=((RasterLiteral)l).read(args[0].stringValue());
                         Integer longitude = Integer.valueOf(args[1].stringValue());
                         Integer latitude = Integer.valueOf(args[2].stringValue());
                         Double result = attribute(geom,longitude,latitude);
                         return valueFactory.createLiteral(result);
                 }
                 return null;
         }
getURI()
String getURI ()
References POSTGIS.st_worldToRasterCoordX.
{
                 return POSTGIS.st_worldToRasterCoordX.stringValue();
         }