rdf4j-postgis: RasterAttributeIntIntIntStringFunction Class Reference
RasterAttributeIntIntIntStringFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract Double attribute (GridCoverage geom, Integer noband, Integer x, Integer y, Boolean excludenodata)
Member Function Documentation
attribute()
abstract Double attribute (GridCoverage geom, Integer noband, Integer x, Integer y, Boolean excludenodata) abstract
Referenced by RasterAttributeIntIntIntStringFunction.evaluate().
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
References RasterAttributeIntIntIntStringFunction.attribute(), and LiteralRegistry.getLiteral().
Referenced by ValueTest.testRasterValue().
{
                 if (args.length != 3) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 4 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof RasterLiteral) {
                         GridCoverage geom=((RasterLiteral)l).read(args[0].stringValue());
                         Integer noband = Integer.valueOf(args[1].stringValue());
                         Integer x = Integer.valueOf(args[2].stringValue());
                         Integer y = Integer.valueOf(args[2].stringValue());
                         Boolean excludenodata = Boolean.valueOf(args[3].stringValue());
                         Double result = attribute(geom,noband,x,y,excludenodata);
                         return valueFactory.createLiteral(result);
                 }
                 return null;
         }