rdf4j-postgis: RasterAlgebraFunction Class Reference
RasterAlgebraFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract GridCoverage modify (GridCoverage coverage, Integer bd1, GridCoverage coverage2, Integer bd2)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
{
                 if (args.length != 4) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 4 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 LiteralType l2=LiteralRegistry.getLiteral(((Literal)args[2]).getDatatype().toString());
                 if(l instanceof RasterLiteral && l2 instanceof RasterLiteral) {
                         GridCoverage geom=((RasterLiteral)l).read(args[0].stringValue());
                         Integer bd1=Integer.valueOf(args[1].stringValue());
                         GridCoverage geom2=((RasterLiteral)l).read(args[2].stringValue());
                         Integer bd2=Integer.valueOf(args[3].stringValue());
                         GridCoverage result = modify(geom,bd1,geom2,bd2);
                         return valueFactory.createLiteral(((RasterLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 return null;
         }
References LiteralRegistry.getLiteral(), and RasterAlgebraFunction.modify().
Referenced by AddTest.testAdd(), AndTest.testAnd(), DivTest.testDiv(), LogTest.testLog(), MultTest.testMult(), OrTest.testOr(), SubtractTest.testSubtract(), and XorTest.testXor().
modify()
abstract GridCoverage modify (GridCoverage coverage, Integer bd1, GridCoverage coverage2, Integer bd2) abstract
Reimplemented in Xor, Threshold, Subtract, Or, Mult, Min, Mean, Max, Log, IDFT, IDCT, Div, DCT, And, Add, and Abs.
Referenced by RasterAlgebraFunction.evaluate().