rdf4j-postgis: RasterAlgebraUnaryFunction Class Reference
RasterAlgebraUnaryFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract GridCoverage modify (GridCoverage coverage, Integer bd1)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
References LiteralRegistry.getLiteral(), and RasterAlgebraUnaryFunction.modify().
Referenced by ExpTest.testExp(), InvertTest.testInvert(), and NotTest.testNot().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof RasterLiteral) {
                         GridCoverage geom=((RasterLiteral)l).read(args[0].stringValue());
                         Integer bd1=Integer.valueOf(args[1].stringValue());
                         GridCoverage result = modify(geom,bd1);
                         return valueFactory.createLiteral(((RasterLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 return null;
         }
modify()
abstract GridCoverage modify (GridCoverage coverage, Integer bd1) abstract
Referenced by RasterAlgebraUnaryFunction.evaluate().