rdf4j-postgis: RasterAlgebraConstFunction Class Reference
RasterAlgebraConstFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract GridCoverage modify (GridCoverage coverage, Integer band, Double constt)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
{
                 if (args.length != 3) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 3 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof RasterLiteral) {
                         GridCoverage geom=((RasterLiteral)l).read(args[0].stringValue());
                         Integer band=Integer.valueOf(args[1].stringValue());
                         Double constt=Double.valueOf(args[2].stringValue());
                         GridCoverage result = modify(geom,band,constt);
                         return valueFactory.createLiteral(((RasterLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 return null;
         }
References LiteralRegistry.getLiteral(), and RasterAlgebraConstFunction.modify().
Referenced by AddConstTest.testAddConst(), AndConstTest.testAndConst(), DivConstTest.testDivConst(), MultConstTest.testMultConst(), OrConstTest.testOrConst(), SubtractConstTest.testSubtractConst(), and XorConstTest.testXorConst().
modify()
abstract GridCoverage modify (GridCoverage coverage, Integer band, Double constt) abstract
Reimplemented in XorConst, SubtractConst, OrConst, MultConst, DivConst, AndConst, and AddConst.
Referenced by RasterAlgebraConstFunction.evaluate().