rdf4j-postgis: RasterAttributeIntFunction Class Reference
RasterAttributeIntFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract Integer attribute (GridCoverage geom)
Member Function Documentation
attribute()
abstract Integer attribute (GridCoverage geom) abstract
Referenced by RasterAttributeIntFunction.evaluate().
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
References RasterAttributeIntFunction.attribute(), and LiteralRegistry.getLiteral().
Referenced by MinTileXTest.testMinTileX(), NumBandsTest.testNumBands(), NumYTilesTest.testNumYTiles(), and TileGridYOffsetTest.testTileGridYOffset().
{
         if (args.length != 1) {
                 throw new ValueExprEvaluationException(getURI() + " requires exactly 1 argument, got " + args.length);
         }
         LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
         if(l instanceof RasterLiteral) {
                 GridCoverage geom=((RasterLiteral)l).read(args[0].stringValue());
                 Integer result = attribute(geom);
                 return valueFactory.createLiteral(result);
         }
         return null;
 }