rdf4j-postgis: RasterAttributeStringFunction Class Reference
RasterAttributeStringFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract String attribute (GridCoverage geom)
Member Function Documentation
attribute()
abstract String attribute (GridCoverage geom) abstract
Reimplemented in Summary.
Referenced by RasterAttributeStringFunction.evaluate().
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 System.out.println(((Literal)args[0]).getDatatype().toString());
                 System.out.println(LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString()));
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 System.out.println(l);
                 if(l instanceof RasterLiteral) {
                         GridCoverage geom=((RasterLiteral)l).read(args[0].stringValue());
                         //System.out.println("Extracted GridCoverage: "+geom);
                         String result = attribute(geom);
                         return valueFactory.createLiteral(result);
                 }
                 return null;
         }
References RasterAttributeStringFunction.attribute(), and LiteralRegistry.getLiteral().
Referenced by SampleRasters.displayRasterSummary().