rdf4j-postgis: Disjoint Class Reference
Disjoint Class Reference
Public Member Functions
String getURI ()
Boolean relation (Value v1, Value v2)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Static Public Member Functions
static Boolean vectorOrRaster (Literal lit)
static Literal getLiteral (Function func, Value v) throws ValueExprEvaluationException
Static Public Attributes
static Set< String > rasterLiteralURIs =new TreeSet<String>()
static Set< String > vectorLiteralURIs =new TreeSet<String>()
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References RasterVectorRelationBinaryFunction.relation().
Referenced by EqualTest.testAdd().
{
                 // TODO Auto-generated method stub
                 return null;
         }
getLiteral()
static Literal getLiteral (Function func, Value v) throws ValueExprEvaluationException static inherited
Referenced by Contains.relation(), Within.relation(), Touches.relation(), Crosses.relation(), Intersects.relation(), Equals.relation(), Disjoint.relation(), Overlaps.relation(), CoveredBy.relation(), and ContainsProperly.relation().
{
                 if (!(v instanceof Literal)) {
                         throw new ValueExprEvaluationException("Invalid argument for " + func.getURI() + ": " + v);
                 }
                 Literal lit = (Literal) v;
                 return lit;
         }
getURI()
String getURI ()
References POSTGIS.st_rast_Disjoint.
{
                 return POSTGIS.st_rast_Disjoint.stringValue();
         }
relation()
Boolean relation (Value v1, Value v2)
References RasterVectorRelationBinaryFunction.getLiteral(), LiteralRegistry.getLiteral(), VectorLiteral.read(), RasterLiteral.read(), LiteralUtils.toGeometry(), and RasterVectorRelationBinaryFunction.vectorOrRaster().
{
                 Literal lit1=getLiteral(this, v1);
                 Literal lit2=getLiteral(this, v2);
                 Boolean type=vectorOrRaster(getLiteral(this, v1));
                 Boolean type2=vectorOrRaster(getLiteral(this, v2));
                 if(type==null || type2==null) {
                         return null;
                 }else if(type && type2) {
                         VectorLiteral vec1=(VectorLiteral) LiteralRegistry.getLiteral(lit1.getDatatype().toString());
                         VectorLiteral vec2=(VectorLiteral) LiteralRegistry.getLiteral(lit2.getDatatype().toString());
                         return vec1.read(v1.stringValue()).disjoint(vec2.read(v2.stringValue()));
                 }else if(type && !type2) {
                         VectorLiteral vec1=(VectorLiteral) LiteralRegistry.getLiteral(lit1.getDatatype().toString());
                         RasterLiteral vec2=(RasterLiteral) LiteralRegistry.getLiteral(lit2.getDatatype().toString());
                         return vec1.read(v1.stringValue()).disjoint(LiteralUtils.toGeometry(vec2.read(v2.stringValue()).getGridGeometry().getEnvelope()));
                 }else if(!type && type2) {
                         RasterLiteral vec1=(RasterLiteral) LiteralRegistry.getLiteral(lit1.getDatatype().toString());
                         VectorLiteral vec2=(VectorLiteral) LiteralRegistry.getLiteral(lit2.getDatatype().toString());
                         return LiteralUtils.toGeometry(((GridCoverage)vec1.read(v1.stringValue())).getGridGeometry().getEnvelope()).disjoint(vec2.read(v2.stringValue()));
                 }else {
                         RasterLiteral vec1=(RasterLiteral) LiteralRegistry.getLiteral(lit1.getDatatype().toString());
                         RasterLiteral vec2=(RasterLiteral) LiteralRegistry.getLiteral(lit2.getDatatype().toString());
                         return LiteralUtils.toGeometry(((GridCoverage)vec1.read(v1.stringValue())).getGridGeometry().getEnvelope()).disjoint(LiteralUtils.toGeometry(vec2.read(v2.stringValue()).getGridGeometry().getEnvelope()));
                 }
         }
vectorOrRaster()
static Boolean vectorOrRaster (Literal lit) static inherited
References LiteralRegistry.literals.
Referenced by Contains.relation(), Within.relation(), Touches.relation(), Crosses.relation(), Intersects.relation(), Equals.relation(), Disjoint.relation(), Overlaps.relation(), CoveredBy.relation(), and ContainsProperly.relation().
{
                 if(LiteralRegistry.literals.containsKey(lit.getDatatype().toString())) {
                         LiteralType lite=LiteralRegistry.literals.get(lit.getDatatype().toString());
                         if(lite instanceof VectorLiteral) {
                                 return true;
                         }else if(lite instanceof RasterLiteral) {
                                 return false;
                         }
                 }
                 return null;
         }
Member Data Documentation
rasterLiteralURIs
Set<String> rasterLiteralURIs =new TreeSet<String>() static inherited
vectorLiteralURIs
Set<String> vectorLiteralURIs =new TreeSet<String>() static inherited