rdf4j-postgis: WorldToRasterCoord Class Reference
WorldToRasterCoord Class Reference
Public Member Functions
String getURI ()
Geometry attribute (GridCoverage raster, Integer longitude, Integer latitude)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Member Function Documentation
attribute()
Geometry attribute (GridCoverage raster, Integer longitude, Integer latitude)
{
         try {
          GridGeometry gg2D = raster.getGridGeometry();
             MathTransform gridToCRS = gg2D.getGridToCRS(PixelInCell.CELL_CENTER);
             MathTransform crsToGrid = gridToCRS.inverse();
             DirectPosition realPos=new DirectPosition2D(latitude, longitude);
             DirectPosition gridPos = new DirectPosition2D();
             DirectPosition res=crsToGrid.transform(realPos, gridPos);
             Coordinate coord=new Coordinate(res.getCoordinate()[0],res.getCoordinate()[1]);
             GeometryFactory fac=new GeometryFactory();
             return fac.createPoint(coord);
        } catch (TransformException e) {
            return null;
        }
         }
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References RasterAttributeIntIntGeomFunction.attribute(), and LiteralRegistry.getLiteral().
Referenced by RasterToWorldCoordTest.testRasterToWorldCoord(), and WorldToRasterCoordTest.testWorldToRasterCoord().
{
                 if (args.length != 3) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof RasterLiteral) {
                         GridCoverage geom=((RasterLiteral)l).read(args[0].stringValue());
                         Integer longitude = Integer.valueOf(args[1].stringValue());
                         Integer latitude = Integer.valueOf(args[2].stringValue());
                         Geometry result = attribute(geom,longitude,latitude);
                         return valueFactory.createLiteral(((VectorLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 return null;
         }
getURI()
String getURI ()
References POSTGIS.st_worldToRasterCoord.
{
                 return POSTGIS.st_worldToRasterCoord.stringValue();
         }