rdf4j-postgis: RasterStringExportFunction Class Reference
RasterStringExportFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract String operation (GridCoverage raster)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
{
                 // TODO Auto-generated method stub
                 return null;
         }
Referenced by AsCoverageJSONTest.testAsCoverageJSON(), AsGeoTIFFTest.testAsGeoTIFF(), AsRastHexWKBTest.testAsRastHexWKB(), and AsRastWKBTest.testAsRastWKB().
operation()
abstract String operation (GridCoverage raster) abstract
Reimplemented in AsRastWKB, AsRastHexWKB, AsNetCDF, AsGMLCOV, AsGeoTIFF, AsCoverageJSON, and BandMetadata.