rdf4j-postgis: RasterModifierFunction Class Reference
RasterModifierFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract GridCoverage modify (GridCoverage coverage)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof RasterLiteral) {
                         GridCoverage geom=((RasterLiteral)l).read(args[0].stringValue());
                         GridCoverage result = modify(geom);
                         return valueFactory.createLiteral(((RasterLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 return null;
         }
References LiteralRegistry.getLiteral(), and RasterModifierFunction.modify().
modify()
abstract GridCoverage modify (GridCoverage coverage) abstract
Reimplemented in Flip, Resample, SetSkew, SetScale, SetRotation, and AddBand.
Referenced by RasterModifierFunction.evaluate().