rdf4j-postgis: RasterConstructorFunction Class Reference
RasterConstructorFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract GridCoverage construct (String input)
Member Function Documentation
construct()
abstract GridCoverage construct (String input) abstract
Reimplemented in RastFromWKB, RastFromNetCDF, RastFromHexWKB, RastFromGMLCOV, and RastFromCoverageJSON.
Referenced by RasterConstructorFunction.evaluate().
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 String geomString = args[0].stringValue();
                 GridCoverage result = construct(geomString);
                 return valueFactory.createLiteral(((RasterLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
         }
References RasterConstructorFunction.construct(), and LiteralRegistry.getLiteral().
Referenced by RastFromCoverageJSONTest.testRastFromCoverageJSON(), and RastFromWKBTest.testRastFromWKB().