rdf4j-postgis: RasterAttributeBooleanIntFunction Class Reference
RasterAttributeBooleanIntFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract Boolean attribute (GridCoverage geom, Integer param)
Member Function Documentation
attribute()
abstract Boolean attribute (GridCoverage geom, Integer param) abstract
Referenced by RasterAttributeBooleanIntFunction.evaluate().
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
References RasterAttributeBooleanIntFunction.attribute(), and LiteralRegistry.getLiteral().
Referenced by HasNoBandTest.testHasNoBandFalse(), and HasNoBandTest.testHasNoBandTrue().
{
         if (args.length != 2) {
                 throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
         }
         LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
         if(l instanceof RasterLiteral) {
                 GridCoverage geom=((RasterLiteral)l).read(args[0].stringValue());
                 Integer parameter = Integer.valueOf(args[1].stringValue());
                 Boolean result = attribute(geom,parameter);
                 return valueFactory.createLiteral(result);
         }
         return null;
 }