rdf4j-postgis: RasterModifierBoolDoubleFunction Class Reference
RasterModifierBoolDoubleFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract GridCoverage modify (GridCoverage coverage, Boolean type, Double zFactor)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
{
                 if (args.length != 3) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof RasterLiteral) {
                         GridCoverage geom=((RasterLiteral)l).read(args[0].stringValue());
                         Boolean type = Boolean.valueOf(args[1].stringValue());
                         Double zFactor = Double.valueOf(args[2].stringValue());
                         GridCoverage result = modify(geom,type,zFactor);
                         return valueFactory.createLiteral(((RasterLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 return null;
         }
References LiteralRegistry.getLiteral(), and RasterModifierBoolDoubleFunction.modify().
modify()
abstract GridCoverage modify (GridCoverage coverage, Boolean type, Double zFactor) abstract
Reimplemented in Mirror.
Referenced by RasterModifierBoolDoubleFunction.evaluate().