rdf4j-postgis: AsCoverageJSON Class Reference
AsCoverageJSON Class Reference
Public Member Functions
String getURI ()
String operation (GridCoverage raster)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
{
                 // TODO Auto-generated method stub
                 return null;
         }
Referenced by AsCoverageJSONTest.testAsCoverageJSON(), AsGeoTIFFTest.testAsGeoTIFF(), AsRastHexWKBTest.testAsRastHexWKB(), and AsRastWKBTest.testAsRastWKB().
getURI()
String getURI ()
{
                 return POSTGIS.ST_ASCOVERAGEJSON.stringValue();
         }
References POSTGIS.ST_ASCOVERAGEJSON.
operation()
String operation (GridCoverage raster)
Reimplemented from RasterStringExportFunction.
{
                 return CovJSONDatatype.INSTANCE.unparse(raster);
         }
References CovJSONDatatype.INSTANCE, and CovJSONDatatype.unparse().