rdf4j-postgis: TopologyStringExportFunction Class Reference
TopologyStringExportFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract String modify (Topology topo)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
References LiteralRegistry.getLiteral(), and TopologyStringExportFunction.modify().
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 LiteralType l2=LiteralRegistry.getLiteral(((Literal)args[1]).getDatatype().toString());
                 if(l instanceof TopologyLiteral && l2 instanceof VectorLiteral) {
                         Topology topo=((TopologyLiteral)l).read(args[0].stringValue());
                         String result = modify(topo);
                         return valueFactory.createLiteral(result,((Literal)args[0]).getDatatype());
                 }
                 return null;
         }
modify()
abstract String modify (Topology topo) abstract
Referenced by TopologyStringExportFunction.evaluate().