rdf4j-postgis: TopologyModificationFunction Class Reference
TopologyModificationFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract Topology modify (Topology topo)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
References LiteralRegistry.getLiteral(), and TopologyModificationFunction.modify().
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof TopologyLiteral) {
                         Topology topo=((TopologyLiteral)l).read(args[0].stringValue());
                         Topology result = modify(topo);
                         return valueFactory.createLiteral(((TopologyLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 return null;
         }
modify()
abstract Topology modify (Topology topo) abstract
Referenced by TopologyModificationFunction.evaluate().