rdf4j-postgis: RasterLiteral Class Reference
RasterLiteral Class Reference abstract
Public Member Functions
abstract String unparse (GridCoverage geom)
abstract GridCoverage read (String literalValue)
Member Function Documentation
read()
abstract GridCoverage read (String literalValue) abstract
Reimplemented in NetCDFDatatype, WKBRastDatatype, HexWKBRastDatatype, GMLCOVDatatype, GeoTIFFDatatype, and CovJSONDatatype.
Referenced by Contains.relation(), ContainsProperly.relation(), CoveredBy.relation(), Crosses.relation(), Disjoint.relation(), Equals.relation(), Intersection.relation(), Intersects.relation(), Overlaps.relation(), Touches.relation(), Within.relation(), and DWithin.relation().
unparse()
abstract String unparse (GridCoverage geom) abstract
Reimplemented in WKBRastDatatype, NetCDFDatatype, HexWKBRastDatatype, GMLCOVDatatype, GeoTIFFDatatype, and CovJSONDatatype.