rdf4j-postgis: Crop Class Reference
Crop Class Reference
Public Member Functions
String getURI ()
GridCoverage modify (GridCoverage inputCoverage, Geometry cropShape)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Private Member Functions
ParameterBlock buildParameterBlock (RenderedImage source, boolean newDescriptor, boolean roiUsed, boolean noDataUsed)
Member Function Documentation
buildParameterBlock()
ParameterBlock buildParameterBlock (RenderedImage source, boolean newDescriptor, boolean roiUsed, boolean noDataUsed) private
Referenced by Crop.modify().
{
                 // Creation of the parameterBlock associated with its operation
                 ParameterBlockJAI pb;
                 if (newDescriptor) {
                     pb = new ParameterBlockJAI("Crop");
                 } else {
                     pb = new ParameterBlockJAI("crop");
                 }
                 // Setting of the source
                 pb.setSource("source0", source);
                 // Setting of the parameters
                 pb.setParameter("x", (float) 0);
                 pb.setParameter("y", (float) 0);
                 pb.setParameter("width", (float) 20);
                 pb.setParameter("height", (float) 20);
                 if (newDescriptor) {
                     // If ROI is present, then it is added
                     if (roiUsed) {
                         ROI roi = new ROIShape(new Rectangle(5, 5, 10, 10));
                         pb.setParameter("ROI", roi);
                     }
                     // If NoData is present, then it is added
                     if (noDataUsed) {
                         Range noData = RangeFactory.create(noDataValue, true, noDataValue, true);
                         pb.setParameter("NoData", noData);
                         pb.setParameter("destNoData", destNoData);
                     }
                 }
                 return pb;
             }
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and RasterModifierGeometryFunction.modify().
{
                 if (args.length != 3) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof RasterLiteral) {
                         GridCoverage geom=((RasterLiteral)l).read(args[0].stringValue());
                         Geometry geom2=((VectorLiteral)l).read(args[1].stringValue());
                         GridCoverage result = modify(geom,geom2);
                         return valueFactory.createLiteral(((RasterLiteral) l).unparse(result),((Literal)args[0]).getDatatype());
                 }
                 return null;
         }
getURI()
String getURI ()
References POSTGIS.st_crop.
{
                 return POSTGIS.st_crop.stringValue();
         }
modify()
GridCoverage modify (GridCoverage inputCoverage, Geometry cropShape)
References Crop.buildParameterBlock().
{
                  CoordinateReferenceSystem crs = inputCoverage.getCoordinateReferenceSystem();
                  ParameterBlock pb = buildParameterBlock(inputCoverage.render(inputCoverage.getGridGeometry().getExtent()), false, false, false);
                 ParameterBlock pbNew = buildParameterBlock(inputCoverage.render(inputCoverage.getGridGeometry().getExtent()), true, false, false);
                 // Images creation
                 RenderedOp cropped = JAI.create("crop", pb);
                 RenderedOp jaiextCropped = JAI.create("Crop", pbNew);
                 // Test on the selected image
                 assertImageEquals(cropped, jaiextCropped);
                 // Display Image
                 if (INTERACTIVE && TEST_SELECTOR == 0) {
                     RenderedImageBrowser.showChain(jaiextCropped, false, false);
                     try {
                         System.in.read();
                     } catch (IOException e) {
                         e.printStackTrace();
                     }
                 }
                 // check geometry
                 GeometryCollection roi = null;
                 if (cropShape == null || cropShape.isEmpty()) {
                     roi = null;
                 } else {
                     Class<?> geomBinding = cropShape.getClass();
                     if (geomBinding.isAssignableFrom(MultiPolygon.class)
                             || geomBinding.isAssignableFrom(Polygon.class)) {
                         if (!cropShape.isValid() || !cropShape.isSimple()) {
                             cropShape = cropShape.buffer(0);
                             cropShape.setUserData(cropShape.getUserData());
                         }
                     }
                     // transform if necessary
                     cropShape = transformGeometry(cropShape, crs);
                     // force it to a collection if necessary
                     if (cropShape instanceof GeometryCollection) {
                         roi = (GeometryCollection) cropShape;
                     } else {
                         roi = cropShape.getFactory().createGeometryCollection(new Geometry[] { cropShape });
                     }
                 }
                 // check bounds
                 GeneralEnvelope bounds = null;
                 if (extent == null || extent.isEmpty() || extent.isNull()) {
                     if (roi != null) {
                         bounds = new GeneralEnvelope(new ReferencedEnvelope(roi.getEnvelopeInternal(), crs));
                     }
                 } else {
                     CoordinateReferenceSystem extCrs = extent.getCoordinateReferenceSystem();
                     if (!CRS.equalsIgnoreMetadata(crs, extCrs)) {
                             MathTransform transform = CRS.findMathTransform(extCrs, crs, true);
                             Envelope env = JTS.transform(extent, transform);
                             bounds = new GeneralEnvelope(new ReferencedEnvelope(env, crs));
                     } else {
                         bounds = new GeneralEnvelope(extent);
                     }
                 }
                 // perform the crops
                 final CoverageProcessor coverageProcessor = CoverageProcessor.getInstance();
                 final Operation cropOperation = coverageProcessor.getOperation("CoverageCrop");
                 final ParameterValueGroup param = cropOperation.getParameters();
                 param.parameter("Source").setValue(inputCoverage);
                 param.parameter("Envelope").setValue(bounds);
                 param.parameter("ROI").setValue(roi);
                 param.parameter("ROITolerance").setValue(roiTolerance); // default
                 return doOperation(param, null);
         }