rdf4j-postgis: WKBRastDatatype Class Reference
WKBRastDatatype Class Reference
Public Member Functions
GridCoverage read (String geometryLiteral)
String toString ()
String unparse (GridCoverage geom)
Static Public Attributes
static final String URI = POSTGIS.NAMESPACE+POSTGIS.WKBRaster
static final WKBRastDatatype INSTANCE = new WKBRastDatatype()
static final IRI LiteralIRI =SimpleValueFactory.getInstance().createIRI(POSTGIS.NAMESPACE+POSTGIS.WKBRaster)
Member Function Documentation
read()
GridCoverage read (String geometryLiteral)
References WKBRasterReader.readCoverage().
Referenced by RastFromWKB.construct().
{
                 WKBRasterReader reader2=new WKBRasterReader();
                 GridCoverage coverage;
                 try {
                         coverage = reader2.readCoverage(geometryLiteral.getBytes(), null);
                         return coverage;
                 } catch (IOException | FactoryException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                         return null;
                 }
         }
toString()
String toString ()
{
         return "WKBRasterDatatype{" + URI + '}';
     }
unparse()
String unparse (GridCoverage geom)
References WKBRasterWriter.write().
Referenced by AsBinary.operation().
{
         WKBRasterWriter writer=new WKBRasterWriter();
                 String rasterWKB;
                 try {
                         rasterWKB = writer.write(geom).toString();
                         return rasterWKB.toString();
                 } catch (IOException | FactoryException e) {
                         throw new AssertionError(e.getMessage());
                 }
         }
Member Data Documentation
INSTANCE
final WKBRastDatatype INSTANCE = new WKBRastDatatype() static
Referenced by RastFromWKB.construct(), LiteralRegistry.LiteralRegistry(), and AsBinary.operation().
LiteralIRI
final IRI LiteralIRI =SimpleValueFactory.getInstance().createIRI(POSTGIS.NAMESPACE+POSTGIS.WKBRaster) static
URI
final String URI = POSTGIS.NAMESPACE+POSTGIS.WKBRaster static
Referenced by LiteralRegistry.LiteralRegistry().