rdf4j-postgis: JtsPolyshapeWriter Class Reference
JtsPolyshapeWriter Class Reference
Public Member Functions
void write (Encoder output, Geometry geom) throws IOException
String getFormatName ()
void write (Writer output, Geometry shape) throws IOException
String toString (Geometry shape)
Static Public Attributes
static final char KEY_POINT = '0'
static final char KEY_LINE = '1'
static final char KEY_POLYGON = '2'
static final char KEY_MULTIPOINT = '3'
static final char KEY_CIRCLE = '4'
static final char KEY_BOX = '5'
static final char KEY_ARG_START = '('
static final char KEY_ARG_END = ')'
static final char KEY_SEPERATOR = ' '
Protected Member Functions
void write (Encoder output, CoordinateSequence coordseq) throws IOException
void write (Encoder output, Coordinate[] coord) throws IOException
void write (Encoder output, Polygon p) throws IOException
Member Function Documentation
getFormatName()
String getFormatName () inherited
{
     return "PolyShape";
   }
toString()
String toString (Geometry shape) inherited
References PolyshapeWriter.write().
Referenced by PolyshapeDatatype.unparse().
{
     try {
       StringWriter buffer = new StringWriter();
       write(buffer, shape);
       return buffer.toString();
     } catch (IOException ex) {
       throw new RuntimeException(ex);
     }
   }
write() [1/5]
void write (Encoder output, CoordinateSequence coordseq) throws IOException protected
Referenced by JtsPolyshapeWriter.write().
{
     int dim = coordseq.getDimension();
 //    if(dim>2) {
 //      throw new IllegalArgumentException("only supports 2d geometry now ("+dim+")");
 //    }
     for (int i = 0; i < coordseq.size(); i++) {
       output.write(coordseq.getOrdinate(i, 0),
                    coordseq.getOrdinate(i, 1));
     }
   }
write() [2/5]
void write (Encoder output, Coordinate [] coord) throws IOException protected
{
     for (int i = 0; i < coord.length; i++) {
       output.write(coord[i].x, coord[i].y);
     }
   }
write() [3/5]
void write (Encoder output, Polygon p) throws IOException protected
References PolyshapeWriter.KEY_POLYGON, and JtsPolyshapeWriter.write().
{
     output.write(PolyshapeWriter.KEY_POLYGON);
     write(output, p.getExteriorRing().getCoordinateSequence());
     for (int i = 0; i < p.getNumInteriorRing(); i++) {
       output.startRing();
       write(output, p.getInteriorRingN(i).getCoordinateSequence());
     }
   }
write() [4/5]
void write (Encoder output, Geometry geom) throws IOException
References PolyshapeWriter.KEY_LINE, PolyshapeWriter.KEY_MULTIPOINT, PolyshapeWriter.KEY_POINT, and JtsPolyshapeWriter.write().
{
     if (geom instanceof Point) {
       Point v = (Point) geom;
       output.write(PolyshapeWriter.KEY_POINT);
       write(output, v.getCoordinateSequence());
       return;
     } else if (geom instanceof Polygon) {
       write(output, (Polygon) geom);
       return;
     } else if (geom instanceof LineString) {
       LineString v = (LineString) geom;
       output.write(PolyshapeWriter.KEY_LINE);
       write(output, v.getCoordinateSequence());
       return;
     } else if (geom instanceof MultiPoint) {
       MultiPoint v = (MultiPoint) geom;
       output.write(PolyshapeWriter.KEY_MULTIPOINT);
       write(output, v.getCoordinates());
       return;
     } else if (geom instanceof GeometryCollection) {
       GeometryCollection v = (GeometryCollection) geom;
       for (int i = 0; i < v.getNumGeometries(); i++) {
         if (i > 0) {
           output.seperator();
         }
         write(output, v.getGeometryN(i));
       }
     } else {
       throw new UnsupportedOperationException("unknown: " + geom);
     }
   }
write() [5/5]
void write (Writer output, Geometry shape) throws IOException inherited
Referenced by PolyshapeWriter.toString().
{
     if (shape == null) {
       throw new NullPointerException("Shape can not be null");
     }
     write(new Encoder(output), shape);
   }
Member Data Documentation
KEY_ARG_END
final char KEY_ARG_END = ')' static inherited
Referenced by PolyshapeReader.read().
KEY_ARG_START
final char KEY_ARG_START = '(' static inherited
Referenced by PolyshapeReader.read().
KEY_BOX
final char KEY_BOX = '5' static inherited
KEY_CIRCLE
final char KEY_CIRCLE = '4' static inherited
Referenced by PolyshapeReader.read().
KEY_LINE
final char KEY_LINE = '1' static inherited
Referenced by PolyshapeReader.read(), and JtsPolyshapeWriter.write().
KEY_MULTIPOINT
final char KEY_MULTIPOINT = '3' static inherited
Referenced by PolyshapeReader.read(), and JtsPolyshapeWriter.write().
KEY_POINT
final char KEY_POINT = '0' static inherited
Referenced by PolyshapeReader.read(), and JtsPolyshapeWriter.write().
KEY_POLYGON
final char KEY_POLYGON = '2' static inherited
Referenced by PolyshapeReader.read(), and JtsPolyshapeWriter.write().
KEY_SEPERATOR
final char KEY_SEPERATOR = ' ' static inherited
Referenced by PolyshapeReader.read().