rdf4j-postgis: VectorLiteral Class Reference
VectorLiteral Class Reference abstract
Public Member Functions
abstract String unparse (Geometry geom)
abstract Geometry read (String literalValue)
Member Function Documentation
read()
abstract Geometry read (String literalValue) abstract
Referenced by Contains.relation(), Within.relation(), Touches.relation(), Overlaps.relation(), Crosses.relation(), Intersects.relation(), Equals.relation(), DWithin.relation(), Disjoint.relation(), CoveredBy.relation(), Intersection.relation(), and ContainsProperly.relation().
unparse()
abstract String unparse (Geometry geom) abstract