rdf4j-postgis: VectorLiteral Class Reference
VectorLiteral Class Reference abstract
Public Member Functions
abstract String unparse (Geometry geom)
abstract Geometry read (String literalValue)
Member Function Documentation
read()
abstract Geometry read (String literalValue) abstract
Reimplemented in SVGDatatype, MVTDatatype, WKTDatatype, WKBDatatype, KMLDatatype, HexWKBDatatype, GPXDatatype, GMLDatatype, GeoURIDatatype, GeoJSONLDDatatype, GeoJSONDatatype, GeoHashDatatype, GeobufDatatype, and EncodedPolylineDatatype.
Referenced by Contains.relation(), ContainsProperly.relation(), CoveredBy.relation(), Crosses.relation(), Disjoint.relation(), Equals.relation(), Intersection.relation(), Intersects.relation(), Overlaps.relation(), Touches.relation(), Within.relation(), and DWithin.relation().
unparse()
abstract String unparse (Geometry geom) abstract
Reimplemented in WKTDatatype, WKBDatatype, KMLDatatype, HexWKBDatatype, GMLDatatype, GeoJSONLDDatatype, GeoJSONDatatype, GeobufDatatype, EncodedPolylineDatatype, GeoHashDatatype, SVGDatatype, MVTDatatype, GPXDatatype, and GeoURIDatatype.