rdf4j-postgis: HexWKBRastDatatype Class Reference
HexWKBRastDatatype Class Reference
Public Member Functions
GridCoverage read (String geometryLiteral)
String toString ()
String unparse (GridCoverage geom)
Static Public Attributes
static final String URI = POSTGIS.NAMESPACE+POSTGIS.HexWKBRaster
static final HexWKBRastDatatype INSTANCE =new HexWKBRastDatatype()
static final IRI LiteralIRI =SimpleValueFactory.getInstance().createIRI(POSTGIS.NAMESPACE+POSTGIS.HexWKBRaster)
Member Function Documentation
read()
GridCoverage read (String geometryLiteral)
References WKBRasterReader.readCoverage().
Referenced by RastFromHexWKB.construct().
{
                 WKBRasterReader reader2=new WKBRasterReader();
                 try {
                         GridCoverage coverage;
                         System.out.println("Read it: "+geometryLiteral);
                         CRSAuthorityFactory crs=CRS.getAuthorityFactory("EPSG");
                         coverage = reader2.readCoverage(WKBReader.hexToBytes(geometryLiteral),crs);
                         //System.out.println("Read wan le: "+coverage);
                         return coverage;
                 } catch (IOException | FactoryException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 }
                 return null;
         }
toString()
String toString ()
Referenced by HexWKBRastDatatype.unparse().
{
         return "HexWKBRasterDatatype{" + URI + '}';
     }
unparse()
String unparse (GridCoverage geom)
References HexWKBRastDatatype.toString(), and WKBRasterWriter.write().
Referenced by AsRastHexWKB.operation().
{
         WKBRasterWriter writer=new WKBRasterWriter();
                 String rasterWKB;
                 try {
                         rasterWKB = WKBWriter.toHex(writer.write((GridCoverage) geom)).toString();
                         return rasterWKB.toString();
                 } catch (IOException | FactoryException e) {
                         throw new AssertionError(e.getMessage());
                 }
         }
Member Data Documentation
INSTANCE
final HexWKBRastDatatype INSTANCE =new HexWKBRastDatatype() static
Referenced by RastFromHexWKB.construct(), LiteralRegistry.LiteralRegistry(), and AsRastHexWKB.operation().
LiteralIRI
final IRI LiteralIRI =SimpleValueFactory.getInstance().createIRI(POSTGIS.NAMESPACE+POSTGIS.HexWKBRaster) static
Referenced by SampleRasters.displayRasterSummary(), AddTest.testAdd(), AddConstTest.testAddConst(), AndTest.testAnd(), AndConstTest.testAndConst(), BandTest.testBand(), BandNoDataValueTest.testBandNoDataValue(), DivTest.testDiv(), DivConstTest.testDivConst(), ExpTest.testExp(), HasNoBandTest.testHasNoBandFalse(), HasNoBandTest.testHasNoBandTrue(), LogTest.testLog(), ScaleXTest.testMinScaleX(), ScaleYTest.testMinScaleY(), SkewXTest.testMinTileX(), SkewYTest.testMinTileX(), MinTileXTest.testMinTileX(), MinTileYTest.testMinTileY(), MultTest.testMult(), MultConstTest.testMultConst(), NumBandsTest.testNumBands(), NumXTilesTest.testNumXTiles(), NumYTilesTest.testNumYTiles(), OrTest.testOr(), OrConstTest.testOrConst(), HeightTest.testRasterHeight(), IsEmptyTest.testRasterIsEmptyFalse(), RasterToWorldCoordTest.testRasterToWorldCoord(), RasterToWorldCoordXTest.testRasterToWorldCoordX(), RasterToWorldCoordYTest.testRasterToWorldCoordY(), WidthTest.testRasterWidth(), ShearXTest.testShearX(), ShearYTest.testShearY(), SubtractTest.testSubtract(), SubtractConstTest.testSubtractConst(), TileGridXOffsetTest.testTileGridXOffset(), TileGridYOffsetTest.testTileGridYOffset(), TileWidthTest.testTileHeight(), TileHeightTest.testTileHeight(), TranslateXTest.testTranslateX(), TranslateYTest.testTranslateY(), UpperLeftXTest.testUpperLeftX(), UpperLeftYTest.testUpperLeftY(), WorldToRasterCoordTest.testWorldToRasterCoord(), WorldToRasterCoordXTest.testWorldToRasterCoordX(), WorldToRasterCoordYTest.testWorldToRasterCoordY(), XorTest.testXor(), and XorConstTest.testXorConst().
URI
final String URI = POSTGIS.NAMESPACE+POSTGIS.HexWKBRaster static
Referenced by LiteralRegistry.LiteralRegistry().