rdf4j-postgis: CovJSONDatatype Class Reference
CovJSONDatatype Class Reference
Public Member Functions
GridCoverage read (String geometryLiteral)
String unparse (GridCoverage geom)
Static Public Attributes
static final String URI = POSTGIS.NAMESPACE+POSTGIS.CoverageJSON
static final CovJSONDatatype INSTANCE =new CovJSONDatatype()
static final IRI LiteralIRI =SimpleValueFactory.getInstance().createIRI(POSTGIS.NAMESPACE+POSTGIS.CoverageJSON)
Member Function Documentation
read()
GridCoverage read (String geometryLiteral)
References CoverageJSONReader.covJSONStringToCoverage().
Referenced by RastFromCoverageJSON.construct().
{
                 return CoverageJSONReader.covJSONStringToCoverage(geometryLiteral);
         }
unparse()
String unparse (GridCoverage geom)
Referenced by AsCoverageJSON.operation().
{
                 /*
                 CoverageJsonConverterImpl covjsonconverter=new CoverageJsonConverterImpl();
                 covjsonconverter.con
                 covjsonconverter.convertFeatureToJson(os, feat);
                 CoverageJsonWriter writer=new CoverageJsonWriter(new StreamingEncoder());
                 // TODO Auto-generated method stub
                 return super.unparse(value);
                 */
                 return null;
         }
Member Data Documentation
INSTANCE
final CovJSONDatatype INSTANCE =new CovJSONDatatype() static
Referenced by RastFromCoverageJSON.construct(), LiteralRegistry.LiteralRegistry(), and AsCoverageJSON.operation().
LiteralIRI
final IRI LiteralIRI =SimpleValueFactory.getInstance().createIRI(POSTGIS.NAMESPACE+POSTGIS.CoverageJSON) static
Referenced by LogTest.testAdd(), AddTest.testAdd(), AddConstTest.testAddConst(), AndTest.testAnd(), AndConstTest.testAndConst(), AsCoverageJSONTest.testAsCoverageJSON(), AsGeoTIFFTest.testAsGeoTIFF(), AsRastHexWKBTest.testAsRastHexWKB(), AsRastWKBTest.testAsRastWKB(), BandTest.testBand(), BandNoDataValueTest.testBandNoDataValue(), DivTest.testDiv(), DivConstTest.testDivConst(), EqualTest.testEqual(), ExpTest.testExp(), HasNoBandTest.testHasNoBandFalse(), HasNoBandTest.testHasNoBandTrue(), InvertTest.testInvert(), ScaleXTest.testMinScaleX(), ScaleYTest.testMinScaleY(), SkewXTest.testMinTileX(), MinTileXTest.testMinTileX(), SkewYTest.testMinTileX(), TileGridXOffsetTest.testMinTileX(), TileGridYOffsetTest.testMinTileX(), UpperLeftXTest.testMinTileX(), UpperLeftYTest.testMinTileX(), MinTileYTest.testMinTileY(), MultTest.testMult(), NotTest.testNot(), NumXTilesTest.testNumXTiles(), NumYTilesTest.testNumYTiles(), OrTest.testOr(), OrConstTest.testOrConst(), HeightTest.testRasterHeight(), IsEmptyTest.testRasterIsEmptyFalse(), RasterToWorldCoordTest.testRasterToWorldCoord(), RasterToWorldCoordXTest.testRasterToWorldCoordX(), RasterToWorldCoordYTest.testRasterToWorldCoordY(), ValueTest.testRasterValue(), RescaleTest.testRasterValue(), ResizeTest.testRasterValue(), WidthTest.testRasterWidth(), RastFromCoverageJSONTest.testRastFromCoverageJSON(), RastFromHexWKBTest.testRastFromHexWKB(), RastFromWKBTest.testRastFromWKB(), ShearXTest.testShearX(), ShearYTest.testShearY(), SubtractTest.testSubtract(), SubtractConstTest.testSubtractConst(), TileWidthTest.testTileHeight(), TileHeightTest.testTileHeight(), TranslateXTest.testTranslateX(), TranslateYTest.testTranslateY(), WorldToRasterCoordTest.testWorldToRasterCoord(), WorldToRasterCoordXTest.testWorldToRasterCoordX(), WorldToRasterCoordYTest.testWorldToRasterCoordY(), XorTest.testXor(), and XorConstTest.testXorConst().
URI
final String URI = POSTGIS.NAMESPACE+POSTGIS.CoverageJSON static
Referenced by LiteralRegistry.LiteralRegistry().