rdf4j-postgis: NetCDFDatatype Class Reference
NetCDFDatatype Class Reference
Public Member Functions
GridCoverage read (String literalValue)
String unparse (GridCoverage geom)
Static Public Attributes
static final String URI =POSTGIS.NAMESPACE+POSTGIS.NETCDF
static final GMLCOVDatatype INSTANCE =new GMLCOVDatatype()
static final IRI LiteralIRI =SimpleValueFactory.getInstance().createIRI(POSTGIS.NAMESPACE+POSTGIS.NETCDF)
Member Function Documentation
read()
GridCoverage read (String literalValue)
{
                 //StorageConnector connect=new StorageConnector(connect);
                 //NetcdfStore netcdf=new NetcdfStoreProvider().open(connector);
                 //netcdf.
                 // TODO Auto-generated method stub
                 return null;
         }
unparse()
String unparse (GridCoverage geom)
{
                 // TODO Auto-generated method stub
                 return null;
         }
Member Data Documentation
INSTANCE
final GMLCOVDatatype INSTANCE =new GMLCOVDatatype() static
Referenced by RastFromNetCDF.construct(), LiteralRegistry.LiteralRegistry(), and AsNetCDF.operation().
LiteralIRI
final IRI LiteralIRI =SimpleValueFactory.getInstance().createIRI(POSTGIS.NAMESPACE+POSTGIS.NETCDF) static
URI
final String URI =POSTGIS.NAMESPACE+POSTGIS.NETCDF static
Referenced by LiteralRegistry.LiteralRegistry().