rdf4j-postgis: RasterLiteral Class Reference
RasterLiteral Class Reference abstract
Public Member Functions
abstract String unparse (GridCoverage geom)
abstract GridCoverage read (String literalValue)
Member Function Documentation
read()
abstract GridCoverage read (String literalValue) abstract
Referenced by Contains.relation(), Within.relation(), Touches.relation(), Overlaps.relation(), Crosses.relation(), Intersects.relation(), Equals.relation(), DWithin.relation(), Disjoint.relation(), CoveredBy.relation(), Intersection.relation(), and ContainsProperly.relation().
unparse()
abstract String unparse (GridCoverage geom) abstract