rdf4j-postgis: MVTDatatype Class Reference
MVTDatatype Class Reference
Public Member Functions
String unparse (Geometry geometry)
This method Un-parses the JTS Geometry to the GML literal.
Geometry read (String geometryLiteral)
String toString ()
Static Public Attributes
static final String URI = POSTGIS.MVT
The default GML type URI.
static final MVTDatatype INSTANCE = new MVTDatatype()
A static instance of GMLDatatype.
static final String KML_PREFIX = "mvt"
XML element tag "gml" is defined for the convenience of GML generation.
Member Function Documentation
read()
Geometry read (String geometryLiteral)
References VectorTileDecoder.decode(), VectorTileDecoder.Feature.getGeometry(), and VectorTileDecoder.FeatureIterable.iterator().
{
         VectorTileDecoder decoder=new VectorTileDecoder();
         FeatureIterable res;
                 try {
                         res = decoder.decode(Base64.base64ToByteArray(geometryLiteral));
         Iterator<Feature> it=res.iterator();
         GeometryFactory fac=new GeometryFactory();
         List<Geometry> geoms=new LinkedList<Geometry>();
         while(it.hasNext()) {
                 Feature feat=it.next();
                 geoms.add(feat.getGeometry());
         }
         if(geoms.isEmpty()) {
                 return fac.createGeometry(null);
         }
         if(geoms.size()==1) {
                 return geoms.get(0);
         }
         return new GeometryCollection(geoms.toArray(new Geometry[geoms.size()]),fac);
                 } catch (IOException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 }
                 return null;
     }
toString()
String toString ()
{
         return "KMLDatatype{" + URI + '}';
     }
unparse()
String unparse (Geometry geometry)
This method Un-parses the JTS Geometry to the GML literal.
Parameters
geometry - the JTS Geometry to be un-parsed
Returns
GML - the returned GML Literal.
Notice that the Spatial Reference System "urn:ogc:def:crs:OGC::CRS84" is predefined in the returned GML literal.
References VectorTileEncoder.addFeature(), and VectorTileEncoder.encode().
Referenced by AsMVT.operation().
{
         VectorTileEncoder encoder = new VectorTileEncoder();
         encoder.addFeature("mvt", new TreeMap<>(), geometry);
         // Finally, get the byte array
         byte[] encoded = encoder.encode();
         return new String(Base64.byteArrayToBase64(encoded));
     }
Member Data Documentation
INSTANCE
final MVTDatatype INSTANCE = new MVTDatatype() static
A static instance of GMLDatatype.
Referenced by AsMVT.operation().
KML_PREFIX
final String KML_PREFIX = "mvt" static
XML element tag "gml" is defined for the convenience of GML generation.
URI
final String URI = POSTGIS.MVT static
The default GML type URI.