rdf4j-postgis: GeobufDatatype Class Reference
GeobufDatatype Class Reference
Public Member Functions
String unparse (Geometry geometry)
This method Un-parses the JTS Geometry to the WKT literal.
Geometry read (String geometryLiteral)
String toString ()
Static Public Attributes
static final String URI = POSTGIS.GeoBuf
The default WKT type URI.
static final GeobufDatatype INSTANCE = new GeobufDatatype()
A static instance of WKTDatatype.
Member Function Documentation
read()
Geometry read (String geometryLiteral)
{
                 InputStream stream = new ByteArrayInputStream(geometryLiteral.getBytes(StandardCharsets.UTF_8));
                 /*GeobufDecoder decoder;
                         try {
                                 decoder = new GeobufDecoder(stream);
                         Geometry geom=decoder.next().geometry;
                         return LiteralUtils.createGeometry(geom.getCoordinates(), geom.getGeometryType(), geom.getSRID());
                         } catch (IOException e) {
                                 // TODO Auto-generated catch block
                                 e.printStackTrace();
                                 throw new RuntimeException();
                         }*/
                 return null;
             }
toString()
String toString ()
{
                 return "GeoBufDatatype{" + URI + '}';
             }
unparse()
String unparse (Geometry geometry)
This method Un-parses the JTS Geometry to the WKT literal.
Parameters
geometry - the JTS Geometry to be un-parsed
Returns
WKT - the returned WKT Literal.
Notice that the Spatial Reference System is not specified in returned WKT literal.
Referenced by AsGeobuf.operation().
{
                     /*ByteArrayOutputStream output=new ByteArrayOutputStream();
                     GeobufEncoder enc=new GeobufEncoder(output,geometry.getPrecisionModel().getMaximumSignificantDigits());
                     return enc.geomToGeobuf(geometry).toString();*/
                 return "";
             }
Member Data Documentation
INSTANCE
final GeobufDatatype INSTANCE = new GeobufDatatype() static
A static instance of WKTDatatype.
Referenced by LiteralRegistry.LiteralRegistry(), and AsGeobuf.operation().
URI
final String URI = POSTGIS.GeoBuf static
The default WKT type URI.
Referenced by LiteralRegistry.LiteralRegistry().