rdf4j-postgis: PolyshapeDatatype Class Reference
PolyshapeDatatype Class Reference
Public Member Functions
String unparse (Geometry geometry)
This method Un-parses the JTS Geometry to the WKT literal.
Geometry read (String geometryLiteral)
Static Public Attributes
static final String URI = POSTGIS.Polyshape
The default WKT type URI.
static final PolyshapeDatatype INSTANCE = new PolyshapeDatatype()
A static instance of WKTDatatype.
Static Private Attributes
static final PolyshapeReader reader =new PolyshapeReader()
static final JtsPolyshapeWriter writer =new JtsPolyshapeWriter()
Member Function Documentation
read()
Geometry read (String geometryLiteral)
References PolyshapeReader.read().
{
         try {
                         return reader.read(geometryLiteral);
                 } catch (IOException | ParseException e) {
                         throw new RuntimeException(e.getMessage());
                 }
     }
unparse()
String unparse (Geometry geometry)
This method Un-parses the JTS Geometry to the WKT literal.
Parameters
geometry - the JTS Geometry to be un-parsed
Returns
WKT - the returned WKT Literal.
Notice that the Spatial Reference System is not specified in returned WKT literal.
References PolyshapeWriter.toString().
{
             return writer.toString(geometry);
     }
Member Data Documentation
INSTANCE
final PolyshapeDatatype INSTANCE = new PolyshapeDatatype() static
A static instance of WKTDatatype.
Referenced by LiteralRegistry.LiteralRegistry().
reader
final PolyshapeReader reader =new PolyshapeReader() static private
URI
final String URI = POSTGIS.Polyshape static
The default WKT type URI.
Referenced by LiteralRegistry.LiteralRegistry().
writer
final JtsPolyshapeWriter writer =new JtsPolyshapeWriter() static private