rdf4j-postgis: VectorTileDecoder Class Reference
VectorTileDecoder Class Reference
Classes
class Feature
class FeatureIterable
class FeatureIterator
Public Member Functions
boolean isAutoScale ()
Get the autoScale setting.
void setAutoScale (boolean autoScale)
Set the autoScale setting.
FeatureIterable decode (byte[] data) throws IOException
FeatureIterable decode (byte[] data, String layerName) throws IOException
FeatureIterable decode (byte[] data, Set< String > layerNames) throws IOException
FeatureIterable decode (byte[] data, Filter filter) throws IOException
Static Package Functions
static int zigZagDecode (int n)
Private Attributes
boolean autoScale = true
Member Function Documentation
decode() [1/4]
FeatureIterable decode (byte [] data) throws IOException
Referenced by VectorTileDecoder.decode(), and MVTDatatype.read().
{
         return decode(data, Filter.ALL);
     }
decode() [2/4]
FeatureIterable decode (byte [] data, String layerName) throws IOException
References VectorTileDecoder.decode().
{
         return decode(data, new Filter.Single(layerName));
     }
decode() [3/4]
FeatureIterable decode (byte [] data, Set< String > layerNames) throws IOException
References VectorTileDecoder.decode().
{
         return decode(data, new Filter.Any(layerNames));
     }
decode() [4/4]
FeatureIterable decode (byte [] data, Filter filter) throws IOException
{
         VectorTile.Tile tile = VectorTile.Tile.parseFrom(data);
         return new FeatureIterable(tile, filter, autoScale);
     }
isAutoScale()
boolean isAutoScale ()
Get the autoScale setting.
Returns
autoScale
References VectorTileDecoder.autoScale.
{
             return autoScale;
     }
setAutoScale()
void setAutoScale (boolean autoScale)
Set the autoScale setting.
Parameters
autoScale when true, the encoder automatically scale and return all coordinates in the 0..255 range. when false, the encoder returns all coordinates in the 0..extent-1 range as they are encoded.
References VectorTileDecoder.autoScale.
{
         this.autoScale = autoScale;
     }
zigZagDecode()
static int zigZagDecode (int n) static package
Referenced by VectorTileDecoder.FeatureIterator.parseFeature().
{
         return ((n >> 1) ^ (-(n & 1)));
     }
Member Data Documentation
autoScale
boolean autoScale = true private
Referenced by VectorTileDecoder.isAutoScale(), and VectorTileDecoder.setAutoScale().