rdf4j-postgis: Coordinate.DimensionalComparator Class Reference
Coordinate.DimensionalComparator Class Reference
Compares two Coordinates, allowing for either a 2-dimensional or 3-dimensional comparison, and handling NaN values correctly.
Public Member Functions
DimensionalComparator ()
Creates a comparator for 2 dimensional coordinates.
DimensionalComparator (int dimensionsToTest)
Creates a comparator for 2 or 3 dimensional coordinates, depending on the value provided.
int compare (Coordinate c1, Coordinate c2)
Compares two Coordinates along to the number of dimensions specified.
Static Public Member Functions
static int compare (double a, double b)
Compare two doubles, allowing for NaN values.
Private Attributes
int dimensionsToTest = 2
Detailed Description
Compares two Coordinates, allowing for either a 2-dimensional or 3-dimensional comparison, and handling NaN values correctly.
Constructor & Destructor Documentation
DimensionalComparator() [1/2]
DimensionalComparator ()
Creates a comparator for 2 dimensional coordinates.
     {
       this(2);
     }
DimensionalComparator() [2/2]
DimensionalComparator (int dimensionsToTest)
Creates a comparator for 2 or 3 dimensional coordinates, depending on the value provided.
Parameters
dimensionsToTest the number of dimensions to test
References Coordinate.DimensionalComparator.dimensionsToTest.
     {
       if (dimensionsToTest != 2 && dimensionsToTest != 3)
         throw new IllegalArgumentException("only 2 or 3 dimensions may be specified");
       this.dimensionsToTest = dimensionsToTest;
     }
Member Function Documentation
compare() [1/2]
static int compare (double a, double b) static
Compare two doubles, allowing for NaN values.
NaN is treated as being less than any valid number.
Parameters
a a double
b a double
Returns
-1, 0, or 1 depending on whether a is less than, equal to or greater than b
Referenced by Coordinate.DimensionalComparator.compare().
     {
       if (a < b) return -1;
       if (a > b) return 1;
       if (Double.isNaN(a)) {
         if (Double.isNaN(b)) return 0;
         return -1;
       }
       if (Double.isNaN(b)) return 1;
       return 0;
     }
compare() [2/2]
int compare (Coordinate c1, Coordinate c2)
Compares two Coordinates along to the number of dimensions specified.
Parameters
o1 a Coordinate
o2 a {link Coordinate}
Returns
-1, 0, or 1 depending on whether o1 is less than, equal to, or greater than 02
References Coordinate.DimensionalComparator.compare(), Coordinate.getZ(), Coordinate.x, and Coordinate.y.
     {
       int compX = compare(c1.x, c2.x);
       if (compX != 0) return compX;
       int compY = compare(c1.y, c2.y);
       if (compY != 0) return compY;
       if (dimensionsToTest <= 2) return 0;
       int compZ = compare(c1.getZ(), c2.getZ());
       return compZ;
     }
Member Data Documentation
dimensionsToTest
int dimensionsToTest = 2 private
Referenced by Coordinate.DimensionalComparator.DimensionalComparator().