rdf4j-postgis: GMLCOVDatatype Class Reference
GMLCOVDatatype Class Reference
Public Member Functions
GridCoverage read (String geometryLiteral)
String unparse (GridCoverage geom)
Static Public Attributes
static final String URI =POSTGIS.NAMESPACE+POSTGIS.GMLCOV
static final GMLCOVDatatype INSTANCE =new GMLCOVDatatype()
static final IRI LiteralIRI =SimpleValueFactory.getInstance().createIRI(POSTGIS.NAMESPACE+POSTGIS.GMLCOV)
Member Function Documentation
read()
GridCoverage read (String geometryLiteral)
Referenced by RastFromGMLCOV.construct(), and RastFromNetCDF.construct().
{
                 // TODO Auto-generated method stub
                 return null;
         }
unparse()
String unparse (GridCoverage geom)
Referenced by AsGMLCOV.operation(), and AsNetCDF.operation().
{
                 // TODO Auto-generated method stub
                 return null;
         }
Member Data Documentation
INSTANCE
final GMLCOVDatatype INSTANCE =new GMLCOVDatatype() static
Referenced by RastFromGMLCOV.construct(), LiteralRegistry.LiteralRegistry(), and AsGMLCOV.operation().
LiteralIRI
final IRI LiteralIRI =SimpleValueFactory.getInstance().createIRI(POSTGIS.NAMESPACE+POSTGIS.GMLCOV) static
URI
final String URI =POSTGIS.NAMESPACE+POSTGIS.GMLCOV static
Referenced by LiteralRegistry.LiteralRegistry().