rdf4j-postgis: PolyshapeReader Class Reference
PolyshapeReader Class Reference
Classes
class XReader
from Apache 2.0 licensed: https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/PolyUtil.java
Public Member Functions
String getFormatName ()
Geometry read (Object value) throws IOException, ParseException
Geometry readIfSupported (Object value)
final Geometry read (Reader r) throws ParseException, IOException
Protected Member Functions
Geometry readPolygon (XReader reader) throws IOException
Package Attributes
final GeometryFactory shpFactory =new GeometryFactory()
Detailed Description
See also
PolyshapeWriter
Member Function Documentation
getFormatName()
String getFormatName ()
{
     return "PolyShape";
   }
read() [1/2]
Geometry read (Object value) throws IOException, ParseException
Referenced by PolyshapeDatatype.read(), and PolyshapeReader.readIfSupported().
{
     return read(new StringReader(value.toString().trim()));
   }
read() [2/2]
final Geometry read (Reader r) throws ParseException, IOException
References PolyshapeReader.XReader.isDone(), PolyshapeReader.XReader.isEvent(), PolyshapeWriter.KEY_ARG_END, PolyshapeWriter.KEY_ARG_START, PolyshapeWriter.KEY_CIRCLE, PolyshapeWriter.KEY_LINE, PolyshapeWriter.KEY_MULTIPOINT, PolyshapeWriter.KEY_POINT, PolyshapeWriter.KEY_POLYGON, PolyshapeWriter.KEY_SEPERATOR, PolyshapeReader.XReader.peek(), PolyshapeReader.XReader.readDouble(), PolyshapeReader.XReader.readKey(), PolyshapeReader.XReader.readLat(), PolyshapeReader.XReader.readLng(), PolyshapeReader.XReader.readPoints(), and PolyshapeReader.readPolygon().
   {
     XReader reader = new XReader(r, shpFactory);
     Double arg = null;
     GeometryFactory fac=new GeometryFactory();
     Geometry lastShape = null;
     List<Geometry> shapes = null;
     while(!reader.isDone()) {
       char event = reader.readKey();
       if(event<'0' || event > '9') {
         if(event == PolyshapeWriter.KEY_SEPERATOR) {
           continue; // read the next key
         }
         throw new ParseException("expecting a shape key.  not '"+event+"'", -1);
       }
       if(lastShape!=null) {
         if(shapes==null) {
           shapes = new ArrayList<Geometry>();
         }
         shapes.add(lastShape);
       }
       arg = null;
       if(reader.peek()==PolyshapeWriter.KEY_ARG_START) {
         reader.readKey(); // skip the key
         arg = reader.readDouble();
         if(reader.readKey()!=PolyshapeWriter.KEY_ARG_END) {
           throw new ParseException("expecting an argument end", -1);
         }
       }
       if(reader.isEvent()) {
         throw new ParseException("Invalid input. Event should be followed by data", -1);
       }
       switch(event) {
         case PolyshapeWriter.KEY_POINT: {
           lastShape = shpFactory.createPoint(new Coordinate(reader.readLat(),reader.readLng()));
           break;
         }
         case PolyshapeWriter.KEY_LINE: {
           //reader.readPoints(builder)
           lastShape=fac.createLineString(reader.readPoints());
           //GeometryFactory.LineStringBuilder lineBuilder = shpFactory.lineString();
           //if(arg!=null) {
             //lineBuilder.buffer(shpFactory.normDist(arg));
           //}
           //lastShape = lineBuilder.build();
           break;
         }
         /*case PolyshapeWriter.KEY_BOX: {
           double lat1 = reader.readLat();
           double lon1 = reader.readLng();
           double lat2= reader.readLat();
           double lon2= reader.readLng();
           lastShape=new Envelope(lat1, lon1, lat2, lon2).;
           break;
         }*/
         case PolyshapeWriter.KEY_MULTIPOINT : {
                 lastShape=fac.createMultiPoint(reader.readPoints());
           break;
         }
         case PolyshapeWriter.KEY_CIRCLE : {
           if(arg==null) {
             throw new IllegalArgumentException("the input should have a radius argument");
           }
           GeometricShapeFactory fac2=new GeometricShapeFactory();
           fac2.setCentre(new Coordinate(reader.readLat(),reader.readLng()));
           fac2.setWidth(arg.doubleValue());
           lastShape=fac2.createCircle();
           /*Polygon circle=fac2.createCircle();
           circle.
           fac.createLinearRing(coordinates)
           lastShape = shpFactory.circle(shpFactory.normX(reader.readLat()), shpFactory.normY(reader.readLng()),
                 shpFactory.normDist(arg.doubleValue()));*/
           break;
         }
         case PolyshapeWriter.KEY_POLYGON: {
           lastShape = readPolygon(reader);
           break;
         }
         default: {
           throw new ParseException("unhandled key: "+event, -1);
         }
       }
     }
     if(shapes!=null) {
       if(lastShape!=null) {
         shapes.add(lastShape);
       }
       if(!shapes.isEmpty() && shapes.get(0)!=null) {
           if(shapes.get(0) instanceof Point) {
                   return fac.createMultiPoint(GeometryFactory.toPointArray(shapes));
           }else if(shapes.get(0) instanceof LineString) {
                   return fac.createMultiLineString(GeometryFactory.toLineStringArray(shapes));
           }else if(shapes.get(0) instanceof Polygon) {
                   return fac.createMultiPolygon(GeometryFactory.toPolygonArray(shapes));
           }
       }
     }
     return lastShape;
   }
readIfSupported()
Geometry readIfSupported (Object value)
References PolyshapeReader.read().
{
     String v = value.toString().trim();
     char first = v.charAt(0);
     if(first >= '0' && first <= '9') {
       try {
         return read(new StringReader(v));
       } catch (ParseException e) {
       } catch (IOException e) {
       }
     }
     return null;
   }
readPolygon()
Geometry readPolygon (XReader reader) throws IOException protected
Referenced by PolyshapeReader.read().
{
     //Geometry.PolygonBuilder polyBuilder = shpFactory.polygon();
     GeometryFactory fac=new GeometryFactory();
     Polygon poly=fac.createPolygon(reader.readPoints());
     //reader.readPoints(polyBuilder);
     /*if(!reader.isDone() && reader.peek()==PolyshapeWriter.KEY_ARG_START) {
       List<LinearRing> list = new ArrayList<LinearRing>();
       while(reader.isEvent() && reader.peek()==PolyshapeWriter.KEY_ARG_START) {
         reader.readKey(); // eat the event;
         reader.readPoints(polyBuilder.hole()).endHole();
       }
     }
     return polyBuilder.build();*/
     return poly;
   }
Member Data Documentation
shpFactory
final GeometryFactory shpFactory =new GeometryFactory() package