rdf4j-postgis: RasterVectorRelationBinaryFunction Class Reference
RasterVectorRelationBinaryFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract Boolean relation (Value v1, Value v2)
Static Public Member Functions
static Boolean vectorOrRaster (Literal lit)
static Literal getLiteral (Function func, Value v) throws ValueExprEvaluationException
Static Public Attributes
static Set< String > rasterLiteralURIs =new TreeSet<String>()
static Set< String > vectorLiteralURIs =new TreeSet<String>()
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
References RasterVectorRelationBinaryFunction.relation().
Referenced by EqualTest.testAdd().
{
                 // TODO Auto-generated method stub
                 return null;
         }
getLiteral()
static Literal getLiteral (Function func, Value v) throws ValueExprEvaluationException static
Referenced by Contains.relation(), Within.relation(), Touches.relation(), Crosses.relation(), Intersects.relation(), Equals.relation(), Disjoint.relation(), Overlaps.relation(), CoveredBy.relation(), and ContainsProperly.relation().
{
                 if (!(v instanceof Literal)) {
                         throw new ValueExprEvaluationException("Invalid argument for " + func.getURI() + ": " + v);
                 }
                 Literal lit = (Literal) v;
                 return lit;
         }
relation()
abstract Boolean relation (Value v1, Value v2) abstract
Referenced by RasterVectorRelationBinaryFunction.evaluate().
vectorOrRaster()
static Boolean vectorOrRaster (Literal lit) static
References LiteralRegistry.literals.
Referenced by Contains.relation(), Within.relation(), Touches.relation(), Crosses.relation(), Intersects.relation(), Equals.relation(), Disjoint.relation(), Overlaps.relation(), CoveredBy.relation(), and ContainsProperly.relation().
{
                 if(LiteralRegistry.literals.containsKey(lit.getDatatype().toString())) {
                         LiteralType lite=LiteralRegistry.literals.get(lit.getDatatype().toString());
                         if(lite instanceof VectorLiteral) {
                                 return true;
                         }else if(lite instanceof RasterLiteral) {
                                 return false;
                         }
                 }
                 return null;
         }
Member Data Documentation
rasterLiteralURIs
Set<String> rasterLiteralURIs =new TreeSet<String>() static
vectorLiteralURIs
Set<String> vectorLiteralURIs =new TreeSet<String>() static