rdf4j-postgis: BoundaryTest Class Reference
BoundaryTest Class Reference
Public Member Functions
void testBoundary ()
Static Public Attributes
static final String testPolygon ="POLYGON ((0 0, 1 0, 1 1, 0.5 3.2e-4, 0 0))"
static final String result ="LINEARRING (0 0, 1 0, 1 1, 0.5 0.00032, 0 0)"
Member Function Documentation
testBoundary()
void testBoundary ()
{
                 Boundary instance=new Boundary();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(testPolygon, WKTDatatype.LiteralIRI);
                 Value resultt=instance.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral(result,WKTDatatype.LiteralIRI);
                 assertEquals(expResult, resultt);
         }
References GeometricUnaryFunction.evaluate(), WKTDatatype.LiteralIRI, BoundaryTest.result, and BoundaryTest.testPolygon.
Member Data Documentation
result
final String result ="LINEARRING (0 0, 1 0, 1 1, 0.5 0.00032, 0 0)" static
Referenced by BoundaryTest.testBoundary().
testPolygon
final String testPolygon ="POLYGON ((0 0, 1 0, 1 1, 0.5 3.2e-4, 0 0))" static
Referenced by BoundaryTest.testBoundary().