rdf4j-postgis: VectorTileEncoder Class Reference
VectorTileEncoder Class Reference
Classes
class Feature
class Layer
Public Member Functions
VectorTileEncoder ()
Create a VectorTileEncoder with the default extent of 4096 and clip buffer of 8.
VectorTileEncoder (int extent)
Create a VectorTileEncoder with the given extent and a clip buffer of 8.
VectorTileEncoder (int extent, int clipBuffer, boolean autoScale)
VectorTileEncoder (int extent, int clipBuffer, boolean autoScale, boolean autoincrementIds)
VectorTileEncoder (int extent, int clipBuffer, boolean autoScale, boolean autoincrementIds, double simplificationDistanceTolerance)
Create a VectorTileEncoder with the given extent value.
void addFeature (String layerName, Map< String, ?> attributes, Geometry geometry)
void addFeature (String layerName, Map< String, ?> attributes, Geometry geometry, long id)
Add a feature with layer name (typically feature type name), some attributes and a Geometry.
byte [] encode ()
Protected Member Functions
boolean clipCovers (Geometry geom)
A short circuit clip to the tile extent (tile boundary + buffer) for points to improve performance.
Geometry clipGeometry (Geometry geometry)
Clip geometry according to buffer given at construct time.
Package Functions
List< Integer > commands (Geometry geometry)
List< Integer > commands (MultiLineString mls)
List< Integer > commands (MultiPolygon mp)
List< Integer > commands (Polygon polygon)
List< Integer > commands (Coordinate[] cs, boolean closePathAtEnd)
// // // Ex.
List< Integer > commands (Coordinate[] cs, boolean closePathAtEnd, boolean multiPoint)
Static Package Functions
static VectorTile.Tile.GeomType toGeomType (Geometry geometry)
static boolean shouldClosePath (Geometry geometry)
static int commandAndLength (int command, int repeat)
static int zigZagEncode (int n)
Static Private Member Functions
static Geometry createTileEnvelope (int buffer, int size)
Private Attributes
final Map< String, Layer > layers = new LinkedHashMap<String, Layer>()
final int extent
final Geometry clipGeometry
final boolean autoScale
long autoincrement
final boolean autoincrementIds
final double simplificationDistanceTolerance
int x = 0
int y = 0
Constructor & Destructor Documentation
VectorTileEncoder() [1/5]
VectorTileEncoder ()
Create a VectorTileEncoder with the default extent of 4096 and clip buffer of 8.
{
         this(4096, 8, true);
     }
VectorTileEncoder() [2/5]
VectorTileEncoder (int extent)
Create a VectorTileEncoder with the given extent and a clip buffer of 8.
References VectorTileEncoder.extent.
{
         this(extent, 8, true);
     }
VectorTileEncoder() [3/5]
VectorTileEncoder (int extent, int clipBuffer, boolean autoScale)
References VectorTileEncoder.autoScale, and VectorTileEncoder.extent.
{
         this(extent, clipBuffer, autoScale, false);
     }
VectorTileEncoder() [4/5]
VectorTileEncoder (int extent, int clipBuffer, boolean autoScale, boolean autoincrementIds)
References VectorTileEncoder.autoincrementIds, VectorTileEncoder.autoScale, and VectorTileEncoder.extent.
{
         this(extent, clipBuffer, autoScale, autoincrementIds, -1.0);
     }
VectorTileEncoder() [5/5]
VectorTileEncoder (int extent, int clipBuffer, boolean autoScale, boolean autoincrementIds, double simplificationDistanceTolerance)
Create a VectorTileEncoder with the given extent value.
The extent value control how detailed the coordinates are encoded in the vector tile. 4096 is a good default, 256 can be used to reduce density.
The clip buffer value control how large the clipping area is outside of the tile for geometries. 0 means that the clipping is done at the tile border. 8 is a good default.
Parameters
extent a int with extent value. 4096 is a good value.
clipBuffer a int with clip buffer size for geometries. 8 is a good value.
autoScale when true, the encoder expects coordinates in the 0..255 range and will scale them automatically to the 0..extent-1 range before encoding. when false, the encoder expects coordinates in the 0..extent-1 range.
autoincrementIds
simplificationDistanceTolerance a positive double representing the distance tolerance to be used for non-points before (optional) scaling and encoding. A value <= 0 will prevent simplifying geometry. 0.1 seem to be a good value when autoScale is turned on.
References VectorTileEncoder.autoincrementIds, VectorTileEncoder.autoScale, VectorTileEncoder.createTileEnvelope(), VectorTileEncoder.extent, and VectorTileEncoder.simplificationDistanceTolerance.
{
         this.extent = extent;
         this.autoScale = autoScale;
         this.autoincrementIds = autoincrementIds;
         this.autoincrement = 1;
         this.simplificationDistanceTolerance = simplificationDistanceTolerance;
         final int size = autoScale ? 256 : extent;
         clipGeometry = createTileEnvelope(clipBuffer, size);
     }
Member Function Documentation
addFeature() [1/2]
void addFeature (String layerName, Map< String, ?> attributes, Geometry geometry)
Referenced by VectorTileEncoder.addFeature().
{
         this.addFeature(layerName, attributes, geometry, this.autoincrementIds ? this.autoincrement++ : -1);
     }
addFeature() [2/2]
void addFeature (String layerName, Map< String, ?> attributes, Geometry geometry, long id)
Add a feature with layer name (typically feature type name), some attributes and a Geometry.
The Geometry must be in "pixel" space 0,0 upper left and 256,256 lower right.
For optimization, geometries will be clipped and simplified. Features with geometries outside of the tile will be skipped.
Parameters
layerName
attributes
geometry
id
References VectorTileEncoder.addFeature(), VectorTileEncoder.clipCovers(), VectorTileEncoder.clipGeometry, VectorTileEncoder.Layer.features, VectorTileEncoder.Feature.geometry, VectorTileEncoder.Feature.id, VectorTileEncoder.Layer.key(), VectorTileEncoder.Feature.tags, and VectorTileEncoder.Layer.value().
{
         // skip small Polygon/LineString.
         if (geometry instanceof MultiPolygon && geometry.getArea() < 1.0d) {
             return;
         }
         if (geometry instanceof Polygon && geometry.getArea() < 1.0d) {
             return;
         }
         if (geometry instanceof LineString && geometry.getLength() < 1.0d) {
             return;
         }
         // special handling of GeometryCollection. subclasses are not handled here.
         if (geometry.getClass().equals(GeometryCollection.class)) {
             for (int i = 0; i < geometry.getNumGeometries(); i++) {
                 Geometry subGeometry = geometry.getGeometryN(i);
                 // keeping the id. any better suggestion?
                 addFeature(layerName, attributes, subGeometry, id);
             }
             return;
         }
         // clip geometry
         if (geometry instanceof Point) {
             if (!clipCovers(geometry)) {
                 return;
             }
         } else {
             geometry = clipGeometry(geometry);
         }
         // simplify non-points
         if (simplificationDistanceTolerance > 0.0 && !(geometry instanceof Point)) {
             geometry = TopologyPreservingSimplifier.simplify(geometry, simplificationDistanceTolerance);
         }
         // no need to add empty geometry
         if (geometry.isEmpty()) {
             return;
         }
         Layer layer = layers.get(layerName);
         if (layer == null) {
             layer = new Layer();
             layers.put(layerName, layer);
         }
         Feature feature = new Feature();
         feature.geometry = geometry;
         feature.id = id;
         this.autoincrement = Math.max(this.autoincrement, id + 1);
         for (Map.Entry<String, ?> e : attributes.entrySet()) {
             // skip attribute without value
             if (e.getValue() == null) {
                 continue;
             }
             feature.tags.add(layer.key(e.getKey()));
             feature.tags.add(layer.value(e.getValue()));
         }
         layer.features.add(feature);
     }
clipCovers()
boolean clipCovers (Geometry geom) protected
A short circuit clip to the tile extent (tile boundary + buffer) for points to improve performance.
This method can be overridden to change clipping behavior. See also clipGeometry(Geometry).
See also
https://github.com/ElectronicChartCentre/java-vector-tile/issues/13
Referenced by VectorTileEncoder.addFeature().
{
         if (geom instanceof Point) {
             Point p = (Point) geom;
             return clipGeometry.getEnvelopeInternal().covers(p.getCoordinate());
         }
         return clipGeometry.covers(geom);
     }
clipGeometry()
Geometry clipGeometry (Geometry geometry) protected
Clip geometry according to buffer given at construct time.
This method can be overridden to change clipping behavior. See also clipCovers(Geometry).
Parameters
geometry
Returns
{
         try {
             Geometry original = geometry;
             geometry = clipGeometry.intersection(original);
             // some times a intersection is returned as an empty geometry.
             // going via wkt fixes the problem.
             if (geometry.isEmpty() && original.intersects(clipGeometry)) {
                 Geometry originalViaWkt = new WKTReader().read(original.toText());
                 geometry = clipGeometry.intersection(originalViaWkt);
             }
             return geometry;
         } catch (TopologyException e) {
             // could not intersect. original geometry will be used instead.
             return geometry;
         } catch (ParseException e1) {
             // could not encode/decode WKT. original geometry will be used
             // instead.
             return geometry;
         }
     }
commandAndLength()
static int commandAndLength (int command, int repeat) static package
Referenced by VectorTileEncoder.commands().
{
         return repeat << 3 | command;
     }
commands() [1/6]
List<Integer> commands (Geometry geometry) package
References VectorTileEncoder.shouldClosePath().
Referenced by VectorTileEncoder.commands(), and VectorTileEncoder.encode().
{
         if (geometry instanceof MultiLineString) {
             return commands((MultiLineString) geometry);
         }
         if (geometry instanceof Polygon) {
             return commands((Polygon) geometry);
         }
         if (geometry instanceof MultiPolygon) {
             return commands((MultiPolygon) geometry);
         }
         return commands(geometry.getCoordinates(), shouldClosePath(geometry), geometry instanceof MultiPoint);
     }
commands() [2/6]
List<Integer> commands (MultiLineString mls) package
References VectorTileEncoder.commands().
{
         List<Integer> commands = new ArrayList<Integer>();
         for (int i = 0; i < mls.getNumGeometries(); i++) {
             commands.addAll(commands(mls.getGeometryN(i).getCoordinates(), false));
         }
         return commands;
     }
commands() [3/6]
List<Integer> commands (MultiPolygon mp) package
References VectorTileEncoder.commands().
{
         List<Integer> commands = new ArrayList<Integer>();
         for (int i = 0; i < mp.getNumGeometries(); i++) {
             Polygon polygon = (Polygon) mp.getGeometryN(i);
             commands.addAll(commands(polygon));
         }
         return commands;
     }
commands() [4/6]
List<Integer> commands (Polygon polygon) package
References VectorTileEncoder.commands().
{
         List<Integer> commands = new ArrayList<Integer>();
         // According to the vector tile specification, the exterior ring of a polygon
         // must be in clockwise order, while the interior ring in counter-clockwise order.
         // In the tile coordinate system, Y axis is positive down.
         //
         // However, in geographic coordinate system, Y axis is positive up.
         // Therefore, we must reverse the coordinates.
         // So, the code below will make sure that exterior ring is in counter-clockwise order
         // and interior ring in clockwise order.
         LineString exteriorRing = polygon.getExteriorRing();
         if (!CGAlgorithms.isCCW(exteriorRing.getCoordinates())) {
             exteriorRing = (LineString) exteriorRing.reverse();
         }
         commands.addAll(commands(exteriorRing.getCoordinates(), true));
         for (int i = 0; i < polygon.getNumInteriorRing(); i++) {
             LineString interiorRing = polygon.getInteriorRingN(i);
             if (CGAlgorithms.isCCW(interiorRing.getCoordinates())) {
                 interiorRing = (LineString) interiorRing.reverse();
             }
             commands.addAll(commands(interiorRing.getCoordinates(), true));
         }
         return commands;
     }
commands() [5/6]
List<Integer> commands (Coordinate [] cs, boolean closePathAtEnd) package
// // // Ex.
: MoveTo(3, 6), LineTo(8, 12), LineTo(20, 34), ClosePath // Encoded as: [ 9 3 6 18 5 6 12 22 15 ] // == command type 7 (ClosePath), length 1 // ===== relative LineTo(+12, +22) == LineTo(20, 34) // === relative LineTo(+5, +6) == LineTo(8, 12) // == [00010 010] = command type 2 (LineTo), length 2 // === relative MoveTo(+3, +6) // == [00001 001] = command type 1 (MoveTo), length 1 // Commands are encoded as uint32 varints, vertex parameters are // encoded as sint32 varints (zigzag). Vertex parameters are // also encoded as deltas to the previous position. The original // position is (0,0)
Parameters
cs
Returns
References VectorTileEncoder.commands().
{
         return commands(cs, closePathAtEnd, false);
     }
commands() [6/6]
List<Integer> commands (Coordinate [] cs, boolean closePathAtEnd, boolean multiPoint) package
References VectorTileEncoder.commandAndLength(), Coordinate.equals(), Coordinate.x, Coordinate.y, and VectorTileEncoder.zigZagEncode().
{
         if (cs.length == 0) {
             throw new IllegalArgumentException("empty geometry");
         }
         List<Integer> r = new ArrayList<Integer>();
         int lineToIndex = 0;
         int lineToLength = 0;
         double scale = autoScale ? (extent / 256.0) : 1.0;
         for (int i = 0; i < cs.length; i++) {
             Coordinate c = cs[i];
             if (i == 0) {
                 r.add(commandAndLength(Command.MoveTo, multiPoint ? cs.length : 1));
             }
             int _x = (int) Math.round(c.x * scale);
             int _y = (int) Math.round(c.y * scale);
             // prevent point equal to the previous
             if (i > 0 && _x == x && _y == y) {
                 lineToLength--;
                 continue;
             }
             // prevent double closing
             if (closePathAtEnd && cs.length > 1 && i == (cs.length - 1) && cs[0].equals(c)) {
                 lineToLength--;
                 continue;
             }
             // delta, then zigzag
             r.add(zigZagEncode(_x - x));
             r.add(zigZagEncode(_y - y));
             x = _x;
             y = _y;
             if (i == 0 && cs.length > 1 && !multiPoint) {
                 // can length be too long?
                 lineToIndex = r.size();
                 lineToLength = cs.length - 1;
                 r.add(commandAndLength(Command.LineTo, lineToLength));
             }
         }
         // update LineTo length
         if (lineToIndex > 0) {
             if (lineToLength == 0) {
                 // remove empty LineTo
                 r.remove(lineToIndex);
             } else {
                 // update LineTo with new length
                 r.set(lineToIndex, commandAndLength(Command.LineTo, lineToLength));
             }
         }
         if (closePathAtEnd) {
             r.add(commandAndLength(Command.ClosePath, 1));
         }
         return r;
     }
createTileEnvelope()
static Geometry createTileEnvelope (int buffer, int size) static private
Referenced by VectorTileEncoder.VectorTileEncoder().
{
         Coordinate[] coords = new Coordinate[5];
         coords[0] = new Coordinate(0 - buffer, size + buffer);
         coords[1] = new Coordinate(size + buffer, size + buffer);
         coords[2] = new Coordinate(size + buffer, 0 - buffer);
         coords[3] = new Coordinate(0 - buffer, 0 - buffer);
         coords[4] = coords[0];
         return new GeometryFactory().createPolygon(coords);
     }
encode()
byte [] encode ()
Returns
a byte array with the vector tile
References VectorTileEncoder.commands(), VectorTileEncoder.Layer.features, VectorTileEncoder.Feature.geometry, VectorTileEncoder.Feature.id, VectorTileEncoder.Layer.keys, VectorTileEncoder.Feature.tags, VectorTileEncoder.toGeomType(), VectorTileEncoder.Layer.values, VectorTileEncoder.x, and VectorTileEncoder.y.
{
         VectorTile.Tile.Builder tile = VectorTile.Tile.newBuilder();
         for (Map.Entry<String, Layer> e : layers.entrySet()) {
             String layerName = e.getKey();
             Layer layer = e.getValue();
             VectorTile.Tile.Layer.Builder tileLayer = VectorTile.Tile.Layer.newBuilder();
             tileLayer.setVersion(2);
             tileLayer.setName(layerName);
             tileLayer.addAllKeys(layer.keys());
             for (Object value : layer.values()) {
                 VectorTile.Tile.Value.Builder tileValue = VectorTile.Tile.Value.newBuilder();
                 if (value instanceof String) {
                     tileValue.setStringValue((String) value);
                 } else if (value instanceof Integer) {
                     tileValue.setSintValue(((Integer) value).intValue());
                 } else if (value instanceof Long) {
                     tileValue.setSintValue(((Long) value).longValue());
                 } else if (value instanceof Float) {
                     tileValue.setFloatValue(((Float) value).floatValue());
                 } else if (value instanceof Double) {
                     tileValue.setDoubleValue(((Double) value).doubleValue());
                 } else if (value instanceof Boolean) {
                     tileValue.setBoolValue(((Boolean) value).booleanValue());
                 } else {
                     tileValue.setStringValue(value.toString());
                 }
                 tileLayer.addValues(tileValue.build());
             }
             tileLayer.setExtent(extent);
             for (Feature feature : layer.features) {
                 Geometry geometry = feature.geometry;
                 VectorTile.Tile.Feature.Builder featureBuilder = VectorTile.Tile.Feature.newBuilder();
                 featureBuilder.addAllTags(feature.tags);
                 if (feature.id >= 0) {
                     featureBuilder.setId(feature.id);
                 }
                 featureBuilder.setType(toGeomType(geometry));
                 x = 0;
                 y = 0;
                 featureBuilder.addAllGeometry(commands(geometry));
                 tileLayer.addFeatures(featureBuilder.build());
             }
             tile.addLayers(tileLayer.build());
         }
         return tile.build().toByteArray();
     }
shouldClosePath()
static boolean shouldClosePath (Geometry geometry) static package
Referenced by VectorTileEncoder.commands().
{
         return (geometry instanceof Polygon) || (geometry instanceof LinearRing);
     }
toGeomType()
static VectorTile.Tile.GeomType toGeomType (Geometry geometry) static package
Referenced by VectorTileEncoder.encode().
{
         if (geometry instanceof Point) {
             return VectorTile.Tile.GeomType.POINT;
         }
         if (geometry instanceof MultiPoint) {
             return VectorTile.Tile.GeomType.POINT;
         }
         if (geometry instanceof LineString) {
             return VectorTile.Tile.GeomType.LINESTRING;
         }
         if (geometry instanceof MultiLineString) {
             return VectorTile.Tile.GeomType.LINESTRING;
         }
         if (geometry instanceof Polygon) {
             return VectorTile.Tile.GeomType.POLYGON;
         }
         if (geometry instanceof MultiPolygon) {
             return VectorTile.Tile.GeomType.POLYGON;
         }
         return VectorTile.Tile.GeomType.UNKNOWN;
     }
zigZagEncode()
static int zigZagEncode (int n) static package
Referenced by VectorTileEncoder.commands().
{
         // https://developers.google.com/protocol-buffers/docs/encoding#types
         return (n << 1) ^ (n >> 31);
     }
Member Data Documentation
autoincrement
long autoincrement private
autoincrementIds
final boolean autoincrementIds private
Referenced by VectorTileEncoder.VectorTileEncoder().
autoScale
final boolean autoScale private
Referenced by VectorTileEncoder.VectorTileEncoder().
clipGeometry
final Geometry clipGeometry private
Referenced by VectorTileEncoder.addFeature().
extent
final int extent private
Referenced by VectorTileEncoder.VectorTileEncoder().
layers
final Map<String, Layer> layers = new LinkedHashMap<String, Layer>() private
simplificationDistanceTolerance
final double simplificationDistanceTolerance private
Referenced by VectorTileEncoder.VectorTileEncoder().
x
int x = 0 private
Referenced by VectorTileEncoder.encode().
y
int y = 0 private
Referenced by VectorTileEncoder.encode().