rdf4j-postgis: VectorTileEncoder.Layer Class Reference
VectorTileEncoder.Layer Class Reference
Public Member Functions
Integer key (String key)
List< String > keys ()
Integer value (Object value)
List< Object > values ()
Package Attributes
final List< Feature > features = new ArrayList<VectorTileEncoder.Feature>()
Private Attributes
final Map< String, Integer > keys = new LinkedHashMap<String, Integer>()
final Map< Object, Integer > values = new LinkedHashMap<Object, Integer>()
Member Function Documentation
key()
Integer key (String key)
Referenced by VectorTileEncoder.addFeature().
{
             Integer i = keys.get(key);
             if (i == null) {
                 i = Integer.valueOf(keys.size());
                 keys.put(key, i);
             }
             return i;
         }
keys()
List<String> keys ()
{
             return new ArrayList<String>(keys.keySet());
         }
value()
Integer value (Object value)
Referenced by VectorTileEncoder.addFeature().
{
             Integer i = values.get(value);
             if (i == null) {
                 i = Integer.valueOf(values.size());
                 values.put(value, i);
             }
             return i;
         }
values()
List<Object> values ()
{
             return Collections.unmodifiableList(new ArrayList<Object>(values.keySet()));
         }
Member Data Documentation
features
final List<Feature> features = new ArrayList<VectorTileEncoder.Feature>() package
Referenced by VectorTileEncoder.addFeature(), and VectorTileEncoder.encode().
keys
final Map<String, Integer> keys = new LinkedHashMap<String, Integer>() private
Referenced by VectorTileEncoder.encode().
values
final Map<Object, Integer> values = new LinkedHashMap<Object, Integer>() private
Referenced by VectorTileEncoder.encode().