rdf4j-postgis: Coordinate Class Reference
Coordinate Class Reference
A lightweight class used to store coordinates on the 2-dimensional Cartesian plane.
Classes
class DimensionalComparator
Compares two Coordinates, allowing for either a 2-dimensional or 3-dimensional comparison, and handling NaN values correctly.
Public Member Functions
Coordinate (double x, double y, double z)
Constructs a Coordinate at (x,y,z).
Coordinate ()
Constructs a Coordinate at (0,0,NaN).
Coordinate (Coordinate c)
Constructs a Coordinate having the same (x,y,z) values as other.
Coordinate (double x, double y)
Constructs a Coordinate at (x,y,NaN).
void setCoordinate (Coordinate other)
Sets this Coordinates (x,y,z) values to that of other.
double getX ()
Retrieves the value of the X ordinate.
void setX (double x)
Sets the X ordinate value.
double getY ()
Retrieves the value of the Y ordinate.
Date getT ()
void setY (double y)
Sets the Y ordinate value.
double getZ ()
Retrieves the value of the Z ordinate, if present.
void setZ (double z)
Sets the Z ordinate value.
void setT (Date t)
void setT (Long t)
double getM ()
Retrieves the value of the measure, if present.
void setM (double m)
Sets the measure value, if supported.
double getOrdinate (int ordinateIndex)
Gets the ordinate value for the given index.
void setOrdinate (int ordinateIndex, double value)
Sets the ordinate for the given index to a given value.
boolean equals2D (Coordinate other)
Returns whether the planar projections of the two Coordinates are equal.
boolean equals2D (Coordinate c, double tolerance)
Tests if another Coordinate has the same values for the X and Y ordinates, within a specified tolerance value.
boolean equals3D (Coordinate other)
Tests if another coordinate has the same values for the X, Y and Z ordinates.
boolean equalInZ (Coordinate c, double tolerance)
Tests if another coordinate has the same value for Z, within a tolerance.
boolean equals (Object other)
Returns true if other has the same values for the x and y ordinates.
int compareTo (Coordinate o)
Compares this Coordinate with the specified Coordinate for order.
String toString ()
Returns a String of the form (x,y,z) .
Object clone ()
Coordinate copy ()
Creates a copy of this Coordinate.
double distance (Coordinate c)
Computes the 2-dimensional Euclidean distance to another location.
double distance3D (Coordinate c)
Computes the 3-dimensional Euclidean distance to another location.
int hashCode ()
Gets a hashcode for this coordinate.
Static Public Member Functions
static int hashCode (double x)
Computes a hash code for a double value, using the algorithm from Joshua Bloch's book Effective Java"
Public Attributes
double x
The x-ordinate.
double y
The y-ordinate.
double z
The z-ordinate.
Date t =null
Static Public Attributes
static final double NULL_ORDINATE = Double.NaN
The value used to indicate a null or missing ordinate value.
static final int X = 0
Standard ordinate index value for, where X is 0.
static final int Y = 1
Standard ordinate index value for, where Y is 1.
static final int T = 4
Standard ordinate index value for, where Y is 1.
static final int Z = 2
Standard ordinate index value for, where Z is 2.
static final int M = 3
Standard ordinate index value for, where M is 3.
Static Private Attributes
static final long serialVersionUID = 6683108902428366910L
Detailed Description
A lightweight class used to store coordinates on the 2-dimensional Cartesian plane.
It is distinct from Point, which is a subclass of Geometry. Unlike objects of type Point (which contain additional information such as an envelope, a precision model, and spatial reference system information), a Coordinate only contains ordinate values and accessor methods.
Coordinates are two-dimensional points, with an additional Z-ordinate. If an Z-ordinate value is not specified or not defined, constructed coordinates have a Z-ordinate of NaN (which is also the value of NULL_ORDINATE). The standard comparison functions ignore the Z-ordinate. Apart from the basic accessor functions, JTS supports only specific operations involving the Z-ordinate.
Implementations may optionally support Z-ordinate and M-measure values as appropriate for a CoordinateSequence. Use of getZ() and getM() accessors, or getOrdinate(int) are recommended.
Version
1.16
Constructor & Destructor Documentation
Coordinate() [1/4]
Coordinate (double x, double y, double z)
Constructs a Coordinate at (x,y,z).
Parameters
x the x-ordinate
y the y-ordinate
z the z-ordinate
References Coordinate.x, Coordinate.y, and Coordinate.z.
{
     this.x = x;
     this.y = y;
     this.z = z;
   }
Coordinate() [2/4]
Coordinate ()
Constructs a Coordinate at (0,0,NaN).
Referenced by Coordinate.clone(), Coordinate.compareTo(), and Coordinate.copy().
                       {
     this(0.0, 0.0);
   }
Coordinate() [3/4]
Coordinate (Coordinate c)
Constructs a Coordinate having the same (x,y,z) values as other.
Parameters
c the Coordinate to copy.
References Coordinate.getZ(), Coordinate.x, and Coordinate.y.
{
     this(c.x, c.y, c.getZ());
   }
Coordinate() [4/4]
Coordinate (double x, double y)
Constructs a Coordinate at (x,y,NaN).
Parameters
x the x-value
y the y-value
References Coordinate.NULL_ORDINATE, Coordinate.x, and Coordinate.y.
{
     this(x, y, NULL_ORDINATE);
   }
Member Function Documentation
clone()
Object clone ()
References Coordinate.clone(), and Coordinate.Coordinate().
Referenced by Coordinate.clone().
{
     try {
       Coordinate coord = (Coordinate) super.clone();
       return coord; // return the clone
     } catch (CloneNotSupportedException e) {
       Assert.shouldNeverReachHere(
           "this shouldn't happen because this class is Cloneable");
       return null;
     }
   }
compareTo()
int compareTo (Coordinate o)
Compares this Coordinate with the specified Coordinate for order.
This method ignores the z value when making the comparison. Returns:
-1 : this.x < other.x || ((this.x == other.x) && (this.y < other.y))
0 : this.x == other.x && this.y = other.y
1 : this.x > other.x || ((this.x == other.x) && (this.y > other.y))
Note: This method assumes that ordinate values are valid numbers. NaN values are not handled correctly.
Parameters
o the Coordinate with which this Coordinate is being compared
Returns
-1, zero, or 1 as this Coordinate is less than, equal to, or greater than the specified Coordinate
References Coordinate.Coordinate(), Coordinate.x, and Coordinate.y.
{
     Coordinate other = (Coordinate) o;
     if (x < other.x) return -1;
     if (x > other.x) return 1;
     if (y < other.y) return -1;
     if (y > other.y) return 1;
     return 0;
   }
copy()
Coordinate copy ()
Creates a copy of this Coordinate.
Returns
a copy of this coordinate.
References Coordinate.Coordinate().
{
     return new Coordinate(this);
   }
distance()
double distance (Coordinate c)
Computes the 2-dimensional Euclidean distance to another location.
The Z-ordinate is ignored.
Parameters
c a point
Returns
the 2-dimensional Euclidean distance between the locations
References Coordinate.x, and Coordinate.y.
Referenced by IsEquilateralTriangle.attribute(), IsIsocelesTriangle.attribute(), LocatePoint.compute(), LocatePoint.pointAlongSegment(), FurthestCoordinate.relation(), and LongestLine.relation().
{
     double dx = x - c.x;
     double dy = y - c.y;
     return Math.sqrt(dx * dx + dy * dy);
   }
distance3D()
double distance3D (Coordinate c)
Computes the 3-dimensional Euclidean distance to another location.
Parameters
c a coordinate
Returns
the 3-dimensional Euclidean distance between the locations
References Coordinate.getZ(), Coordinate.x, and Coordinate.y.
{
     double dx = x - c.x;
     double dy = y - c.y;
     double dz = getZ() - c.getZ();
     return Math.sqrt(dx * dx + dy * dy + dz * dz);
   }
equalInZ()
boolean equalInZ (Coordinate c, double tolerance)
Tests if another coordinate has the same value for Z, within a tolerance.
Parameters
c a coordinate
tolerance the tolerance value
Returns
true if the Z ordinates are within the given tolerance
References Coordinate.getZ().
{
     return NumberUtil.equalsWithTolerance(this.getZ(), c.getZ(), tolerance);
   }
equals()
boolean equals (Object other)
Returns true if other has the same values for the x and y ordinates.
Since Coordinates are 2.5D, this routine ignores the z value when making the comparison.
Parameters
other a Coordinate with which to do the comparison.
Returns
true if other is a Coordinate with the same values for the x and y ordinates.
References Coordinate.equals2D().
Referenced by VectorTileEncoder.commands().
{
     if (!(other instanceof Coordinate)) {
       return false;
     }
     return equals2D((Coordinate) other);
   }
equals2D() [1/2]
boolean equals2D (Coordinate other)
Returns whether the planar projections of the two Coordinates are equal.
Parameters
other a Coordinate with which to do the 2D comparison.
Returns
true if the x- and y-coordinates are equal; the z-coordinates do not have to be equal.
References Coordinate.x, and Coordinate.y.
Referenced by Coordinate.equals().
{
     if (x != other.x) {
       return false;
     }
     if (y != other.y) {
       return false;
     }
     return true;
   }
equals2D() [2/2]
boolean equals2D (Coordinate c, double tolerance)
Tests if another Coordinate has the same values for the X and Y ordinates, within a specified tolerance value.
The Z ordinate is ignored.
Parameters
c a Coordinate with which to do the 2D comparison.
tolerance the tolerance value to use
Returns
true if other is a Coordinate with the same values for X and Y.
References Coordinate.x, and Coordinate.y.
{
     if (! NumberUtil.equalsWithTolerance(this.x, c.x, tolerance)) {
       return false;
     }
     if (! NumberUtil.equalsWithTolerance(this.y, c.y, tolerance)) {
       return false;
     }
     return true;
   }
equals3D()
boolean equals3D (Coordinate other)
Tests if another coordinate has the same values for the X, Y and Z ordinates.
Parameters
other a Coordinate with which to do the 3D comparison.
Returns
true if other is a Coordinate with the same values for X, Y and Z.
References Coordinate.getZ(), Coordinate.x, and Coordinate.y.
{
     return (x == other.x) && (y == other.y) &&
                ((getZ() == other.getZ()) ||
                (Double.isNaN(getZ()) && Double.isNaN(other.getZ())));
   }
getM()
double getM ()
Retrieves the value of the measure, if present.
If no measure value is present returns NaN.
Returns
the value of the measure, or NaN
Referenced by NDims.attribute(), TWKBWriter.ExtendedPrecisionWriter.checkCoordinate(), Zmflag.operation(), and TWKBWriter.write().
{
     return Double.NaN;
   }
getOrdinate()
double getOrdinate (int ordinateIndex)
Gets the ordinate value for the given index.
The base implementation supports values for the index are X, Y, and Z.
Parameters
ordinateIndex the ordinate index
Returns
the value of the ordinate
Exceptions
IllegalArgumentException if the index is not valid
References Coordinate.getZ(), Coordinate.X, Coordinate.x, Coordinate.Y, Coordinate.y, and Coordinate.Z.
   {
     switch (ordinateIndex) {
     case X: return x;
     case Y: return y;
     case Z: return getZ(); // sure to delegate to subclass rather than offer direct field access
     }
     throw new IllegalArgumentException("Invalid ordinate index: " + ordinateIndex);
   }
getT()
Date getT ()
References Coordinate.t.
                      {
       return t;
   }
getX()
double getX ()
Retrieves the value of the X ordinate.
Returns
the value of the X ordinate
References Coordinate.x.
Referenced by TWKBWriter.PrecisionWriter.checkCoordinate(), and IsRightTriangle.getLength().
{
     return x;
   }
getY()
double getY ()
Retrieves the value of the Y ordinate.
Returns
the value of the Y ordinate
References Coordinate.y.
Referenced by TWKBWriter.PrecisionWriter.checkCoordinate(), and IsRightTriangle.getLength().
{
       return y;
   }
getZ()
double getZ ()
Retrieves the value of the Z ordinate, if present.
If no Z value is present returns NaN.
Returns
the value of the Z ordinate, or NaN
References Coordinate.z.
Referenced by NDims.attribute(), TWKBWriter.ExtendedPrecisionWriter.checkCoordinate(), Coordinate.DimensionalComparator.compare(), Coordinate.Coordinate(), Coordinate.distance3D(), Coordinate.equalInZ(), Coordinate.equals3D(), Coordinate.getOrdinate(), Zmflag.operation(), Coordinate.setCoordinate(), Coordinate.toString(), and TWKBWriter.write().
{
       return z;
   }
hashCode() [1/2]
int hashCode ()
Gets a hashcode for this coordinate.
Returns
a hashcode for this coordinate
{
     //Algorithm from Effective Java by Joshua Bloch [Jon Aquino]
     int result = 17;
     result = 37 * result + hashCode(x);
     result = 37 * result + hashCode(y);
     return result;
   }
hashCode() [2/2]
static int hashCode (double x) static
Computes a hash code for a double value, using the algorithm from Joshua Bloch's book Effective Java"
Parameters
x the value to compute for
Returns
a hashcode for x
{
     long f = Double.doubleToLongBits(x);
     return (int)(f^(f>>>32));
   }
setCoordinate()
void setCoordinate (Coordinate other)
Sets this Coordinates (x,y,z) values to that of other.
Parameters
other the Coordinate to copy
References Coordinate.getZ(), Coordinate.x, and Coordinate.y.
{
     x = other.x;
     y = other.y;
     z = other.getZ();
   }
setM()
void setM (double m)
Sets the measure value, if supported.
Parameters
m the value to set as M
Referenced by TWKBReader.ExtendedPrecisionReader.readPoint(), and TWKBReader.ExtendedPrecisionReader.readPointArray().
{
     throw new IllegalArgumentException("Invalid ordinate index: " + M);
   }
setOrdinate()
void setOrdinate (int ordinateIndex, double value)
Sets the ordinate for the given index to a given value.
The base implementation supported values for the index are X, Y, and Z.
Parameters
ordinateIndex the ordinate index
value the value to set
Exceptions
IllegalArgumentException if the index is not valid
References Coordinate.setZ(), Coordinate.X, Coordinate.Y, and Coordinate.Z.
   {
     switch (ordinateIndex) {
       case X:
         x = value;
         break;
       case Y:
         y = value;
         break;
       case Z:
         setZ(value); // delegate to subclass rather than offer direct field access
         break;
       default:
         throw new IllegalArgumentException("Invalid ordinate index: " + ordinateIndex);
     }
   }
setT() [1/2]
void setT (Date t)
References Coordinate.t.
{
             this.t = t;
   }
setT() [2/2]
void setT (Long t)
{
             this.t = new Date(t);
 }
setX()
void setX (double x)
Sets the X ordinate value.
Parameters
x the value to set as X
References Coordinate.x.
{
     this.x = x;
   }
setY()
void setY (double y)
Sets the Y ordinate value.
Parameters
y the value to set as Y
References Coordinate.y.
{
     this.y = y;
   }
setZ()
void setZ (double z)
Sets the Z ordinate value.
Parameters
z the value to set as Z
References Coordinate.z.
Referenced by TWKBReader.ExtendedPrecisionReader.readPoint(), TWKBReader.ExtendedPrecisionReader.readPointArray(), and Coordinate.setOrdinate().
{
     this.z = z;
   }
toString()
String toString ()
Returns a String of the form (x,y,z) .
Returns
a String of the form (x,y,z)
References Coordinate.getZ().
Referenced by AsOSMLink.operation().
{
     return "(" + x + ", " + y + ", " + getZ() + ")";
   }
Member Data Documentation
M
final int M = 3 static
Standard ordinate index value for, where M is 3.
This constant assumes XYZM coordinate sequence definition, please check this assumption using getDimension() and getMeasures() before use.
NULL_ORDINATE
final double NULL_ORDINATE = Double.NaN static
The value used to indicate a null or missing ordinate value.
In particular, used for the value of ordinates for dimensions greater than the defined dimension of a coordinate.
Referenced by Coordinate.Coordinate().
serialVersionUID
final long serialVersionUID = 6683108902428366910L static private
T
final int T = 4 static
Standard ordinate index value for, where Y is 1.
t
Date t =null
Referenced by Coordinate.getT(), and Coordinate.setT().
X
final int X = 0 static
Standard ordinate index value for, where X is 0.
Referenced by Coordinate.getOrdinate(), and Coordinate.setOrdinate().
x
double x
The x-ordinate.
Referenced by RasterToWorldCoordX.attribute(), WorldToRasterCoordX.attribute(), VectorTileEncoder.commands(), Coordinate.DimensionalComparator.compare(), Coordinate.compareTo(), Coordinate.Coordinate(), Coordinate.distance(), Coordinate.distance3D(), Coordinate.equals2D(), Coordinate.equals3D(), Angle.findAngle(), GeometricMedian.getGeoMedian(), Coordinate.getOrdinate(), Coordinate.getX(), IsConvex.isConvex(), LineLength3D.length3D(), AsOSMLink.operation(), LocatePoint.pointAlongSegment(), LocatePoint.pointAlongSegmentByFraction(), ManhattanDistance.relation(), Coordinate.setCoordinate(), and Coordinate.setX().
Y
final int Y = 1 static
Standard ordinate index value for, where Y is 1.
Referenced by Coordinate.getOrdinate(), and Coordinate.setOrdinate().
y
double y
The y-ordinate.
Referenced by RasterToWorldCoordY.attribute(), WorldToRasterCoordY.attribute(), VectorTileEncoder.commands(), Coordinate.DimensionalComparator.compare(), Coordinate.compareTo(), Coordinate.Coordinate(), Coordinate.distance(), Coordinate.distance3D(), Coordinate.equals2D(), Coordinate.equals3D(), Angle.findAngle(), GeometricMedian.getGeoMedian(), Coordinate.getOrdinate(), Coordinate.getY(), IsConvex.isConvex(), LineLength3D.length3D(), AsOSMLink.operation(), LocatePoint.pointAlongSegment(), LocatePoint.pointAlongSegmentByFraction(), ManhattanDistance.relation(), Coordinate.setCoordinate(), and Coordinate.setY().
Z
final int Z = 2 static
Standard ordinate index value for, where Z is 2.
This constant assumes XYZM coordinate sequence definition, please check this assumption using getDimension() and getMeasures() before use.
Referenced by Coordinate.getOrdinate(), and Coordinate.setOrdinate().
z
double z
The z-ordinate.
Direct access to this field is discouraged; use getZ().
Referenced by Coordinate.Coordinate(), Coordinate.getZ(), LineLength3D.length3D(), and Coordinate.setZ().