rdf4j-postgis: AddPointTest Class Reference
AddPointTest Class Reference
Public Member Functions
void testAddPointZ ()
void testAddPoint ()
Static Public Attributes
static final String lineString ="LINESTRING (0 0 1, 1 1 1)"
static final String point ="POINT (1 2 3)"
Member Function Documentation
testAddPoint()
void testAddPoint ()
{
                 AddPoint instance=new AddPoint();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(lineString, WKTDatatype.LiteralIRI);
                 Value geo2=valfac.createLiteral(point, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo,geo2);
                 Value expResult=valfac.createLiteral("LINESTRING (0 0, 1 1, 1 2)", WKTDatatype.LiteralIRI);
                 assertEquals(expResult, result);
         }
References GeometricModifierFunction.evaluate(), AddPointTest.lineString, WKTDatatype.LiteralIRI, and AddPointTest.point.
testAddPointZ()
void testAddPointZ ()
{
                 AddPoint instance=new AddPoint();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(lineString, WKTDatatype.LiteralIRI);
                 Value geo2=valfac.createLiteral(point, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo,geo2);
                 Value expResult=valfac.createLiteral("LINESTRING (0 0 1, 1 1 1, 1 2 3)", WKTDatatype.LiteralIRI);
                 assertEquals(expResult, result);
         }
References GeometricModifierFunction.evaluate(), AddPointTest.lineString, WKTDatatype.LiteralIRI, and AddPointTest.point.
Member Data Documentation
lineString
final String lineString ="LINESTRING (0 0 1, 1 1 1)" static
Referenced by AddPointTest.testAddPoint(), and AddPointTest.testAddPointZ().
point
final String point ="POINT (1 2 3)" static
Referenced by AddPointTest.testAddPoint(), and AddPointTest.testAddPointZ().