rdf4j-postgis: EqualTypeTest Class Reference
EqualTypeTest Class Reference
Public Member Functions
void testEqual ()
void testNotEqual ()
Static Public Attributes
static final String testGeom ="LINESTRING(743238 2967416,743238 2967450,743265 2967450, 743265.625 2967416,743238 2967416)"
static final String testGeom2 ="MULTIPOINT (0 1, 1 0, 2 1)"
Member Function Documentation
testEqual()
void testEqual ()
{
                 EqualType instance=new EqualType();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(testGeom, WKTDatatype.LiteralIRI);
                 Value geo2=valfac.createLiteral(testGeom, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo,geo2);
                 Value expResult=valfac.createLiteral(true);
             assertEquals(expResult, result);
         }
References GeometricRelationBinaryFunction.evaluate(), WKTDatatype.LiteralIRI, and EqualTypeTest.testGeom.
testNotEqual()
void testNotEqual ()
{
                 EqualType instance=new EqualType();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(testGeom, WKTDatatype.LiteralIRI);
                 Value geo2=valfac.createLiteral(testGeom2, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo,geo2);
                 Value expResult=valfac.createLiteral(false);
             assertEquals(expResult, result);
         }
References GeometricRelationBinaryFunction.evaluate(), WKTDatatype.LiteralIRI, EqualTypeTest.testGeom, and EqualTypeTest.testGeom2.
Member Data Documentation
testGeom
final String testGeom ="LINESTRING(743238 2967416,743238 2967450,743265 2967450, 743265.625 2967416,743238 2967416)" static
Referenced by EqualTypeTest.testEqual(), and EqualTypeTest.testNotEqual().
testGeom2
final String testGeom2 ="MULTIPOINT (0 1, 1 0, 2 1)" static
Referenced by EqualTypeTest.testNotEqual().