rdf4j-postgis: PolyshapeWriter.Encoder Class Reference
PolyshapeWriter.Encoder Class Reference
Encodes a sequence of LatLngs into an encoded path string.
Public Member Functions
Encoder (Writer writer)
void seperator () throws IOException
void startRing () throws IOException
void write (char event) throws IOException
void writeArg (double value) throws IOException
void write (double latitude, double longitude) throws IOException
Package Attributes
long lastLat = 0
long lastLng = 0
final Writer writer
Private Member Functions
void encode (long v) throws IOException
Detailed Description
Encodes a sequence of LatLngs into an encoded path string.
from Apache 2.0 licensed: https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/PolyUtil.java
Constructor & Destructor Documentation
Encoder()
Encoder (Writer writer)
References PolyshapeWriter.Encoder.writer.
{
       this.writer = writer;
     }
Member Function Documentation
encode()
void encode (long v) throws IOException private
Referenced by PolyshapeWriter.Encoder.write(), and PolyshapeWriter.Encoder.writeArg().
{
       v = v < 0 ? ~(v << 1) : v << 1;
       while (v >= 0x20) {
         writer.write(Character.toChars((int) ((0x20 | (v & 0x1f)) + 63)));
         v >>= 5;
       }
       writer.write(Character.toChars((int) (v + 63)));
     }
seperator()
void seperator () throws IOException
{
       writer.write(KEY_SEPERATOR);
       lastLat = lastLng = 0;
     }
startRing()
void startRing () throws IOException
{
       writer.write(KEY_ARG_START);
       lastLat = lastLng = 0;
     }
write() [1/2]
void write (char event) throws IOException
{
       writer.write(event);
       lastLat = lastLng = 0;
     }
write() [2/2]
void write (double latitude, double longitude) throws IOException
References PolyshapeWriter.Encoder.encode(), PolyshapeWriter.Encoder.lastLat, and PolyshapeWriter.Encoder.lastLng.
{
       long lat = Math.round(latitude * 1e5);
       long lng = Math.round(longitude * 1e5);
       long dLat = lat - lastLat;
       long dLng = lng - lastLng;
       encode(dLat);
       encode(dLng);
       lastLat = lat;
       lastLng = lng;
     }
writeArg()
void writeArg (double value) throws IOException
References PolyshapeWriter.Encoder.encode().
{
       writer.write(KEY_ARG_START);
       encode(Math.round(value * 1e5));
       writer.write(KEY_ARG_END);
     }
Member Data Documentation
lastLat
long lastLat = 0 package
Referenced by PolyshapeWriter.Encoder.write().
lastLng
long lastLng = 0 package
Referenced by PolyshapeWriter.Encoder.write().
writer
final Writer writer package
Referenced by PolyshapeWriter.Encoder.Encoder().