rdf4j-postgis: WKTDatatype Class Reference
WKTDatatype Class Reference
Classes
class WKBTextSRS
Public Member Functions
String unparse (Geometry geometry)
This method Un-parses the JTS Geometry to the WKT literal.
Geometry read (String geometryLiteral)
String toString ()
Static Public Attributes
static final String URI = POSTGIS.NAMESPACE+"wktLiteral"
The default WKT type URI.
static final IRI LiteralIRI =SimpleValueFactory.getInstance().createIRI(POSTGIS.NAMESPACE+"wktLiteral")
static final WKTDatatype INSTANCE = new WKTDatatype()
A static instance of WKTDatatype.
Member Function Documentation
read()
Geometry read (String geometryLiteral)
References WKTDatatype.WKBTextSRS.getWkbText().
Referenced by GeneratePointsTest.testGeneratePoints().
{
         WKBTextSRS wkbTextSRS = new WKBTextSRS(geometryLiteral);
         WKTReader wkbReader = new WKTReader();
         Geometry geometry;
                 try {
                         geometry = wkbReader.read(wkbTextSRS.getWkbText());
                         return geometry;
                 } catch (ParseException e) {
                         throw new RuntimeException(e.getMessage());
                 }
     }
toString()
String toString ()
{
         return "WKTDatatype{" + URI + '}';
     }
unparse()
String unparse (Geometry geometry)
This method Un-parses the JTS Geometry to the WKT literal.
Parameters
geometry - the JTS Geometry to be un-parsed
Returns
WKT - the returned WKT Literal.
Notice that the Spatial Reference System is not specified in returned WKT literal.
Referenced by GeometricConstructor.evaluate().
{
             WKTWriter writer=new WKTWriter();
             return writer.write(geometry).toString();
     }
Member Data Documentation
INSTANCE
final WKTDatatype INSTANCE = new WKTDatatype() static
A static instance of WKTDatatype.
Referenced by GeometricConstructor.evaluate(), LiteralRegistry.LiteralRegistry(), GeneratePointsTest.testGeneratePoints(), and NodeTest.testNode().
LiteralIRI
final IRI LiteralIRI =SimpleValueFactory.getInstance().createIRI(POSTGIS.NAMESPACE+"wktLiteral") static
Referenced by GeometricConstructor.evaluate(), NDimsTest.test2DGeom(), NDimsTest.test3DGeom(), AddGeometryTest.testAddGeometry(), AddGeometryTest.testAddGeometryZ(), AddPointTest.testAddPoint(), AddPointTest.testAddPointZ(), AddRingTest.testAddRing(), AngleTest.testAngle(), AreaTest.testArea(), AreaSimilarityTest.testAreaSimilarity(), AreaSimilarityTest.testAreaSimilarity2(), AsBinaryTest.testAsBinary(), AsHexWKBTest.testAsEncodedPolyline(), AsEncodedPolylineTest.testAsEncodedPolyline(), AsGARSTest.testAsGARS(), AsGeoJSONTest.testAsGeoJSON(), AsGeoRSSTest.testAsGeoRSS(), AsGeoURITest.testAsGeoURI(), AsLatLonTextTest.testAsLatLonText(), AsOSMLinkTest.testAsOSMLink(), AsPolyshapeTest.testAsPolyShape(), AsSVGTest.testAsSVG(), AsTextTest.testAsText(), AsTextRawTest.testAsTextRaw(), AsTextRoundTest.testAsTextRound(), AsTextTest.testAsTextZ(), AsTWKBTest.testAsTWKB(), AzimuthTest.testAzimuth1(), BBOXAboveTest.testBBOXAbove(), BBOXAboveTest.testBBOXAbove1(), BBOXBelowTest.testBBOXBelow(), BBOXBelowTest.testBBOXBelow1(), BBOXContainsTest.testBBOXContainsFalse(), BBOXContainsTest.testBBOXContainsTrue(), BBOXDistanceTest.testBBOXDistance(), BBOXEqualsTest.testBBOXEqualsFalse(), BBOXEqualsTest.testBBOXEqualsTrue(), BBOXIntersectsTest.testBBOXIntersectsFalse(), BBOXIntersectsTest.testBBOXIntersectsTrue(), BBOXIsContainedByTest.testBBOXIsContainedByFalse(), BBOXIsContainedByTest.testBBOXIsContainedByTrue(), BBOXLeftOfTest.testBBOXLeftOf(), BBOXLeftOfTest.testBBOXLeftOf1(), BBOXOverlapsLeftTest.testBBOXLeftOfFalse(), BBOXOverlapsLeftTest.testBBOXLeftOfTrue(), BBOXOverlapsRightTest.testBBOXRightOf(), BBOXRightOfTest.testBBOXRightOf(), BBOXOverlapsRightTest.testBBOXRightOf1(), BBOXRightOfTest.testBBOXRightOf1(), BoundingDiagonalTest.testBoundingDiagonal(), BoundaryTest.testBoundingDiagonal(), CentroidTest.testCentroid(), CentroidDistanceTest.testCentroidDistance(), CentroidDistanceTest.testCentroidDistance2(), StartPointTest.testCircularString(), CircumcentreTest.testCircumcentre1(), ClosestPointTest.testClosestPoint(), CollectionExtractTest.testCollectionExtract(), CollectionHomogenizeTest.testCollectionHomogenize(), CompactnessRatioTest.testCompactnessRatio(), CompactnessRatioTest.testCompactnessRatioNaN(), DensifyTest.testDensify(), DistanceTest.testDistance(), DistanceTest.testDistance2(), DistanceSphereTest.testDistanceSphere(), DistanceSphereTest.testDistanceSphere2(), DumpTest.testDump(), EnsureClosedTest.testEnsureClosed(), EnsureClosedTest.testEnsureClosed2(), EqualTypeTest.testEqual(), EqualNormTest.testEqualNormFalse(), EqualNormTest.testEqualNormTrue(), EqualSRSTest.testEqualSRS(), EqualTopoTest.testEqualTopoFalse(), EqualTopoTest.testEqualTopoTrue(), FlipCoordinatesTest.testFlipCoordinates(), Force2DTest.testForce2D(), Force3DTest.testForce3D(), Force3DMTest.testForce3DM(), Force3DMTest.testForce3DM2(), Force4DTest.testForce4D(), ForceCollectionTest.testForceCollection(), ForceCollectionTest.testForceCollectionZ(), ForcePolygonCCWTest.testForcePolygonCCW(), ForcePolygonCWTest.testForcePolygonCW(), FullyWithinDistanceTest.testFullyWithinDistanceFalse(), FullyWithinDistanceTest.testFullyWithinDistanceTrue(), FurthestCoordinateTest.testFurthestCoordinate(), GeneratePointsTest.testGeneratePoints(), GeomCRSToWKTTest.testGeomCRSToWKT(), IsCollectionTest.testGeometryCollectionIsCollection(), GeomFromGeoJSONTest.testGeomFromGeoJSON(), GeomFromTextTest.testGeomFromText(), GeomFromWKBTest.testGeomFromWKB(), HasConnectedInteriorTest.testHasConnectedInteriorFalse(), HasConnectedInteriorTest.testHasConnectedInteriorTrue(), HasDuplicateRingsTest.testHasDuplicateRingsFalse(), HasDuplicateRingsTest.testHasDuplicateRingsTrue(), HasHorizontalCRSTest.testHasHorizontalCRSFalse(), HasHorizontalCRSTest.testHasHorizontalCRSTrue(), HasRepeatedPointsTest.testHasRepeatedPoints(), HasRepeatedPointsTest.testHasRepeatedPoints2(), HasSelfIntersectionsTest.testHasSelfIntersectionsFalse(), HasSelfIntersectionsTest.testHasSelfIntersectionsTrue(), HausdorffDistanceTest.testHausdorffDistance(), IntersectionMatrixTest.testIntersectionMatrix(), IntersectionPercentageTest.testIntersectionPercentage(), IntersectionPercentageTest.testIntersectionPercentage2(), Is3DTest.testIs3DFalse(), IsAcuteTest.testIsAcuteFalse(), IsAcuteTest.testIsAcuteTrue(), IsConvexTest.testIsConvexFalse(), IsConvexTest.testIsConvexTrue(), IsEmptyTest.testIsEmptyFalse(), IsEmptyTest.testIsEmptyTrue(), IsEquilateralTriangleTest.testIsEquilateralTriangleFalse(), IsEquilateralTriangleTest.testIsEquilateralTriangleTrue(), IsInCRSAreaOfValidityTest.testIsInCRSAreaOfValidityFalse(), IsInCRSAreaOfValidityTest.testIsInCRSAreaOfValidityTrue(), IsIsocelesTriangleTest.testIsIsocelesTriangleFalse(), IsIsocelesTriangleTest.testIsIsocelesTriangleTrue(), IsMeasuredTest.testIsMeasuredFalse(), IsMeasuredTest.testIsMeasuredTrue(), IsMorePreciseTest.testIsMorePreciseEqual(), IsMorePreciseTest.testIsMorePreciseFirst(), IsMorePreciseTest.testIsMorePreciseSecond(), IsNodingValidTest.testIsNodingValuedTrue(), IsObliqueTriangleTest.testIsObliqueTriangleFalse(), IsObtuseTriangleTest.testIsObliqueTriangleFalse(), IsObliqueTriangleTest.testIsObliqueTriangleTrue(), IsObtuseTriangleTest.testIsObliqueTriangleTrue(), IsPlanarTest.testIsPlanarTrue(), IsPolygonCCWTest.testIsPolygonCCWFalse(), IsPolygonCCWTest.testIsPolygonCCWTrue(), IsPolygonCWTest.testIsPolygonCWFalse(), IsPolygonCWTest.testIsPolygonCWTrue(), IsRectangleTest.testIsRectangleFalse(), IsRectangleTest.testIsRectangleTrue(), IsRightTriangleTest.testIsRightTriangleFalse(), IsRightTriangleTest.testIsRightTriangleTrue(), CircularityTest.testIsScaleneTriangleFalse(), CircularityTest.testIsScaleneTriangleTrue(), IsSolidTest.testIsSolidFalse(), IsSquareTest.testIsSquareFalse(), IsSquareTest.testIsSquareTrue(), IsTriangleTest.testIsTriangleFalse(), IsTriangleTest.testIsTriangleTrue(), IsValidTest.testIsValidFalse(), IsValidTest.testIsValidTrue(), LengthTest.testLineString(), GeometryTypeTest.testLineString(), PointNTest.testLineString(), EndPointTest.testLineString2D(), StartPointTest.testLineString2D(), EndPointTest.testLineString3D(), StartPointTest.testLineString3D(), IsClosedTest.testLineStringClosed(), IsCollectionTest.testLineStringIsCollection(), IsRingTest.testLineStringIsNotRing(), IsRingTest.testLineStringIsRing(), IsClosedTest.testLineStringNotClosed(), LongestLineTest.testLongestLine(), MTest.testM(), MakeLineTest.testMakeLine1(), MakePointTest.testMakePoint1(), MakePointTest.testMakePointXYZ(), ManhattanDistanceTest.testManhattanDistance(), MaxDistance3DTest.testMaxDistance(), MaxDistanceTest.testMaxDistance(), NDimsTest.testMGeom(), MinimumBoundingCircleCenterTest.testMinimumBoundingCircle(), MinimumBoundingCircleTest.testMinimumBoundingCircle(), MinimumBoundingRadiusTest.testMinimumBoundingRadius(), MinimumClearanceTest.testMinimumClearance(), MinimumClearanceLineTest.testMinimumClearanceLine(), MinimumDiameterTest.testMinimumDiameter(), MinimumDiameterLineTest.testMinimumDiameterLine(), MinimumRectangleTest.testMinimumRectangle(), MaxMTest.testMMax(), MinMTest.testMMin(), MultiTest.testMulti2D(), MultiTest.testMulti3D(), IsCollectionTest.testMultiLineStringIsCollection(), IsClosedTest.testMultiLineStringNotClosed(), IsClosedTest.testmultiPointClosed(), IsCollectionTest.testMultiPointIsCollection(), IsCollectionTest.testMultiPolygonIsCollection(), NodeTest.testNode(), SelfIntersectionsTest.testNoSelfIntersections(), EqualSRSTest.testNoSRS(), EqualTypeTest.testNotEqual(), EqualSRSTest.testNotEqualSRS(), NRingsTest.testNRings(), NumDistinctInteriorRingsTest.testNRings(), NumDistinctGeometriesTest.testNumDistinctGeometries(), NumDistinctGeometriesTest.testNumDistinctGeometriesCollection(), NumDistinctPointsTest.testNumDistinctPoints(), NumGeometriesTest.testNumGeometries(), NumGeometriesTest.testNumGeometriesCollection(), NumPointsTest.testNumPoints(), OrderingEqualsTest.testOrderingEquals1(), OrderingEqualsTest.testOrderingEquals2(), OrderingEqualsTest.testOrderingEquals3(), PerimeterTest.testPerimeter(), EndPointTest.testPoint(), StartPointTest.testPoint(), IsClosedTest.testpointClosed(), PointFromTextTest.testPointFromText(), PointInsideCircleTest.testPointInsideCircleFalse(), PointInsideCircleTest.testPointInsideCircleTrue(), IsCollectionTest.testPointIsCollection(), PointsTest.testPoints(), PointsTest.testPoints3D(), PolygonFromTextTest.testPolygonFromText(), IsCollectionTest.testPolygonIsCollection(), PrecisionReducerTest.testPrecisionReducer(), RelateTest.testRelate(), RemoveGeometryTest.testRemoveGeometry1(), RemoveGeometryTest.testRemoveGeometry1Z(), RemoveGeometryTest.testRemoveGeometry2(), RemoveGeometryTest.testRemoveGeometry2Z(), RemovePointTest.testRemovePoint(), RemovePointTest.testRemovePointZ(), RemoveRepeatedPointsTest.testRemoveRepeatedPoints(), RemoveRingTest.testRemoveRing(), ReverseTest.testReverse(), ReverseRingTest.testReverseRing(), SelfIntersectionsTest.testSelfIntersections(), SetEndPointTest.testSetEndPoint(), SetGeometryTest.testSetGeometry(), SetGeometryTest.testSetGeometryZ(), SetPointTest.testSetPoint(), SetRingTest.testSetRing(), SetStartPointTest.testSetStartPoint(), ShiftLongitudeTest.testShiftLongitude(), ShortestLineTest.testShortestLine(), ShortestLine3DTest.testShortestLine3D(), SimplifyTest.testSimplify(), SimplifyVWTest.testSimplifyVW(), SimplifyPreserveTopologyTest.testSimplifyVW(), SridGetAxis1OrientationTest.testSridAxis1Orientation(), SridGetAxis2OrientationTest.testSridAxis2Orientation(), SridGetAxis1NameTest.testSridGetAxis1Name(), SridGetAxis2NameTest.testSridGetAxis2Name(), SridGetDatumTest.testSridGetDatum(), SridHasFlippedAxisTest.testSridHasFlippedAxis(), SridIsGeographicTest.testSridIsGeographicFalse(), SridIsGeographicTest.testSridIsGeographicTrue(), SridIsProjectedTest.testSridIsProjectedTrue(), SridIsVerticalTest.testSridIsVerticalTrue(), SwapOrdinatesTest.testSwapOrdinates(), TransScaleTest.testTransScale(), XTest.testX(), MaxXTest.testXMax(), MinXTest.testXMin(), YTest.testY(), MaxYTest.testYMax(), MinYTest.testYMin(), ZTest.testZ(), MaxZTest.testZMax(), and MinZTest.testZMin().
URI
final String URI = POSTGIS.NAMESPACE+"wktLiteral" static
The default WKT type URI.
Referenced by LiteralRegistry.LiteralRegistry(), AzimuthTest.testAzimuth1(), and AzimuthTest.testAzimuth2().