rdf4j-postgis: IsCollectionTest Class Reference
IsCollectionTest Class Reference
Public Member Functions
void testMultiPointIsCollection ()
void testMultiPolygonIsCollection ()
void testMultiLineStringIsCollection ()
void testGeometryCollectionIsCollection ()
void testPointIsCollection ()
void testLineStringIsCollection ()
void testPolygonIsCollection ()
Member Function Documentation
testGeometryCollectionIsCollection()
void testGeometryCollectionIsCollection ()
References GeometricBinaryAttributeFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 IsCollection is3d=new IsCollection();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral("<http://www.opengis.net/def/crs/EPSG/0/27700> GEOMETRYCOLLECTION(POINT(4 6),LINESTRING(4 6,7 10))", WKTDatatype.LiteralIRI);
                 Value result=is3d.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral(true);
             assertEquals(expResult, result);
         }
testLineStringIsCollection()
void testLineStringIsCollection ()
References GeometricBinaryAttributeFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 IsCollection is3d=new IsCollection();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral("<http://www.opengis.net/def/crs/EPSG/0/27700> LINESTRING (30 10, 10 30, 40 40)", WKTDatatype.LiteralIRI);
                 Value result=is3d.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral(false);
             assertEquals(expResult, result);
         }
testMultiLineStringIsCollection()
void testMultiLineStringIsCollection ()
References GeometricBinaryAttributeFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 IsCollection is3d=new IsCollection();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral("<http://www.opengis.net/def/crs/EPSG/0/27700> MULTILINESTRING ((10 10, 20 20, 10 40),(40 40, 30 30, 40 20, 30 10))", WKTDatatype.LiteralIRI);
                 Value result=is3d.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral(true);
             assertEquals(expResult, result);
         }
testMultiPointIsCollection()
void testMultiPointIsCollection ()
References GeometricBinaryAttributeFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 IsCollection is3d=new IsCollection();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral("<http://www.opengis.net/def/crs/EPSG/0/27700> MULTIPOINT (10 40, 40 30, 20 20, 30 10)", WKTDatatype.LiteralIRI);
                 Value result=is3d.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral(true);
             assertEquals(expResult, result);
         }
testMultiPolygonIsCollection()
void testMultiPolygonIsCollection ()
References GeometricBinaryAttributeFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 IsCollection is3d=new IsCollection();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral("<http://www.opengis.net/def/crs/EPSG/0/27700> MULTIPOLYGON (((40 40, 20 45, 45 30, 40 40)),((20 35, 10 30, 10 10, 30 5, 45 20, 20 35),(30 20, 20 15, 20 25, 30 20)))", WKTDatatype.LiteralIRI);
                 Value result=is3d.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral(true);
             assertEquals(expResult, result);
         }
testPointIsCollection()
void testPointIsCollection ()
References GeometricBinaryAttributeFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 IsCollection is3d=new IsCollection();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral("<http://www.opengis.net/def/crs/EPSG/0/27700> POINT (30 10)", WKTDatatype.LiteralIRI);
                 Value result=is3d.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral(false);
             assertEquals(expResult, result);
         }
testPolygonIsCollection()
void testPolygonIsCollection ()
References GeometricBinaryAttributeFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 IsCollection is3d=new IsCollection();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral("<http://www.opengis.net/def/crs/EPSG/0/27700> POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))", WKTDatatype.LiteralIRI);
                 Value result=is3d.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral(false);
             assertEquals(expResult, result);
         }