rdf4j-postgis: TWKBDatatype Class Reference
TWKBDatatype Class Reference
WKTDatatype class allows the URI "geo:wktLiteral" to be used as a datatype and it will parse that datatype to a JTS Geometry.
Classes
class WKBTextSRS
Public Member Functions
String unparse (Geometry geometry)
This method Un-parses the JTS Geometry to the WKT literal.
Geometry read (String geometryLiteral)
String toString ()
Static Public Attributes
static final String URI = POSTGIS.NAMESPACE+POSTGIS.TWKB
The default WKT type URI.
static final TWKBDatatype INSTANCE = new TWKBDatatype()
A static instance of WKTDatatype.
static final IRI LiteralIRI =SimpleValueFactory.getInstance().createIRI(POSTGIS.NAMESPACE+POSTGIS.TWKB)
Detailed Description
WKTDatatype class allows the URI "geo:wktLiteral" to be used as a datatype and it will parse that datatype to a JTS Geometry.
Req 10 All RDFS Literals of type geo:wktLiteral shall consist of an optional URI identifying the coordinate reference system followed by Simple Features Well Known Text (WKT) describing a geometric value. Valid geo:wktLiterals are formed by concatenating a valid, absolute URI as defined in [RFC 2396], one or more spaces (Unicode U+0020 character) as a separator, and a WKT string as defined in Simple Features [ISO 19125-1].
Req 11 The URI
<http://www.opengis.net/def/crs/OGC/1.3/CRS84>
shall be assumed as the spatial reference system for geo:wktLiterals that do not * specify an explicit spatial reference system URI.
Member Function Documentation
read()
Geometry read (String geometryLiteral)
References LiteralUtils.createGeometry(), TWKBDatatype.WKBTextSRS.getWkbText(), and TWKBReader.read().
{
         WKBTextSRS wkbTextSRS = new WKBTextSRS(geometryLiteral);
         TWKBReader wkbReader = new TWKBReader();
         Geometry geometry;
                 try {
                         geometry = wkbReader.read(wkbTextSRS.getWkbText().getBytes());
                         return LiteralUtils.createGeometry(geometry.getCoordinates(), geometry.getGeometryType(), geometry.getSRID());
                 } catch (ParseException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                         throw new RuntimeException();
                 }
     }
toString()
String toString ()
{
         return "TWKBDatatype{" + URI + '}';
     }
unparse()
String unparse (Geometry geometry)
This method Un-parses the JTS Geometry to the WKT literal.
Parameters
geometry - the JTS Geometry to be un-parsed
Returns
WKT - the returned WKT Literal.
Notice that the Spatial Reference System is not specified in returned WKT literal.
References TWKBWriter.write().
Referenced by AsTWKB.operation().
{
             TWKBWriter writer=new TWKBWriter();
             return writer.write(geometry).toString();
     }
Member Data Documentation
INSTANCE
final TWKBDatatype INSTANCE = new TWKBDatatype() static
A static instance of WKTDatatype.
Referenced by LiteralRegistry.LiteralRegistry().
LiteralIRI
final IRI LiteralIRI =SimpleValueFactory.getInstance().createIRI(POSTGIS.NAMESPACE+POSTGIS.TWKB) static
URI
final String URI = POSTGIS.NAMESPACE+POSTGIS.TWKB static
The default WKT type URI.
Referenced by LiteralRegistry.LiteralRegistry().