rdf4j-postgis: CovJSONCoverage Class Reference
CovJSONCoverage Class Reference
Wraps an EDAL Feature into a CoverageJSON compatible Coverage object.
Classes
class Axis
enum DataType
class Domain
class NdArray
class ReferenceSystemConnection
class TupleAxis
Public Member Functions
CovJSONCoverage (Feature<?> feature)
Package Attributes
final DiscreteFeature<?,?> feature
Domain domain
Map< String, Parameter > parameters = new HashMap<>()
Map< String, NdArray > ranges = new HashMap<>()
Private Member Functions
void init ()
Static Private Member Functions
static Domain getDomain (DiscreteFeature<?, ?> feature)
static Domain doGetDomain (MapFeature feature)
static Domain doGetDomain (GridFeature feature)
static Domain doGetDomain (ProfileFeature feature)
static Domain doGetDomain (PointSeriesFeature feature)
static Domain doGetDomain (PointFeature feature)
static Domain doGetDomain (TrajectoryFeature feature)
static Set< ReferenceSystemConnection > getRefSysConnections (CoordinateReferenceSystem xy, Chronology t, VerticalCrs z)
static Map< String, Axis > getAxes (ReferenceableAxis<?> x, ReferenceableAxis<?> y, TimeAxis t, VerticalAxis z)
static Map< String, Axis > getAxes (TrajectoryDomain trajectoryDomain)
Detailed Description
Wraps an EDAL Feature into a CoverageJSON compatible Coverage object.
Author
Maik Riechert
Constructor & Destructor Documentation
CovJSONCoverage()
CovJSONCoverage (Feature<?> feature)
References CovJSONCoverage.init().
{
                 if (!(feature instanceof DiscreteFeature)) {
                         throw new EdalException("Only discrete-type features are supported");
                 }
                 this.feature = (DiscreteFeature<?, ?>) feature;
                 this.init();
         }
Member Function Documentation
doGetDomain() [1/6]
static Domain doGetDomain (MapFeature feature) static private
Referenced by CovJSONCoverage.getDomain().
{
                 return doGetDomain(Util.convertToGridFeature(feature));
         }
doGetDomain() [2/6]
static Domain doGetDomain (GridFeature feature) static private
References CovJSONCoverage.Domain.axes, CovJSONCoverage.Domain.Domain(), CovJSONCoverage.getAxes(), and CovJSONCoverage.getRefSysConnections().
{
                 GridDomain domain = feature.getDomain();
                 VerticalAxis z = domain.getVerticalAxis();
                 HorizontalGrid xy = domain.getHorizontalGrid();
                 TimeAxis t = domain.getTimeAxis();
                 RectilinearGrid rectGrid;
                 if (xy instanceof RectilinearGrid) {
                         rectGrid = (RectilinearGrid) xy;
                 } else {
                         throw new RuntimeException("Unsupported grid type: " + xy.getClass().getSimpleName());
                 }
                 ReferenceableAxis<?> x = rectGrid.getXAxis();
                 ReferenceableAxis<?> y = rectGrid.getYAxis();
                 Map<String, Axis> axes = getAxes(x, y, t, z);
                 Set<ReferenceSystemConnection> refSysConnections = getRefSysConnections(
                                  xy.getCoordinateReferenceSystem(), t != null ? t.getChronology() : null, z != null ? z.getVerticalCrs() : null);
                 return new Domain(axes, refSysConnections, Vals.GRID);
         }
doGetDomain() [3/6]
static Domain doGetDomain (ProfileFeature feature) static private
References CovJSONCoverage.Domain.axes, CovJSONCoverage.Domain.Domain(), CovJSONCoverage.getAxes(), and CovJSONCoverage.getRefSysConnections().
{
                 VerticalAxis z = feature.getDomain();
                 HorizontalPosition xy = feature.getHorizontalPosition();
                 DateTime time = feature.getTime();
                 TimeAxis t = time != null ? new TimeAxisImpl(Keys.T, Arrays.asList(time)) : null;
                 ReferenceableAxis<?> x = new ReferenceableAxisImpl(Keys.X, Arrays.asList(xy.getX()), false);
                 ReferenceableAxis<?> y = new ReferenceableAxisImpl(Keys.Y, Arrays.asList(xy.getY()), false);
                 Map<String, Axis> axes = getAxes(x, y, t, z);
                 Set<ReferenceSystemConnection> refSysConnections = getRefSysConnections(
                                  xy.getCoordinateReferenceSystem(), t != null ? t.getChronology() : null, z != null ? z.getVerticalCrs() : null);
                 return new Domain(axes, refSysConnections, Vals.VERTICALPROFILE);
         }
doGetDomain() [4/6]
static Domain doGetDomain (PointSeriesFeature feature) static private
References CovJSONCoverage.Domain.axes, CovJSONCoverage.Domain.Domain(), CovJSONCoverage.getAxes(), and CovJSONCoverage.getRefSysConnections().
{
         TimeAxis tAxis = feature.getDomain();
         HorizontalPosition xy = feature.getHorizontalPosition();
         VerticalPosition z = feature.getVerticalPosition();
         VerticalAxis zAxis = z != null ? new VerticalAxisImpl(Keys.Z, Arrays.asList(z.getZ()),
                 z.getCoordinateReferenceSystem()) : null;
         ReferenceableAxis<?> x = new ReferenceableAxisImpl(Keys.X, Arrays.asList(xy.getX()), false);
         ReferenceableAxis<?> y = new ReferenceableAxisImpl(Keys.Y, Arrays.asList(xy.getY()), false);
         Map<String, Axis> axes = getAxes(x, y, tAxis, zAxis);
         Set<ReferenceSystemConnection> refSysConnections = getRefSysConnections(
                 xy.getCoordinateReferenceSystem(), tAxis != null ? tAxis.getChronology() : null,
                 z != null ? z.getCoordinateReferenceSystem() : null);
         return new Domain(axes, refSysConnections, Vals.POINTSERIES);
     }
doGetDomain() [5/6]
static Domain doGetDomain (PointFeature feature) static private
References CovJSONCoverage.Domain.axes, CovJSONCoverage.Domain.Domain(), CovJSONCoverage.getAxes(), and CovJSONCoverage.getRefSysConnections().
{
                 GeoPosition domain = feature.getGeoPosition();
                 VerticalPosition zpos = domain.getVerticalPosition();
                 HorizontalPosition xy = domain.getHorizontalPosition();
                 DateTime time = domain.getTime();
                 VerticalAxis z = new VerticalAxisImpl(Keys.Z,
                                 Arrays.asList(zpos.getZ()), zpos.getCoordinateReferenceSystem());
                 TimeAxis t = time != null ? new TimeAxisImpl(Keys.T, Arrays.asList(domain.getTime())) : null;
                 ReferenceableAxis<?> x = new ReferenceableAxisImpl(Keys.X, Arrays.asList(xy.getX()), false);
                 ReferenceableAxis<?> y = new ReferenceableAxisImpl(Keys.Y, Arrays.asList(xy.getY()), false);
                 Map<String, Axis> axes = getAxes(x, y, t, z);
                 Set<ReferenceSystemConnection> refSysConnections = getRefSysConnections(
                                  xy.getCoordinateReferenceSystem(), t != null ? t.getChronology() : null, z != null ? z.getVerticalCrs() : null);
                 return new Domain(axes, refSysConnections, Vals.POINT);
         }
doGetDomain() [6/6]
static Domain doGetDomain (TrajectoryFeature feature) static private
References CovJSONCoverage.Domain.axes, CovJSONCoverage.Domain.Domain(), CovJSONCoverage.getAxes(), and CovJSONCoverage.getRefSysConnections().
{
                 TrajectoryDomain domain = feature.getDomain();
                 Map<String, Axis> axes = getAxes(domain);
                 Set<ReferenceSystemConnection> refSysConnections = getRefSysConnections(
                                  domain.getHorizontalCrs(), domain.getChronology(), domain.getVerticalCrs());
                 return new Domain(axes, refSysConnections, Vals.TRAJECTORY);
         }
getAxes() [1/2]
static Map<String, Axis> getAxes (ReferenceableAxis<?> x, ReferenceableAxis<?> y, TimeAxis t, VerticalAxis z) static private
References CovJSONCoverage.Domain.axes.
Referenced by CovJSONCoverage.doGetDomain().
{
                 Map<String, Axis> axes = new HashMap<>();
                 axes.put(Keys.X, new Axis(x, null));
                 axes.put(Keys.Y, new Axis(y, null));
                 if (t != null) {
                         axes.put(Keys.T, new Axis(t, null));
                 }
                 if (z != null) {
                         axes.put(Keys.Z, new Axis(z, null));
                 }
                 return axes;
         }
getAxes() [2/2]
static Map<String, Axis> getAxes (TrajectoryDomain trajectoryDomain) static private
References CovJSONCoverage.Domain.axes.
{
                 List<String> coordinateIds = new LinkedList<>();
                 coordinateIds.add(Keys.T);
                 coordinateIds.add(Keys.X);
                 coordinateIds.add(Keys.Y);
                 boolean hasZ = trajectoryDomain.getVerticalCrs() != null;
                 if (hasZ) {
                         coordinateIds.add(Keys.Z);
                 }
                 int size = trajectoryDomain.size();
                 List<DateTime> ts = new ArrayList<>(size);
                 List<Double> xs = new ArrayList<>(size);
                 List<Double> ys = new ArrayList<>(size);
                 List<Double> zs = hasZ ? new ArrayList<Double>(size) : null;
                 Array1D<GeoPosition> positions = trajectoryDomain.getDomainObjects();
                 for (GeoPosition pos : positions) {
                         ts.add(pos.getTime());
                         xs.add(pos.getHorizontalPosition().getX());
                         ys.add(pos.getHorizontalPosition().getY());
                         if (hasZ) {
                                 zs.add(pos.getVerticalPosition().getZ());
                         }
                 }
                 TimeAxis t = new TimeAxisImpl(Keys.T, ts);
                 ReferenceableAxis<Double> x = new ReferenceableAxisImpl(Keys.X, xs, false);
                 ReferenceableAxis<Double> y = new ReferenceableAxisImpl(Keys.Y, ys, false);
                 List<ReferenceableAxis<?>> nestedAxes = new LinkedList<>();
                 nestedAxes.add(t);
                 nestedAxes.add(x);
                 nestedAxes.add(y);
                 if (hasZ) {
                         ReferenceableAxis<Double> z = new ReferenceableAxisImpl(Keys.Z, zs, false);
                         nestedAxes.add(z);
                 }
                 TupleAxis tupleAxis = new TupleAxis(nestedAxes, size);
                 Map<String, Axis> axes = new HashMap<>();
                 axes.put(Keys.COMPOSITE, new Axis(tupleAxis, coordinateIds));
                 return axes;
         }
getDomain()
static Domain getDomain (DiscreteFeature<?, ?> feature) static private
References CovJSONCoverage.doGetDomain().
Referenced by CovJSONCoverage.init().
{
                 if (feature instanceof GridFeature) {
                         return doGetDomain((GridFeature) feature);
                 } else if (feature instanceof MapFeature) {
                         return doGetDomain((MapFeature) feature);
                 } else if (feature instanceof ProfileFeature) {
                         return doGetDomain((ProfileFeature) feature);
                 } else if (feature instanceof PointSeriesFeature) {
                     return doGetDomain((PointSeriesFeature) feature);
                 } else if (feature instanceof PointFeature) {
                         return doGetDomain((PointFeature) feature);
                 } else if (feature instanceof TrajectoryFeature) {
                         return doGetDomain((TrajectoryFeature) feature);
                 } else {
                         throw new EdalException("Unsupported feature type: " + feature.getClass().getSimpleName());
                 }
         }
getRefSysConnections()
static Set<ReferenceSystemConnection> getRefSysConnections (CoordinateReferenceSystem xy, Chronology t, VerticalCrs z) static private
Referenced by CovJSONCoverage.doGetDomain().
{
                 Set<ReferenceSystemConnection> refSysConnections = new HashSet<>();
                 refSysConnections.add(new ReferenceSystemConnection(Arrays.asList(Keys.X, Keys.Y), xy));
                 if (t != null) {
                         refSysConnections.add(new ReferenceSystemConnection(Arrays.asList(Keys.T), t));
                 }
                 if (z != null) {
                         refSysConnections.add(new ReferenceSystemConnection(Arrays.asList(Keys.Z), z));
                 }
                 return refSysConnections;
         }
init()
void init () private
References CovJSONCoverage.feature, and CovJSONCoverage.getDomain().
Referenced by CovJSONCoverage.CovJSONCoverage().
{
                 this.domain = getDomain(this.feature);
                 for (Parameter param : Util.withoutParameterGroups(this.feature.getParameterMap().values(), this.feature)) {
                         String key = param.getVariableId();
                         this.parameters.put(key, param);
                         this.ranges.put(key, new NdArray(this.feature, key, this.domain));
                 }
         }
Member Data Documentation
domain
Domain domain package
feature
final DiscreteFeature<?,?> feature package
Referenced by CovJSONCoverage.init().
parameters
Map<String, Parameter> parameters = new HashMap<>() package
ranges
Map<String, NdArray> ranges = new HashMap<>() package