rdf4j-postgis: NDimsTest Class Reference
NDimsTest Class Reference
Public Member Functions
void test2DGeom ()
void test3DGeom ()
void testMGeom ()
Static Public Attributes
static final String geom2D ="POINT(1 1)"
static final String geom3D ="POINT Z(1 1 2)"
static final String geomM ="POINT M(1 1 0.5)"
Member Function Documentation
test2DGeom()
void test2DGeom ()
References GeometricIntegerAttributeFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 NDims instance=new NDims();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(geom2D, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral(2);
                 assertEquals(expResult, result);
         }
test3DGeom()
void test3DGeom ()
References GeometricIntegerAttributeFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 NDims instance=new NDims();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(geom3D, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral(3);
                 assertEquals(expResult, result);
         }
testMGeom()
void testMGeom ()
References GeometricIntegerAttributeFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 NDims instance=new NDims();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(geomM, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral(2);
                 assertEquals(expResult, result);
         }
Member Data Documentation
geom2D
final String geom2D ="POINT(1 1)" static
geom3D
final String geom3D ="POINT Z(1 1 2)" static
geomM
final String geomM ="POINT M(1 1 0.5)" static