rdf4j-postgis: RasterUtils Class Reference
RasterUtils Class Reference
Static Public Member Functions
static GridCoverage createGridCoverage (CharSequence name, PlanarImage tiledImage)
static double [][] getSubMatrix (GridCoordinates pos, int width, int height, double zFactor)
static double [][] getSubMatrix (GridCoordinates pos, int width, int height)
static boolean compareDouble (double a, double b)
static boolean compareDouble (double a, double b, double rTol)
static boolean compareFloat (float a, float b, float rTol)
static boolean compareFloat (float a, float b)
Static Public Attributes
static final double DOUBLE_COMPARE_TOLERANCE = 0.00000001d
Default tolerance for double comparisons: 1.0e-8 = 0.00000001.
static final float FLOAT_COMPARE_TOLERANCE = 0.0001f
Default tolerance for float comparisons: 1.0e-4 = 0.0001.
Protected Member Functions
void initSurface (GridCoverage gc)
GridCoverage createGridCoverage (CharSequence name, RenderedImage image, SampleDimension[] bands, double noDataValue, double minValue, double maxValue, Envelope extent)
Protected Attributes
double srcNoData = -Float.MAX_VALUE
double CellSizeX =30.
double CellSizeY =30.
double _8DX = CellSizeX * 8
double _8DY = CellSizeY * 8
PlanarImage image
java.awt.Rectangle bounds
Envelope Extent = null
RasterPixelType PixelType = RasterPixelType.INTEGER
double NoData = Float.MIN_VALUE
double MinValue = Double.MAX_VALUE
double MaxValue = Double.MIN_VALUE
Private Attributes
int maxCol
int maxRow
Member Function Documentation
compareDouble() [1/2]
static boolean compareDouble (double a, double b) static
Referenced by RasterUtils.getSubMatrix().
{
                 return compareDouble(a, b, DOUBLE_COMPARE_TOLERANCE);
             }
compareDouble() [2/2]
static boolean compareDouble (double a, double b, double rTol) static
{
                 final double aTol = 0.00000001;
                 if (Math.abs(a - b) < aTol + (rTol * Math.abs(b))) {
                     return true;
                 }
                 return false;
             }
compareFloat() [1/2]
static boolean compareFloat (float a, float b, float rTol) static
Referenced by RasterUtils.compareFloat().
{
                 final float aTol = 0.0001f;
                 if (Math.abs(a - b) < aTol + (rTol * Math.abs(b))) {
                     return true;
                 }
                 return false;
             }
compareFloat() [2/2]
static boolean compareFloat (float a, float b) static
References RasterUtils.compareFloat().
{
                 return compareFloat(a, b, FLOAT_COMPARE_TOLERANCE);
             }
createGridCoverage() [1/2]
static GridCoverage createGridCoverage (CharSequence name, PlanarImage tiledImage) static
Referenced by RasterIterator.execute().
{
         return createGridCoverage(name, tiledImage, 1, NoData, MinValue, MaxValue, Extent);
     }
createGridCoverage() [2/2]
GridCoverage createGridCoverage (CharSequence name, RenderedImage image, SampleDimension [] bands, double noDataValue, double minValue, double maxValue, Envelope extent) protected
{
         if (image == null || extent == null) {
             throw new NullPointerException("WritableRaster is null!");
         }
         if (noDataValue == minValue) {
             noDataValue = minValue - 1;
         } else if (noDataValue == maxValue) {
             noDataValue = maxValue + 1;
         } else if (noDataValue > minValue && noDataValue < maxValue) {
             noDataValue = minValue - 1;
         }
         CharSequence noDataName = Vocabulary.formatInternational(VocabularyKeys.NODATA);
         // setting metadata
         final Map<CharSequence, Double> properties = new HashMap<CharSequence, Double>();
         properties.put("Maximum", Double.valueOf(maxValue));
         properties.put("Minimum", Double.valueOf(minValue));
         // properties.put("Mean", 1.0);
         // properties.put("StdDev", 1.0);
         properties.put(noDataName, Double.valueOf(noDataValue));
         properties.put("GC_NODATA", Double.valueOf(noDataValue));
         GridCoverageFactory factory = CoverageFactoryFinder.getGridCoverageFactory(null);
         return factory.create(name, image, extent, bands, null, properties);
     }
getSubMatrix() [1/2]
static double [][] getSubMatrix (GridCoordinates pos, int width, int height, double zFactor) static
References RasterUtils.bounds, and RasterUtils.compareDouble().
Referenced by RasterUtils.getSubMatrix().
{
         int posX = width / 2;
         int posY = height / 2;
         // upper-left corner
         GridCoordinates ulPos = new GridCoordinates(pos.x - posX, pos.y - posY);
         Rectangle rect = new Rectangle(ulPos.x, ulPos.y, width, height);
         Raster subsetRs = image.getData(rect);
         boolean hasNAN = false;
         double[][] mx = new double[width][height];
         for (int dy = ulPos.y, row = 0; row < height; dy++, row++) {
             for (int dx = ulPos.x, col = 0; col < width; dx++, col++) {
                 if (dx < bounds.x || dy < bounds.y || dx >= maxCol || dy >= maxRow) {
                     mx[col][row] = Double.NaN;
                     hasNAN = true;
                 } else {
                     double ret = subsetRs.getSampleDouble(dx, dy, 0);
                     if (RasterUtils.compareDouble(ret, this.srcNoData)) {
                         mx[col][row] = Double.NaN;
                         hasNAN = true;
                     } else {
                         mx[col][row] = ret * zFactor;
                     }
                 }
             }
         }
         if (Double.isNaN(mx[1][1])) {
             return mx;
         }
         // http://help.arcgis.com/en/arcgisdesktop/10.0/help/index.html#/How_Slope_works/009z000000vz000000/
         // If any neighborhood cells are NoData, they are assigned the value of the center cell;
         // then the slope is computed.
         if (hasNAN) {
             for (int drow = 0; drow < height; drow++) {
                 for (int dcol = 0; dcol < width; dcol++) {
                     if (Double.isNaN(mx[dcol][drow])) {
                         mx[dcol][drow] = mx[1][1];
                     }
                 }
             }
         }
         return mx;
     }
getSubMatrix() [2/2]
static double [][] getSubMatrix (GridCoordinates pos, int width, int height) static
References RasterUtils.getSubMatrix().
{
                 return getSubMatrix(pos, width, height, 1.0);
             }
initSurface()
void initSurface (GridCoverage gc) protected
References RasterUtils.bounds.
Referenced by RasterIterator.execute().
{
                 GridGeometry gridGeometry2D = gc.getGridGeometry();
                 AffineTransform gridToWorld = (AffineTransform) gridGeometry2D.getGridToCRS2D();
                 CellSizeX = Math.abs(gridToWorld.getScaleX());
                 CellSizeY = Math.abs(gridToWorld.getScaleY());
                 srcNoData = RasterHelper.getNoDataValue(gc);
                 NoData = -9999;
                 _8DX = CellSizeX * 8;
                 _8DY = CellSizeY * 8;
                 image = (PlanarImage) gc.getRenderedImage();
                 bounds = image.getBounds();
                 maxCol = bounds.x + image.getWidth();
                 maxRow = bounds.y + image.getHeight();
             }
Member Data Documentation
_8DX
double _8DX = CellSizeX * 8 protected
_8DY
double _8DY = CellSizeY * 8 protected
bounds
java.awt.Rectangle bounds protected
Referenced by RasterIterator.execute(), RasterUtils.getSubMatrix(), and RasterUtils.initSurface().
CellSizeX
double CellSizeX =30. protected
CellSizeY
double CellSizeY =30. protected
DOUBLE_COMPARE_TOLERANCE
final double DOUBLE_COMPARE_TOLERANCE = 0.00000001d static
Default tolerance for double comparisons: 1.0e-8 = 0.00000001.
Extent
Envelope Extent = null protected
FLOAT_COMPARE_TOLERANCE
final float FLOAT_COMPARE_TOLERANCE = 0.0001f static
Default tolerance for float comparisons: 1.0e-4 = 0.0001.
image
PlanarImage image protected
maxCol
int maxCol private
maxRow
int maxRow private
MaxValue
double MaxValue = Double.MIN_VALUE protected
MinValue
double MinValue = Double.MAX_VALUE protected
NoData
double NoData = Float.MIN_VALUE protected
PixelType
RasterPixelType PixelType = RasterPixelType.INTEGER protected
srcNoData
double srcNoData = -Float.MAX_VALUE protected