rdf4j-postgis: MaxDistance3DTest Class Reference
MaxDistance3DTest Class Reference
Public Member Functions
void testMaxDistance3D ()
Static Public Attributes
static final String testGeom ="LINESTRING(77.29 29.07 3,77.42 29.26 4,77.27 29.31 5,77.29 29.07 3)"
static final String testGeom2 ="LINESTRING(5 5 1 ,10 10 2)"
Member Function Documentation
testMaxDistance3D()
void testMaxDistance3D ()
{
                 MaxDistance3D instance=new MaxDistance3D();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(testGeom, WKTDatatype.LiteralIRI);
                 Value geo2=valfac.createLiteral(testGeom2, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo,geo2);
                 Value expResult=valfac.createLiteral(76.37541489249011e0);
                 assertEquals(expResult, result);
         }
References GeometricRelationDoubleFunction.evaluate(), WKTDatatype.LiteralIRI, MaxDistance3DTest.testGeom, and MaxDistance3DTest.testGeom2.
Member Data Documentation
testGeom
final String testGeom ="LINESTRING(77.29 29.07 3,77.42 29.26 4,77.27 29.31 5,77.29 29.07 3)" static
Referenced by MaxDistance3DTest.testMaxDistance3D().
testGeom2
final String testGeom2 ="LINESTRING(5 5 1 ,10 10 2)" static
Referenced by MaxDistance3DTest.testMaxDistance3D().