rdf4j-postgis: RemoveGeometryTest Class Reference
RemoveGeometryTest Class Reference
Public Member Functions
void testRemoveGeometry1 ()
void testRemoveGeometry1Z ()
void testRemoveGeometry2 ()
void testRemoveGeometry2Z ()
Static Public Attributes
static final String lineString ="GEOMETRYCOLLECTION(LINESTRING(0 0 1, 1 1 1, 1 2 3),POINT(1 2 3))"
static final String point ="POINT(1 2 3)"
Member Function Documentation
testRemoveGeometry1()
void testRemoveGeometry1 ()
References GeometricModifierDoubleFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 RemoveGeometry instance=new RemoveGeometry();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(lineString, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac,geo,valfac.createLiteral(1));
                 Value expResult=valfac.createLiteral("GEOMETRYCOLLECTION (LINESTRING (0 0, 1 1, 1 2))", WKTDatatype.LiteralIRI);
                 assertEquals(expResult, result);
         }
testRemoveGeometry1Z()
void testRemoveGeometry1Z ()
References GeometricModifierDoubleFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 RemoveGeometry instance=new RemoveGeometry();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(lineString, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac,geo,valfac.createLiteral(1));
                 Value expResult=valfac.createLiteral("GEOMETRYCOLLECTION (LINESTRING (0 0 1, 1 1 1, 1 2 3))", WKTDatatype.LiteralIRI);
                 assertEquals(expResult, result);
         }
testRemoveGeometry2()
void testRemoveGeometry2 ()
References GeometricModifierDoubleFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 RemoveGeometry instance=new RemoveGeometry();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(lineString, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac,geo,valfac.createLiteral(0));
                 Value expResult=valfac.createLiteral("GEOMETRYCOLLECTION (POINT (1 2))", WKTDatatype.LiteralIRI);
                 assertEquals(expResult, result);
         }
testRemoveGeometry2Z()
void testRemoveGeometry2Z ()
References GeometricModifierDoubleFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 RemoveGeometry instance=new RemoveGeometry();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(lineString, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac,geo,valfac.createLiteral(0));
                 Value expResult=valfac.createLiteral("GEOMETRYCOLLECTION (POINT (1 2 3))", WKTDatatype.LiteralIRI);
                 assertEquals(expResult, result);
         }
Member Data Documentation
lineString
final String lineString ="GEOMETRYCOLLECTION(LINESTRING(0 0 1, 1 1 1, 1 2 3),POINT(1 2 3))" static
point
final String point ="POINT(1 2 3)" static