rdf4j-postgis: SetEndPointTest Class Reference
SetEndPointTest Class Reference
Public Member Functions
void testSetEndPoint ()
Static Public Attributes
static final String LineString2D ="LINESTRING(0 1, 0 2)"
static final String point ="POINT(1 1)"
Member Function Documentation
testSetEndPoint()
void testSetEndPoint ()
{
                 SetEndPoint instance=new SetEndPoint();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(LineString2D, WKTDatatype.LiteralIRI);
                 Value geo2=valfac.createLiteral(point, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo,geo2);
                 Value expResult=valfac.createLiteral("LINESTRING (0 1, 1 1)", WKTDatatype.LiteralIRI);
                 assertEquals(expResult, result);
         }
References GeometricModifierFunction.evaluate(), SetEndPointTest.LineString2D, WKTDatatype.LiteralIRI, and SetEndPointTest.point.
Member Data Documentation
LineString2D
final String LineString2D ="LINESTRING(0 1, 0 2)" static
Referenced by SetEndPointTest.testSetEndPoint().
point
final String point ="POINT(1 1)" static
Referenced by SetEndPointTest.testSetEndPoint().