rdf4j-postgis: OrderingEqualsTest Class Reference
OrderingEqualsTest Class Reference
Public Member Functions
void testOrderingEquals1 ()
void testOrderingEquals2 ()
void testOrderingEquals3 ()
Static Public Attributes
static final String lineStringSmall ="LINESTRING(0 0, 10 10)"
static final String lineStringSmallReverse ="LINESTRING(10 10, 0 0)"
static final String lineStringMedium ="LINESTRING(0 0, 5 5, 10 10)"
static final String lineStringMedium2 ="LINESTRING(0 0, 0 0, 10 10)"
Member Function Documentation
testOrderingEquals1()
void testOrderingEquals1 ()
References GeometricRelationBinaryFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 OrderingEquals instance=new OrderingEquals();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(lineStringSmall, WKTDatatype.LiteralIRI);
                 Value geo2=valfac.createLiteral(lineStringMedium, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo,geo2);
                 Value expResult=valfac.createLiteral(false);
                 assertEquals(expResult, result);
         }
testOrderingEquals2()
void testOrderingEquals2 ()
References GeometricRelationBinaryFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 OrderingEquals instance=new OrderingEquals();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(lineStringSmall, WKTDatatype.LiteralIRI);
                 Value geo2=valfac.createLiteral(lineStringMedium2, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo,geo2);
                 Value expResult=valfac.createLiteral(true);
                 assertEquals(expResult, result);
         }
testOrderingEquals3()
void testOrderingEquals3 ()
References GeometricRelationBinaryFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 OrderingEquals instance=new OrderingEquals();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(lineStringSmallReverse, WKTDatatype.LiteralIRI);
                 Value geo2=valfac.createLiteral(lineStringMedium2, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo,geo2);
                 Value expResult=valfac.createLiteral(false);
                 assertEquals(expResult, result);
         }
Member Data Documentation
lineStringMedium
final String lineStringMedium ="LINESTRING(0 0, 5 5, 10 10)" static
lineStringMedium2
final String lineStringMedium2 ="LINESTRING(0 0, 0 0, 10 10)" static
lineStringSmall
final String lineStringSmall ="LINESTRING(0 0, 10 10)" static
lineStringSmallReverse
final String lineStringSmallReverse ="LINESTRING(10 10, 0 0)" static