rdf4j-postgis: StartPointTest Class Reference
StartPointTest Class Reference
Public Member Functions
void testLineString2D ()
void testLineString3D ()
void testCircularString ()
void testPoint ()
Static Public Attributes
static final String LineString2D ="LINESTRING(0 1, 0 2)"
static final String point ="POINT(0 1)"
static final String LineString3D ="LINESTRING(0 1 1, 0 2 2)"
static final String CircularString ="CIRCULARSTRING(5 2,-3 1.999999, -2 1, -4 2, 5 2)"
Member Function Documentation
testCircularString()
void testCircularString ()
References GeometricUnaryFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 StartPoint instance=new StartPoint();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(CircularString, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral("POINT (5 2)", WKTDatatype.LiteralIRI);
                 assertEquals(expResult, result);
         }
testLineString2D()
void testLineString2D ()
References GeometricUnaryFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 StartPoint instance=new StartPoint();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(LineString2D, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral("POINT (0 1)", WKTDatatype.LiteralIRI);
                 assertEquals(expResult, result);
         }
testLineString3D()
void testLineString3D ()
References GeometricUnaryFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 StartPoint instance=new StartPoint();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(LineString3D, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral("POINT Z (0 1 1)", WKTDatatype.LiteralIRI);
                 assertEquals(expResult, result);
         }
testPoint()
void testPoint ()
References GeometricUnaryFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 StartPoint instance=new StartPoint();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(point, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral("POINT (0 1)", WKTDatatype.LiteralIRI);
                 assertEquals(expResult, result);
         }
Member Data Documentation
CircularString
final String CircularString ="CIRCULARSTRING(5 2,-3 1.999999, -2 1, -4 2, 5 2)" static
LineString2D
final String LineString2D ="LINESTRING(0 1, 0 2)" static
LineString3D
final String LineString3D ="LINESTRING(0 1 1, 0 2 2)" static
point
final String point ="POINT(0 1)" static