rdf4j-postgis: IsClosedTest Class Reference
IsClosedTest Class Reference
Public Member Functions
void testLineStringNotClosed ()
void testLineStringClosed ()
void testMultiLineStringNotClosed ()
void testpointClosed ()
void testmultiPointClosed ()
Static Public Attributes
static final String notClosed ="LINESTRING(0 0, 1 1)"
static final String isClosed ="LINESTRING(0 0, 0 1, 1 1, 0 0)"
static final String mlNotClosed ="MULTILINESTRING((0 0, 0 1, 1 1, 0 0),(0 0, 1 1))"
static final String pointClosed ="POINT(0 0)"
static final String multiPointClosed ="MULTIPOINT((0 0), (1 1), (0 0))"
Member Function Documentation
testLineStringClosed()
void testLineStringClosed ()
References GeometricBinaryAttributeFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 IsClosed instance=new IsClosed();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(isClosed, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral(true);
                 assertEquals(expResult, result);
         }
testLineStringNotClosed()
void testLineStringNotClosed ()
References GeometricBinaryAttributeFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 IsClosed instance=new IsClosed();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(notClosed, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral(false);
                 assertEquals(expResult, result);
         }
testMultiLineStringNotClosed()
void testMultiLineStringNotClosed ()
References GeometricBinaryAttributeFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 IsClosed instance=new IsClosed();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(mlNotClosed, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral(false);
                 assertEquals(expResult, result);
         }
testmultiPointClosed()
void testmultiPointClosed ()
References GeometricBinaryAttributeFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 IsClosed instance=new IsClosed();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(multiPointClosed, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral(true);
                 assertEquals(expResult, result);
         }
testpointClosed()
void testpointClosed ()
References GeometricBinaryAttributeFunction.evaluate(), and WKTDatatype.LiteralIRI.
{
                 IsClosed instance=new IsClosed();
                 ValueFactory valfac=SimpleValueFactory.getInstance();
                 Value geo=valfac.createLiteral(pointClosed, WKTDatatype.LiteralIRI);
                 Value result=instance.evaluate(valfac, geo);
                 Value expResult=valfac.createLiteral(false);
                 assertEquals(expResult, result);
         }
Member Data Documentation
isClosed
final String isClosed ="LINESTRING(0 0, 0 1, 1 1, 0 0)" static
mlNotClosed
final String mlNotClosed ="MULTILINESTRING((0 0, 0 1, 1 1, 0 0),(0 0, 1 1))" static
multiPointClosed
final String multiPointClosed ="MULTIPOINT((0 0), (1 1), (0 0))" static
notClosed
final String notClosed ="LINESTRING(0 0, 1 1)" static
pointClosed
final String pointClosed ="POINT(0 0)" static